### ISSUE TITLE
Fehler im iobroker LOG (2634) string does not contain......

### ISSUE THREAD

**Issue by Nickybroke** [simatec/ioBroker.shuttercontrol#101]
Vielen Dank für deine tolle Arbeit.
Habe plötzlich folgende Fehler im LOG stehen:

shuttercontrol.0 | 2020-08-14 21:34:49.084 | error | (6161) string does not contain :  21:11
shuttercontrol.0 | 2020-08-14 21:34:49.083 | error | (6161) string does not contain :  21:11
shuttercontrol.0 | 2020-08-14 21:34:49.082 | error | (6161) string does not contain :  21:11
shuttercontrol.0 | 2020-08-14 21:34:49.081 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.080 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.080 | error | (6161) string does not contain :
shuttercontrol.0 | 2020-08-14 21:34:49.079 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.079 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.077 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.076 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.075 | error | (6161) string does not contain :
shuttercontrol.0 | 2020-08-14 21:34:49.074 | error | (6161) string does not contain : 06:44
shuttercontrol.0 | 2020-08-14 21:34:49.073 | error | (6161) string does not contain : 06:44

Habe keinerlei Einschränkungen damit. Wollte es nur mitteilen.
Ich selbst nutze nur die Funktion des Sonnenschutzes.

**Comment by simatec** [comment]
fix
