### ISSUE TITLE
Anfrage: Anwesendheit aktiviert/deaktiviert Autofahrt von einzelner Jalousie/Rolllade 

### ISSUE THREAD

**Issue by TJJochen** [simatec/ioBroker.shuttercontrol#105]
Hallo Simatec,

könnte man in dem Adapter evtl. die Anwesendheitserkennung etwas ausgefeilter erweitern? 
Hintergrund ist folgender:
Ich nutze die Auto-Wohnbereich Funktion für die Jalousien im Wohnbereich. Diese fahren aufgrund der Astro Funktion ja selbsständig die Jalousien. Aktuell ja jeden Tag Abends wieder ein wenig früher. Mein Lebensgefährtin nutzt aber die Tür zur Terrasse, um dort Rauchen zu gehen. Da Sie nicht bei mir wohnt, sind die Tage die es betrifft, immer unterschiedlich.

Könnte man nicht, ähnlich wie du es mit der Objekt ID zum Sperren/Aktivieren des gesamten Auto-Wohnbereichs gemacht hast, solch einen Punkt direkt bei der betreffenden Jalousie/Rolllade implementieren? 
![image](https://user-images.githubusercontent.com/35068587/91171783-5e260e00-e6db-11ea-8599-94e170f79417.png)
Dann könnte man hier wieder mit der Anwesendheitserkennung diese Jalousie/Rolllade von der Automatik gezielt ausklammern.
![image](https://user-images.githubusercontent.com/35068587/91172709-e822a680-e6dc-11ea-8ef9-c6b8e8f72c7b.png)

Vielen Dank.

Schöne Grüße

Jochen

**Comment by FoxRo** [comment]
Hallo Jochen
Entschuldige wenn ich mich hier einmische - Wenn Du einen Sensor für die Türe hast, nimm diesen als Trigger in die Konfiguration der entsprechenden Jalousie mit auf - diese Funktion ist genau für das gemacht. Wenn du aber keinen Türsensor hast würde ich an Deiner Stelle wohl im ShutterControl "autoDown" Objektbaum die entsprechende Jalousie ausfindig machen und da den Status auf "False" setzen. Dann fährt die Jalousie am Abend nicht mehr automatisch runter. Sobald sie wieder auf "True" steht, fährt sie wieder zu den definierten Auto-Zeiten.
Vorteil dieser Lösung - manuell und mit den Buttons kann man die Jalousie trotzdem normal verfahren und am Morgen öffnet sie auch wieder mit der gewohnten Zeit. Auch der Sonnenschutz sollte normal weiterlaufen.
Hoffe das hilft Dir weiter.
Viele Grüsse
Roli

**Comment by TJJochen** [comment]
> Hallo Jochen
> Entschuldige wenn ich mich hier einmische - Wenn Du einen Sensor für die Türe hast, nimm diesen als Trigger in die Konfiguration der entsprechenden Jalousie mit auf - diese Funktion ist genau für das gemacht. Wenn du aber keinen Türsensor hast würde ich an Deiner Stelle wohl im ShutterControl "autoDown" Objektbaum die entsprechende Jalousie ausfindig machen und da den Status auf "False" setzen. Dann fährt die Jalousie am Abend nicht mehr automatisch runter. Sobald sie wieder auf "True" steht, fährt sie wieder zu den definierten Auto-Zeiten.
> Vorteil dieser Lösung - manuell und mit den Buttons kann man die Jalousie trotzdem normal verfahren und am Morgen öffnet sie auch wieder mit der gewohnten Zeit. Auch der Sonnenschutz sollte normal weiterlaufen.
> Hoffe das hilft Dir weiter.
> Viele Grüsse
> Roli

Hallo

**Comment by TJJochen** [comment]
Hallo Roli,

Danke für deine Antwort, ist aber nicht das, was ich suche. Türkontakt ist bereits vorhanden, eingepflegt und macht auch das, was du beschreibst inkl. Aussperrschutz.

Hier möchte ich, dass wenn eine bestimmte Person anwesend ist, einzig für diese Tür ein true/false der Automatik gesetzt werden kann und nicht für eine komplette Automatik Gruppe!
Vorteil  wäre, es läuft automatisch.

Gruß 
Jochen
