### ISSUE TITLE
Sonntag wird wie Wochentag behandelt

### ISSUE THREAD

**Issue by Tom-Germany** [simatec/ioBroker.shuttercontrol#106]
Hallo,

erstmal Glückwunsch zu diesem Adapter(0.8.6) ist perfekt, genau das was ich auch immer in FHEM hatte. Nur leider habe ich seit Wochen das Problem das die Abstimmungen nicht mehr perfekt laufen. 

Das Größte Problem. Der Sonntag wird mit dem Wochentagprogramm hochgefahren. Gibt es hier noch eine Einstellung USA/DE Kalender oder ein Bug?

Ausserdem fahren komischerweise die Rollo's am Morgen im Wohnbereich nicht mehr hoch (Hab nochmal eine Einstellung vorgenommen -mal sehen)

Vielen Dank für die Rückmeldung

**Comment by MMeinhardt1** [comment]
Hi,

bei mir ist es genauso. Das ganze ist mir gestern allerdings zum ersten mal aufgefallen. 
Frühestens hochfahren 6 Uhr und spätestens hochfahren 6:30 Uhr, Sonnenaufgang ist nach 6:30 Uhr und die Rollläden fahren alle brav um 6 Uhr hoch.
Werde dazu morgen entsprechend meine Config und Logs hochladen wenn ich am Rechner bin. 

Aber irgendwie ist da der Wurm drin.

**Comment by simatec** [comment]
Bitte prüft mal eure Zeitzonen und Zeiteinstellungen eures Systems

**Comment by MMeinhardt1** [comment]
Bei mir stimmt die Zeit und auch die Zeitzone. Das ganze ist bei mir um eine halbe Stunde verschoben, das ist ja recht seltsam als wenn der Adapter nicht mehr weiß welcher Wochentag aktuell ist bzw. nicht weiß das Wochenende ist.

**Comment by simatec** [comment]
Hast du mal dein ganzes System neugestartet?
Shuttercontrol holz sich ja jeder Zeit aus dem System und es werden schedule gesetzt

**Comment by MMeinhardt1** [comment]
Ich habe das System jetzt mal neugestartet und werde dann wohl bis zum nächsten Wochenende abwarten müssen. Kann man die erstellten Schedules irgendwo einsehen? Wäre allerdings irgendwie schade wenn es nach dem neustarten wieder läuft, das könnte ja bedeuten das man sein System regelmäßig neustarten müsste damit es zuverlässig funktioniert.
Ich melde mich am Samstag wieder mit Neuigkeiten.

**Comment by Tom-Germany** [comment]
Also 

keine Aktivität bei den Rollos am Morgen im Wohnbereich. Am Abend gehen die Rollos runter (0%) auch mit Logeintrag und am Morgen bleiben diese alle geschlossen obwohl der Log Eintrag auch die 100% anzeigt. Es geht kein einziges Rollo hoch was komisch ist denn der Schlafbereich funktioniert daher würde ich auch eine Fehlfunktion von raspberrymatic ausschliessen, denn der Befehl kommt da nicht an. man kann die Rollos nur manuell hochfahren. 

Bin somit ratlos -

**Comment by Tom-Germany** [comment]
bin wohl auf den falschen Knopf gekommen - ist noch ein Problem.

**Comment by simatec** [comment]
Bitte poste die Config der betroffenen Rollläden

**Comment by Tom-Germany** [comment]
<img width="705" alt="image" src="https://user-images.githubusercontent.com/36127912/91713898-e187a980-eb8a-11ea-8035-0c97130b0528.png">
<img width="705" alt="image" src="https://user-images.githubusercontent.com/36127912/91713957-00863b80-eb8b-11ea-9356-18ea8069b8fa.png">

Das ist die Konfiguration eines Fensters mit Sensor für Aussperrschutz

**Comment by MMeinhardt1** [comment]
Heute morgen sind die Rollläden wieder schön um 6 Uhr hochgefahren, ich habe zur Probe die Zeiten mal neu gesetzt und schaue mal ob sich morgen etwas ändert. Ich werde berichten.

**Comment by simatec** [comment]
Poste mal bitte deine Config

**Comment by MMeinhardt1** [comment]
Hi, hier meine Config. 
[system.adapter.shuttercontrol.0.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/5177861/system.adapter.shuttercontrol.0.txt)

**Comment by MMeinhardt1** [comment]
Hi simatec,
mein Rollladen im Keller fährt am Wochenende leider abends nicht mehr herunter mit shuttercontrol, unter der Woche funktioniert das alles super. Es scheint als wäre für das Wochenende der Wurm drin.
Hast Du Dir meine Config schon mal angeschaut?

**Comment by MMeinhardt1** [comment]
Hi,
ich muss mich dann mal wieder zu Wort melden. Meine Rollläden fahren am Wochenende nicht so wie sie es sollten. Entweder wird auch am Wochenende das Wochenprogramm genutzt oder aber der Sonnenaufgang nicht korrekt verarbeitet. Meine Config habe ich bereits gepostet und an dieser hat sich zeittechnisch nichts geändert.
Hast Du Dir die Config denn mittlerweile mal anschauen können?
Was kann ich testen bzw. einstellen damit Du einen eventuellen Fehler besser / schneller finden kannst? Würde es helfen wenn ich den Adapter vor dem nächsten Wochenende auf Debug laufen lasse?

**Comment by MMeinhardt1** [comment]
Mit V0.8.7 sind meine Probleme scheinbar behoben. 
Ich denke das hier kann geschlossen werden.

**Comment by simatec** [comment]
Danke für dein Feedback...
