### ISSUE TITLE
Einbinden von Schichtplänen, oder Automatikbetrieb erst über Verfahrstatus

### ISSUE THREAD

**Issue by quorle** [simatec/ioBroker.shuttercontrol#108]
Ich hätte ein Anregung für die nähere Zukunft.

Es sollte eine Auswertung geben, die die Automatik erst in Betrieb nimmt, wenn die Rollos manuell von oben nach ganz oben gefahren wurden. 
Dies würde verhindern, dass Fenster mit Rollos in den Autobetrieb gehen, ohne es zu wollen. Wäre Prima für Schichtarbeiter, denn nach der Nachtschicht ist es nicht so toll, wenn das Rollo hoch fährt.

**Comment by quorle** [comment]
Ich hätte noch weiter Vorschläge für die nahe Zukunft. 
- Verfahren nach Sonnenstand ( Die Rollos verfahren je nach Sonnenstand in eine definierte Position z.b. 25,50,75,90 Prozent )
- Azimut Bereichseinstellung (z.B. von 5-10 )
- Windalarm ( Bei Windalarm Rollos hoch, Beschattungsautomatik aus, und wenn Windalarm weg, dann wieder Beschattung aktivieren.
- Brandalarm 
- Regenalarm

Ich orientiere mich gerade an den Funktionen der MDT Jalousieaktoren für KNX. Eventuell wären diese ganzen Funtionen, die der MDT Aktor kann, eine Anregung.

**Comment by BT133** [comment]
Ich habe den Nachtdienst über einen Trigger und die Automatikfunktion gelöst. 
Ein eigener Datenpunkt der immer auf true steht und durch ical auf false gestellt wird wenn ich am Vortag Nachtdienst in google-Kalender eingetragen habe. Dadurch wird dann die Automatik ausgesetzt und die Jalousie bleibt unten.
Java Script und blockly ist angehängt

Wäre natürlich super einen weiteren Trigger zu haben, der würde das erleichtern. Aber es ist so ein funktionierender workaround

[script iobroker shuttercontrolnachtdiesnt.docx](https://github.com/simatec/ioBroker.shuttercontrol/files/5971787/script.iobroker.shuttercontrolnachtdiesnt.docx)
`var timeout, timeout4, timeout3, timeout2;

schedule('{"time":{"exactTime":true,"start":"09:00"},"period":{"days":1}}', function () {
  if (getState("ical.0.events.0.today.Urlaub").val) {
    console.log('Urlaub');
  } else if (getState("ical.0.events.0.today.frei").val) {
    console.log('Dienstfrei');
  } else {
    if (getState("ical.0.events.0.today.Nachtdienst").val) {
      console.warn('nachtdient heute, kein urlaub oder dienstfrei');
      timeout = setTimeout(function () {
        setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, false);
        setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, false, true);
        console.warn('nachtdient gestern, Jalousien hochfahren für 11Uhr  gesperrt');
        if (getState("ical.0.events.0.today.Nachtdienst").val) {
          console.warn('zusatznachtdient heute');
          timeout3 = setTimeout(function () {
            setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, false);
            setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, false, true);
            console.warn('zusatznachtdient gestern, Jalousie gesperrt  / falsch');
            timeout2 = setTimeout(function () {
              setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, true);
              setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, true, true);
              console.warn(([getState("ical.0.events.0.today.Nachtdienst").val,':   Zusatznachtdienst','   /   objekt ical änderung auf : ',getState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern").val].join('')));
            }, 43200000);
          }, 86400000);
        } else {
          timeout4 = setTimeout(function () {
            setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, true);
            setState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern"/*Jalousie ical auf false ändern*/, true, true);
            console.warn(([getState("ical.0.events.0.today.Nachtdienst").val,'... nachtdienst','.... objekt ical änderung auf : ',getState("0_userdata.0.Jalousie.Jalousie_ical_auf_false_ändern").val].join('')));
          }, 43200000);
        }
      }, 86400000);
    }
  }
});
`
