### ISSUE TITLE
Fehler beim Ansteuern

### ISSUE THREAD

**Issue by nodwan** [simatec/ioBroker.shuttercontrol#109]
hm-rpc.0 | 2020-09-12 07:00:11.244 | error | (1330) Error: XML-RPC fault: Failure
-- | -- | -- | --
hm-rpc.0 | 2020-09-12 07:00:11.234 | error | (1330) xmlrpc -> setValue ["OEQ0979754:1","LEVEL",1] FLOAT
shuttercontrol.0 | 2020-09-12 07:00:10.100 | info | (29182) #16 Set ID: HM-LC-Bl1PBU-FM OEQ0979754:1.LEVEL value: 100%

Diesen Fehler bekomme ich immer wieder wenn ich denn Aktor in die Steuerung einbinde! Danach ist die Aktor tot! Erst ein kurzer klick auf Config am Gerät macht ihn wieder Ansprechbar. 

Programmiere ich irgendwas eigenes passiert das nicht. Nur bei shuttercontrol

**Comment by nodwan** [comment]
Versuche einen Workaround, ich habe ein kleines Script gemacht welches denn aktuellen Level des Tür Rollos Überwacht und dann mit 2 Minuten Verzögerung das Fensterrollo auf die gleich Position Fährt. Mal sehen ob das klappt!?!?! 

Der Türaktor ist ein: shuttercontrol.0.shutters.autoState.HM-LC-Bl1PBU-FM_MEQ0732973:1_LEVEL
Der Scheint keine Probleme zu haben mit shuttercontrol

**Comment by simatec** [comment]
shuttercontrol setzt nur Werte in die Objekte ... Bitte prüfe deine Config ...
