### ISSUE TITLE
Aussenhelligkeitsabhängiger Automatik Up/Down

### ISSUE THREAD

**Issue by vosi2** [simatec/ioBroker.shuttercontrol#113]
Hi,
ich hätte gern die Möglichkeit die Automatifunktion Up and Down nicht nur Zeit und Sonnenstandsabhängig zu nutzen, sondern auch einen Dämmerungssensor zu nutzen. Damit würden die Rolläden erst fahren wenn eine bestimmte Aussenhelligkeit erreicht ist.

Danke.

**Comment by poidi** [comment]
Oder eben wenn eine Aussenhelligkeit unterschritten wird. Ja das hätte ich auch gerne! Wurde auch in den closed Issues schon einige male gewünscht, und mit mehr oder weniger guten Workarounds gelöst. (zB Bürgerliche Dämmerung per Delta "nachbauen")

**Comment by poidi** [comment]
Ich habe jetzt einfach ein java-script mit blockly gemacht, dass 30 Minuten vor Sonnenuntergang startet und alle 5 minuten den Helligkeitssensor auswertet. Wenn der den Threshold unterschreitet, dann sende ich mittles shuttercontrol ein closeAll.

Könnte man in der Früh auch machen, aber da will ich eigentlich mit dem "Wecker" die Rolläden rauffahren.

**Comment by vain90** [comment]
Habe eben auch im ioBroker Forum einen sehr sehr ähnlichen Wunsch geäußert.

Ich könnte es mir so vorstellen, dass man eine Zeitspanne (+-) vom Sunset und Sunrise angibt. Beispielsweise 30min. Innerhalb dieser Zeitspanne ist ein Helligkeitssensor aktiv und es wird darauf gewartet dass ein vorher definierter Schwellwert unter bzw. überschritten wird. (Für Sunset unterschritten. Für Sunrise überschritten)

Das hat den charmanten Vorteil das die Rolladen bei klarem Himmel erst später schließen bzw. früher hochfahren. Und bei bewölktem Himmel oder sehr dunklen Tagen die Rolladen früher schließen bzw. später hochfahren.

Wichtig wäre mir nur, dass die Funktionen "früheste Zeit für das hochfahren" und "späteste Zeit für das hochfahren "in den Zeiteinstellungen nicht überschrieben werden. Die müssen Vorrang haben.
Außerdem sollte bei Ablauf der Zeitspanne trotzdem geschlossen oder geöffnet werden auch wenn der Schwellwert nicht erreicht wurde.

Beste Grüße
vain

**Comment by AlexanderSch90** [comment]
@vain90 genauso stelle ich mir das auch vor! Wäre schön wenn das implementiert wird.

**Comment by 03-20** [comment]
Schließe mich dem Wunsch von vain90 an.

Habe einen Helligkeitssensor und würde den gerne in den Regeln mit nutzen.

**Comment by vain90** [comment]
Jetzt wo in Mitteldeutschland sehr viel Schnee liegt, fällt uns wieder auf das die reine Sunrise/Sunset Steuerung nicht vollends befriedigend ist. Heute waren die Rolladen gefühlt viel zu früh runter gefahren. Durch den Schnee und dem heutigen Sonnenschein ist es aktuell länger schön hell draußen.

mich würde mich sehr freuen wenn dieses Feature nicht komplett von der ToDo-Liste rutscht. :)

**Comment by simatec** [comment]
Ist ab Version 1.2.0 integriert ...
