### ISSUE TITLE
Mehr Zeiten für Sonnenaufgang und Sonnenuntergang #Astro

### ISSUE THREAD

**Issue by anubiss1337** [simatec/ioBroker.shuttercontrol#123]
Hallo,

wäre es möglich bei den "Zeit Einstellungen" unter "Art der Automatiksteuerung für den Wohnbereich (Schlafbereich)" mehr Auswahl bei der Astro Funktion zu haben? z.B. "Zeit Wohnbereich (Schlafbereich) mit Bürgerliche Morgendämmerung & Bürgerliche Abenddämmerung (Analog zu dem Sonnenauf- und Sonnenuntergang, jedoch mit dem Beginn und Ende der "Bürgerliche Morgendämmerung" als Referenz)"

![Bildschirmfoto vom 2020-10-20 20-03-24](https://user-images.githubusercontent.com/73192932/96626236-8747d100-130f-11eb-9512-4472e8b89f28.png)

Besonders morgens würde ich mir Wünschen, das die Rollladen, entweder zum Ende der nautischen Morgendämmerung oder zum Anfang der Bürgerlichen Morgendämmerung auf gehen. 
Leider unterscheidet sich, wie auch auf den Bild zu sehen, der Sonnenaufgang kaum bis gar nicht zum Anfang der Golden Hour. 

Wäre echt kasse wenn so was noch zum sonst Super laufenden Adapter hinzukommen würde.

**Comment by FredF63** [comment]
Du kannst doch in den Extra-Einstellungen - Astro-Einstellungen eine Zeitverzögerung eingeben
![grafik](https://user-images.githubusercontent.com/43332106/97468272-60a81c80-1945-11eb-9adc-7ac4970f8367.png)

**Comment by FredF63** [comment]
Du kannst doch unter Extra-Einstellungen - Astro-Einstellungen das als Zeitverzögerung eingeben...

![grafik](https://user-images.githubusercontent.com/43332106/97468746-e926bd00-1945-11eb-9fd5-12b8b3b2c98d.png)

**Comment by anubiss1337** [comment]
Du meinst einen Negativen Wert wie z.B. -35? Ich möchte ja wie oben beschrieben das mein Rollladen nicht um 08:01 aufgeht sondern schon um 07:26. 
Ich Teste das mal. Wenn das Wirklich geht dann hat sich meine Anfrage hiermit erledigt ;)

**Comment by anubiss1337** [comment]
Lösung: Einfach **-** xx min eingeben und fertig.

**Comment by poidi** [comment]
naja - das ist nur dann eine lösung, wenn man das immer wieder händisch ändert. Denn der Zeitunterschied zwischen Bürgerlicher Dämmerung und Sonnenuntergang/aufgang ist ja nicht fix, sondern jahreszeitabhängig.
