### ISSUE TITLE
SceduledLevel

### ISSUE THREAD

**Issue by zahnheinrich** [simatec/ioBroker.shuttercontrol#13]
Die AKTUELLE Rolladenhöhe, welche bei Automatik an Schaltpunkten angefahren wird/würde.
Wird gesetzt auch bei ausgeschalteter Automatik.
Dadurch kann bei Wiedereinschalten der Automatik sofort die gesetzte Position angefahren werden.
Besonders nützlich auch für den Ist/Soll Vergleich und evtl. Nachführen bei Shelly Aktoren.
Diese schalten etwas unzuverlässig und zeitweise unpräzise.

**Comment by simatec** [comment]
Sorry ich kann mit deiner Aussage garnix abfangen. 
Was willst du damit sagen?

**Comment by irudi** [comment]
Finde ich eine gute Idee: einen State der pro Shutter den durch die Automatik berechneten Level ausgibt - auch wenn die Automatik gerade außer Betrieb ist. 
Das hilft beim Nachvollziehen der eigenen Config und der Automatik und man könnte diesen Wert nutzen um explizit genau diese Position wieder anzufahren.

**Comment by irudi** [comment]
Hast Du das denn eingebaut? Ich finde diese Werte nicht ...!?
