### ISSUE TITLE
Unterstützung für Kippstellung

### ISSUE THREAD

**Issue by spaceduck518** [simatec/ioBroker.shuttercontrol#130]
Hi,
besteht die Möglichkeit auf eine "gekippt" Stellung bei Fenstern zu reagieren, d.h. eine zusätzliches Setting für eine Behanghöhe (0-100) in Stellung "gekippt", zusätzlich zur schon vorhandenen Einstellmöglichkeit bei Fenster offen?

**Comment by Flipperbastler** [comment]
Darüber wäre ich auch sehr dankbar!

**Comment by RettungsTim** [comment]
Wird es das noch geben? Die Homematic Fensterkontakte geben. Close(0) Tilted(1) open(2)
Das ist echt doof. Weil wenn ich das Fenster auf Kipp stellen will geht es über die 1 somit fährt das Rollo hoch und dann wenn es auf ist (2) wieder runter…

**Comment by simatec** [comment]
Kommt in Version 1.3.0
