### ISSUE TITLE
Enhancement - Sonnenschutz ein- bzw ausschalten

### ISSUE THREAD

**Issue by mediaDS** [simatec/ioBroker.shuttercontrol#132]
Hallo,

toller Adapter, den ich gerne nutze. Zwei Erweiterungen würden ihn aber noch toller machen:

1. Bei Sonnenschutz fährt der Rolladen herunter auf den eingestellten Sollwert. Soweit so gut. Ist aber die Sonne weg, verbleibt der Rolladen in der Position und wird nicht wieder hochgefahren (egal, was ich einstelle). Wäre sinnvoll, den (oder die) Rolladen nach Wegfall des Sonnenschutzes wieder in die Position zu fahren, in der er (sie) vorher war(en).

2. Wäre es möglich, beim Herunterfahren (Sonnenuntergang) bzw. Hochfahren (Sonnenaufgang) einen Datenpunkt auf **true** bzw. **false** zu setzen - als Trigger für andere Skripte, die bei Dämmerung bzw. Tagesbeginn weitere Aktionen ausführen.

Das würde es perfekt machen.

Danke für den Adapter und hoffe auf entsprechende Enhancements :)

**Comment by simatec** [comment]
Punkt 1 kann ich nicht nachvollziehen. So wie ich es verstehe, fährst du nach einen Lichtsensor in den Sonnenschutz. Prüfe deine Range, dann fährt der Rollladen auch wieder hoch. 

Punkt 2 gibt es doch in JavaScript alles.

**Comment by mediaDS** [comment]
Hi

> Punkt 1 kann ich nicht nachvollziehen. So wie ich es verstehe, fährst du nach einen Lichtsensor in den Sonnenschutz. Prüfe deine Range, dann fährt der Rollladen auch wieder hoch.

Nein. Der Sonnenschutz wird (momentan) über die Elevation und einen weiteren Logikwert (Sonne = true|false) über z.B. den Datenpunkt shuttercontrol.0.shutters.autoSun.Rolladen_Wohnz getriggert. Wenn der Datenpunkt auf false gesetzt wird, dann fährt der Rolladen nicht wieder in seine ursprüngliche Position.

> Punkt 2 gibt es doch in JavaScript alles.

Klar gibt es das, aber wenn ich alles selber in JS mache, dann brauche ich auch kein shuttercontrol :)

Ich helfe mir momentan, indem ich (bei Sonnenaufgang bzw  Sonnenuntergang) einen virtuellen Datenpunkt wie einen Rolladen auf 0 oder 1 setze und diesen dann in einem Skript auswerte und dann einen weiteren Datenpunkt Dämmerung auf true|false setze. Irgendwie umständlich - es wäre natürlich schön, wenn shuttercontrol diese Möglichkeit direkt integriert hätte. Kein Muss, sicher. Wäre nur toll, wenn es möglich wäre. Wenn nicht, dann nicht.

**Comment by simatec** [comment]
Also dafür ist der state autoSun nicht gedacht und auch nicht geeignet. Damit gibst du nur den Rollladen für den Sonnenschutz frei. 
Lies dir mal bitte die Doku durch. 

Punkt 2 kann ich nicht nachvollziehen. Was haben deine anderen Skipte und Funktionen mit shuttercontrol zu tun und warum machst du shuttercontrol davon abhängig. Es ist ein simple Trigger in blockly, der dir den Sonnenaufgang und Sonnenuntgang triggert und hat nix mit shuttercontrol zu tun

**Comment by mediaDS** [comment]
Mein Gott, bist du schnell angepisst.

> Also dafür ist der state autoSun nicht gedacht und auch nicht geeignet. Damit gibst du nur den Rollladen für den Sonnenschutz frei.
> Lies dir mal bitte die Doku durch.

Habe ich. Das war kein Bugreport, sonder eine Frage nach einem Enhancement. Aber lass mal stecken. Davon abgesehen ist es dann Doku-mässig missverständlich - wenn ich den Sonnenschutz ausschalte, dann gehe ich davon aus, das der Rolladen dann ebenfalls wieder in seine Ursprungs-Position geht. Das ist (für mich) der Sinn einer solchen Funktion.

> Punkt 2 kann ich nicht nachvollziehen. Was haben deine anderen Skipte und Funktionen mit shuttercontrol zu tun und warum machst du shuttercontrol davon abhängig. Es ist ein simple Trigger in blockly, der dir den Sonnenaufgang und Sonnenuntgang triggert und hat nix mit shuttercontrol zu tun

Echt jetzt? Wenn shuttercontrol sowieso die Astro-Funktion verwendet, wäre ein weiteres Script doppelt gemoppelt. Aber lass mal stecken, ich programmier es mir dann selber in Blockly, dann brauche ich shuttercontrol nicht mehr.

Danke trotzdem.

**Comment by simatec** [comment]
Hier ist doch keine ange*****. 
Es ist nur meine Meinung dazu. 
Und nein die Funktion des states interpretiest du leider falsch. Hiermit wird lediglich festgestellt, ob der jeweilige Rollladen für die Automatik freigegeben ist oder nicht. Ein Beispiel: Bei mir wird der state für autoDown und autoSun meiner Terrassetür in Verbindung mit Anwesehenheit getriggert. Bin ich nicht daheim, dann sind die true und der Rollladen fährt automatisch. Bin ich zu Hause sind diese false. Somit habe ich immer die Sicherheit mich nicht auszusperren. Für die Regelung des Sonnenschutzes gibt es Trigger im Menü wie z.B. Außentemp, Innentemp, Lichtsensor, und Himmelsrichtung. Damit werden die Rollläden in den Sonnenschutz gefahren und auch wieder hochgefahren
