### ISSUE TITLE
Feature Request: Offset to the individual settings

### ISSUE THREAD

**Issue by MojitoJoe1813** [simatec/ioBroker.shuttercontrol#134]
I do have one shutter (of all my shutters) which I would like to get closed after golden hour (as this is too early) but roughly 20min before sunset (as this would be to late) in order to prevent people seeing my screen shining bright inside when working in my home-office. So setting the individual settings to something inbetween would be great. The ideal flexibility would be offered by a kind of offset optional to be used.

Einer meiner Rolläden soll sich etwas früher schließen als alle anderen auf den Sonnenuntergang eingestellten, da er verhindern soll, dass man meinen geschäftskritischen Bildschirminhalt im Home-Office von draußen erkennen kann, weil es draußen zu dunkel wird. Golden Hour ist ca. eine halbe Stunde zu früh - da wäre es noch 30 Minuten hell genug. Ein Offset auf die eingestellte Zeit in den individuellen Einstellungen würde mir die volle Flexibilität pro Rollladen erlauben, von den zentralen Einstellungen in Minuten abzuweichen.

**Comment by simatec** [comment]
Du kannst bei diesen Rollladen Elevation für das schließen wählen und dir dort den Wert der Sonnenhöhe einstellen, dass er genau nach deinen Bedürfnissen schließt.
![image](https://user-images.githubusercontent.com/39792461/100841263-5662cc00-3477-11eb-80e9-73423a1e9f6a.png)
