### ISSUE TITLE
Wieder mal der Aussperrschutz

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#135]
Hi, 

ich mal wieder mit dem leidigen Thema. Aktuell steht in der Doku zum Aussperrschutz folgendes:

"""
Rollladenautomatik auch bei geöffneten Fenster/Tür benutzen (Aussperrschutz)
Entspricht zum Zeitpunkt des automatischen Schließens der Fenster/Tür Sensor nicht dem dort eingegebenen Wert (Fenster/Tür offen) wird folgendes ausgeführt:

    Aus: Aussperrschutz ist in beide Richtungen aktiv, die Rollläden bewegen nicht wenn der egal wie der Sensor steht.
    Öffnen: Bei Verdunklungs- / Beschattungsende fährt der Rollladen hoch
    Schließen: Bei Verdunklungs- / Beschattungsbeginn fährt der Rollladen herunter
    Öffnen und Schließen: Der Rollladen darf sich egal wie der Sensor steht, in beide Richtungen bewegen
"""

vor allem der Text bei "Aus" ist nach wie vor nicht klar. Ich denke der Satz ist aktuell nicht mal wirklich deutsch - hier wurde offenbar der Satz mehrmals umformuliert.

Bei "Aus" und bei "Öffnen und Schließen" steht nach wie vor "egal wie der Sensor steht" somit ist das nicht wirklich hilfreich.

Danke
poidi

PS: will nicht nerven, aber die Doku ist in diesem Punkt leider "...seit anbegin der Zeit..." nicht wirklich verständlich.

**Comment by simatec** [comment]
Dann mache doch einen PR und sende damit deine Vorschläge zur besseren Formulierung ...

**Comment by poidi** [comment]
Würde ich gern, wenn ich wüsste was es denn tut!

**Comment by poidi** [comment]
Ich verstehe einfach nicht, was der aussperrschutz in welcher Situation (Sensor hat 2 Möglichkeiten - Tür auf, Tür zu; Rolladen hat 3 Möglichkeiten: Rauf, Runter, Nichts) das Aus, Öffnen, Schließen, Öffnen und Schließen wie reagiert.

Ich verstehe einen Aussperrschutz so, dass aufgrund der Sensorstellung "Tür Auf" nicht das normale Programm gefahren wird, sondern eben das, was hier eingestellt wird:
 - Aus: Der Rolladen bewegt sich nicht, wenn Tür offen signalisiert wird, und ein Zeitgesteuertes Kommando an den Rolladen gesendet werden würde. Bei Tür geschlossen macht er es aber.
 - Öffnen: Der Rolladen öffnet sich, egal wie der Sensor steht. Wenn der Sensor aber "Tür Auf" zeigt, so fährt der Rolladen nicht runter, wenn das zeitgesteuerte Kommande gesendet werden würde. Bei Tür geschlossen macht er es aber.
- Schließen: Der Rolladen schließt sich, egal wie der Sensor steht. Wenn der Sensor aber "Tür Auf" zeigt, so fährt der Rolladen nicht rauf, wenn das zeitgesteuerte Kommande gesendet werden würde. Bei Tür geschlossen macht er es aber.
- Öffnen und Schließen: Kein Aussperrschutz. Es wird laut zeitgesteuertem Kommando gefahren

Stimmt das?

Wenn ja, so würde ich die Einstellung 
 - "Aus" in "Runterfahren und Öffnen verhindern",
 - "Öffnen" in "Runterfahren verhindern"
 - "Schließen" in "Öffnen verhindern"
 - "Öffnen und Schließen" in "Kein Aussperrschutz"
umbenennen - oder zumindest so beschreiben.
