### ISSUE TITLE
Rollladen Fahrt bei Fenster auf

### ISSUE THREAD

**Issue by as149** [simatec/ioBroker.shuttercontrol#137]
Hallo,

in der Issue #92 wird gefragt ob es möglich ist, den Rolladen bei "Fenster auf" nicht herunterzufahren, wenn dieser höher geöffnet ist, als in den Einstellungen (Rollladenhöhe bei öffnen des Fensters oder Tür) angegeben.
Ich habe eingestellt, dass bei "Fenster auf" der Rolladen auf 25% geöffnet wird.
Ist mein Rolladen höher als 25% geöffnet, fährt dieser auf 25% runter wenn das Fenster geöffnet wird.
Die Antwort soll das Release 1.0.0 geben, aber in den Einstellungen habe ich nichts dazu gefunden.

Es wäre tatsächlich besser, wenn die Rolläden nur auf die eingestellten 25% fahren, wenn sie tiefer geschlossen sind.
Man muss hierbei aufpassen ob der aktuelle Status des Rolladens größer oder kleiner 25% ist, da man in den Haupteinstellungen einstellen kann, dass 0% geöffnet oder geschlossen bzw. 100% geöffnet oder geschlossen sind.

Wo kann man mein Anliegen steuern?

**Comment by FoxRo** [comment]
Hallo @as149 
Das ist heute schon so umgesetzt.
Wenn das Fenster geöffnet wird und der Rollo weiter oben ist als die geforderte Position, dann fährt dieser nicht zu.
Wenn er das bei Dir trotzdem macht, dann stimmt etwas mit der Aktualisierung der aktuellen Position nicht. Bitte prüfe dies mal unter "autoLevel" in den Shuttercontrol Objekten..

**Comment by as149** [comment]
Hallo FoxRo,
danke für die Info.
Es ist tatsächlich so, dass der Level von Homematic nicht immer übergeben wird.
Wenn man den Level per CCU oder IoBroker WebUI ändert, wird dieser auch sauber in die "autolevel" geschrieben.
Drückt man auf einen Taster an der Wand, wird der Level von Homematic auf 0% bzw. 100% gesetzt.
Ich verwende eine verdrahtete installation mit HmIPW-DRBL4.

Weiß nicht ob das ein Bug der CCU ist.

**Comment by as149** [comment]
Hallo FoxRo,
bei den HM-Aktoren gibt es sog. statedatapoints und controldatapoints also einen Statuskanal und einen Steuerkanal. Beide haben jew. einen LEVEL-Datenpunkt.
Wenn per WebUI oder App keine prozentuale Position an den Steuerkanal abgesetzt wird, sind die Level-Werte des  Statuskanals und des Steuerkanals, nach der Rolladenfahrt, gleich.
Wenn der Rolladen per Taster an der Wand betätigt wird, wird der Steuerkanal auf 0% (rauf oder runter) bzw. 100% (rauf oder runter) gesetzt. Stoppt man dann den Rolladen per erneuten Tastendruck, wird nur im Statuskanal der aktuell angefahrene Level angezeigt. Der Level des Steuerkanals bleibt bei 0% oder 100%.
Wie ich aus diesem Beitrag (ganz unten https://forum.fhem.de/index.php/topic,100152.0.html) lesen konnte, sind diese unterschiedlichen Datapoints von Homematic Absicht.

Man müsste z.B. für Homematic Aktoren unterschiedliche Level auslesen, da nur der Level des Steuerkanals write Rechte besitzt.
Ist das irgendwie realisierbar?

**Comment by FoxRo** [comment]
Hallo as149
Das IoBroker Konzept tickt an dieser Stelle grundsätzlich anders. Da gibt es nur ein Objekt für Befehle und Status. Das gleiche Problem hat auch KNX wo Befehl und Statusobjekt getrennt sind. Da führt der IoBroker KNX Adapter dies zusammen.
Im Forum hatte Nagelein das gleiche Problem.
er hat [hier](https://forum.iobroker.net/topic/43678/hm-rpc-level-kanal-3-4-nicht-synchron/67) offensichtlich eine Lösung gefunden.
Vielleicht ist das auch was für Dich?
Viel Erfolg!

**Comment by as149** [comment]
Hi FoxRo,
ich habe das Blocklyscript erstellt und erste Fahrten gemacht.
Der Status aktualisiert sich bis jetzt zuverlässig.
Ich werde nun wieder die Fenster-Auf Funktion aktivieren und beobachten.
Danke für die tolle Info.

**Comment by as149** [comment]
Die Werte werden zunächst vom Blocklyscript aktualisiert, soweit alles OK.
Einige Zeit danach sendet anscheinend die CCU erneut die Werte und macht dann alles wieder zunichte, also 0% oder 100%.

**Comment by as149** [comment]
Wenn man im Block Script den trigger auf "wurde aktualisiert" stellt, werden die Werte von der CCU nicht mehr überschrieben.
Ich teste nun seit einer Woche und habe bislang immer nur korrekte aktualisierte Werte gesehen.
