### ISSUE TITLE
Schließen bei Trigger begrenzen

### ISSUE THREAD

**Issue by mameier1234** [simatec/ioBroker.shuttercontrol#14]
Wie schon im Forum geschrieben...

ich vermisse eine Funktion, z.B. bei geöffneter Balkontür zum Zeitpunk des schließens auf max 40 % zu fahren.. (damit bei der Hitze weiter gelüftet wird...)

**Comment by simatec** [comment]
Das kannst du über die Sonnenschutz Einstellungen lösen.

**Comment by mameier1234** [comment]
Du meinst das abendliche schließen ? Wenn die Rollos abends runterfahren, am Balkon die Tür aber noch offen ist, soll nicht sofort auf 0% fahren , sondern eben nur auf 40% ... und später beim schließen, dann auf 0% oder eben manuell...
