### ISSUE TITLE
Fenster-/Türkontakt weitere Werte

### ISSUE THREAD

**Issue by Schmakus** [simatec/ioBroker.shuttercontrol#141]
Hallo.
Es sollte die Möglichkeit geben, die Werte für den Fenster- oder Türkontakt selbst bestimmen zu können, anstatt nur zwischen true, false, 0 - 2 wählen zu können.
In meinem Fall habe ich alle Kontakte mit linkeddevices erstellt und den Wert in eine Zeichenkette "offen/geschlossen" geändert. Nun lassen sich die Kontakte nicht in shuttercontrol verwenden, außer ich verwende die Quell-Datenpunkte.

**Comment by simatec** [comment]
Die Werte entsprechen dem iobroker Standard Objekten.
Bitte passe ggfs. deine dem Standard an oder erstelle dafür weitere States
