### ISSUE TITLE
Zeitlicher Versatz zu Astrozeiten

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#144]
Hallo @simatec,

ich weiß nicht ob es irgendwo schon mal angesprochen wurde, aber ich würde mir wünschen einen Versatz zu den Astrozeiten einstellen zu können in + und -.

Vielen Dank 
Michael

**Comment by simatec** [comment]
Was meinst du genau? Eine Range gibt es doch

**Comment by MMeinhardt1** [comment]
Guten Morgen,
Du hast natürlich vollkommen recht das es das gibt. Habe dies auch zu Anfang mal eingestellt. Es ist aber ja nur eine globale Einstellung. Wenn es Deine Zeit zuläßt und es für Dich Sinn ergibt würde ich mir wünschen das man dieses unter "Zeit-Einstellungen" des jeweiligen Bereiches einstellen könnte, dann wäre es etwas variabler.

Danke

**Comment by MMeinhardt1** [comment]
Hallo @simatec,
hast Du Dir schon Gedanken gemacht diesen Versatz pro Bereich einbauen zu können bzw. zu wollen?

Vielen Dank 
Michael

**Comment by simatec** [comment]
Inzwischen bietet shuttercontrol für das hochfahren 9 Automatikoptionen und für das runterfahren 10 Automatikoptionen.
Das heißt in meiner Welt, dass ich meinem Haus fast jeden Rollladen zeitlich anders fahren könnte.
Denke das ist mehr als ausreichend und eine Integration nach deinem Wunsch würde das Konzept von shuttercontrol über den Haufen werfen.

Sorry, aber das wird nicht umgesetzt
