### ISSUE TITLE
Sonnenrichtung berücksichtigen

### ISSUE THREAD

**Issue by dagoellner** [simatec/ioBroker.shuttercontrol#145]
Hallo es wäre toll, wenn man die Rolläden/Jalousien in der Himmelsrichtung wo aktuell die Sonne steht schliessen könnte. Abhängig von der aktuellen Bewölkung und Temperatur. z.B. Wenn die Sonne weiter Richtung Süden wandert,  schliessen sich die Rolläden im Süden  und die im Osten gehen wieder auf...

**Comment by simatec** [comment]
Deine gewünschte Einstellung kannst du bereits umsetzen. Dafür kannst du die Himmelsrichtungen in den Sonnenschutz Einstellungen verwenden.
