### ISSUE TITLE
Homematic Drehgriffsensor mehrere Werte

### ISSUE THREAD

**Issue by ChrissT23** [simatec/ioBroker.shuttercontrol#147]
Hallo, 

wäre es möglich das man in dem Fensterstatus einen weiteren Wert angeben könnte ? 

Ich habe den Homematic Drehgriffsensor welcher 0/Closed 1/Tilted 2/open als Werte ausgibt. 

Ich würde gerne bei Tilted das Fenster auf einen anderen Wert fahren lassen wie bei open. Aktuell fährt der Rolladen immer auf ganz auf, bei gekippt soll er aber nur auf einen Wert für das Lüften fahren und bei open soll er ganz öffnen. 

Vielen Dank für den super Adapter !

**Comment by xxstasxx** [comment]
Hallo,

die Abfrage für die gekippte Stellung würde mich auch interessieren.

**Comment by TJJochen** [comment]
@simatec 

Hallo,

ich habe auch ausschliesslich die Homematic IP Drehgriffsensoren. Wie ChrissT23 bereits angefragt hat, würde ich mich auch über einen weiteren Wert für die gekippte Flügelstellung interessieren.

Danke und schöne Grüße
Jochen

**Comment by simatec** [comment]
Kannst du mir bitte die Werte für offen, gekippt und geschlossen übermitteln?
Ich überlege mir dann mal was

**Comment by ChrissT23** [comment]
Hi, 

Offen=2
Gekippt=1
Geschlossen=0

Dankeschön !

**Comment by Tratonis** [comment]
@simatec 
mich würde auch ein erweiterter Aussperrschutz mit dem Homematic Fenstergriffsensoren interessieren. Bei offen (2) kein fahren, bei gekippt (1) in Lüftungsstellung.

**Comment by simatec** [comment]
Die Auswahl für eine Kippstellung kommt in Version 1.3.0
