### ISSUE TITLE
Sleep Mode

### ISSUE THREAD

**Issue by miwa4711** [simatec/ioBroker.shuttercontrol#150]
Hallo simatec, würde gerne diesen Adapter verwenden. Leider fehlt mir eine wesentliche Funktion "Sleep" für jeden Schlaf-Raum. Damit soll mit Prio der Rollo auf die Stellung Verdunkelung fahren. Verwende ich für Kinderzimmer (Schlafen unter Tag), Gäste (schlafen länger), Schichtarbeit (schlafen zu besonderen Zeiten), Jugendliche/Langschläfer (nach Feier wird viiiiiiel länger geschlafen). Wenn Sleep aktiv, dann sind viele Auto-Fkt im Zimmer deaktiviert (z.B. Licht über Bewegungsmelder etc.).
Wäre über Datenpunkt je Zimmer doch machbar, oder?
Was hältst du davon?

Vielen Dank.

VG
MiWa

**Comment by simatec** [comment]
Das könntest du doch über die Button Funktion lösen und bei autoUp des entsprechenden Rollladens auch noch ein hochfahren verhindern
