### ISSUE TITLE
Neigung für Jalousien / Ruffstore

### ISSUE THREAD

**Issue by btiegel** [simatec/ioBroker.shuttercontrol#152]
Hallo,
ich habe neben "normalen" Rolläden auch außen Jalousien / Ruffstore. Bei diesen ist der Neigungswinkel der Lamellen veränderlich.
Beim nach unten Fahren werden die Lamellen "hochgestellt" und beim hochfahren "geöffnet". Ich würde mir also eine Funktion wünschen beispielsweise nach dem Runterfahren noch mal für 1 Sekunde Hochzufahren um die Lamellen zu öffnen.
Selber Skripten stelle ich mir schwierig vor, da ich ja schlecht erkennen kann wann die Rollläden manuell geschlossen wurden und dann wann vom Adapter (oder kann ich das?)
Gibt es Ideen dazu?

Gruß

Benedikt

PS: Danke auf jeden Fall für den super nützlichen Adapter!

**Comment by MiBe17** [comment]
Hi,
ich habe das selbe Problem. Meine Shutter Aktoren werden über Shelly 2.5 gesteuert. Nach dem Runterfahren sind die Lamellen zu und beim Hochfahren gehen sie wieder auf.

Ich habe das aktuell so gelöst:
Wird ein bestimmer Helligkeitswert erreicht während die Shutter im Shuttercontrol-Modus "sunProtect" sind, fahre ich sie über ein Script für 700ms (der Wert hängt natürlich von dem Modell ab) hoch. Dadurch öffnen sich die Lamellen während die Shutter Position sich nicht merklich verändert. Umgekehrt fahre ich sie wieder zu. 

Den aktuellen Zustand (also ob Lamellen zu oder Lamellen offen sind) halte ich in einem Objekt fest. Hierzu überwache ich mit einem weiteren Script den Shelly-State und gucke ob ein "Close" oder "Open" Event getriggert wurde und ändere entsprechend den Zustand der Lamellen im Objekt. Das funktioniert dann auch bei manueller Bedienung über die Wandschalter. 

Allerdings hat das ganze einen Haken: 
Selbst bei einer ganz kurzen Bewegung der Shutter per Script (in meinem Fall wie gesagt 700ms) registriert Shuttercontrol die Veränderung und setzt den Modus auf "Manu_Mode". Dementsprechend wird danach der Sonnenschutz nicht mehr korrekt ausgeführt und auch nicht mehr korrekt beendet. Auch die Option "Halte Rolladen im Sonnenschutz" hilft hier nicht weiter.

Auch ich würde hier eine Lösung sehr begrüßen - im Idealfall eine die komplett ohne zusätzliches Script auskommt und auch solche Aktoren berücksichtigt, die keinen eigenen Datenpunkt für die Lamellen haben (wie eben die Shelly 2.5).

**Comment by simatec** [comment]
Ich würde hier mit Alias arbeiten. Alias ist für das verknüpfen solcher Anwendungen entwickelt wurden. 
Den erzeugten Alias könnt ihr dann in shuttercontrol als Rollladen eintragen
