### ISSUE TITLE
has no existing object nach upgrade js-controller 3.2.x

### ISSUE THREAD

**Issue by crunchip77** [simatec/ioBroker.shuttercontrol#153]
folgende Meldung seit dem JS-Controller upgrade
`

(21563) State "shuttercontrol.0..control.Holiday" has no existing object, this might lead to an error in future versions
--

`

**Comment by simatec** [comment]
Wird in der nächsten Version gefixt

**Comment by simatec** [comment]
fix in Version 1.1.2
