### ISSUE TITLE
Frostschutz vorsehen

### ISSUE THREAD

**Issue by SpezialAgent** [simatec/ioBroker.shuttercontrol#162]
Ich hatte heute das Problem, dass bei einer Terassentür das Rollo am Boden festgefroren war. Ich habe nun allen drei Terassentüren den Wert für das runterfahren auf 20 gesetzt.

Was hältst du von dem Vorschlag, eine "Frost-Einstellung" einzubauen.

Wenn Aussentemperatur < XX °C dann fahre die Rollos nur auf xx% runter und nur YY% hoch (damit die nicht oben festfrieren.

**Comment by Monox83** [comment]
Habe auch das Problem, einen spalt offen zu lassen, ist natürlich ein Weg, dazu muss aber auch das Wetter der Nacht berücksichtigt werden.
Darunter leidet aber die Wärmedämmung. Muss man abwägen...
Ich bin am überlegen ob ich kleine Korkabstandshalter anbringe um unten einen kleine Bereich offen zulassen, aber das Rollo kann vollständig runter fahren.

**Comment by SpezialAgent** [comment]
Ich habe das in der Zeit mit Schnee und Frost so gelöst, dass ich die Angabe von Geschlossen von 0 auf 10 erhöht habe. Da blieb der Rollladen immer einige Zentimeter über den Boden stehen und verklebte nicht mit Schnee und Eis.
Das ist keine schöne Lösung, aber ich kam so durch den Winter.

**Comment by simatec** [comment]
Kommt in Version 1.3.0

**Comment by SpezialAgent** [comment]
Hallo Simatec,

wann ist denn mit der Version 1.3 zu rechnen?

Mit freundlichen Grüßen 

Martin Brüning
