### ISSUE TITLE
Nutzung mit shelly 2.5 bei Jalousieschalter mit Wippe / Sperre

### ISSUE THREAD

**Issue by MpunktMpunkt** [simatec/ioBroker.shuttercontrol#163]
Meine Rollläden werden durch Shelly 2.5 und Jalousieschaltern mit Wippe und Sperre gesteuert. Die mechanische Sperre verhindert dabei, den Motor gleichzeitig mit Auf und Ab anzusteuern.

Es kann dabei vorkommen, dass ein Schalter in der Stellung Auf oder Ab verbleibt. Das bedeutet, dass ich den Shelly 2.5 immer erst mit "Pause" ansteuere bevor ich den Rollladen mit einem bestimmen Level ansteuere. Dadurch wird die Stellung des mechanischen Schalters quasi "übersteuert" und somit neutralisiert. Geschieht dies nicht und der Shelly 2.5 bekommt den Befehl zum schließen (Level 0) während der mechanische Schalter auf "Auf" steht (oder umgekehrt), würde man Gefahr laufen, den Motor gleichzeitig in beide Richtungen anzusteuern.

In shuttercontrol habe ich hierfür kein Setting gefunden. Macht shuttercontrol das automatisch? Falls nicht wäre es prima, wenn es in den Extra Einstellungen hierfür ein Setting gäbe in der Art "Vor jeder Ansteuerung Datenpunkt ... aktualisieren".

Der DP im Shelly 2.5 ist ein button und lautet z.B. shelly.0.SHSW-25#xyz#1.Shutter.Pause

In Blockly aktualisiere ich diesen DP einmal, was dem Drücken des Buttons Pause entspricht.

**Comment by simatec** [comment]
Ist für shuttercontrol nicht geplant...

**Comment by MpunktMpunkt** [comment]
Ok, dann muss ich bei Blocky bleiben.

Danke Dir.

**Comment by simatec** [comment]
Nein du solltest es technisch sauber lösen. Mit 230V sollte man nicht experimentieren

**Comment by MpunktMpunkt** [comment]
Wie meinst Du das?

Die Jalousieschalter sind Standard. Hier wird mechanisch verhindert, dass der Motor in zwei Richtungen gleichzeitig angesteuert wird. Aber aufgrund der Bauart kann es eben sein, dass der Schalter in einer Stellung stehen bleibt.

Mag sein, dass man heute nur noch Taster für diese Anwendung verbaut.

Der Shelly 2.5 nimmt darauf Rücksicht, indem er eine Pause triggern kann und damit die jeweilige Phase zum Motor stromlos schaltet und somit die mechanische Schalterstellung neutralisiert.

Das hat ja nichts mit "experimentieren" an 230V zu tun.

**Comment by MpunktMpunkt** [comment]
https://www.shelly-support.eu/forum/index.php?thread/3327-shelly-2-5-und-gira-015800-jalousietaster/&postID=41032#post41032

Das Thema hat sich damit erledigt.
