### ISSUE TITLE
Extra-Einstellungen funktioniert nicht

### ISSUE THREAD

**Issue by amg666** [simatec/ioBroker.shuttercontrol#165]
Wenn ich im Adapter unter Extra-Einstellungen bei
"Objekt-ID zum Aktivieren/Deaktivieren des Auto-Schlafbereichs (z.B. Anwesenheitserkennung)" einen Datenpunkt (typ Boolean, wahr/falsch) eintrage dann hat das keinen Einfluss auf den Adapter. Egal ob true oder false der Adapter steuert weiterhin die Rolläden.
Aus der Adapterbeschreibung hätte ich erwartet, dass bei einem "true" die Steuerung aktiv ist und bei "false" deaktiviert.
Ich wollte ursprünglich sicherstellen, dass meine Rolläden bei Frost nicht mehr gesteurt werden (Variable, die in einem Skript gesetzt wird). Um Fehler auszuschliessen habe ich es aber auch mit anderen Datenpunkten aus Objekten versucht, die wahr oder falsch sind, das hatte ebenfalls keine Auswirkungen

**Comment by simatec** [comment]
Hab es gerade getestet ... Die Objekte `shuttercontrol.0.control.autoLiving` und `shuttercontrol.0.control.autoSleep` werden sauber gesetzt. 
Eventuell hast du für deine Rollläden nicht den korrekten Typ der Steuerung ausgewählt.
Hier müsste dann jeweils Wohnbereich (Automatik) oder Schalfbereich (Automatik) ausgewählt sein.

**Comment by amg666** [comment]
Danke für die Rückmeldung, dann war das mein Fehler, die Geräte standen auf Wohnbereich und Schlafbereich und nicht auf Wohnbereich(Automatik), Schlafbereich(Automatik).
Ich hab das grade nochmal gecheckt, in der Adapterbeschreibung steht es unter "Individuelle Rollladeneinstellungen" auch drin, dass auf die Extras Einstellungen nur geachtet wird, wenn man ...(Automatik) auswählt.
Vielleicht wäre es sinnvoll in der Beschreibung unter "Extra-Einstellungen" nochmal den Hinweis zu geben, dass die nur greifen wenn auch ...(Automatik) gewählt wurde ? Da kam mein Fehler her, ich habe mir nur den Abschnitt angeschaut um zu checken ob ich alles richtig eingetragen habe und habe daher den Hinweis auf ...(Automatik) nicht mitbekommen.
