### ISSUE TITLE
Sonnenschutz zusätzlich in Abhängigkeit von der Sonnenhöhe

### ISSUE THREAD

**Issue by lonsimbt** [simatec/ioBroker.shuttercontrol#166]
Es wäre hilreich, wenn beim Sonnenschutz nach Himmelsrichtung zusätzlich auch ein Bedingung zur Sonnenhöhe angegeben werden könnte. In den Wintermonaten misst mein Sonnensensor richtigerweise Sonnenschein und die Sonne steht auch in der für mein Arbeitszimmer angegebenen Himmelsrichtung, sie steht aber nicht über den umliegenden Häusern und damit auch nicht auf dem Fenster des Arbeitszimmers.

**Comment by vain90** [comment]
"EXTRA-EINSTELLUNGEN" --> "Astro-Einstellungen" --> "Beenden der Sonnenschutzfunktion mit Sonnenhöhe (Elevation)"

Ist es das was du suchst?

**Comment by simatec** [comment]
Nimm die Himmelsrichtungen mit in deine Sonnenschutz Optionen auf und du kannst nach Sonnenstand fahren.

**Comment by lonsimbt** [comment]
Aber nur nach Azimut und nicht nach Elevation. Oder übersehe ich etwas?
