### ISSUE TITLE
Anzeige Zeit für Hoch-/Runterfahren in Konfiguration

### ISSUE THREAD

**Issue by Bostil87** [simatec/ioBroker.shuttercontrol#167]
Wie im Forum besprochen: Die Anzeige der jeweiligen Fahrzeit unter Berücksichtigung des eingestellten Offsets direkt in der Konfiguration könnte sehr hilfreich sein. DANKE @simatec 

https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v1-1-x/2890

**Comment by simatec** [comment]
Ist nicht geplant, das es eine Config ind keine VIS ist. 
Eventuell kommt ein Tab Menü. Dort könnte man sowas einbauen
