### ISSUE TITLE
Alarmanlage mit einbinden

### ISSUE THREAD

**Issue by Monox83** [simatec/ioBroker.shuttercontrol#17]
Hi, super Adapter, wollte ich mal als Script so lösen war aber bis jetzt zu faul.
Währe es noch mögliche für jedes Rollo zu prüfen ob eine variabel true oder false ist um das fahren komplett zu unterbinden.

Zb fahren die Rollos bei mir im EG nicht hoch, wenn keiner da ist.

Grüße Monox

**Comment by simatec** [comment]
Das kannst du mit der aktuellen Version lösen. 
Jeder Rolladen legt 3 Datenpunkte für den Autobetrieb an. Hoch, runter und Sonnenschutz

**Comment by Monox83** [comment]
Super danke
