### ISSUE TITLE
Zweite Rollladenhöhe  bei Erhöhter Sonneneinstrahlung 

### ISSUE THREAD

**Issue by Maddin3011** [simatec/ioBroker.shuttercontrol#172]
Würde mir eine zweite Rollladenstufe wünschen.

Beispiel
(Rolladen offen bei 100%)
Stufe 1 - Rollladen bei Helligkeit von >40000 lumen auf 70%.
Stufe 2 - Rollladen bei Helligkeit von >60000 lumen auf 10% (also fast zu).

Somit wäre  der Sonnenschutz je nach Lichtitensität grösser oder eben kleiner, der zu beschattende Raum mehr oder weniger dunkel.

> *created by ioBroker.info*

**Comment by radebold** [comment]
Das wäre gerade bei den Temperaturen für mich auch sehr wichtig

**Comment by Tweety94** [comment]
Alternativ könnte man die Höhe als Variable/Datenpunkt angeben. Dann könnte man das flexibel mit einem Skript steuern.

**Comment by radebold** [comment]
@simatec 

Hi, gibt es zu diesem Thema schon etwas Neues?

**Comment by simatec** [comment]
Aktuell nicht in Planung, da dies ein sehr großer Umbau des Codes wäre

**Comment by simatec** [comment]
Man könnte hier einen Alarm Zweckentfremden ... Denke Feueralarm wäre hier ne Möglichkeit.
Bei Außentemp > xx den State setzen und die Rollläden fahren auf den gewünschten Wert

**Comment by simatec** [comment]
Wurde mit der Hitzeschutz Funktion erledigt
