### ISSUE TITLE
Automatiksteuerung nach Elevation

### ISSUE THREAD

**Issue by pphlwmarcel** [simatec/ioBroker.shuttercontrol#173]
Hallo,

leider habe ich noch keine Möglichkeit gefunden, Rolladen über den Sonnenstand (Elevation) zu öffnen.
Die Golden Hour und der Sonnenaufgang ist leider jeweils zu spät für meine Bedarfe (Ich öffne aktuell bei einer Elevation von -4°).
Vielleicht ist es möglich, den Wert sogar für die einzelnen Bereiche so zu konfigurieren, alternativ nur individuell pro Rolladen.

Viele Grüße
Marcel

**Comment by simatec** [comment]
Ab Version 1.2.0 kannst du über einen Helligkeitssensor öffnen und schließen.
Das macht sicher für deine Anforderungen mehr Sinn

**Comment by pphlwmarcel** [comment]
Hallo und vielen Dank für die Implementation des Helligkeitssensors. Mit dem Wert kann ich grundsätzlich gut arbeiten.

So wie ich das sehe, kann ich den Helligkeitswerte aber but systemweit eingeben und nicht pro Rolladen/Zone definieren bei welcher Helligkeit geöffnet wird oder? 

Das wäre grundsätzlich gut wenn das gehen würde.

viele Grüße 
Marcel
