### ISSUE TITLE
Sonnenschutz Zeitverzögerung

### ISSUE THREAD

**Issue by pphlwmarcel** [simatec/ioBroker.shuttercontrol#174]
Hallo,

zusätzlich zur prozentualen Hysterese der einzelnen Faktoren wäre es super, wenn eine Zeitverzögerung zum Öffnen / Schließen beim Sonnenschutz eingetragen werden kann.

Viele Grüße
Marcel

**Comment by mhoerche** [comment]
Das würde ich auch begrüßen! 
Heute ist es abwechselnd sonnig und bewölkt. Die Rolladen fahren ständig rauf und runter.

**Comment by Dino0811** [comment]
Das wäre wirklich sehr gut. 
Ich habe aktuell einen Schwellenwerte von 500 W/m² meiner Wetterstation eingesetzt.
Zusätzlich habe ich eine eigene Variable, welche per Blockly über eine Liste mit 10 Einträgen den 10 Minuten Mittelwert bildet - so dass bei einer größeren Wolke nicht sofort aufgefahren wird.

**Comment by simatec** [comment]
Es macht Sinn mehrere Faktoren einzusetzen. Nur nach Helligkeit fahren halte ich für nicht Sinnvoll, da man im Frühjahr oder Herbst eher die Sonnenstrahlen im Haus haben will, um Heizkosten zu sparen. 
nutzt eine zusätzliche Option wie Innentemperatur oder der gleichen und ihr habt dieses Problem nicht mehr
