### ISSUE TITLE
Log-Eintrag mit js-Controller 3.3.1

### ISSUE THREAD

**Issue by darkman242** [simatec/ioBroker.shuttercontrol#175]
Nach Update des js-Controllers wird nachfolgendes im Log angezeigt.

`

shuttercontrol.0 | 2021-04-30 07:30:00.004 | warn | State value to set for "shuttercontrol.0.info.Elevation" has wrong type "number" but has to be "string"
-- | -- | -- | --
shuttercontrol.0 | 2021-04-30 07:30:00.004 | warn | State value to set for "shuttercontrol.0.info.Azimut" has wrong type "number" but has to be "string"

`

**Comment by MMeinhardt1** [comment]
Ich hänge mich mal mit folgender Meldung mit an,


Adaptername | Uhrzeit | Status | Meldung
-- | -- | -- | --
shuttercontrol.0 | 2021-05-02 20:49:00.150 | info | State value to set for "shuttercontrol.0.shutters.autoLevel.Jalousie_Keller" has to be type "number" but received type "string"

**Comment by Schimi1983** [comment]
shuttercontrol.0	2021-05-03 12:40:00.007	info	State value to set for "shuttercontrol.0.info.Elevation" has to be type "string" but received type "number"
shuttercontrol.0	2021-05-03 12:40:00.006	info	State value to set for "shuttercontrol.0.info.Azimut" has to be type "string" but received type "number"

**Comment by simatec** [comment]
Fix in 1.2.0
