### ISSUE TITLE
Status für Rollladen aktiv hinzufügen

### ISSUE THREAD

**Issue by passuff** [simatec/ioBroker.shuttercontrol#18]
Ich würde es begrüßen, wenn ich an einem Datenpunkt ablesen könnte, ob ein Rollladen gerade vom Adapter, oder manuell gesteuert wurde.

**Comment by simatec** [comment]
Was stellst du dir genau vor? Wie soll der Datenpunkt aussehen und was soll er ausgeben?

**Comment by passuff** [comment]
Ein Dp Typ Logik der, sobald und solange das Skript einen Rolladen steuert (und der Rl nicht per Taster gefahren wird) auf "true" gesetzt wird.

**Comment by simatec** [comment]
Nehme ich mit auf die Todo

**Comment by passuff** [comment]
Danke!

simatec <notifications@github.com> schrieb am Do., 18. Juli 2019, 10:46:

**Comment by irudi** [comment]
Das würde gut zu #13 passen: pro Rolladen ein Objekt, mit einem Logikwert auto true/false und dem level, den der Rolladen hat bzw. laut Berechnung der Automatik haben sollte.

**Comment by simatec** [comment]
kommt mit Version 0.7.4
