### ISSUE TITLE
Benachrichtigung über "Telegram"

### ISSUE THREAD

**Issue by mumu-rik** [simatec/ioBroker.shuttercontrol#180]
Es wäre wünschenswert im Adapter auch die Benachrichtigung in Richtung "Telegram" anzusteuern, so dass man per Telegram benachrichtigt wird, wenn die Rollos hoch/runter fahren.

**Comment by simatec** [comment]
Ist nicht geplant und kann sehr einfach mit dem Adapter „Ereignisse“ umgesetzt werden
