### ISSUE TITLE
Bosch/HomematicIP und Rolladenhöhe passen nicht zusammen

### ISSUE THREAD

**Issue by firebowl** [simatec/ioBroker.shuttercontrol#185]
Die Rolladenhöhe muss zwischen 0 und 100 definiert werden.
Bei Bosch Rolladenaktoren werdeb die Höhen aber leider anders angegeben.
100% geöffnet wird mit 1 angegeben.
Eine 10% Veränderung ist demnach eine 0,1 Veränderung.

Zur Verdeutlichung:

Manuell über die App oder direkt am Taster auf 10% geschlossen:
![image](https://user-images.githubusercontent.com/73579226/118545188-8ddbe100-b756-11eb-9a6e-2b072fcaa8c6.png)

Nach Klick auf openAll:
![image](https://user-images.githubusercontent.com/73579226/118545506-fc20a380-b756-11eb-8ad5-8e4eb70c096f.png)

So sieht es danach im Bosch Adapter aus:
![image](https://user-images.githubusercontent.com/73579226/118545563-0b075600-b757-11eb-8c12-e0c227d37b88.png)

Anstatt der 100 müsste aber eine 1 eingetragen werden damit der Bosch Adapter etwas tut.

**Comment by firebowl** [comment]
Danke, funktioniert. :)

**Comment by RkcCorian** [comment]
Freut mich! :-) Danke für die Rückmeldung!
