### ISSUE TITLE
Manueller Betrieb wird nicht berücksichtigt (Fürs Lüften)

### ISSUE THREAD

**Issue by RkcCorian** [simatec/ioBroker.shuttercontrol#186]
**Is your feature request related to a problem? Please describe.**
Ich würde gerne den Adapter benutzen. Allerdings habe ich folgendes Problem: Wenn ich den Rollladen über Alexa oder Manuell runterfahre und das Fenster bereits offen ist erkennt der Adapter dies nicht und fährt komplett runter.

**Describe the solution you'd like**
LEVEL überwachen und bei offener Tür / offenem Fenster begrenzen oder falls nicht möglich den Rollladen auf Lüftungsposition fahren, sobald er unten ist. (Habe es aktuell mit einem eigenen Skript gelöst, da ich nicht in die Steuerung eingreifen kann, aber nachdem der Rollladen komplett unten ist fahre ich direkt auf Lüftungsposition.

**Describe alternatives you've considered**
Eigene zusätzliche Skripte

**Additional context**
Bin für Rückfragen offen :-)

**Comment by simatec** [comment]
Dies kannst du in den Einstellungen der einzelnen Rollläden konfigurieren und festlegen, was bei offenen Fenstern passieren soll. In der Doku steht dies sehr gut beschrieben.

**Comment by RkcCorian** [comment]
Ggf. habe ich die Beschreibung nicht ausreichend beschrieben... es geht darum, dass paralleler MANUELLER Betrieb nicht "richtig" berücksichtigt wird, bzw. gar nicht.
