### ISSUE TITLE
autoState: Erweitern um den Zustand: "Lüften" (bzw. englischer Übersetzung)

### ISSUE THREAD

**Issue by RkcCorian** [simatec/ioBroker.shuttercontrol#188]
**Is your feature request related to a problem? Please describe.**
autoState um den Zustand "Lüften" erweitern, wenn der Rollladen aufgrund Tür-/Fensteröffnung etwas hochgefahren wurde

**Describe the solution you'd like**
Fehlenden Zustand "Lüften" melden

**Describe alternatives you've considered**
Sehe keine Alternative

**Additional context**
Bin für Rückfragen offen :-)

**Comment by simatec** [comment]
Es muss ja nicht zwingend zum Lüften geöffnet werden … also sehe ich den state lüften als nicht passend.

**Comment by RkcCorian** [comment]
Schade, hab den Adapter wieder deinstalliert und eigene Skripte geschrieben. Diese unterstützen Zustände bislang...
  "0": "Benutzer",
  "1": "Aussperrschutz",
  "2": "Lüften",
  "3": "Sonnenuntergang",
  "4": "Beschattung",
  "5": "Anwesenheitssimulation",
  "6": "Sonnenaufgang"
