### ISSUE TITLE
autoState: Leer

### ISSUE THREAD

**Issue by RkcCorian** [simatec/ioBroker.shuttercontrol#189]
**Describe the bug**  
autoState ist leer, sollte m.E. jedoch jederzeit einen Status anzeigen

**To Reproduce**  
1. Rollladen wurde Abends automatisch über den Adapter runtergefahren
2. Fenster wurde geöffnet, Rollladen fuhr korrekt in Lüftungsposition
3. Rollladen wurde manuell "etwas" weiter hochgefahren
4. Fenster wurde geschlossen, Rollladen fährt automatisch nach ganz unten
Bis hier hat der Rollladen korrekt funktioniert. Allerdings ist der Status des Rollladen nun leer

**Expected behavior**  
autoState zeigt den korrekten Status

**Screenshots & Logfiles**  
Falls gewünscht kann ich versuchen den Fehler nachzustellen und ein Log aufzeichen. Bitte sagen was hier hilfreich wäre.

**Versions:**  
 - Adapter version: 1.1.5
 - JS-Controller version: 3.1.6 
 - Node version: 12.21.0 
 - Operating system: Synology NAS, Docker

**Additional context**

**Comment by simatec** [comment]
Gefixt in version 1.2.1
