### ISSUE TITLE
Rollo fahren über Helligkeitssensor

### ISSUE THREAD

**Issue by DrHappy90** [simatec/ioBroker.shuttercontrol#191]
Ich lasse die Rollos über das neue Feature Helligkeitssensor schließen.
Die Zeitverzögerung wirkt leider nicht, sprich alle Rollos fahren gleichzeitig.
Eventuell kann man die Verzögerung auf Rollos gruppieren z.B Terrassentür und Fenster daneben sollen gleichzeitig fahren, der Rest mit Verzögerung.
Der Griffsensor lässt das Rollo beim Öffnen nach oben fahren, sobald er geschlossen wird fährt der Rollo wieder runter obwohl: 
Art der Steuerung für schließen des Rollladens --> Helligkeitssensor
Rollladen fahren bei Änderung des Fenster/Tür Zustandes --> Öffnen
Rollladenautomatik auch bei geöffneten Fenster/Tür benutzen (Aussperrschutz) --> Öffnen

Ist es möglich Rolladen Verzögerung bei Fenster schliessen (s) auf min. 3600 s zu erhöhen?

Vielen Dank für deine Arbeit, bester Adapter.

**Comment by simatec** [comment]
Gefixt in Version 1.2.1
