### ISSUE TITLE
'Rolläden schließen spät in der Nacht' schließt nur einen Rollladen

### ISSUE THREAD

**Issue by mango1402** [simatec/ioBroker.shuttercontrol#192]
**Describe the bug**
bei aktivierter Option 'Rolläden schließen spät in der Nacht' fährt nur der erste in der Liste unter 'Haupteinstellung' parametrierte.

**To Reproduce**
1. wait for automatic closing of (more than one) shutter
2. Open (more than one) shutter manually
3. wait until 'down late all' time exceeds
--> only the first parameteritzed of List from 'Haupteinstellung' closed, all other do not move.

**Expected behavior**  
Es sollten alle Rollos schließen, bei denen die Funktion 'Rollläden spät schließen' aktiviert ist.

**Screenshots & Logfiles**  
[iobroker.2021-05-24_Shuttercontrol_bug.log](https://github.com/simatec/ioBroker.shuttercontrol/files/6532367/iobroker.2021-05-24_Shuttercontrol_bug.log)
(Logfile beinhaltet Ausgaben von V1.2.0 und V1.1.5)

**Versions:**  
 - Version 1.2.0 in /opt/iobroker/node_modules/iobroker.shuttercontrol, node: v12.22.0, js-controller: 3.2.16
 - Operating system: Raspian OS

**Additional context**  
Diese Funktionalität funktioniert jedoch mit Version 1.1.5 einwandfrei!
Für weitergehende Infos bzw. Tests und Logs stehe ich gerne zur Verfügung.

**Comment by selfmadesmarthome** [comment]
Hab das gleiche Problem

**Comment by simatec** [comment]
Fix in Version 1.2.1
