### ISSUE TITLE
Frage zur Elevation

### ISSUE THREAD

**Issue by maschinsta** [simatec/ioBroker.shuttercontrol#194]
Hallo! Vielen Dank für den tollen Adapter. Ich hatte es bisher mit vielen komplizierten Blocklys gelöst. Nun will ich gerne das Jalousien bei einer Elevation von mind. -6 hochfahren. Aber erst 6:00 und spätestens 9:00. Ich bekomme das nicht hin. Es funktioniert entweder nur Zeit oder nur Sonnenaufgang. Der Sonnenaufgang jetzt ist mir aber jetzt zu zeitig. Kann man das mit dem Adapter lösen?
Vielen Dank

**Comment by Dino0811** [comment]
Hallo,
Das würde mich auch interessieren.
Ich möchte auch eine Kombination fahren - in meinem Fall nicht nach Elevation sondern nach Helligkeitssensor...und auch hier eine zeitliche Einschränkung geben wann dies frühestens geschieht. - Wie realisiert man diese Einschränkung?

**Comment by simatec** [comment]
Nein das ist nicht möglich. Entweder Elevation oder was für eure Fälle eher passt ist Zeiteinstellung in Verbindung mit Goldenhour. Da könnt ihr auch die Grenzzeiten festlegen und auch noch Verzögerungen einstellen.
