### ISSUE TITLE
Helligkeitssensor - Manuelles Öffnen danach nicht möglich

### ISSUE THREAD

**Issue by 5G7K** [simatec/ioBroker.shuttercontrol#195]
Hallo Simatec, ich habe die neue Funkton mal getestet. Folgendes ist mir aufgefallen:

Rollladen wurde mit der neuen Funktion "Helligkeitssensor" geschlossen. ->ok
Rollladen wird danach wieder manuell geöffnet.
Jede Minute habe ich einen Eintrag im Log: 
`2021-06-04 22:51:00.181 - debug: shuttercontrol.0 (7875) Brightness sensor value: 1`
Nun wird der Rollladen wieder geschlossen, weil Helligkeit korrekterweise zu gering ist.
Dieser sollte aber trotzdem offen bleiben, nachdem er wieder manuell geöffnet wurde.

**Comment by 5G7K** [comment]
Bringst du gerade Öffnen/Schließen per Helligkeitssensor (Sonne mehr als z.B. 500 öffnen der ROllladen, unter 400 = Schließen) und Sonnenschutz per Lichtsensor (Sonne mehr als 700 = Sonnenschutz) durcheinander?

**Comment by Dino0811** [comment]
Sonnenschutz-Einstellung:
Sollwert des Sonnenschutzlichtsensors (500) --> ab 500+ wird in Sonnenschutzposition gefahren

Extra-Einstellungen -> Einstellungen Helligkeitssensor:

hier wäre dann " Öffnen/Schließen per Helligkeitssensor (Sonne mehr als z.B. 500 öffnen der ROllladen, unter 400 = Schließen)" gemeint?

zu diesem Punkt habe ich leider keine Doku/Info's gefunden und weiß nicht recht was hier einzustellen ist.
Gefühlt würde "größer 500 = öffnen" und "kleiner 400 = schließen" ja der oben genannten Sonnenschutzschwelle widersprechen? - denn je höher der Wert desto mehr Sonne/Licht ist ja present - oder kann ich die Werte hier auch leer lassen?

**Comment by 5G7K** [comment]
Ich bin mir unsicher, ob wir vom Gleichen reden...

In den Sonnenschutz-Einstellungen (direkt in den Rollladeneinstellungen pro Rollladen) definiert man den Sonnenschutz ab Licht > x und die Hystherese

Der Lichtsensor in den Extra-Einstellungen hat damit nichts zu tun meines Wissens. Diese Einstellungen dort kann man in den Rollladen-Einstellungen verwenden, um das Öffnen oder Schließen zu steuern (anstatt z.B. Öffnen nach Uhrzeit oder Sonnenstand)

**Comment by Dino0811** [comment]
> Der Lichtsensor in den Extra-Einstellungen hat damit nichts zu tun meines Wissens. Diese Einstellungen dort kann man in den Rollladen-Einstellungen verwenden, um das Öffnen oder Schließen zu steuern (anstatt z.B. Öffnen nach Uhrzeit oder Sonnenstand)

Ok, das hat den Knoten in meinem Kopf gelöst...da stand ich auf dem Schlauch. Danke! - dann macht die entgegengesetzte Einstellung der Werte natürlich Sinn. - Somit kann diese Einstellung auch nicht für das sofortige runterfahren nach manueller Schalterbetätigung verantwortlich sein (was ich zuerst vermutet hatte)

Dann hoffe ich mal auf einen FIX dieses Problems. - denn die Beschattung per Helligkeitssensor finde ich super, da sitzen unsere Katzen nicht aus Spaß jeden Tag im düsteren sondern nur wenn es auch notwendig ist...

Danke für deine Hilfreiche Antwort!

**Comment by simatec** [comment]
> Hallo Simatec, ich habe die neue Funkton mal getestet. Folgendes ist mir aufgefallen:
> 
> Rollladen wurde mit der neuen Funktion "Helligkeitssensor" geschlossen. ->ok
> Rollladen wird danach wieder manuell geöffnet.
> Jede Minute habe ich einen Eintrag im Log:
> `2021-06-04 22:51:00.181 - debug: shuttercontrol.0 (7875) Brightness sensor value: 1`
> Nun wird der Rollladen wieder geschlossen, weil Helligkeit korrekterweise zu gering ist.
> Dieser sollte aber trotzdem offen bleiben, nachdem er wieder manuell geöffnet wurde.

Das scheint ein Bug zu sein. Schaue ich mir an.

**Comment by simatec** [comment]
Fix in Version 1.2.1
