### ISSUE TITLE
Rolladen fahren Abends nicht immer runter

### ISSUE THREAD

**Issue by dAjaY85** [simatec/ioBroker.shuttercontrol#196]
Rolladen fahren nur ab und zu automatisch runter, in der Regel muss ich manuell den Button in iobtoker drücken. Mittels Button Close Living fahren alle Rolladen wie gewünscht runter.

Kann es eventuell sein, das in einer bestimmten Konstellation, das Runterfahren der Rolladen nicht getriggert wird?

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: 3.3.11
 - Node version: v12.22.0
 - Operating system: Linux, Raspberry Pi OS

**Comment by simatec** [comment]
Ich kann ohne genauer Angaben leider nur in die Glaskugel schauen, wie deine Config ausschaut und was bei dir so passiert
