### ISSUE TITLE
Möglichkeit für String als Level

### ISSUE THREAD

**Issue by Schmakus** [simatec/ioBroker.shuttercontrol#197]
Ich verwende wie viele andere vermutlich auch, HomematicIP für die Rollladen-/Jalousiensteuerung.
Bei der Lamellenverstellung der Jalousien stößt Shuttercontrol dabei aktuell an seine Grenzen.

Das Problem ist, dass Homematic für die Lamellenverstellung immer 2 Werte verlangt. Zuerst die Position der Lamellen und dann eine Behanghöhe. Bedeutet man muss 2 Datenpunkte nacheinander beschreiben.

Für das ausschließliche Schließen und Öffnen der Jalousien funktioniert dies, wenn man quasi in der Adapter Config für die Lamellenverstellung und Behanghöhe einen separaten "Rollladen" anlegt.

Jedoch funktioniert dies nicht ordentlich beim Sonnenschutz und andere Funktionen. Auch wird es sehr schnell unübersichtlich.

Jedoch gibt es bei Homematic einen weiteren Datenpunkt: "Combined_Parameter". Mit diesem kann man die Lamellenverstellung und Behanghöhe gleichzeitig setzten. Der Datenpunkt ist vom Typ "String"

Leider lässt der Adapter "ShutterControl" nur einen numerischen Wert als Level zu.

**Describe the solution you'd like**
Als Level sollte es die Möglichkeit geben, auch einen String vorzugeben.
Beispiele:
Geöffnet:  **L=100,L2=101** (L: Behanghöhe 100%, L2 Lamellen => 101% = ignoriert)
Geschlossen: **L=0,L2=0**
Bei Fenster offen: L=101,L2=50 (Behanghöhe 101% = ignoriert, Lamellen 50%)
usw.

**Describe alternatives you've considered**
Alternativ evtl. 2 Datenpunkte pro "Rollladen". Einen für die Behanghöhe und einen für die Lamellenverstellung, welche mit einem kurzen Zeitabstand gesetzt werden.
Die könnte evtl. auch für andere Aktoren wie z.B. shellys, etc. verwendet werden. Wie dort die Gegebenheiten sind, kann ich aufgrund fehlender Hardware nicht sagen.

**Additional context**
Ich denke, als "Level" einen String vorzugeben, dürfte die einfachere Variante sein. Gerne könnte ich eine Test Version erstellen, benötige jedoch hierfür die Information, wo im Script überall der Level verwendet wird.

EDIT: Habe nicht beachtet, dass der Adapter auch die aktuelle Behanghöhe überwacht. Demnach wird es vermutlich doch etwas komplexer mit dem String. Deshalb vermutlich doch die Variante mit 2 Datenpunkten....

**Comment by simatec** [comment]
Bitte erstelle für diese Anwendung ein Alias und nutze den erzeugten Alias als Rollladen in der Config von shuttercontrol. 

Alias wurde extra für solche Anwendungen entwickelt.
