### ISSUE TITLE
Innentemperatur & Lichtsensor & Himmelsrichtung fehlt mir

### ISSUE THREAD

**Issue by radebold** [simatec/ioBroker.shuttercontrol#198]
Hi,

in den Sonnenschutzeinstellungen fehlt mir die o.g. option.

Innentemperatur & Lichtsensor & Himmelsrichtung
Lichtsensor & Himmelsrichtung

Ich habe ein Niedrigenergiehaus und jeder Sonnenstrahl kommt rein, aber nicht wieder raus :-)

**Comment by simatec** [comment]
Schuttercontrol ist flexibel aufgebaut. 
Du kannst für deine Anwendung "Innen/Außentemperatur/Lichtsensor & Himmelsrichtung" nutzen und für die Außentemperatur nichts eintragen oder du nutzt die Option "Außentemperatur/Lichtsensor & Himmelsrichtung" und trägst die Daten der Innentemperatur bei der Außentemperatur ein.
