### ISSUE TITLE
Abwesenheitssteuerung und Sonnenschutz bei Anwesenheit 

### ISSUE THREAD

**Issue by maduuto** [simatec/ioBroker.shuttercontrol#199]
Hallo, vielleicht bin ich zu doof, aber aktuell habe ich ein Skript in ioBroker, was bei Abwesenheit close shutter for sun protect auslöst und alle bereiche auf manuell umstellt. Wenn ich Anwesend bin, gehen alle Bereiche per Skript wieder auf auto und in Shuttercontrol habe ich Anwesenheit auch direkt die Variable als Auslöser gesetzt.

Nun hätte ich gerne, dass die Rollläden bei Anwesenheit wieder in die Stellung fahren, die eigentlich geplant wäre, d.h. alle sonnenabgewandten Rollläden fahren hoch und die der sonne zugewandten bleiben unten, es sei denn ich bin z.B. nach 22 Uhr zuhause, dann sollen die gemäß Zeitplan so bleiben. Gibt es da eine Lösung, die ich übersehen habe? DAs scheint nicht richtig zu funktionieren.

**Comment by simatec** [comment]
Wenn du mit einem Skript eingreifst, fahren die Rollläden in den Manu Mode und bleiben bis zum abendlichen schließen so. Das ist so gewollt und steht auch in der Doku. 

Shuttercontrol arbeitet unabhängig von Anwesenheit nach den äußeren und inneren Bedingungen. 

Lass Shuttercontrol entscheiden und greife nicht mit Skripten ein.
