### ISSUE TITLE
Helligkeitswert

### ISSUE THREAD

**Issue by Loi83** [simatec/ioBroker.shuttercontrol#20]
Servus, ich kann in den Sonnenschutz Einstellungen der einzelnen Rollos nur einen Wert von 0 - 100 angeben. Mein Helligkeitssensor gibt aber in der Früh, wenn die Sonne noch gar nicht da ist, schon einen Wert von 1800 Lux aus. Kann man das irgendwie anpassen?

**Comment by simatec** [comment]
Wird gefixt ...
