### ISSUE TITLE
Jalousien fahren früh nicht hoch und abends nicht runter

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#200]
Hallo zusammen,

zunächst erst einmal vielen lieben Dank für die hervorragende Arbeit - dies erspart sehr viel individuellen Programmieraufwand. Tolle Sache!

Ich habe aber ein Problem - während der Sonnenschutz sehr gut funktioniert, fahren die Jalousien früh nicht hoch und abends nicht runter. Ich bin nach der Beschreibung vorgegangen, aber etwas scheint nicht richtig zu sein. 
Hat dies eventuell mit den Objekt-IDs der Trigger für den entsprechenden Bereich zu tun? Ich hab dort alles leer gelassen, weil ich nicht wusste was einzutragen ist. 

Auch ist mir aufgefallen, dass es jetzt unter Extra-Einstellungen neue Einstellungen für den Helligkeitssensor gibt. Was bewirken diese und haben diese eventuell etwas mit meinem Problem zu tun?

Vielen Dank und viel Grüße!

**Comment by simatec** [comment]
Bitte poste hier deine Config

**Comment by guitardoc** [comment]
Hier ist die configuration.

Danke schon mal im Voraus!

{
  "_id": "system.adapter.shuttercontrol.0",
  "common": {
    "name": "shuttercontrol",
    "version": "1.2.0",
    "title": "shuttercontrol",
    "authors": [
      "simatec <nais@gmx.net>"
    ],
    "contributors": [
      "Rene G. <info@rg-engineering.eu>"
    ],
    "keywords": [
      "ioBroker",
      "Smart Home",
      "home automation",
      "Rollladen",
      "Jalousie",
      "Rollladensteuerung"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "main": "main.js",
    "icon": "shuttercontrol.png",
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.shuttercontrol/master/admin/shuttercontrol.png",
    "readme": "https://github.com/simatec/ioBroker.shuttercontrol/blob/master/README.md",
    "loglevel": "info",
    "mode": "daemon",
    "type": "climate-control",
    "compact": true,
    "materialize": true,
    "connectionType": "local",
    "dataSource": "push",
    "stopBeforeUpdate": true,
    "adminUI": {
      "config": "materialize"
    },
    "plugins": {
      "sentry": {
        "dsn": "https://5f58df7167d846e3a90bae5414d4fc09@sentry.iobroker.net/62"
      }
    },
    "installedFrom": "iobroker.shuttercontrol@1.2.0",
    "installedVersion": "1.2.0",
    "host": "raspberrypi"
  },
  "native": {
    "livingAutomatic": "livingSunriseSunset",
    "W_shutterDownLiving": "23:00",
    "W_shutterUpLivingMin": "05:00",
    "W_shutterUpLivingMax": "08:00",
    "driveDelayUpLiving": "0",
    "WE_shutterDownLiving": "23:00",
    "WE_shutterUpLivingMin": "05:00",
    "WE_shutterUpLivingMax": "08:00",
    "sleepAutomatic": "sleepSunriseSunset",
    "W_shutterDownSleep": "23:00",
    "W_shutterUpSleepMin": "08:00",
    "W_shutterUpSleepMax": "09:00",
    "driveDelayUpSleep": "0",
    "WE_shutterDownSleep": "23:00",
    "WE_shutterUpSleepMin": "08:00",
    "WE_shutterUpSleepMax": "09:00",
    "childrenAutomatic": "childrenSunriseSunset",
    "W_shutterDownChildren": "20:00",
    "W_shutterUpChildrenMin": "06:00",
    "W_shutterUpChildrenMax": "06:30",
    "driveDelayUpChildren": "10",
    "WE_shutterDownChildren": "21:00",
    "WE_shutterUpChildrenMin": "06:00",
    "WE_shutterUpChildrenMax": "06:30",
    "latitude": "51.278486150000006",
    "longitude": "12.507069799527972",
    "sunProtEndElevation": "10",
    "astroDelayUp": "0",
    "astroDelayDown": "0",
    "driveDelayUpAstro": "0",
    "SummerStart": "01.03.",
    "SummerEnd": "30.09.",
    "XMasStart": "01.12.",
    "XMasEnd": "06.01.",
    "publicHolidays": true,
    "publicHolInstance": "feiertage.0",
    "HolidayDP": "feiertage.0.heute.boolean",
    "lightsensorDown": "400",
    "lightsensorUp": "500",
    "lightsensorUpDown": "wiffi-wz.0.root.192_168_188_3.w_lux",
    "schoolfree": false,
    "schoolfreeInstance": "",
    "schoolfreeChildrenArea": true,
    "schoolfreeSleepArea": false,
    "schoolfreeLivingArea": false,
    "LateAllDown": false,
    "LateAllDownTime": "22:15",
    "betweenPositionTime": "22:00",
    "noGoTime": "0",
    "currentShutterState": false,
    "currentShutterStateTime": "60",
    "triggerAutoSleep": "true",
    "triggerAutoLiving": "true",
    "triggerAutoChildren": "true",
    "heightDownSun": "100",
    "direction": "0",
    "type": "outside temperature and direction",
    "directionRange": "0",
    "actualValueTemp": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
    "actualValueLight": "wiffi-wz.0.root.192_168_188_3.w_lux",
    "actualValueTempInside": "",
    "typeDown": "living-auto",
    "typeUp": "living-auto",
    "triggerStateShutter": "true",
    "triggerChangeShutter": "off",
    "triggerDriveShutter": "100",
    "autoDriveShutter": "off",
    "heightDownShutter": "0",
    "heightUpShutter": "100",
    "triggerID": "",
    "LateDown": false,
    "inSummerNotDown": false,
    "driveAfterClose": false,
    "useXmasLevel": false,
    "XmasLevel": "0",
    "KeepSunProtect": false,
    "trigDelyUp": "0",
    "trigDelyDown": "0",
    "betweenPosition": false,
    "betweenPositionLevel": "50",
    "events": [
      {
        "enabled": true,
        "shutterName": "Bad Nordwestseite",
        "name": "shelly.0.SHSW-25#8CAAB55DC865#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "0",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Bad Nordseite",
        "name": "shelly.0.SHSW-25#8CAAB55DD307#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "0",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Bad Nordostseite",
        "name": "shelly.0.SHSW-25#84CCA8A121F4#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "0",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Arbeitszimmer",
        "name": "shelly.0.SHSW-25#483FDA826DF1#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "90",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Treppenhaus",
        "name": "shelly.0.SHSW-25#8CAAB55DBD6F#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "90",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Gästetoilette",
        "name": "shelly.0.SHSW-25#8CAAB55DE743#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "90",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Küche",
        "name": "shelly.0.SHSW-25#483FDA823847#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "90",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Südostseite",
        "name": "shelly.0.SHSW-25#483FDA820C6A#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "135",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Südseite",
        "name": "shelly.0.SHSW-25#483FDA8D26EC#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "180",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Südwestseite",
        "name": "shelly.0.SHSW-25#483FDA4D72DE#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "225",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Tür Wintergarten",
        "name": "shelly.0.SHSW-25#8CAAB55D8EED#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "270",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": true,
        "XmasLevel": "100",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Fenster Wintergarten",
        "name": "shelly.0.SHSW-25#68C63AFA7C16#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "100",
        "direction": "180",
        "directionRange": "0",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "true",
        "triggerDrive": "100",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": true,
        "XmasLevel": "100",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Tür Terrasse",
        "name": "shelly.0.SHSW-25#483FDA4CCB58#1.Shutter.Position",
        "triggerID": "shelly.0.SHDW-2#E8DB84D4EF9D#1.sensor.door",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "270",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": true,
        "XmasLevel": "100",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Gästezimmer",
        "name": "shelly.0.SHSW-25#10521CF12B71#1.Shutter.Position",
        "triggerID": "shelly.0.SHDW-2#E8DB84D324E1#1.sensor.door",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "270",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "100",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Schlafzimmer",
        "name": "shelly.0.SHSW-25#68C63AFAB018#1.Shutter.Position",
        "triggerID": "",
        "typeUp": "sleep-auto",
        "typeDown": "sleep-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "270",
        "directionRange": "45",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "wiffi-wz.0.root.192_168_188_3.w_temperatur",
        "tempOutside": "23",
        "lightSensor": "wiffi-wz.0.root.192_168_188_3.w_lux",
        "valueLight": "6000",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "100",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      }
    ]
  }
}

**Comment by guitardoc** [comment]
Ich habe zwischenzeitlich noch mal ein bisschen an den Parametern gedreht, das hat aber nichts gebracht. 
Die Jalousien fahren weiterhin früh nicht hoch und abends nicht runter… :-(

**Comment by simatec** [comment]
Du musst in den Objekten die states für living-auto und sleep-auto auf true setzen. 
Oder du wählst in den Rollladen Einstellungen nicht Wohnbereich Auto und Schlafbereich Auto sondern nur Wohnbereich bzw. Schlafbereich. 

Die Auto Bereiche sind eher für Bereiche gedacht, die nicht immer automatisch fahren sollen, sondern nur bei z.B. Abwesenheit

**Comment by guitardoc** [comment]
Funktioniert - danke!
