### ISSUE TITLE
Automatik fährt nicht nach manueller Bedienung

### ISSUE THREAD

**Issue by Toysman** [simatec/ioBroker.shuttercontrol#201]
Hallo simatec,

mir ist aufgefallen, das die Automatikfunktion, z.B. Beschattung, nach den manuellen öffnen der Beschattung 
nicht mehr greift. Die anderen Rolladen fahren je nach Einstellung runter | rauf, jedoch der manuell geöffnete
Rolladen bleibt, trotz Sonnenschein, weiterhin offen. Aktoren sind von Homematic und der Öffnungswert bleibt
bei 30% (Wert der Beschattung) und wird nicht aus dem Aktor ausgelesen, dort 100%.

<img width="1520" alt="Bildschirmfoto 2021-06-20 um 14 14 57" src="https://user-images.githubusercontent.com/76917387/122673682-e9741100-d1d1-11eb-9eb8-cfec3ee4e011.png">

Läßt sich dieses ändern ?

Danke & Gruß

**Comment by simatec** [comment]
Steht auch so in der Dolu und ist gewollt. Bis zum nächsten schließen am Abend bleibt der Manu Mode
