### ISSUE TITLE
Button autoposAll/Living/Children/Sleep und sunProtectChildren

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#202]
Laut https://github.com/simatec/ioBroker.shuttercontrol/issues/94 ist es so, dass die Buttons "openAll" & Co anscheinend nicht das tun, was sie sagen, sondern dass sie in den AutomatikModus fahren. Das ist jetzt nicht unmittelbar einsichtig.

Ich hätte mir erwartet, dass die Rollos wirklich einfach auf 100% hochfahren, wenn ich auf den Knopf drücke. Somit bräuchte es aus meiner Sicht eine Unterscheidung zwischen "Hochfahren" und in den "Automatismus fahren". Also wirkliche Buttons für 
-autoposAll & Co

Außerdem fehlt in der Version 1.2.0 der Knopf für
  sunProtectChildren

**Comment by simatec** [comment]
Die Buttons machen genau dass, was sie sollen. 
open und close sind ja eindeutig.

**Comment by poidi** [comment]
Hallo simatec. Fürchte wir verstehen uns nicht ganz.

1. Es fehlt der Button sunProtectChildren in 1.2.0
2. Wie kann ich alle Rolläden 
a) alle Öffnen und offen lassen (keine Automatik)
b) alle direkt in die automatische Position fahren (nach manuellen änderungen) ohne alle erstmals öffnen zu müssen.
