### ISSUE TITLE
spät schließen im sommer funktioniert nicht

### ISSUE THREAD

**Issue by sjfm-design** [simatec/ioBroker.shuttercontrol#203]
4 rollos, eingestellt alle gleich als kinderbereich für die werkstatt. sonnenaufgang funzt.
sollen um 19:00 schließen. aber im sommer, sollen sie erst um 21:00 schließen.
was soll ich sagen, die dinger sind einfach um 19:00 runter gerattert. es gibt keinen manu mode, nix.

**Screenshots & Config**  
https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v1-2-x/3307?_=1624136457019
[system.adapter.shuttercontrol.0.json.TXT](https://github.com/simatec/ioBroker.shuttercontrol/files/6688887/system.adapter.shuttercontrol.0.json.TXT)

```
shuttercontrol.0
	2021-06-21 19:00:00.215	info	#27 Set ID: Holz2 Position value: 0%
shuttercontrol.0
	2021-06-21 19:00:00.170	info	#27 Set ID: Holz1 Position value: 0%
shuttercontrol.0
	2021-06-21 19:00:00.168	info	#27 Set ID: Lager Position value: 0%
shuttercontrol.0
	2021-06-21 19:00:00.162	info	#27 Set ID: Büro Position value: 0%
```
**Versions:**  
 - Adapter version: 1.2.0
 - JS-Controller version: 3.3.14

 - Node version: 12.22.1
 - Operating system: Proxmox/Debian10

**Comment by simatec** [comment]
Das ist kein Bug sondern eine falsche Einstellung von dir.
Spät schließen, schließt alle Rollläden die noch offen sind zu der definierten Zeit.

Steht auch in der Doku beschrieben. 
Was du für deinen Anwendungsfall nutzen könntest, wäre die Zwischenposition.

![image](https://user-images.githubusercontent.com/39792461/122896062-fc5d2180-d348-11eb-9d69-3d4e61c78863.png)

![image](https://user-images.githubusercontent.com/39792461/122896223-24e51b80-d349-11eb-813f-989b209c2749.png)
