### ISSUE TITLE
mehr Räume/Bereiche

### ISSUE THREAD

**Issue by Negalein** [simatec/ioBroker.shuttercontrol#204]
Hallo

ich würde mich freuen, wenn es noch mehr Räume zur Auswahl geben würde. Oder die Möglichkeit eigene Räume/Bereiche anzulegen.
Mit den 3 möglichen (Kinder, Schlafen, Wohnen) steh ich aktuell an, da ich für Küche, Bad, Werkstatt, usw. eigene Räume bräuchte.

**Comment by simatec** [comment]
Dieses Thema wurde hier schon einige male diskutiert ...
Für das öffnen gibt stellt shutterontrol 9 Optionen zur Auswahl und für das schließen in Summe 10.
Damit sollten alle Fenster und Türen abgedeckt werden und wie in meinem Fall, könnte ich so gut wie jeden Rollladen nach einer anderen Regel fahren lassen.

Schau mal in der Doku ... Hier gibt es sehr viele individuelle Möglichkeiten

**Comment by Negalein** [comment]
Ja, aber will ich zB die DP in shuttercontrol.0.control in VIS nutzen, hab ich nur die 3 Möglichen Bereiche.

**Comment by simatec** [comment]
Die Frage stellt sich hier halt, was man will. shuttercontrol hat die Philosophie die automatische Steuerung der Rollläden zu übernehmen ... Manuelles Eingreifen sollte hier nur im Notfall erfolgen.
Wenn shuttercotrol richtig konfiguriert ist, dann kann die Automatik 99% aller Fahrvorgänge händeln.

**Comment by poidi** [comment]
notfalls kann man ja auch mehrere instanzen vom shuttercontrol haben, die jeweils andere rolladen fahren lassen.
