### ISSUE TITLE
Update der Beschreibung - Einstellungen Helligkeitssensor

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#206]
In der Dokumentation fehlen Hinweise wie die ‚Einstellungen Helligkeitssensor‘ funktionieren bzw. was sie genau bewirken. Was kann man mit ihnen einstellen? 

Die Dokumentation bezieht sich derzeit noch auf Version 1.1.5. 

Danke!

**Comment by simatec** [comment]
Doku wird noch erweitert.
