### ISSUE TITLE
Rollladen früh und abends in Abhängigkeit der Lichtstärke fahren

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#208]
Meiner Frau ist es oft zu zeitig dass die Rollläden mit Sonnenuntergang runter gefahren werden. Oft ist es dann noch hell draußen. Die Möglichkeit, die Rollläden in Abhängigkeit der tatsächlich außen vorhandenen Lichtstärke zu fahren wäre eine tolle Sache.

**Comment by simatec** [comment]
Geht über den Helligkeitssensor oder halt wenn kein Sensor vorhanden ist den Delay für den Sonnenuntergang erhöhen
