### ISSUE TITLE
Einstellung Lichtstärke für automatisches Fahren

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#209]
Wo muss man denn den Lichtsensor für das nächtliche Öffnen/Schließen einstellen?
Ich habe bei Extra-Einstellungen / Einstellungen Helligkeitssensor den Sensor eingetragen und auf 10Lux gestellt. 

Und wo muss man auswählen, dass der Helligkeitssensor genutzt werden soll? In den Zeiteinstellungen für die Bereiche gibt es nur Zeit; Zeit mit Sonnenaufgang- und Untergang sowie Zeit mit Golden Hour.

**Comment by simatec** [comment]
Direkt in den Rollladen Einstellungen kannst du den Helligkeitssensor auswählen

**Comment by guitardoc** [comment]
Ja, der funktioniert ja auch - für die Sonnenverschattung. Aber eben nicht für das nächtliche Herunterfahren. Oder wo kann ich da einstellen, bei wieviel Lux der Rollladen Abends runterfahren soll? Ich finde da nichts dazu. Egal was ich wo einstelle, die Rollläden fahren brav bei Sonnenuntergang runter.

**Comment by 5G7K** [comment]
Direkt im Rollladen hast du unter "Art der Steuerung für schließen des Rollladens" ==> "Helligkeitssensor" ausgewählt? Funktioniert bei mir

**Comment by guitardoc** [comment]
Ahhhh - jetzt hab ich es gefunden. Vielen vielen Dank!!! 🥇 

Bei den vielen Einstellungsmöglichkeiten hab ich das doch glatt übersehen. Wie so oft sitzt das Problem vor dem Bildschirm… 👍

**Comment by guitardoc** [comment]
Aber doch noch eine Frage - kann man irgendwo einstellen, bei welcher Beleuchtungsstärke die Rollläden dann abends runterfahren? Oder welcher Grenzwert ist da eingestellt? Mein Sensor geht manchmal nicht bis auf Null sondern bleibt auf 0,05 Lux stehen.

**Comment by simatec** [comment]
Die Werte und die Sensor-ID kannst du hier einstellen ...
<img width="1150" alt="Bildschirmfoto 2021-06-26 um 11 37 23" src="https://user-images.githubusercontent.com/39792461/123509018-65a7a200-d673-11eb-89e9-cc645c3f9bc1.png">

**Comment by guitardoc** [comment]
Ahh, dafür sind die Einstellungen da. Die waren in der Doku nicht beschrieben, daher wusste ich nichts damit anzufangen. 

Vielen Dank für die Info und viele Grüße!

**Comment by simatec** [comment]
Ja die sind noch recht neu und müssen in der Doku noch eingepflegt werden

**Comment by BlueBook4** [comment]
Hallo zusammen,
sorry, wenn ich das Ticket noch mal aufmachen muss. (ich hoffe es wird autom. wieder eröffnet).
Und auch noch mal danke für den tollen Adapter!!!

Super, dass die Funktion mit dem Helligkeitssensor reingekommen ist (ich wollte diese gerade schon nachfragen).
Allerdings hätte ich es anders erwartet. Zumindest hab ich es bisher ohne shuttercontrol so programmiert, dass die RolladenHelligkeitsgesteuert in einem Zeitraum hoch und runter fahren (ähnlich der vorhanden Sonnenaufgangs- und untergangsfunktion).

Daher die Frage:

Müsste die Auswahl der Helligkeitssensors nicht unter den übergreifenden Haupteinstellungen zu finden sein, also unter:
Zeit-Einstellungen- z.B. EInnstellungen für den Wohnbereich - "Art der Automatiksteuerung für den Wohnbereich

Müsste hier nicht eine Auswahl:
"Zeit Wohnbereich mit Helligkeitssensor"
existieren?

Und unter den eigentlichen individuellen Rolladeneinstellungen kann man dann unter "Art der Steuerung für schließen/öffnen des Rolladens wählen:
"Wohnbereich (automatik)"

Okay, jetzt wo ich es schreibe, wäre es wahrscheinlich eher ein Featurewunsch, oder?

Gruß
BB

**Comment by simatec** [comment]
Der Lichtsensor ist unabhängig von Zeiten. 
wenn du es mit Zeiten kombinieren willst, dann nimm die Elevation

**Comment by BlueBook4** [comment]
Elevation und Lichtsensor ist schon ein großer Unterschied.

Gerade an dunklen, teils regnerischen Tagen, finde ich es gut, dass die Rollos autom. früher runterfahren.
Über den Helligkeitssensor geht dies, über Elevation leider nicht.

Nur den Helligkeitssensor ohne Zeiten zu nehmen geht auch nicht, weil es teilweise im Winter schon um 14-15 Uhr entsprechend dunkel sein kann. 
Bzw. im Sommer es ab 4-5 Uhr entsprechend Hell wird.
Hier ist eine Zeitvorgabe sinnvoll.

Zumindest hab ich es bisher so manuell programmiert.
Jetzt dachte ich, es wäre insg. einfacher auf Deinen Adapter umzusteigen, zumal dieser ausgereifte Sonnenschutzfeatures hat (die sind bisher bei mir sehr rudimentär)

Wäre dies nicht sinnvoll, wenn der jetzt schon coole Adapter, auch eine zeitgesteuerte Helligkeitssteuerung unterstützen könnte? :)
