### ISSUE TITLE
Invertien von 0-100 der levelwerte

### ISSUE THREAD

**Issue by dirkhe** [simatec/ioBroker.shuttercontrol#21]
Hallo, bei meinen Sonoff Schaltern habe ich 100 für zu und 0 für auf, also umgekehrt wie in den Bespielen. Ich kann das zwar auch alles eintragen, aber dann funktioniert der Sonnenschutz nicht. Ich habe mal debuggt und ich denke, dass zumindest diese Zeile (1663) Falsch ist:
`function sunProtect()
...
case outside temperature and direction
..
  adapter.getForeignState(result[i].name, (err, state) => {
                                                                        if (state) {
                                                                            if (parseFloat(state.val) > parseFloat(result[i].heightDownSun) && parseFloat(state.val) == parseFloat(result[i].currentHeight) && result[i].currentHeight == result[i].heightUp) {`

heightDownSun ist bei mir 90
heightUp ist 0

Wenn die Richtung also umgedreht ist, müsste es "<" heissen.

Also entweder muss man noch mit direction arbeiten oder intern die werte negieren (könnte man ja beim abspeichern negieren. Das hätte dann wahrscheinlich den Vorteil, dass der code nicht ganz so viel angepasst werden müsste. Die logik kann überall bleiben, aber beim Setzten der Werte müsste ein abs() um den den Wert gesetzt werden, damit der immer positiv ist.

gruss
Dirk

**Comment by simatec** [comment]
Du musst deine shellys dementsprechend konfigurieren, damit 100 = oben und 0 = unten ist

**Comment by dirkhe** [comment]
Ich hatte schon per E-Mail geantwortet, aber irgendwie ist der hier nicht angekommen...

Ich habe die sonoff t1 aber schon angeschlossen und zwar um 90 grad verdreht, so dass die linke taste hoch und die rechte runter. Dadurch musste ich schon tasmota umkonfigurieren.
Aber unabhängig davon, kann man die Werte ja in der Oberfläche eingeben, dass suggeriert ja, dass man die Logik umdrehen kann. Ich habe ziemlich lange gesucht, um mir das Verhalten zu erklären, bis ich halt debugged habe. Ich könnte mir vorstellen, dass andere vlt. auch das Problem haben könnten..
Vlt. Sollte man dann eine Warnmeldung ausgeben, wenn wert für unten größer als hoch eingegeben wird?

Ich bekomme das bei mir schon irgendwie hin, aber für andere User mag so ein Hinweis hilfreich sein.

Gruß
Dirk

**Comment by dirkhe** [comment]
Da  man das invertieren jetzt im tasmota komplett einstellen kann, würde ich diesen issue jetzt mal schlissen
