### ISSUE TITLE
Helligkeitssensor - Manuelles Öffnen danach nicht möglich - Fix funktioniert nicht

### ISSUE THREAD

**Issue by 5G7K** [simatec/ioBroker.shuttercontrol#210]
Hi Simatec,

siehe #195

Habe ich gerade nochmal getestet. FIx funktioniert nicht bei mir.
Rollladen wird per Helligkeitssensor geschlossen -> funktioniert
Danach möchte ich ihn aber nochmal manuell öffnen
Sobald der nächste Helligkeitswert nach 1Min abgefragt wird, wird er aber wieder geschlossen.

`
shuttercontrol.0 | 2021-06-25 22:20:50.168 | debug | (29998) OG.Schlaf.Garten Old value = 0. New value = 0. automatic is active
-- | -- | -- | --
shuttercontrol.0 | 2021-06-25 22:20:50.160 | info | (29998) State value to set for "shuttercontrol.0.shutters.autoLevel.OG_Schlaf_Garten" has to be type "string" but received type "number"
shuttercontrol.0 | 2021-06-25 22:20:50.157 | debug | (29998) save current height: 0% from OG.Schlaf.Garten
shuttercontrol.0 | 2021-06-25 22:20:50.156 | info | (29998) **Lightsensor #9 Set ID: OG.Schlaf.Garten value: 0%**
shuttercontrol.0 | 2021-06-25 22:20:40.157 | debug | (29998) Lightsensor down OG.Schlaf.Strasse already down at: 0% - setting current action: down
shuttercontrol.0 | 2021-06-25 22:20:30.157 | debug | (29998) Lightsensor down OG.Ankleide already down at: 0% - setting current action: down
shuttercontrol.0 | 2021-06-25 22:20:23.100 | debug | (29998) system.adapter.admin.0: logging true
shuttercontrol.0 | 2021-06-25 22:20:20.157 | debug | (29998) Lightsensor down EG.Speise already down at: 0% - setting current action: down
shuttercontrol.0 | 2021-06-25 22:20:10.156 | debug | (29998) Lightsensor down EG.WC already down at: 0% - setting current action: down
shuttercontrol.0 | 2021-06-25 22:20:05.686 | debug | (29998) OG.Schlaf.Garten Updated trigger action to Manu_Mode to prevent moving after window close
shuttercontrol.0 | 2021-06-25 22:20:05.686 | debug | (29998) **OG.Schlaf.Garten drived manually to 100. Old value = 0**. New value = 100
`

Kannst du das bitte nochmal prüfen? Danke dir!

**Comment by simatec** [comment]
dann tauche ich da nochmal tiefer ab ... danke für die info

**Comment by simatec** [comment]
Fix in Version 1.3.0
