### ISSUE TITLE
sunProtect funktioniert nicht, wenn Rollo irgendwann vorher manuell runter und wieder hochgefahren wurde

### ISSUE THREAD

**Issue by tobsta** [simatec/ioBroker.shuttercontrol#212]
**Describe the bug**  
SunProtect wird nicht aktiviert wenn das Rollo zuvor manuell runter und wieder hochgefahren wurde

**To Reproduce**  
Rollo konfiguriert mit SunProtect über Sonnenstand
SunProtect aktiviert
(in meinem Fall ist autoUp und autoDown deaktiviert)
Rollo lange vor der SunProtect Zeit einmal manuell runter und manuell wieder hochfahren
-> Rolle bleibt oben und fährt nicht beim eingestellten Sonnenstand herunter

Rollos, die morgens manuell hochgefahren wurden, ohne ein weiteres mal manuell runter/hoch, gehen wie gewollt in den SunProtect

**Expected behavior**  
Rollos, die komplett offen sind und "autoSun"=true haben sollten in den SunProtect fahren 

**Versions:**  
 - Adapter version: 1.2.1
 - JS-Controller version: 3.3.12
 - Node version: v12.22.1
 - Operating system: Linux iobroker 5.10.17-v7l+

Hoffe das ist so verständlich. Helfe gerne, wenn ich kann...

**Comment by simatec** [comment]
You have now deactivated the automatic mode. You can reactivate it using the button

**Comment by tobsta** [comment]
okay - understood - then its not a bug and its meant to be this way (nevertheless i think most of the users would prefer the functionality like I described in "expected behavior", at least in the shutter control iobroker thread it feels like)

> You can reactivate it using the button
which button do you mean @simatec?

**Comment by vain90** [comment]
@tobsta
> which button do you mean @simatec?

In Version 1.2.1 you have the "AutoAll" button under "control"
Description of this button is: "set all Shutter to Auto Mode"
