### ISSUE TITLE
Bug: Rollo schließt am Tag bei Verwendung eines Türkontaktes, wenn Balkontuer geschlossen wird

### ISSUE THREAD

**Issue by hadavid2482** [simatec/ioBroker.shuttercontrol#214]
Hallo! 

Erstmal vielen Dank für die super Arbeit. Das Plugin ist wirklich super!!!

Ich habe jedoch mit allen Rollos ein Problem, wo auch ein Fenster-/Tuersensor zum Einsatz kommt. Die Rollos stehen auf Automatik und sollen erst am Abend schließen. Öffne ich jedoch die Fesnter-/Tueren und schließe irgendwann wieder, dann geht auch das Rollo runter, obwohl es noch nicht Abend ist.

Es wäre super, wenn sich das lösen ließe. Dann wäre das Plugin eine runde Sache.

Beste Grüße!!

**Comment by simatec** [comment]
Bitte poste deine Config der Rollos und die Version von shuttercontrol.

**Comment by hadavid2482** [comment]
Hi! Ich verwende die Version 1.2.1

Hier die Konfiguration:

{
  "_id": "system.adapter.shuttercontrol.0",
  "common": {
    "name": "shuttercontrol",
    "version": "1.2.1",
    "title": "shuttercontrol",
    "authors": [
      "simatec <nais@gmx.net>"
    ],
    "contributors": [
      "Rene G. <info@rg-engineering.eu>"
    ],
    "keywords": [
      "ioBroker",
      "Smart Home",
      "home automation",
      "Rollladen",
      "Jalousie",
      "Rollladensteuerung"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "main": "main.js",
    "icon": "shuttercontrol.png",
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.shuttercontrol/master/admin/shuttercontrol.png",
    "readme": "https://github.com/simatec/ioBroker.shuttercontrol/blob/master/README.md",
    "loglevel": "info",
    "mode": "daemon",
    "type": "climate-control",
    "compact": true,
    "materialize": true,
    "stopBeforeUpdate": true,
    "plugins": {
      "sentry": {
        "dsn": "https://5f58df7167d846e3a90bae5414d4fc09@sentry.iobroker.net/62"
      }
    },
    "installedFrom": "iobroker.shuttercontrol@1.2.1",
    "installedVersion": "1.2.1",
    "host": "iobroker",
    "connectionType": "local",
    "dataSource": "push",
    "adminUI": {
      "config": "materialize"
    }
  },
  "native": {
    "livingAutomatic": "livingSunriseSunset",
    "W_shutterDownLiving": "21:30",
    "W_shutterUpLivingMin": "07:00",
    "W_shutterUpLivingMax": "07:30",
    "driveDelayUpLiving": "0",
    "WE_shutterDownLiving": "21:30",
    "WE_shutterUpLivingMin": "08:00",
    "WE_shutterUpLivingMax": "08:30",
    "sleepAutomatic": "sleepSunriseSunset",
    "W_shutterDownSleep": "21:30",
    "W_shutterUpSleepMin": "07:00",
    "W_shutterUpSleepMax": "07:30",
    "driveDelayUpSleep": "0",
    "WE_shutterDownSleep": "21:30",
    "WE_shutterUpSleepMin": "08:00",
    "WE_shutterUpSleepMax": "08:30",
    "childrenAutomatic": "childrenSunriseSunset",
    "W_shutterDownChildren": "21:30",
    "W_shutterUpChildrenMin": "07:00",
    "W_shutterUpChildrenMax": "07:30",
    "driveDelayUpChildren": "0",
    "WE_shutterDownChildren": "21:30",
    "WE_shutterUpChildrenMin": "08:00",
    "WE_shutterUpChildrenMax": "08:30",
    "latitude": "49.45203",
    "longitude": "11.07675",
    "sunProtEndElevation": "10",
    "astroDelayUp": "30",
    "astroDelayDown": "30",
    "driveDelayUpAstro": "10",
    "SummerStart": "01.03.",
    "SummerEnd": "30.09.",
    "XMasStart": "01.12.",
    "XMasEnd": "06.01.",
    "publicHolidays": true,
    "publicHolInstance": "feiertage.0",
    "HolidayDP": "ical.0.events.1.Vacation",
    "lightsensorDown": "400",
    "lightsensorUp": "500",
    "lightsensorUpDown": "",
    "schoolfree": false,
    "schoolfreeInstance": "",
    "schoolfreeChildrenArea": true,
    "schoolfreeSleepArea": false,
    "schoolfreeLivingArea": false,
    "LateAllDown": false,
    "LateAllDownTime": "22:15",
    "betweenPositionTime": "22:00",
    "noGoTime": "0",
    "currentShutterState": true,
    "currentShutterStateTime": "60",
    "triggerAutoSleep": "",
    "triggerAutoLiving": "",
    "triggerAutoChildren": "",
    "heightDownSun": "50",
    "direction": "290",
    "type": "in- & outside temperature",
    "directionRange": "15",
    "actualValueTemp": "",
    "actualValueLight": "",
    "actualValueTempInside": "",
    "typeDown": "sleep-auto",
    "typeUp": "sleep-auto",
    "triggerStateShutter": "false",
    "triggerChangeShutter": "upDown",
    "triggerDriveShutter": "100",
    "autoDriveShutter": "onlyUp",
    "heightDownShutter": "0",
    "heightUpShutter": "100",
    "triggerID": "deconz.0.Sensors.36.open",
    "LateDown": true,
    "inSummerNotDown": false,
    "driveAfterClose": true,
    "useXmasLevel": false,
    "XmasLevel": "0",
    "KeepSunProtect": false,
    "trigDelyUp": "1",
    "trigDelyDown": "10",
    "betweenPosition": false,
    "betweenPositionLevel": "50",
    "events": [
      {
        "enabled": true,
        "shutterName": "Schlafzimmer",
        "name": "mqtt.0.Switch.Fenster-Rollo-Schlafzimmer",
        "triggerID": "deconz.0.Sensors.36.open",
        "typeUp": "sleep-auto",
        "typeDown": "sleep-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "10"
      },
      {
        "enabled": true,
        "shutterName": "Arbeitszimmer",
        "name": "mqtt.0.Switch.Fenster-Rollo-Arbeitszimmer",
        "triggerID": "",
        "typeUp": "children-auto",
        "typeDown": "children-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "5"
      },
      {
        "enabled": true,
        "shutterName": "Kueche-Links",
        "name": "mqtt.0.Switch.Fenster-Rollo-Kueche-Links",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "5"
      },
      {
        "enabled": true,
        "shutterName": "Kueche-Rechts",
        "name": "mqtt.0.Switch.Fenster-Rollo-Kueche-Rechts",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "5"
      },
      {
        "enabled": true,
        "shutterName": "Balkon-Tuer",
        "name": "mqtt.0.Switch.Fenster-Rollo-Balkon-Tuer",
        "triggerID": "deconz.0.Sensors.37.open",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": true,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "10"
      },
      {
        "enabled": true,
        "shutterName": "Balkon-Fenster",
        "name": "mqtt.0.Switch.Fenster-Rollo-Balkon-Fenster",
        "triggerID": "",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "in- & outside temperature",
        "heightDownSun": "50",
        "direction": "290",
        "directionRange": "15",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerDrive": "100",
        "triggerChange": "upDown",
        "elevation": "4",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "",
        "hysteresisInside": "",
        "hysteresisLight": "",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "1",
        "trigDelyDown": "1"
      }
    ]
  }
}

**Comment by guitardoc** [comment]
Ich habe das gleiche Verhalten festgestellt. Es tritt dann auf, wenn während der Sonnenverschattung die Tür schon mal geöffnet und geschlossen wurde (da funktioniert der Aussperrschutz richtig). Wenn dann später, nachdem die Verschattung vorüber ist, die Tür wieder geschlossen wird, dann fährt der Rollladen herunter obwohl er dann ja oben bleiben muss.

**Comment by mango1402** [comment]
Selbes, sehr nerviges Problem. Tritt auch bei mir auf.
'Trigger' müsste bei jeder automatischen Aktion neu gesetzt werden - unabhängig vom Türkontakt.....
also z.B.: bei öffnen in der Früh (obwohl schon durch Türkontakt offen) auch den Trigger auf 'öffnen' setzen.....
lg Manfred

**Comment by simatec** [comment]
The error cannot be reproduced.
It will certainly be the case with you that the shutter status changes. Please activate the following setting
![image](https://user-images.githubusercontent.com/39792461/139808476-628086ef-e7dd-44ca-afef-e967863cc575.png)
