### ISSUE TITLE
Verschiedene Probleme mit einem Rollladen…

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#215]
Ich habe diverse Probleme mit einem Rollladen:

Es handelt sich um den letzten Rollladen in der Liste - vielleicht hat es damit etwas zu tun.
Es ist auch der einzige Rollladen, welcher dem Kreis ‚Schlafzimmer‘ zugeordnet ist. Dieser öffnet nur früh später als der Rest, ansonsten ist soweit ich das überblicke alles gleich.

Ich habe bei diesem Rollladen das Häkchen bei „Rollladen im Sommer nicht schließen“ gesetzt und Sommer steht auf 01.03. - 30.09. Trotzdem fährt dieser Rollladen gemeinsam mit den anderen Rollläden bei Erreichen der Dunkelheitsschwelle herunter. Hab ich etwas falsch eingestellt oder ist das eventuell ein Fehler?

Er fährt bei Sonne auch gemeinsam mit den anderen Rollläden, welche die gleiche Ausrichtung haben, herunter und auch wieder hoch. Allerdings nur zwei mal - danach bleibt er auf der unteren Position stehen, auch wenn die anderen Rollläden wieder hoch und auch wieder runter gehen. Auch das kann eigentlich nur ein Fehler sein, oder hab ich bei den vielen Einstellungen vielleicht irgendwo ein Häkchen gesetzt wo keins hingehört?

Danke für die Hilfe.

**Comment by DrHappy90** [comment]
Werden die Rollos über den Helligkeitsensor runter gefahren? Falls ja, liegt es wahrscheinlich daran, da gibt es wohl noch den ein oder anderen Bug.
Habe meine Rollos erstmal wieder auf Sonnenuntergang gestellt. 
Gruß Kevin

**Comment by guitardoc** [comment]
Ja, über den Helligkeitssensor. Mit Sonnenuntergang hat es funktioniert, da werde ich es auch erst mal wieder zurückstellen müssen. Seltsam, dass es nur den letzten Rollladen in der Liste betrifft.

**Comment by guitardoc** [comment]
Ich hab jetzt mal die Version 1.2.1 installiert - das Verhalten ist das Gleiche.

**Comment by Syskonia** [comment]
Guten Tag
Ich bin mir nicht sicher ob das der richtige Bereich ist.

Ich würde gerne den adapter mit Rolladenmotoren die an einer Siemens Logo angeschlossen sind nutzen.

Könnte etwas hilfe gebrauchen.

**Comment by simatec** [comment]
Ist in Version 1.3.0 gefixt
