### ISSUE TITLE
Sonnenschutz (Hitzeschutz)

### ISSUE THREAD

**Issue by mczeus** [simatec/ioBroker.shuttercontrol#217]
Die Option "Halte Rollladen in Sonnenschutz" ist eine Super Sache.
Würde mir dort aber noch eine Option wünschen, die es erlaubt bei niedriger Außentemperatur den Rollladen nicht zu halten, sondern wieder hoch zu fahren.
Bei Hoher Außentemperatur soll er den Rollladen im Sonnenschutz halten.

Beispiel:

Außentemperatur > 27grad = Sonnenschutz halten
Außentemperatur < 27grad = Rollladen nach beenden der Bedienungen, den Sonnenschutz verlassen.

**Comment by Dino0811** [comment]
Hallo,

Ich wollte auch gerade eine weitere Halteoption vorschlagen, daher würde ich dass hier mit ergänzen.
Da ich über den Helligkeitssensor (bzw. Sonneneinstrahlung der Wetterstation [W/m²]) steuere fahren die Rollläden an einem wechselhaft bewölkten Tag mehrfach hoch und runter (weil bei unterschreiten der Helligkeit inkl. Hysterese geöffnet wird, und später wieder geschlossen ...etc.)

daher fände ich gar eine Halteoption nach der Uhrzeit für praktikabel:
unter Extras:
[X] halte Sonnenschutz   [X] bis Uhrzeit: [18:30]

da hier manchmal der Sensorwert (bzw.) auch am Abend unterschritten wird, obwohl die Sonne noch flach in die Fenster scheint und den Innenraum erwärmen würde.

**Comment by simatec** [comment]
Die Optionen gibt es doch am Ende bereits in den Einstellungen. 
Nach Außentemperatur einstellen und den Wert demensprechend wählen.

Dann wird automatisch bis zum Ende der Beschattung der Rollladen im Sonnenschutz gehalten.
