### ISSUE TITLE
wrong time set by selecting "Nur die Zeit für den Kinderbereich" (shuttercontrol)

### ISSUE THREAD

**Issue by zs003527** [simatec/ioBroker.shuttercontrol#218]
It is currently Fridy evening 
and you select the instance "shuttercontrol.0" (e.g. version 1.2.0 & 1.2.1) 
-> Zeit-Einstellungen 
-> Einstellungen für den Kinderbereich

If you select under "Art der Automatiksteuerung für den Kinderbereich"
->"Zeit Kinderbereich mit Sonnenauf- & Sonnenuntergang" 
-> you will find under Object "downtimechildren" the time of weekend.  :-)

If you select under "Art der Automatiksteuerung für den Kinderbereich"
-> "Nur die Zeit für den Kinderbereich" 
->  you will find under Object "downtimechildren" the time of working day instead of weekend. :-(

Could you pls. verify and correct if you can reproduce the issue ?

If you have any question, pls. let me know.

**Comment by zs003527** [comment]
Me again.

On Saturday everything went fine.

On Sunday I had a similar issue with the "Einstellungen für den Kinderbereich"
that Object "downtimechildren" will show the time of WE instead of working day.

Conclusion:
The related object "downtimechildren" is affected at Friday & Sunday only.

The hint:
Das Schließen von Rollläden am Freitag erfolgt zur eingestellten Wochenendzeit
und am Sonntag zur eingestellten Arbeitswochenzeit!

The hint is not working for the area of "Kinderbereich" for closing time of the shutters.

Br
zs003527

**Comment by simatec** [comment]
Fix in Version 1.3.0
