### ISSUE TITLE
Noch mehr Features bitte 😁

### ISSUE THREAD

**Issue by EvilEls** [simatec/ioBroker.shuttercontrol#22]
Hallo! Danke für deine großartige Arbeit! Der Adapter ist wirklich ordentlich und, im Gegensatz zu vielen Anderen, sehr gut dokumentiert! Wirklich Klasse! 

Ein paar Anmerkungen habe ich aber dennoch:

Ich fahre meine Rollläden derzeit per Script in Abhängigkeit von Astro und Zeit in mehreren Stufen auf und zu. Also nicht bei Sonnenaufgang ganz auf und bei Sonnenuntergang ganz zu.

Sondern in mehreren Schritten:
![image](https://user-images.githubusercontent.com/29343914/65077220-d6983100-d99a-11e9-911d-e2efae6dda1f.png)

![image](https://user-images.githubusercontent.com/29343914/65077268-eca5f180-d99a-11e9-9962-784af40e16b7.png)

![image](https://user-images.githubusercontent.com/29343914/65077328-06dfcf80-d99b-11e9-967d-b74052509c27.png)

und 

![image](https://user-images.githubusercontent.com/29343914/65077414-2c6cd900-d99b-11e9-96e3-f08ddb21b874.png)

Abends dann genau das Gleiche, nur anders herum und mit Aussperrschutz und zusätzlich in Abhängigkeit der Außentemperatur.

![image](https://user-images.githubusercontent.com/29343914/65078182-d436d680-d99c-11e9-8f0e-9e0dc612fb8e.png)

Wäre es möglich ebenfalls schrittweises Auf- bzw. Zufahren einzurichten?
Und die Außentemperatur dabei zu berücksichtigen? 
Wenn man die Start und Stop Werte (100->0) tauschen könnte, könnte man mit dem Adapter prima Lampen dimmen. Man könnte so zB die Beleuchtung immer heller stellen, je mehr man verdunkelt.

Besten Dank nochmals und viele Grüße!

**Comment by handy80** [comment]
Hi EvilEls, das sieht schon ordentlich aus, hast du das mit der iobroker community irgendwo geteilt? Bin immer auf der Suche nach "Re-Use" ;-) alles was mir programmierarbeit spart... Lieben Gruß Holger
