### ISSUE TITLE
Beschattungsautomatik beendet nicht bei Unterschreiten des eingestellten Elevationswertes

### ISSUE THREAD

**Issue by puppet1912** [simatec/ioBroker.shuttercontrol#221]
Ich verwende die latest Version 1.2.1 und steuere mit dem Adapter Aktoren von Homematic IP (mit AP). 
In den Astro-Einstellungen ist 

_"Beenden der Sonnenschutzfunktion mit Sonnenhöhe (Elevation)" = 10_ 

gesetzt/eingetragen. Der Haken bei "Halte Rolladen in Sonnenschutz" ist *nicht* gesetzt. Im Logfile unterschreitet der berechnete Elevationswert auch den eingestellten Grenzwert, der Rolladen fährt jedoch nicht. Folgendes steht dann im Logfile: 

<html><body>

2021-08-14 19:20:00.020  - debug: shuttercontrol.0 (8825) calculate astrodata... 
2021-08-14 19:20:00.021  - debug: shuttercontrol.0 (8825) Sun Azimut: 281.1°
2021-08-14 19:20:00.022  - debug: shuttercontrol.0 (8825) Sun Elevation: 9.4°
2021-08-14 19:20:02.039  - debug: shuttercontrol.0 (8825) WzRechts level conversion is enabled
2021-08-14 19:22:02.045  - debug: shuttercontrol.0 (8825) WzRechts level conversion is enabled
2021-08-14 19:25:00.016  - debug: shuttercontrol.0 (8825) calculate astrodata ...
2021-08-14 19:25:00.017  - debug: shuttercontrol.0 (8825) Sun Azimut: 282°
2021-08-14 19:25:00.018  - debug: shuttercontrol.0 (8825) Sun Elevation: 8.6°

</body>
</html>

Folgende Einstellungen nutze ich: 

{
  "_id": "system.adapter.shuttercontrol.0",
  "common": {
    "name": "shuttercontrol",
    "version": "1.2.1",
    "title": "shuttercontrol",
    "authors": [
      "simatec <nais@gmx.net>"
    ],
    "contributors": [
      "Rene G. <info@rg-engineering.eu>"
    ],
    "keywords": [
      "ioBroker",
      "Smart Home",
      "home automation",
      "Rollladen",
      "Jalousie",
      "Rollladensteuerung"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "main": "main.js",
    "icon": "shuttercontrol.png",
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.shuttercontrol/master/admin/shuttercontrol.png",
    "readme": "https://github.com/simatec/ioBroker.shuttercontrol/blob/master/README.md",
    "loglevel": "debug",
    "mode": "daemon",
    "type": "climate-control",
    "compact": true,
    "materialize": true,
    "connectionType": "local",
    "dataSource": "push",
    "stopBeforeUpdate": true,
    "adminUI": {
      "config": "materialize"
    },
    "plugins": {
      "sentry": {
        "dsn": "https://5f58df7167d846e3a90bae5414d4fc09@sentry.iobroker.net/62"
      }
    },
    "installedFrom": "iobroker.shuttercontrol@1.2.1",
    "installedVersion": "1.2.1",
    "host": "raspberrypi"
  },
  "native": {
    "livingAutomatic": "livingTime",
    "W_shutterDownLiving": "21:00",
    "W_shutterUpLivingMin": "08:00",
    "W_shutterUpLivingMax": "07:30",
    "driveDelayUpLiving": "10",
    "WE_shutterDownLiving": "22:00",
    "WE_shutterUpLivingMin": "08:00",
    "WE_shutterUpLivingMax": "09:00",
    "sleepAutomatic": "sleepSunriseSunset",
    "W_shutterDownSleep": "20:00",
    "W_shutterUpSleepMin": "06:00",
    "W_shutterUpSleepMax": "06:30",
    "driveDelayUpSleep": "10",
    "WE_shutterDownSleep": "21:00",
    "WE_shutterUpSleepMin": "06:00",
    "WE_shutterUpSleepMax": "06:30",
    "childrenAutomatic": "childrenSunriseSunset",
    "W_shutterDownChildren": "20:00",
    "W_shutterUpChildrenMin": "06:00",
    "W_shutterUpChildrenMax": "06:30",
    "driveDelayUpChildren": "10",
    "WE_shutterDownChildren": "21:00",
    "WE_shutterUpChildrenMin": "06:00",
    "WE_shutterUpChildrenMax": "06:30",
    "latitude": "50.95670156243523",
    "longitude": "13.930901303870996",
    "sunProtEndElevation": "10",
    "astroDelayUp": "30",
    "astroDelayDown": "30",
    "driveDelayUpAstro": "10",
    "SummerStart": "01.03.",
    "SummerEnd": "30.09.",
    "XMasStart": "01.12.",
    "XMasEnd": "06.01.",
    "publicHolidays": true,
    "publicHolInstance": "",
    "HolidayDP": "",
    "lightsensorDown": "400",
    "lightsensorUp": "500",
    "lightsensorUpDown": "",
    "schoolfree": false,
    "schoolfreeInstance": "",
    "schoolfreeChildrenArea": true,
    "schoolfreeSleepArea": false,
    "schoolfreeLivingArea": false,
    "LateAllDown": false,
    "LateAllDownTime": "22:15",
    "betweenPositionTime": "22:00",
    "noGoTime": "0",
    "currentShutterState": true,
    "currentShutterStateTime": "35",
    "triggerAutoSleep": "",
    "triggerAutoLiving": "",
    "triggerAutoChildren": "",
    "heightDownSun": "0.4",
    "direction": "200",
    "type": "only direction",
    "directionRange": "55",
    "actualValueTemp": "",
    "actualValueLight": "",
    "actualValueTempInside": "",
    "typeDown": "living",
    "typeUp": "living",
    "triggerStateShutter": "true",
    "triggerChangeShutter": "off",
    "triggerDriveShutter": "1",
    "autoDriveShutter": "off",
    "heightDownShutter": "1",
    "heightUpShutter": "0",
    "triggerID": "",
    "LateDown": false,
    "inSummerNotDown": false,
    "driveAfterClose": false,
    "useXmasLevel": false,
    "XmasLevel": "0",
    "KeepSunProtect": false,
    "trigDelyUp": "0",
    "trigDelyDown": "0",
    "betweenPosition": false,
    "betweenPositionLevel": "50",
    "events": [
      {
        "enabled": true,
        "shutterName": "Kaempfer",
        "name": "hmip.0.devices.3014F711A000111A498E3899.channels.1.shutterLevel",
        "triggerID": "",
        "typeUp": "living",
        "typeDown": "living",
        "type": "only direction",
        "heightDownSun": "0.55",
        "direction": "120",
        "directionRange": "25",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "0",
        "heightDown": "1",
        "triggerState": "true",
        "triggerDrive": "0",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Kueche",
        "name": "hmip.0.devices.3014F711A000111A498E385E.channels.1.shutterLevel",
        "triggerID": "",
        "typeUp": "living",
        "typeDown": "living",
        "type": "only direction",
        "heightDownSun": "0.4",
        "direction": "200",
        "directionRange": "55",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "0",
        "heightDown": "1",
        "triggerState": "true",
        "triggerDrive": "1",
        "triggerChange": "off",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "Essen",
        "name": "hmip.0.devices.3014F711A000111A498E382C.channels.1.shutterLevel",
        "triggerID": "",
        "typeUp": "living",
        "typeDown": "living",
        "type": "only direction",
        "heightDownSun": "0.4",
        "direction": "200",
        "directionRange": "55",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "0",
        "heightDown": "1",
        "triggerState": "true",
        "triggerDrive": "0",
        "triggerChange": "upDown",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": false,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      },
      {
        "enabled": true,
        "shutterName": "WzRechts",
        "name": "hmip.0.devices.3014F711A000111A498E3805.channels.1.shutterLevel",
        "triggerID": "hmip.0.devices.3014F711A00007DD898A4554.channels.1.windowOpen",
        "typeUp": "living",
        "typeDown": "living",
        "type": "only direction",
        "heightDownSun": "0.36",
        "direction": "265",
        "directionRange": "25",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "0",
        "heightDown": "1",
        "triggerState": "false",
        "triggerDrive": "0",
        "triggerChange": "upDown",
        "elevation": "",
        "autoDrive": "off",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "0",
        "trigDelyDown": "0"
      }
    ]
  }
}
Danke und Grüße

**Comment by simatec** [comment]
Ist für mich nicht reproduzierbar

**Comment by simatec** [comment]
Bitte darauf achten, dass die Rollläden nicht manuell bewegt werden. Dann wird die Automatik ausgesetzt.
Des Weiteren sollte man bei HM-IP die Überprüfung des Rollladen Status aktivieren und auf ca. 60 Sekunden einstellen.
