### ISSUE TITLE
has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by crunchip77** [simatec/ioBroker.shuttercontrol#222]
Datenpunkte müsste noch angepasst werden
z.b.
State value to set for "shuttercontrol.0.shutters.autoLevel.xyz" has to be type "number" but received type "string"
oder 
State value to set for "hmip.0.devices.3014F711A000111A498E380E.channels.1.endpositionAutoDetectionEnabled" has to be type "string" but received type "boolean"

**Comment by Dirk-Peter-md** [comment]
Hallo, habe die gleiche Meldung 'State value to set for "shuttercontrol.0.shutters.autoLevel.HmIPW-DRBL4_DG-KZ-2-1" has to be type "number" but received type "string"' beim anlegen eines neuen Rollos. Info: "def": "" ist nicht vom type "number", daher die Meldung.

**Comment by simatec** [comment]
comming in Version 1.3.0
