### ISSUE TITLE
Kombination GoldenHour & SunSet/Rise

### ISSUE THREAD

**Issue by satisfied83** [simatec/ioBroker.shuttercontrol#225]
Hallo zusammen,

bisher habe ich meine Rolladensteuerung ohne Shuttercontrol gelöst. Ich möchte gerne auf den Adapter umsteigen aber meine Realisierung weitgehend beibehalten.

Ist es möglich die Fahrten für GoldenHour und Sunset/rise wie folgt zu kombinieren:
Der Trigger GoldenHour löst eine Fahrt auf eine Zwischenstellung aus.
Der Trigger Sunset löst die Fahrt auf die komplett geschlossene Position aus.

Umgekehrt natürlich auch bei Sonnenaufgang -> 50% Öffnung -> 100% Öffnung.

Danke für den Adapter !

**Comment by simatec** [comment]
Nein ist so nicht angedacht
