### ISSUE TITLE
Datenpunkte in der Konfiguration werden nicht unter "events" sondern bzw. zusätzlich unter "native" abgelegt

### ISSUE THREAD

**Issue by Dirk-Peter-md** [simatec/ioBroker.shuttercontrol#226]
Hallo, ich hatte die gleichen Probleme beim Speichern der Konfiguration in sprinklecontrol. Mit Hilfe des Forums konnten wir es so lösen.
**index_m.html** 
-  id="mainSettings" in Zeile 51 eingefügt
![Screenshot 2021-09-01 132220](https://user-images.githubusercontent.com/52133172/131663009-26e3522f-2525-4e87-8ce0-9e7f366acd09.jpg)
**index_m.js**
- alle Zeilen 50; 52; 60 mit *.select(); gelöscht oder aus kommentiert
![Screenshot 2021-09-01 133210](https://user-images.githubusercontent.com/52133172/131664291-4f7c9b03-09a9-46be-bc55-c3efbd1b79da.jpg)
- Zeile 405 #mainSettings einfügen
![Screenshot 2021-09-01 133509](https://user-images.githubusercontent.com/52133172/131664688-5af685b3-3cf1-4f34-9d05-5f3d2547465c.jpg)
Bei mir habe ich seit dem keine Probleme mehr! Ich hoffe es hilft dir auch.
MfG Dirk Peter

**Comment by simatec** [comment]
Ich verstehe dein Issue nicht so recht. 
Es gibt mit den speichern der Config keine Probleme und die Config von dem Array events gehört in native.

**Comment by Dirk-Peter-md** [comment]
Hallo, 
erstmal vor weck, wenn du hier keine Probleme siehst, so kannst du es auch rein als Info betrachten und diese Issues einfach als erledigt betrachten.
Ich habe in meinem Adapter sehr viel aus deinem mit einfließen lassen. Dafür erstmal danke, ohne diesen hätte ich meinen nicht auf die Beine stellen können.
Was mir nun bei mir in meinem Adapter aufgefallen ist: Seit dem ich Kombifelder im Event-Bereich, also alles unter div class="m material-dialogs" , eingebaut hatte, traten Fehler beim abspeichern der Konfiguration auf. Sie äußerten sich dahin gehend, das Werte aus dem letzten geöffneten Event, nicht unter Event sondern unter native abgespeichert wurden. Hierdurch arbeitete der Adapter dann nicht so, wie in der Konfiguration hinterlegt war.
Ich glaube so etwas auch in deinem Adapter bei den Tests gelesen zu haben, das sich jemand wunderte das ein Wert nicht so in der Konfiguration stand, wie er es eingegeben hatte.
So und nun zu deiner Konfiguration bei mir. Ich habe unter Instanzen => shuttercontrol.0 => Konfiguration => diese in einer Datei gespeichert.
Hier ein Auszug:
![Screenshot 2021-09-01 190442](https://user-images.githubusercontent.com/52133172/131713834-11defa2a-ca21-402f-815f-c460275d9e05.jpg)
Ich habe nur einen kleinen Teil der werte aus dem event Bereich die in der HTML ja unter "m material-dialogs" stehen mal markiert. Diese wurden aber auch unter native abgespeichert. Also doppelt. Und wie gesagt, bei mir unter sprinklecontrol kam es auch vor, das ein Wert dann unter native gespeichert wurde und nicht unter event.
Ich hoffe das war jetzt verständlich! Bin leider nur Anfänger und da fehlen mir die richtigen Worte.  ;-)

Vielleicht hilft dir auch dieser
[Dialog im Forum](https://forum.iobroker.net/topic/46674/sprinkle-control-hilfe-fehler-in-der-index_m-html?_=1630516808354)  , um es besser zu verstehen!

MfG Dirk Peter

**Comment by simatec** [comment]
Die nativen Objekte sind normal, da ich diese im Adapter auch angelegt habe. 
dies sind die Menüpunkte aus dem Dialog. 

Wenn bei dir nicht alle Werte gespeichert werden, kann es ein timeout Problem sein. 
sprich die Events wurden noch nicht komplett geschrieben und es wurde bereits auf speichern geklickt. 

Mir sind allerdings die Probleme in shuttercontrol neu. Deinen Adapter kenne. Ich leider nicht weiter. 
Hatte nur kurz deinen code überflogen und grundsätzlich ist vieles sehr ähnlich zu shuttercontrol. Aber wie gesagt, hab es nicht im Detail durchgeschaut. 

Wenn du mal einen Link hast zu dem von dir angesprochenen Problem in shuttercontrol, wäre es gut, wenn du ihn hier mal postest

**Comment by Dirk-Peter-md** [comment]
O.K. werde ich machen, sie es als erledigt an.
Danke für deine Arbeit,
Dirk Peter

**Comment by simatec** [comment]
Ich schaue mir dein Code aber gerne mal näher an und werde mal versuchen, ob deine Änderungen Einfluss auf die Funktion des Dialogs und von Events haben. 
events ist am Ende ja nur das ausgegebene Array der Tabelle

**Comment by Dirk-Peter-md** [comment]
Danke für deine angebotene Hilfe, aber mit Hilfe des Forums ist das Problem, so weit wie ich es beurteilen kann, gelöst. Ich habe auch keine negativen Rückmeldungen aus den Tests mehr erhalten. Daher wollte ich dir die Ergebnisse nur mitteilen bzw. zukommen lassen.
In der Hoffnung das ich auch etwas zurückgeben kann, nachdem ich bei dir so viel lernen konnte.
Also Danke nochmal, für die angebotene Hilfe!
Übrigens deine Konfiguration würde mit diesen Änderungen so aussehen.
![Screenshot 2021-09-01 202904](https://user-images.githubusercontent.com/52133172/131725126-3171e51a-1dac-4284-ad8b-6b31c50cb920.jpg)
MfG Dirk Peter

**Comment by simatec** [comment]
Hab es mal so umgebaut und teste das mal ... danke für deinen Support
