### ISSUE TITLE
Beleuchtung Steuern

### ISSUE THREAD

**Issue by SGhoktar** [simatec/ioBroker.shuttercontrol#228]
Ich finde, es wäre eine nette Funktion, wenn es noch einen Datenpunkt für die Raumbeleuchtung geben würde. Die Beleuchtung wird dann EIN, bzw. AUS geschaltet, wenn morgens der Rollladen hoch oder abends runterfährt.

**Comment by simatec** [comment]
Der Adapter soll die Rollläden steuern. 
Für die weiteren Folgeketten kannst du dann mit Szenen, Scripten oder sonstigen alles nach deinen Bedürfnissen erstellen. Nimm den Rollladen State und steuere danach. In dem state stehen die genauen Rollläden States
