### ISSUE TITLE
Zeit-Einstellungen: Helligkeitssensor berücksichtigen

### ISSUE THREAD

**Issue by Schmakus** [simatec/ioBroker.shuttercontrol#229]
Aktuell werden in den Zeiteinstellungen nur Sonnenauf- und untergang, wie auch GoldenHour berücksichtigt.
Hier sollte jedoch noch der Helligkeitssensor mit integriert werden. z.B.: "Wohnbereich mit Helligkeitssensor"

**Comment by simatec** [comment]
Dann musst du dort den Wert für das runterfahren setzen. Denke die Werte sind selbsterklärend

**Comment by Schmakus** [comment]
Thema ist leider nicht geklärt. Das Eintragen der Schwellwerte ist klar. Aber es fehlt die Berücksichtigung der Uhrzeiten, wie z.B. Wohnbereich, Schlafen und Kinder. Dort gibt es nur die Option mit Sonnenuntergang,Sonnenaufgang und GoldenHour.

**Comment by simatec** [comment]
Entweder nach Helligkeit fahren oder nach Zeiten. Goldenhour usw. sind feste Zeiten. Helligkeit ist keine Zeit, sondern ein Wert in Lux.

**Comment by Schmakus** [comment]
Deshalb ja mein Verbesserungsvorschlag. 
zB.: Wohnbereich mit Helligkeit. 

Bedeutet, die Rollläden fahren nach Helligkeit aber unter Berücksichtigung von Uhrzeiten. Quasi öffnen nicht vor X Uhr. Schließen spätestens um X Uhr. 



Mit freundlichen Grüßen 
Markus Hartmann

**Comment by Schmakus** [comment]
Verstehe ich nicht. 
Wenn z.b. eingestellt ist, dass die Rollläden frühestens um 9 öffnen sollen, der Lichtsensor jedoch um 8 seinen Schwellwert erreicht hat, können sich die Rollläden bis 9 zu bleiben und dann öffnen?
Abends dasselbe. Wenn eingestellt ist, die Rollläden spät. um 21 Uhr zu schließen, aber der Schwellwert noch nicht erreicht ist, dann können die Rollläden doch trotzdem schließen?!

**Comment by Schmakus** [comment]
In JS würde ich das ungefähr so lösen:
`const closeWeek = '21:00';
const soonestOpen = '08:00';
const latestOpen = '10:00';
const thresholdOpen = 400;
const thresholdClose = 200;

on({id: 'deconz.0.Sensors.40.lux', change: "ne"}, async function (obj) {
  var value = obj.state.val;
  if (value >= thresholdOpen && compareTime(soonestOpen, null, ">=", null) && getState("hm-rpc.1.00165A49924753.1.LEVEL").val != 100) {
    await shutterOpen();
  } else if (value <= thresholdClose && getState("hm-rpc.1.00165A49924753.1.LEVEL").val != 0) {
    await shutterClose();
  }
});

let Close = schedule(('' + getDateObject(closeWeek).getHours()).toString().trim() + ' ' + ('' + getDateObject(closeWeek).getHours()).toString().trim() + ' ' + '*'.toString().trim() + ' ' + '*'.toString().trim() + ' ' + '*'.toString().trim(), async function () {
  if (getState("hm-rpc.1.00165A49924753.1.LEVEL").val != 0) {
    await shutterClose();
  }
});
Open = schedule(('' + getDateObject(latestOpen).getHours()).toString().trim() + ' ' + ('' + getDateObject(latestOpen).getHours()).toString().trim() + ' ' + '*'.toString().trim() + ' ' + '*'.toString().trim() + ' ' + '*'.toString().trim(), async function () {
  if (getState("hm-rpc.1.00165A49924753.1.LEVEL").val != 100) {
    await shutterOpen();
  }
});`

**Comment by MojitoJoe1813** [comment]
Ich kann Schmakus Vorschlag nachvollziehen und finde ihn auch sinnvoll. 
Meine Vorstellung ging jedoch in eine etwas andere Richtung:
Ich kann genau einen Helligkeitssensor bzw. -schwellwert definieren. Dieser scheint dann für alle Rolläden gleichermaßen zu gelten. Das ist für mich praxisfern: 
Je nach Standort eines Helligkeitssensors ist z.B. bei Sonnenuntergang der Wert auf der Westseite meines Hauses noch hell genug, auf der Ostseite ist zur gleichen Zeit (z.B. durch Beschattung etc.) der Helligkeitswert deutlich niedriger - Bei Sonnenaufgang anders herum. Demnach möchte ich jeden Rolladen einzeln (wäre am flexibelsten; sonst z.B. auch Wohnbereiche) mit einem positiven oder negativen Offset zum einzigen definierbaren Sensor/Wert reagieren lassen.
