### ISSUE TITLE
Helligkeitsensor fährt Rollos immer wieder zu

### ISSUE THREAD

**Issue by DrHappy90** [simatec/ioBroker.shuttercontrol#233]
In Version 1.3.0 fahren die Rollos nach manuellem Hochfahren immer wieder runter.

**Expected behavior**  
Ich denke es sollte so sein:
Helligkeitswert ist unterschritten, Rollos fahren runter. 
Rollo wird manuell hoch gefahren. Rollo soll geöffnet bleiben bis (Rollladen spät schließen) oder erst am nächsten Abend.

Vielen Dank für die Integration von gekippten Zustand des Fenstergriffsensors und den sonst super guten Adapter👍

Wenn logfiles benötigt werden, kurze Rückmeldung. 

Spende zur Unterstützung geht raus an dich 😉👍

Vielen Dank

**Comment by simatec** [comment]
Fix in Version 1.3.1
