### ISSUE TITLE
Weihnachtseinstellungen - Option für Aktion

### ISSUE THREAD

**Issue by meifi** [simatec/ioBroker.shuttercontrol#234]
Moin, erst einmal vielen Dank für den klasse Adapter! Alles Funktioniert ohne Probleme und nimmt viel Arbeit für das erstellen diverser Skripte ab! 

Wäre es möglich, die Weihnachtseinstellung um eine Konfigurierbare Variable, pro Rollladen zu erweitern, welche z.B. mit dem Status einer Steckdose verknüpft werden kann? Somit könnte man in den globalen Einstellungen eine bestimmte Uhrzeit festlegen, welche alle Steckdosen zur Weihnachtszeit gemeinsam einschaltet, evtl. auch mit einstellbaren delay. Werden die Rolläden später vom Weihnachtsstand in den geschlossenen gefahren, werden die Steckdosen automatisch ausgeschaltet. Dies evtl. auch mit einem negativen konfigurierbaren delay (Steckdose wird ausgeschaltet, 2 Sekunden später wird der Rollladen geschlossen.)

Vielen Dank :)

**Comment by simatec** [comment]
Das Thema bzw. vergleichbare Themen hatten wir bereits in der Vergangenheit.
Shuttercontrol dient zur Automatisierung der rollläden und soll nicht dafür gedacht sein, andere Geräte im Smarthome zu steuern.
Da aber Shuttercontrol states zum Status der Rollläden ausgibt, kann man über Skripte oder Szenen sich da selber nach eigenen Wünschen alles aufbauen.
