### ISSUE TITLE
bei Schulferieneinstellungen einen eigenen DP verwenden

### ISSUE THREAD

**Issue by Negalein** [simatec/ioBroker.shuttercontrol#235]
Ich hätte einen Feature-Request! 😉

Wir haben darüber schonmal gesprochen.
Ist es in einer nächsten Version möglich, dass in den Schulferieneinstellungen die Möglichkeit besteht, einen eigenen DP einzutragen (so wie beim Urlaub)?
Leider kennt der Schoolfree-Adapter nur die deutschen Ferien.

**Comment by simatec** [comment]
Habe ich mit eingebaut und kommt mit Version 1.3.1
