### ISSUE TITLE
Automatisches hoch und rutnerfahren wird nicht mehr getriggerd

### ISSUE THREAD

**Issue by Sepalod** [simatec/ioBroker.shuttercontrol#248]
Hallo Zusammen,

Ich habe die seltsame Situation, dass bei mir seit einigen Tagen kein Event mehr automatisch (Astro) getriggered wird für das automatische Hoch und Herunterfahren der Rolläden. Dies ist bei mir der Fall nachdem ich einen Stromausfall hatte. Triggere Ich  das Event (openAll, closeAll) manuell funktioniert alles wie es soll - leider jedoch nicht mehr das automatische Triggeren nach Astro Einstellungen. Hätte jemand noch eine Idee woran dies noch liegen könnte?

**Comment by simatec** [comment]
Prüfe mal deine States für autoUp, autoDown und autoSun.
Bei einem Absturz von iobroker kann es sein, dass dir States verloren gehen

**Comment by Sepalod** [comment]
Hi @simatec ,

die states sind in der Tat alle null. Ich dachte diese werden automatisch neu initialisiert wenn ich openAll ausführe? Wie kann ich dies denn fixen?

**Comment by simatec** [comment]
openAll setzt dir nicht die States ... Die States sind für deine eigene Config, welcher Rollladen wann automatisch fahren darf.
Wenn nun die States durch einen Chrash weg sind, musst du diese händisch wieder auf true setzen

**Comment by Sepalod** [comment]
Hi @simatec ,

habe die States nun alle wieder von Hand gesetzt und nun funktionert auch alles wieder. Veilen Dank für die Info. Issue kann hiermit geschlossen werden. DANKE

**Comment by tschortschde** [comment]
> Wenn nun die States durch einen Chrash weg sind, musst du diese händisch wieder auf true setzen

Kann / Wie kann man das aktualisieren?
