### ISSUE TITLE
Beschattung SunProtect triggern über einen Datenpunkt

### ISSUE THREAD

**Issue by SpezialAgent** [simatec/ioBroker.shuttercontrol#254]
Ich würde gerne die Beschattung (sunprotect) über einen Trigger ein- und ausschaltbar machen. Damit kann ich in einer VIS den Trigger setzen.

Der Grund ist, dass ich im Sommer das Haus vor einer Sonneneinstrahlung schützen möchte. Im Winter möchte ich aber die Sonne als zusätzliche Wärmeenergie ins Haus lassen.

Gruß
Martin

**Comment by hombach** [comment]
FYI - habe das Thema in meiner Beschattung-Steuerung (noch per SPS, nicht iOBroker) auf die 24h-Aussen- Durchschnittstemperatur gelegt. Sprich bei rund 16 Grad wird in zwei Stufen (erst keine Fenster mehr öffnen, dann keine Beschattung) von Beschatten auf "Heizen" umgestellt....  funktioniert seit 10 Jahren prima, muss da nie korrigieren, auch in den Übergangsphasen, wo es tageweise hin und her geht.

**Comment by simatec** [comment]
Mit den richtigen Einstellungen kannst du mit Außentemperaturen und Innentemperaturen so arbeiten, dass Shuttercontrol diese Regelung für dich übernimmt. Alternativ kannst du auch mit den Objekten in autoSun arbeiten. Steht alles in der Doku
