### ISSUE TITLE
Option "frühstens schließen"

### ISSUE THREAD

**Issue by J3susC** [simatec/ioBroker.shuttercontrol#255]
Zunächst einmal danke für das Modul! Gibt es die Möglichkeit für eine Option "abends frühstens schließen" analog zum "morgens spätestens öffnen"?

Ich hatte die Steuerung bis dato direkt über Homematic gelöst und konnte dort im Programm entsprechend festlegen, dass die Rollläden abends frühstens zu einer bestimmten Uhrzeit schließen (Hintergedanke: Weihnachtszeit, Rollläden schließen nicht zum Sonnenuntergang sondern erst ein paar Stunden später). Da ich gerne auf Shuttercontrol umsteigen möchte, wäre eine entsprechende Option nett... oder kann man das anderweitig lösen und ich habe das bis jetzt übersehen?

Grüße

jC

**Comment by simatec** [comment]
Das ist mit shuttercontrol umsetzbar. 
In der Doku sind alle Funktionen erklärt

**Comment by paddybo93** [comment]
Moin Zusammen,
ich habe mich gerade das gleiche gefragt, konnte aber nichts in der Doku finden. Dort steht zwar, das es geht, aber nicht wie es geht. Oder bin ich einfach nur blind? 🙈
Beste Grüße 
Paddy

**Comment by simatec** [comment]
Hier kann man z.B. die Weihnachtseinstellungen nutzen, oder die Zwischenposition oder auch die Option spät schließen.
Also im Prinzip 3 Möglichkeiten dies umzusetzen

**Comment by Dino0811** [comment]
Hier ist es wohl besser aufgehoben:

Hallo,
Ich fände ein frühestens schließen auch super.

Mein Wohnbereich soll im Winter und der "Übergangszeit" 20:00 schließen (Außnahme Weihnachten, hier bleiben einige Fenster offen und 22:30 wird per "spät schließen" dann komplett geschlossen)

daher hätte ich gern das mein Wohnbereich mit dem Sonnenuntergang/Golden Hour schließt, jedoch frühestens 20:00

sprich z.B.:
Winter Sonnenuntergang 17:00 --> Rollladen schließt trotzdem erst 20:00
Übergangszeit, Sonnenuntergang 18:30 --> Rollladen schließt erst 20:00
Sommer: Sonnenuntergang 20:50 --> Rolladen schließt 20:50

Ich habe den Weihnachtsmodus aktiviert, mit Spät schließen 22:30 (das möchte ich auch nicht manuell nach Jahreszeit anpassen)
Wohnbereich schließt nach Zeit 20:00, in der helleren Jahreszeit soll dies aber auch erst später passieren, in der dunkleren aber auch nicht (nach Astroeinstellungen früher - sondern eben 20:00)

wie könnte man dies noch lösen?

beste Grüße und vielen Dank!

PS: der Adapter ist was an Automatisierung möglich ist der Hammer! - Vor allem der Sonnenschutz in Verbindung mit der Wetterstation!

_Originally posted by @Dino0811 in https://github.com/simatec/ioBroker.shuttercontrol/issues/367#issuecomment-1061119748_
