### ISSUE TITLE
Rollo fährt auf gekippt Position, obwohl Rollo geöffnet

### ISSUE THREAD

**Issue by ChrissT23** [simatec/ioBroker.shuttercontrol#256]
Ich habe bei der Version 1.3.2 das Problem, dass bei meinen Terrassentüren, mit dem Homematic Drehgriff, die Rollos auch tagsüber auf den Wert für gekippt fahren. Die anderen Fenster machen das nicht. 
`

Shuttercontrol.0 | 2021-11-06 16:33:42.681 | debug | (11437) save back trigger action: up for device Rollo Wohnzimmer Links
-- | -- | -- | --
shuttercontrol.0 | 2021-11-06 16:33:42.680 | debug | (11437) #1 shutter trigger released Rollo Wohnzimmer Links already in place: 100%
shuttercontrol.0 | 2021-11-06 16:33:42.680 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger Change is:upDown
shuttercontrol.0 | 2021-11-06 16:33:42.679 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger Action is:up
shuttercontrol.0 | 2021-11-06 16:33:42.679 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger Height is:100
shuttercontrol.0 | 2021-11-06 16:33:42.679 | debug | (11437) Rollo Wohnzimmer Links - shutter current Height is:100
shuttercontrol.0 | 2021-11-06 16:33:42.678 | debug | (11437) Rollo Wohnzimmer Links - shutter current state.val is:100
shuttercontrol.0 | 2021-11-06 16:33:42.477 | debug | (11437) Rollo Wohnzimmer Links - shutter conversion is:false
shuttercontrol.0 | 2021-11-06 16:33:42.383 | debug | (11437) TriggerID changed: hm-rpc.2.0007DBE991C9BC.1.STATE Value: 0
shuttercontrol.0 | 2021-11-06 16:33:37.987 | debug | (11437) Rollo Wohnzimmer Links Old value = 100. New value = 100. automatic is active
shuttercontrol.0 | 2021-11-06 16:33:37.929 | debug | (11437) Rollo Wohnzimmer Links - window is still open -> driving now to :100
shuttercontrol.0 | 2021-11-06 16:33:37.927 | info | (11437) #1 Set ID: Rollo Wohnzimmer Links value: 100%
shuttercontrol.0 | 2021-11-06 16:33:37.927 | debug | (11437) #1 save trigger action: up for device Rollo Wohnzimmer Links
shuttercontrol.0 | 2021-11-06 16:33:37.927 | debug | (11437) #1 save trigger height: 100% for device Rollo Wohnzimmer Links
shuttercontrol.0 | 2021-11-06 16:33:37.927 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger change is:upDown
shuttercontrol.0 | 2021-11-06 16:33:37.926 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger drive-up is:100
shuttercontrol.0 | 2021-11-06 16:33:37.926 | debug | (11437) Rollo Wohnzimmer Links - shutter current state.val is:15
shuttercontrol.0 | 2021-11-06 16:33:37.910 | debug | (11437) Rollo Wohnzimmer Links - shutter conversion is:false
shuttercontrol.0 | 2021-11-06 16:33:37.891 | debug | (11437) TriggerID changed: hm-rpc.2.0007DBE991C9BC.1.STATE Value: 2
shuttercontrol.0 | 2021-11-06 16:33:37.454 | debug | (11437) outsidetemperature changed: hm-rpc.2.00181A499047BC.1.ACTUAL_TEMPERATURE Value: 9.8
shuttercontrol.0 | 2021-11-06 16:33:37.433 | debug | (11437) Lightsensor changed: hm-rpc.2.00181A499047BC.1.ILLUMINATION Value: 258.3
shuttercontrol.0 | 2021-11-06 16:33:37.433 | debug | (11437) Brightness sensor value: 258.3
shuttercontrol.0 | 2021-11-06 16:33:31.458 | debug | (11437) Rollo Wohnzimmer Links Old value = 100. New value = 15. automatic is active
shuttercontrol.0 | 2021-11-06 16:33:31.457 | debug | (11437) Shutter state changed: Rollo Wohnzimmer Links old value = 100 new value = 15
shuttercontrol.0 | 2021-11-06 16:33:31.437 | debug | (11437) Rollo Wohnzimmer Links - window is still open -> driving now to :15
shuttercontrol.0 | 2021-11-06 16:33:31.358 | info | (11437) #1 Set ID: Rollo Wohnzimmer Links value: 15%
shuttercontrol.0 | 2021-11-06 16:33:31.357 | debug | (11437) #1 save trigger action: up for device Rollo Wohnzimmer Links
shuttercontrol.0 | 2021-11-06 16:33:31.356 | debug | (11437) #1 save trigger height: 100% for device Rollo Wohnzimmer Links
shuttercontrol.0 | 2021-11-06 16:33:31.356 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger change is:upDown
shuttercontrol.0 | 2021-11-06 16:33:31.356 | debug | (11437) Rollo Wohnzimmer Links - shutter trigger drive-up is:15
shuttercontrol.0 | 2021-11-06 16:33:31.355 | debug | (11437) Rollo Wohnzimmer Links - shutter current state.val is:100
shuttercontrol.0 | 2021-11-06 16:33:31.297 | debug | (11437) Rollo Wohnzimmer Links - shutter conversion is:false
shuttercontrol.0 | 2021-11-06 16:33:31.250 | debug | (11437) TriggerID changed: hm-rpc.2.0007DBE991C9BC.1.STATE Value: 1

`

**Comment by simatec** [comment]
Sollte in Version 1.3.3 gefixt sein

**Comment by ChrissT23** [comment]
Installiert und getestet, bis jetzt sieht es gut aus. 

Vielen Dank ! Ging ja wirklich sehr fix.
