### ISSUE TITLE
Install nicht möglich

### ISSUE THREAD

**Issue by mp80spike** [simatec/ioBroker.shuttercontrol#258]
Hallo,

Kann es sein das der Adapter gerade nicht zu installieren ist. 

NODE.JS: V14.18.1NPM: V6.14.15
 bekomme immer eine Fehlermeldung 

iobroker add shuttercontrol 1 --host iobroker

NPM version: 6.14.15

npm install iobroker.shuttercontrol@1.2.1 --loglevel error --prefix "/opt/iobroker" (System call)

npm ERR! code ERR_INVALID_ARG_TYPE

npm ERR! The "from" argument must be of type string. Received null

npm ERR! A complete log of this run can be found in:npm ERR! /home/iobroker/.npm/_logs/2021-11-08T13_22_24_546Z-debug.log

host.iobroker Cannot install iobroker.shuttercontrol@1.2.1: 1

ERROR: Process exited with code 25

**Describe the bug**  

**To Reproduce**  
2. Click on '...'

**Expected behavior**  

**Screenshots & Logfiles**  
If applicable, add screenshots and logfiles to help explain your problem.

**Versions:**  
 - Adapter version: <adapter-version>
 - JS-Controller version: <js-controller-version> 
 - Node version: <node-version> 
 - Operating system: <os-name>

**Additional context**

**Comment by simatec** [comment]
Kann ich nicht bestätigen ... Hab es auf 3 Systemen getestet

![image](https://user-images.githubusercontent.com/39792461/140767492-99083e54-0cfd-44a0-a6ce-3838780cd949.png)

**Comment by mp80spike** [comment]
Danke fürs nachgucken. Dann muss es an etwas anderem liegen. Komisch
