### ISSUE TITLE
Feature related questions

### ISSUE THREAD

**Issue by klassisch** [simatec/ioBroker.shuttercontrol#30]
Some feature related questions which arose during my carry over from HM based shutter control to this iobroker adapter
1.	During the weekend shuttercontrol  seems to work differnently to workdays. During the weekend the shutter up seems tob e controllable by time only and cannot be influenced by sunrise or golden hour. Does this have a special reason or could it be implemented in a similar way?
2.	In Homeatic I did not couple the shutter of the patio door to the sensor of the belonging window. If the patio shutter is open and the door is unlocked then the shutter would not close. This would be even worse. So I coupled the automated closing to the neighboured window shutter. The patio shutter closes a few minutes after the window shutter. So, the window shutter works as a kind of alert. Could this be achieved with shuttercontrol in a similar way?
3.	Is it possible to have an additional „global“ closing for all shutters? So e.g. at 22:00 all shutters could be closed for security reasons.
4.	Is it possible to have a global safety opening for all shutters or at least for some sutters which are located toward the street or entrance? This kind of behaviour is recommended e.g. by the fire brigade. If e.g. a smoke detector triggers it is recommended to open all the shutters and to switch on all lights. This helps the firefighters to find the alarming house.

**Comment by simatec** [comment]
added > 0.7.0
