### ISSUE TITLE
Individuelle Rollladeneinstellungen - getrennter Fenster Kontakt für Öffnen und Kipp

### ISSUE THREAD

**Issue by fox512** [simatec/ioBroker.shuttercontrol#301]
Ich habe zwei getrennte Kontakte für Fenster offen (Sensor auf Griffseite unten) und Fenster kipp (Sensor auf Scharnierseite oben).
Es wäre cool wenn ihr diesen zusätzlichen Kontakt berücksichtigen könntet, um Öffnen bzw. Lüften zu unterstützen.
Beste Grüße

**Comment by simatec** [comment]
Gibt es bereits in der aktuellen latest Version

**Comment by fox512** [comment]
Danke für die schnelle Antwort, leider trifft das m.E. zumindest in der v1.4.4 noch nicht zu ...
Es gibt einen Kontakt mit verschiedenen Zuständen für geschlossen / offen / kipp. So einen habe ich leider nicht, sondern wie oben angegeben zwei Kontakte ...

**Comment by simatec** [comment]
Dann würde ich dir einen kleinen Script empfehlen, der dir die beiden Kontakte zusammenfasst. Sollte auch mit Alias machbar sein.
