### ISSUE TITLE
Einbindung Helligkeitssensor Wetterstation zum schließen / öffnen der Rolläden

### ISSUE THREAD

**Issue by Markus-3** [simatec/ioBroker.shuttercontrol#305]
Liebe kreatives Entwicklerteam,
bisher wird das schließen und öffnen der Rolläden durch die Astro Einstellungen festgelegt.

Gäbe es nicht die Möglichkeit die Werte eines externen Helligkeitssensor einzubinden? 
So könnte man selbst festlegen das die Rollöden z.B bei 50lux Tageslicht hochfahren und bei 100lux runter.

Das wäre wesentlich einfacher als mit der Zeitlichen Verzögerung die man einstellen kann.
Würde mich freuen wenn dies umsetzbar wäre!!!
Ansonsten muss ich noch sagen das ich aller größten Respekt vor dem habe was Ihr hier mal wieder auf die Beine gestellt habt.
TOP macht weiter so!!!
Gruß Markus

**Comment by simatec** [comment]
Einen Helligkeitssensor zum öffnen und schließen der Rollläden kannst du bereits in Shuttercontrol einbinden und deine Schwellwerte festlegen

**Comment by Markus-3** [comment]
Also unter den Extra-Einstellungen gibt es unter Einstellungen Helligkeitssensor eine Möglichkeit. Mir war bisher nur nicht klar ob
1. Wenn die Einstellungen in Astro Einstellungen ausgefüllt sind er dann nach Uhrzeit oder nach Helligkeit schließt und öffnet
2. ob sich das auf die Beschattung oder das schließen und öffnen an Tagesbiginn und Ende bezieht

**Comment by simatec** [comment]
In den Rollladen-Einstellungen kannst du wählen, wonach dein Rollladen geöffnet bzw. geschlossen werden soll.
Da musste du den Helligkeitssensor auswählen

**Comment by Markus-3** [comment]
Also ich verwende die Version 1.3.8 und unter den Rolladeneinstellungen finde ich nichts diesbezüglich. Nur zum Sonnenschutz finde ich was aber das ist ja nicht das richtige
Sorry , entweder bin ich zu blöd, ich habe die falsche Version oder ich habe mein Anliegen falsch beschrieben????

**Comment by simatec** [comment]
Du kannst den Helligkeitssensor direkt in den Rollladen Einstellungen und Art der Rollladensteuerung …. auswählen
