### ISSUE TITLE
Nach Update auf 1.4.5 Rollläden öffnen nicht

### ISSUE THREAD

**Issue by tobasium** [simatec/ioBroker.shuttercontrol#309]
Guten Morgen,

nach dem Update auf 1.4.5 sind heute morgen die Rolläden nicht in den zustand offen gefahren.
Ebenfalls hatte der Button open Shutter for LIving area nicht reagiert.

io:
3.3.21
Node.js
v14.18.2
NPM
6.14.15

![shutter](https://user-images.githubusercontent.com/23247891/146140367-86a18afb-b1ca-4925-bf6c-361e5f366b26.png)

**Comment by simatec** [comment]
Der Bug ist bekannt und wird heute mit einem Update behoben

**Comment by tobasium** [comment]
Hi,
Super. Vielen DANK

**Comment by simatec** [comment]
Bitte die Version 1.4.6 testen

**Comment by tobasium** [comment]
Guten Morgen,
Rolladen öffnen und schließen wieder. Ich teste heute Abend noch genauer.

Sieht soweit aber gut aus.

**Comment by tobasium** [comment]
Also so wie ich sehe läuft wieder alles
