### ISSUE TITLE
Weihnachtszeit wird nicht beendet

### ISSUE THREAD

**Issue by jimknopf63** [simatec/ioBroker.shuttercontrol#329]
Die automatische Weihnachtszeiteinstellung ist zwar beendet, trotzdem bleiben die Rolläden im Weihnachtszeitmodus. In AutoState der Rollos steht immer noch XMAS. Neuste Version 1.49 installiert. Auch mit 1.48 und 1.47 getestet, gleiches Problem.

**Comment by guitardoc** [comment]
Gleiches Problem auch bei mir. Siehe auch ioBroker Forum.

**Comment by PalmManiac** [comment]
Hier das gleiche. Heute ist der 13.01. und die Rollos im Wohnzimmer laufen immer noch im Weihnachtsmodus ohne etwas daran ändern zu können.

**Comment by lonsimbt** [comment]
Gleiches tritt hier auch auf. Das Ende der Weihnachtszeit (bei mir 06.01.) wird nicht berücksichtigt.

**Comment by rg-engineering** [comment]
der PR https://github.com/simatec/ioBroker.shuttercontrol/pull/333 sollte das Problem beheben...

**Comment by simatec** [comment]
Fix in Version 1.4.10
