### ISSUE TITLE
Default State for shutters.autoUp/autoDown

### ISSUE THREAD

**Issue by tsvsj** [simatec/ioBroker.shuttercontrol#34]
Hi,

fist of all thank you very much for this awesome adapter! I was doing the exactly same thing using the javascript adapter, but pretty less professional and more buggy. ;-)

After configuring the adapter for the first time, I was a little bit confused, that the shutters didn't go up at the morning. A short check on the objects showed the reason for that: The default states for the shutters is `false`. I thought, that setting a shutter mode to, i.e. "Sleeping (Auto)", would set this state to `true`.
Is this some kind of an issue or an expected behavior? Within the adapter configuration I couldn't find any other configuration to change this setting.

Thanks!

**Comment by simatec** [comment]
Fix
