### ISSUE TITLE
[FeatureRequest] Jede Nacht ist anders

### ISSUE THREAD

**Issue by none007** [simatec/ioBroker.shuttercontrol#343]
Wäre es möglich zu den vorhanden Sonnenuntergangs etc. Zeit noch folgende Idee mit einzubauen?

https://www.stall.biz/project/jede-nacht-ist-anders-dynamische-rolladenbetatigung

**Comment by OstfrieseUnterwegs** [comment]
Vlt kannst Du das mit 'Elevation' erreichen? Dämmerungs-Ende/Anfang  ist bei Sonnenstand -6°

> Die bürgerliche Dämmerung ist die hellste Dämmerungsphase. In der Regel benötigt man draußen kein zusätzliches künstliches Licht, um den meisten Aktivitäten nachzugehen. Ohne Hilfsmittel können während dieser Phase nur die hellsten Himmelskörper am Himmel gesehen werden.
[https://www.timeanddate.de/astronomie/daemmerung-phasen](url)

**Comment by none007** [comment]
Danke für deinen Hinweis, leider beträgt die Abweichung zu meinen aktuellen Zeiten (ich verwende aktuell das obige Skript auf meiner Homematic) locker eine Stunde. Z.B. wäre die bürgerliche Dämmerung am kürzesten Tag 21.12.2022 kurz vor 17 Uhr wohingegen mit dem Skript und meinen persönlichen (ok, die gewünschten Zeiten meiner Frau) Parametern die Schließzeit erst um kurz vor 18 Uhr wäre, Die Idee hinter dem obigen Skript ist ja, dass gerade im Winter es eigentlich schon dunkel ist, aber man evtl. noch nicht im Rolladenkäfig sitzen möchte.
Vielleicht findet die Idee ja doch noch Eingang in den Adapter.

**Comment by Flipperbastler** [comment]
Ein frei wählbarer Datenpunkt für Öffnen und Schließen wäre für die Anforderung bereits ausreichend, so könnte man das Script einfach auf der CCU laufen lassen und die Variablen an den Broker übergeben. Wäre wirklich toll, wenn das Einzug finden würde! Danke.
