### ISSUE TITLE
Trigger other states from shutter

### ISSUE THREAD

**Issue by tsvsj** [simatec/ioBroker.shuttercontrol#35]
Hi,

before getting to know the shutcontrol adapter I used javascript for adding astro schedules. I was using scenes, from the scenes adapter, to trigger a group of devices. Within the group I had Philip Hue lights, which were simply turned off, when the shutters are opened, or turned on, when the shutters are closed.

It would be great to have the possibility to trigger another state (OID), with just `true` or `false` from the adapter itself (like triggering scenes). As a workaround I will use state subscriptions, which will work great, but it would be perfect to have everything in the same place, without any annoying scripts from the javascript adapter.

Thanks for considering this idea.

**Comment by simatec** [comment]
Du kannst du weiterhin deine Scripte nutzen und triggerst auf dein Rolladenlevel
