### ISSUE TITLE
Adding control for earliest and latest shutdown

### ISSUE THREAD

**Issue by tsvsj** [simatec/ioBroker.shuttercontrol#36]
Hi,

in the time configuration it's possible to define the earliest and latest time for bringing the shutters up. It would be great to do the same for shutters down. I'm aware that I can define an offset from the astro time as well. But in my case it would be more practical to set static times for earliest and latest.

Thanks in advance!

**Comment by kugelkopf123** [comment]
That is exactly what I would wish for.
Maybe also a data point for the DWD adapter. So that when the storm is reported, the roller shutters move up or down completely.

Thanks in advance!

**Comment by simatec** [comment]
Ist ab Version 0.7.0 möglich ...

**Comment by kugelkopf123** [comment]
Das ist nun bezogen auf den Wunsch vom Threadopener nicht auf meine Anfrage oder? Stehe etwas auf dem Schlauch. Mir ist nicht bewusst wie man meinen "Vorschlag" mit der aktuellen Version umsetzen könnte. Vielleicht hast du da einen Tipp?
