### ISSUE TITLE
[Frage] Windalarm nicht schließen bei false

### ISSUE THREAD

**Issue by Jack77777777** [simatec/ioBroker.shuttercontrol#360]
Ich habe einen Windalarm mit Höhe 100% aktiviert. Nun fahren meine Rollos dauernd hoch und runter bei Windschwankungen.
Ist es möglich auch eine Höhe für false einzustellen oder, dass die Rollos nicht wieder herunterfahren bei false, sondern erst wieder nach Astro, Sonnenschutz oder manuell ?

**Comment by simatec** [comment]
Der Windalarm ist ein Switch und kein Zahlenwert. 
bitte lies dazu die Doku

**Comment by Jack77777777** [comment]
Ichvhab die Doku schon gelesen. Verstehe halt nicht warum die Rollos wenn kein Alsrm anliegt wieder runter fahren müssen. Die hören ja gar nicht mehr auf hoch und runter zu fahren wenn starke Windböen sind.

**Comment by simatec** [comment]
Zeige mal bitte deine Config und den State für den Windalarm

**Comment by Jack77777777** [comment]
![image](https://user-images.githubusercontent.com/64719909/152751989-b991668f-0452-448d-a874-4881c8b8f9c4.png)
![image](https://user-images.githubusercontent.com/64719909/152752013-53d1206a-c545-4c0b-bfb8-7ec672aec392.png)
![image](https://user-images.githubusercontent.com/64719909/152752020-eafb022c-70dc-4223-870a-850fd1a2b307.png)
[system.adapter.shuttercontrol.0.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/8013549/system.adapter.shuttercontrol.0.txt)

**Comment by simatec** [comment]
Wenn der von einer eigenen Wetterstation kommt, dann ist aber klar, dass die Rollläden da immer hoch und runter fahren. Gerade bei den stürmischen Tagen schwankt dies enorm. Baue dir da mal ein Script, um das zu entprellen

**Comment by Jack77777777** [comment]
Ich hab gestern schon das Programm in der CCU angepasst, dass die Alarmvariable bei 50kmh aktiv und bei 10kmh inaktiv wird. Dachte man kann das herunterfahren in Deinem Plugin evtl. deaktivieren.

**Comment by Jack77777777** [comment]
Ich verstehe immer noch nicht warum die Rollos hochfahren wenn der Alarm aufgehoben wird. 
Aktuelles Beispiel:
- Alarm an: Rollos fahren hoch
- Dann fahre ich die manuell runter
- Alarm aus: Rollos fahren wieder hoch

**Comment by simatec** [comment]
Fix in Version 1.4.12
