### ISSUE TITLE
Rollladen schließen bei Sonnenuntergang

### ISSUE THREAD

**Issue by OlaninS** [simatec/ioBroker.shuttercontrol#367]
Hallo,

ist es möglich, den Rollladen bei Sonnenuntergang zu schließen, so wie ich ihn bei Sonnenaufgang öffnen kann. Finde es nicht.

Gruß
Sascha

**Comment by Jack77777777** [comment]
Ist beides an der selben Stelle.
Extraeinstellungen->Astro die Verzögerung, falls gewünscht
![image](https://user-images.githubusercontent.com/64719909/152852909-82c263a8-4f78-4fa2-9709-bad5d2eebbe1.png)

Bei Zeit-Einstellungen z.B. Wohnbereich ...mit Sonnenauf & Sonnenuntergang
![image](https://user-images.githubusercontent.com/64719909/152852989-d48ecece-487f-4b74-bd36-ebe5465ee26a.png)

und beim den Rollos (Haupteinstellungen dann Wohnbereich auswählen
![image](https://user-images.githubusercontent.com/64719909/152853117-6e37b5e8-348e-46bc-af7c-5fb832bc897d.png)

**Comment by OlaninS** [comment]
ja, dachte ich auch...
![image](https://user-images.githubusercontent.com/59517888/152989170-2ed3b468-c1f1-494e-9c16-622bc3ae67dd.png)
Aber hier kann ich für das Herunterfahren nur eine feste Zeit einstellen, nicht wie beim Hochfahren frühestens und spätestens. Und es interessiert ihn auch nicht, wann die Sonne untergeht, er fährt immer genau zu der Zeit, welche hier eingestellt ist...

Oder mach ich noch etwas verkehrt?

**Comment by Jack77777777** [comment]
In Bezug auf Deinen Screenshot für die Arbeitswoche:
Sonnenaufgang 4:30 -> hoch um 05:00
Sonnenaufgang 5:30 -> hoch um 05:30
Sonnenaufgang 7:30  -> hoch um 07:00
Mit Sonnenuntergang gehen die Rollos runter, es sei denn Du hast eine Verzögerung definiert->schaue Dir nochmal mein erstes Bild an. Die feste zeit ist nur, wenn Du im Drop Down "_**Nur die Zeit für den Wohnbereich**_" auswählst

Du sieht auch genau die Zeiten für auf bzw. zu am heutigen Tag unter den Objekten bei shuttercontrol.0/info
![image](https://user-images.githubusercontent.com/64719909/152993845-5d4da71f-fdf9-42be-989f-82c36ee39d83.png)

**Comment by tschortschde** [comment]
Das wäre echt prima ;-)
