### ISSUE TITLE
Rolladentyp z.B. Dooya mit Datenpunkten für Up & Down

### ISSUE THREAD

**Issue by Domme33** [simatec/ioBroker.shuttercontrol#370]
Hi,

ich benutze in meinem Haus Dooya Rolladensteuerungen. Diese haben die Datenpunkte Level, Up, Down, Stop und Status.
Das Problem ist, dass bei Level 100 der Behang nur bis Bodenkante schließt. Komplett geschlossen wird das Rollo, indem der Datenpunkt Down mit "true" angesprochen wird. Das bedeutet, dass die Rolläden alle nur bis Bodenkante geschkossen werden.

Ist es möglich für das Schließen der Rolläden einen anderen Datenpunkt zu nutzen?

**Comment by simatec** [comment]
Das kann mit Alias gelöst werden.
Shuttercontrol braucht einen Datenpunkt von 0-100%
