### ISSUE TITLE
Zuordnung zu Bereich funktioniert nicht

### ISSUE THREAD

**Issue by aufruf** [simatec/ioBroker.shuttercontrol#371]
allo,

erstmal vielen Dank für den tollen Adapter. Ich hatte bisher drei Rollladen in einem Bereich (zugeordnet zu Wohnbereich Automatik) und die Steuerung hat super funktioniert. Ich hatte hierzu zusätzlich in meiner VIS einen Button der den Control Datenpunkt "closeLiving" steuert zum schließen aller Rollladen im Wohnbereich. Nun hab ich zwei weitere Rollladen im Kinder Bereich hinzugefügt und hierfür wiederum auch einen Button für closeChildren.

Wenn ich einen der beiden Control Befehle setze (closeLiving oder closeChildren // mit open aber gleiches Spiel) fahren aber alle Rollladen und nicht nur der Bereich. Das ist unabhängig von der VIS und passiert auch wenn ich direkt in den Objekten auf den jeweiligen Control Befehl drücke. Hat hier jemand eine Idee woran das liegen könnte?

**Comment by aufruf** [comment]
Problem bleibt auch bestehen wenn ich die Zuordnung von „Wohnbereich Automatik“ zu „Wohnbereich“ ändere und dies analog auch für den Kinderbereich. Es fahren immer alle fünf Rollladen sobald ich versuche nur einen einzelnen Bereich zu steuern

**Comment by simatec** [comment]
Bitte den Debuglog bei Betätigung der Buttons posten
