### ISSUE TITLE
Zufällige fahrten der Rollos (täglich anders)

### ISSUE THREAD

**Issue by D3ltorohd** [simatec/ioBroker.shuttercontrol#372]
Hallo, ich hätte da eine Idee bzw. ein Feature Request.

Zum Thema Random fahren, wie war das ? Sonnenaufgan die Rollos fahren von mir aus um 8:00 Uhr. Dann kann ich für jedes Rollo oder Raum eine andere Zusatzzeit einstellen. Mal 5 Sekunden, andere 10 usw. Das heißt aber auch, die fahren jeden Tag immer in der gleichen Reihenfolge hoch.

Könnte man da vllt einfach eine Random Zeit einbauen, das die einfach auch in unterschiedlicher Reihenfolge fahren. Jeden Tag anders ? Würde grad im Urlaub eine Anwesenheit besser simulieren oder wenn man nicht zu Hause ist.

Mann könnte ja hier pro Raum das lösen, es muss nicht jeder Rollo separat fahren. Aber Raumweise und diese eben jeden Tag nicht in der selben Reihenfolge sondern zufällig durcheinander.

Grüße

**Comment by simatec** [comment]
Das würde gegen das Gesamtkonzept von Shuttercontrol sprechen.
