### ISSUE TITLE
Add pre-action - turn on power of shutter actors 

### ISSUE THREAD

**Issue by mar565** [simatec/ioBroker.shuttercontrol#38]
First of all, thank you for the great adapter.
I have a suggestion that would help me use the adapter more efficiently.
In my smart home the shutters must first be turned on by a sonoff relay. I made this because of the high idle power consumption my shutters have.
Is it possible for you to add a pre-action (switch on the relay) before any controls are send? If yes, please consider the boot time of the ESP-chips. The simplest solution would be to add an adjustable delay.

**Comment by simatec** [comment]
Das würde ich über Javascript lösen ... für den Adapter ist das wohl eher zu speziell

**Comment by mar565** [comment]
> Das würde ich über Javascript lösen ... für den Adapter ist das wohl eher zu speziell

Ich möchte meine Code teilen, falls noch jemand vor dem gleichen Problem steht.
Eventuell kann es ja doch im Adapter integriert werden.

`
on({id: 'Hilfsvariable_Position', change: "ne"}, function (obj) {
    console.log(obj.state.from);
    if(obj.state.from != "system.adapter.shuttercontrol.0" && String(obj.state.from) != "system.adapter.web.0"){
        console.log("falscher Ursprung");
        return;
    }
    if(!getState('alive_Status_Gurtwickler').val){
        console.log("Warteschleife");
        setState('Schaltaktor_Stromversorgung_Gurtwickler',true);
        var Intervall_Gurtwickler = setInterval(function () {
            log("warte...");
            if (getState('alive_Status_Gurtwickler').val) {
                log("übertragen nach warten");
                setState("Gurtwickler_position", obj.state.val);
                clearInterval(Intervall_Gurtwickler);
            }
        }, 1000);
    }
    else{
        log("direkt übertragen");
        setState("Gurtwickler_position", obj.state.val);
    }
});

on({id: 'Gurtwickler_position', change: "ne"}, function (obj) {
    if(obj.state.from !="mqtt-client.0"){
        return;
    }
    setState("Hilfsvariable_Position", obj.state.val);
});
`
Die "Hilfsvariable_Position" wird anstelle von "Gurtwickler_position" im Adapter eingetragen. Funktioniert dann wie gehabt.
