### ISSUE TITLE
Shuttercontrol V.1.4.10 Automatikfunktion funktioniert nicht

### ISSUE THREAD

**Issue by Gwenselah** [simatec/ioBroker.shuttercontrol#384]
Hallo zusammen,

shuttercontrol läuft bei mir seit mehr als einem Jahr problemlos. Nun habe ich eigene Datenpunkte ergänzt um das automatische Fahren der Rollläden (de-)aktivieren zu können.
Leider erkennt das System die Zustände der Datenpunkte nicht. Meine Konfiguration:
![image](https://user-images.githubusercontent.com/47796674/156896150-29d5fdcb-3be4-457e-8018-f3d924ef562b.png)

![image](https://user-images.githubusercontent.com/47796674/156896136-39751e60-508b-493a-8ac2-19e085c9d70a.png)

![image](https://user-images.githubusercontent.com/47796674/156896160-f105a2c6-6d0d-46cb-b972-e607dd4fe662.png)

Hab den Adapter auf Debug gestellt, aber leider werden alle Rollläden, die auf "...(Automatik)" stehen, ignoriert. Egal welcher Zustand die Datenpunkte 0_userdata.0.iQontrol.RollladenAutomatik.Schlafbereich, 0_userdata.0.iQontrol.RollladenAutomatik.Wohnbereich, 0_userdata.0.iQontrol.RollladenAutomatik.Kinderbereich haben.

Mir ist folgendes aufgefallen: Egal, welche Werte ich in meinen Datenpunkten geben, diese ändern sich nicht:
![image](https://user-images.githubusercontent.com/47796674/156896173-3eba6327-9b3c-4507-9381-643aa967d365.png)

Welche Bedeutung haben diese Datenpunkte?

Viele Grüße
Andy

**Comment by simatec** [comment]
Bitte mal den Debuglog posten. Deine Datenpunkte sollte nur true/false liefern

**Comment by Gwenselah** [comment]
Nochmals über mehrere Tage getestet. Der Fehler besteht nicht mehr. Es ist unklar, warum der Fehler auftrat, die Konfiguration wurde nicht angepasst.
Sorry für den unnötigen Issue.
