### ISSUE TITLE
Next shutter open time.

### ISSUE THREAD

**Issue by radebold** [simatec/ioBroker.shuttercontrol#385]
I show in my Vis the open and close time of my shutter, but it shows only the open time from today.

I would like to know when the shutter will open tomorrow, because over the whole day they are still opened in the morning.

Can you implement a new data point or overwrite if still opened with data of next morning?

Thx for great adapter

Thomas

**Comment by simatec** [comment]
The calculation takes place at night around 2 a.m

**Comment by radebold** [comment]
maybe it is possible a recalculation after opening/closing time ?
