### ISSUE TITLE
No automatic drive

### ISSUE THREAD

**Issue by Maschine20** [simatec/ioBroker.shuttercontrol#387]
Version 1.4.11

**Describe the bug**  
If I lower a shutter in manual mode the day before, the shutter does not go up automatically the next day.

**Versions:**  
 - Adapter version: Version 1.4.11
 - Operating system: iobroker
 - 
![Screenshot 2022-03-20 07 32 09](https://user-images.githubusercontent.com/89000090/159151097-927babde-a102-4d73-b591-ceb4e16e0632.png)

**Comment by simatec** [comment]
Please post your Debuglog

**Comment by Maschine20** [comment]
Can be closed. It was a issue because of a combination of backup of the vm and rebooting the iobroker vm.

Sorry for wrong alarm.
