### ISSUE TITLE
Täglich andere Zeiten zum hochfahren

### ISSUE THREAD

**Issue by RePa02** [simatec/ioBroker.shuttercontrol#388]
Ich habe schon vieles, was ich in einem CCU Skript habe, in dem Adapter wiedergefunden. Eine tolle Arbeit, vielen Dank!

Zum grundsätzlichen öffnen und schließen bin ich allerdings ganz altmodisch. Hoch geht es, wenn wir aufstehen müssen und runter, wenn es dunkel wird.

Was mir aber fehlt, ist Tage unterschiedlich zu konfigurieren.
Zum Beispiel haben die Kinder Freitags erst zur 2. Stunde Unterricht, da würde ich die Rollläden zumindest im Schlaf und Kinderbereich in diesem Fall gerne am Freitag später öffnen.
Ich habe es hier bisher noch nicht gefunden und möchte es daher gerne vorschlagen.

Wenn es keine Zustimmung findet, würde wohl ich ein Script schreiben, das die Datenpunkte anspricht und damit Freitags den Automatik Modus ausstellt und dann zu einer festen Zeit die Rollläden hoch fährt.

**Comment by simatec** [comment]
Das würde gegen das Gesamtkonzept sprechen

**Comment by RePa02** [comment]
> Das würde gegen das Gesamtkonzept sprechen
Okay, schade. 

Ich habe es inzwischen schon über ein Script gelöst, was den Automatikmodus für den Kinderbereich temporär deaktiviert. Funktioniert so und eine sauberere Lösung ist mir nicht eingefallen.

**Comment by simatec** [comment]
Ist doch eine gute Lösung. Dafür gibt es ja auch am Ende den Javascript Adapter, damit jeder sich sein Smarthome individuell anpassen kann.
Ein Adapter kann nie zu 100% alle Userwünsche und Vorstellungen abdecken.
