### ISSUE TITLE
HMIP Problem

### ISSUE THREAD

**Issue by UBPhoto** [simatec/ioBroker.shuttercontrol#39]
Hallo ich habe wie in der Beschreibung alles genau so eingestellt aber irgend wie hat sich ein kleines Problem eingenistet. 

Die Rolladen fahren zu einer bestimmten Zeit runter aber leider nicht mehr hoch.

Was mache ich falsch bzw welche angaben braucht ihr noch um Hilfe zu leisten.

LG. Uwe

**Comment by simatec** [comment]
Am besten wäre deine Config des Adapters
