### ISSUE TITLE
Helligkeitswert zu Verfahren wird durch Pollintervall übersprungen

### ISSUE THREAD

**Issue by vosi2** [simatec/ioBroker.shuttercontrol#399]
Hallo,
um die Helligkeit zum verfahren der Jalousien zu bekommen betreibe ich eine Modbus Wetterstation.
Durch den Pollintervall kommt es dazu das der Wert zum runter- oder rauffahren übersprungen wird.
z.b Helligkeit zum Herunterfahren 100Lux und die Wetterstation liefert 120Lux und im nächsten Poll 80 Lux.

Ich vermute das aus diesem Grund meine Jalousien nicht herunter oder rauffahren.

Kann man das so programmieren das ein Wert kleiner als 100Lux die Jalousien herunter und größer als  wieder hochfahren lässt?

Ich nutze die Version 1.4.10

Alle anderen Betriebsmodi funktionieren sehr gut. 
Danke für deine Arbeit.

Mfg Vosi2

**Comment by simatec** [comment]
Nein das liegt nicht am unterschrittenen Wert.
Shuttercontrol prüft, ob der Wert kleiner oder gleich ist.
https://github.com/simatec/ioBroker.shuttercontrol/blob/40025c792fdb8415653594968f3d3c106a875b6b/lib/shutterBrightnessSensor.js#L56

Da schein etwas an deinen Einstellungen nicht zu passen.

**Comment by vosi2** [comment]
OK danke für die Info. Ich werde weiter suchen.Mfg AxelAm 11.04.2022 11:09 schrieb simatec ***@***.***>:

Nein das liegt nicht am unterschrittenen Wert.

Shuttercontrol prüft, ob der Wert kleiner oder gleich ist.

https://github.com/simatec/ioBroker.shuttercontrol/blob/40025c792fdb8415653594968f3d3c106a875b6b/lib/shutterBrightnessSensor.js#L56

Da schein etwas an deinen Einstellungen nicht zu passen.
