### ISSUE TITLE
Kein Update möglich

### ISSUE THREAD

**Issue by DanielHD80** [simatec/ioBroker.shuttercontrol#4]
Bei mir sind nie Updates möglich, ich muss immer den Adapter löschen und neu installieren. Das ist keine Lösung... :(

Cannot find io-package.json in "null": Error: ENOENT: no such file or directory, open 'null/io-package.json'

**Comment by simatec** [comment]
Das ist kein Problem des Adapters. 
Du kannst es inzwischen auch direkt im iobroker über die Adapter in der latest repro installieren
