### ISSUE TITLE
Schoolfree values not considered?

### ISSUE THREAD

**Issue by mivodu** [simatec/ioBroker.shuttercontrol#405]
I am using schoolfree adapter and have set it up accordingly in shuttercontrol. Currently we have Eastern school holidays but the related object in shuttercontrol does not reflect it.

Do I miss something in the setup?

Setup:
![image](https://user-images.githubusercontent.com/47735196/163327281-e8823feb-5f94-463e-b649-1279495f98e5.png)

Schoolfree Objects:
![image](https://user-images.githubusercontent.com/47735196/163323246-418375f2-54c7-4812-b59e-d9c2fcc949c8.png)

Shuttercontrol Objects:
![image](https://user-images.githubusercontent.com/47735196/163327084-92cca2cd-ed34-4239-83f0-383ea5cc8d89.png)

**Comment by simatec** [comment]
The state "schoolfree" is for manual input.  if you use the schoolfree adapter you will see the results in the log
