### ISSUE TITLE
Rolladen in Manu_Mode + Sonnenschutz fährt nicht. Debug vorhanden.

### ISSUE THREAD

**Issue by Maschine20** [simatec/ioBroker.shuttercontrol#407]
Hallo,

ich habe gesehen, dass all meine Rollladen im Manu_Mode sind und nicht in Auto (siehe Bild unten). Es gibt Rollläden, die nicht von Hand verfahren wurden.

![image](https://user-images.githubusercontent.com/89000090/163728005-c283a8eb-fdc6-4906-b0bc-b2471e6c3607.png)

Meine Rollladen verfahren nicht in den Sonnenschutz/nachdem die Tür geöffnet/geschlossen wurde. Habe ich hier etwas falsch gemacht?

![Screenshot 2022-04-17 20 43 50](https://user-images.githubusercontent.com/89000090/163728163-309e2977-8c92-4e61-af2e-c885932ec3e1.png)
![Screenshot 2022-04-17 20 42 42](https://user-images.githubusercontent.com/89000090/163728166-4e6db9af-a0cd-49f7-8bfd-6a35c4007a51.png)
![Screenshot 2022-04-17 20 43 59](https://user-images.githubusercontent.com/89000090/163728161-fb1b4084-d3ba-4a90-b2ed-2bf28162fa32.png)

Anderer Rollladen mit Testkonfiguration
![Screenshot 2022-04-17 20 43 06](https://user-images.githubusercontent.com/89000090/163728165-fe4aea77-0647-4e6e-b72e-21d6030dcb2f.png)

**Versions:**  

![image](https://user-images.githubusercontent.com/89000090/163727984-c9f78957-3147-4e2a-a24d-385a412c3ec0.png)

Grüße Maschine20

**Comment by alpha7-bravo4** [comment]
Hallo ich habe bei zwei Rolladen (Obergeschoß) das selbe Verhalten. Obwohl ich diese nicht manuell bediene ändern diesen nach dem fahren in den Sonnenschutz den Status auf Manu_Mode und bleiben in der Sonnenschutzstellung "hängen".  Rolladenaktor ist von Homematic. In einer weiteren Instanz habe ich zwei weitere (Erdgeschoß) Rolladen mit den selben Einstellungen und diese Verhalten sich korrekt. Welche Informationen werden benötigt bzw was kann ich tun um herauszufinden warum diese in den Manu_Mode gehen.
Danke Grüße Alex

**Comment by simatec** [comment]
Aktiviere die Überprüfung der Rollläden nach der Fahrt

**Comment by alpha7-bravo4** [comment]
Danke Dir! Das so scheint war die Lösung.
Grüße Alex
