### ISSUE TITLE
Requested Feature: Symbol beim Einrichten des Sonnenschutzes für Bedingung

### ISSUE THREAD

**Issue by Maschine20** [simatec/ioBroker.shuttercontrol#408]
Hallo,

es wäre hilfreich zum Einrichten des Sonnenschutzes, wenn in dem Einstellungsfenster ein Symbol hinter der Bedingung ist, dass den Zustand der Bedingung signalisiert.

Zum Beispiel ein rotes Kästchen, dass die Bedingung nicht erfüllt ist.
Zum Beispiel ein grünes Kästchen, dass die Bedingung erfüllt ist.

Grüße Maschine20

**Comment by simatec** [comment]
Das sieht man doch in den States, die du für deine Bedingungen verwendest.
Die Config sehe ich nicht als VIS, die dir die aktuellen Zustände zeigt.

Aber du kannst dir das in eine VIS legen
