### ISSUE TITLE
Raffstore / Jalousien Lamellensteuerung

### ISSUE THREAD

**Issue by Skol6** [simatec/ioBroker.shuttercontrol#409]
Erstmals Gratualation zu dem Super Adapter - 10 Daumen Hoch...
Für die Steuerung von Raffstores wäre eine Lamellensteuerung super.

Beitrag von QLink ist zwar schon alt, aber noch immer aktuell.
[https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v1-4-x/142](url)

**Comment by Jack77777777** [comment]
Schau Dir mal das Skript an. 
Ich hab das mit Shuttercontrol kombiniert und es funktioniert einwandfrei. 
Shuttercontrol Adapter ist für mich littlerweile unerlässlich. Top simatec!!!

https://github.com/Schmakus/ioBroker.SetShutterLevel-HomematicIP

**Comment by Skol6** [comment]
Danke für den Tipp, das klappt nur nicht mit meinem Homematic Standard Aktor HM-LC-Bl1PBU.

Oder hast du da einen Trick auf lager?

 

Von: Jack77777777 ***@***.***> 
Gesendet: Samstag, 30. April 2022 09:23
An: simatec/ioBroker.shuttercontrol ***@***.***>
Cc: Skol6 ***@***.***>; Author ***@***.***>
Betreff: Re: [simatec/ioBroker.shuttercontrol] Raffstore / Jalousien Lamellensteuerung (Issue #409)

 

Schau Dir mal das Skript an.
Ich hab das mit Shuttercontrol kombiniert und es funktioniert einwandfrei.
Shuttercontrol Adapter ist für mich littlerweile unerlässlich. Top simatec!!!

https://github.com/Schmakus/ioBroker.SetShutterLevel-HomematicIP

**Comment by Jack77777777** [comment]
Ich habe die HmIP-DRBLI4. Weiß nicht ob es mit Deinem Aktor geht. Wenn ich die Lamellen bei über den Datenpunkt vom Skript auf 50% stelle, gehen Sie erst auf 100% und dann auf 50%. Vielleicht gehts ja doch mit Deinem Aktor oder hast Du das schon probiert. Du musst in Shuttercontrol für den Raffstore zwei Datenpunkt des Skripts hinzufügen. Einen für fahren und einen für die Verstellung der Lamellen.

**Comment by simatec** [comment]
Hierzu gab es schon mehrere Issues
