### ISSUE TITLE
Helligkeitssensor als Trigger für Automatik 

### ISSUE THREAD

**Issue by Bastelritius** [simatec/ioBroker.shuttercontrol#42]
Hallo,

ich würde es gut finden wenn man einen Helligkeitssensor als Trigger für das Autoschließen verwenden könnte. Mein HM-Sensor gibt mir z.B. Werte von 0-255 aus.

Danke

**Comment by lonsimbt** [comment]
Dem Wunsch schließe ich mich an. Es wäre sinnvoll, wenn man sowohl zum automatischen Öffnen als auch zum Schließen zusätzlich nach Helligkeit steuern könnten, also z. B.:

- Automatisches Öffnen nach Sonnenaufgang, aber nicht vor 06:00 Uhr und erst wenn der Helligkeitswert mindestens 90 ist.
- Automatisches Schließen nach Golden hour, aber erst wenn der Helligkeitswert unter 90 sinkt, spätestens aber um 22:00 Uhr

Ansonsten aber auch an dieser Stelle vielen Dank für den Adapter!

Gruß Marco
