### ISSUE TITLE
Rollo Hochfahren nach Alarm

### ISSUE THREAD

**Issue by Loi83** [simatec/ioBroker.shuttercontrol#420]
Hi, bei mir schließen sich die Rollos bei Regen über die Alarmeinstellung. Das Klappt auch sehr gut. 
Aber sollten sie nicht auch wieder in die Ausgangsposition fahren? Das passiert nämlich nicht. Anbei auch ein Bild.

![image](https://user-images.githubusercontent.com/45265773/166704269-bf697bd6-a0f0-428e-902b-6d644044a273.png)

**Comment by simatec** [comment]
Bitte den Debuglog posten (nicht als Screenshot)

**Comment by Loi83** [comment]
So Log wie gewünscht :) ich hoffe du kannst damit was anfangen :)

shuttercontrol.0 | 2022-05-16 09:52:22.334 | info | (32305) #Shutter alarm rain end Set ID: Noah value: 20%
-- | -- | -- | --
shuttercontrol.0 | 2022-05-16 09:52:22.333 | info | (32305) Alarm Rain endet for ID: Noah driving to next highest alarm priority
shuttercontrol.0 | 2022-05-16 09:52:07.284 | info | (32305) #Shutter alarm rain end Set ID: Schlafzimmer value: 20%
shuttercontrol.0 | 2022-05-16 09:52:07.283 | info | (32305) Alarm Rain endet for ID: Schlafzimmer driving to next highest alarm priority
shuttercontrol.0 | 2022-05-16 09:45:22.339 | info | (32305) #Shutter alarm Rain Set ID: Noah value: 20%
shuttercontrol.0 | 2022-05-16 09:45:07.248 | info | (32305) #Shutter alarm Rain Set ID: Schlafzimmer value: 20%

**Comment by simatec** [comment]
Ist mit Version 1.4.13 behoben
