### ISSUE TITLE
Frage zu Art der Sonnenschutzsteuerung  +/- Bereich der Sonnenposition für den aktiven Sonnenschutz

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#422]
Wie ist 

Art der Sonnenschutzsteuerung  +/- Bereich der Sonnenposition für den aktiven Sonnenschutz

zu verstehen?

Bedeutet beispielsweise 60 und Himmelsrichtung 270 einen aktiven Sonnenschutz von 210…330 (270+-60) oder 240…300 (270+-60/2)?

Danke!

**Comment by simatec** [comment]
Die Range bezieht sich auf -/+ wie in deinem ersten Beispiel 210…330 (270+-60)

https://github.com/simatec/ioBroker.shuttercontrol/blob/master/docs/de/shuttercontrol.md#sonnenschutz-einstellungen

**Comment by guitardoc** [comment]
Danke für die Info - in der Beschreibung war es für mich nicht ganz eindeutig herauszulesen.
