### ISSUE TITLE
Sonnenschutz oberhalb einer bestimmten Elevation nicht durchführen

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#423]
Hallo Simatic,

Danke für den Adapter, bei mir läuft er weitgehend störungsfrei und das Problem, welches Störungen verursacht, sitzt meist vor dem Bildschirm… :-)

Ich habe aber eine Idee, welche den Adapter möglicherweise noch leistungsfähiger machen könnte.

Oftmals sind Fenster von Vordächern oder Überdachungen verdeckt. Wenn die Sonne recht tief steht (Frühjahr oder Herbst), dann haben diese Verdeckungen keinen Einfluss auf eine Verschattung der Fenster, da die Sonne dann ungehindert einstrahlen kann. Steht die Sonne aber sehr hoch (Sommer), dann sind manche Fenster schon durch die Dachüberstände etc. verdeckt.
Daher wäre es möglicherweise sinnvoll, für jedes Fenster abhängig von der Sonnenelevation einstellbar zu machen, dass bei Überschreiten dieser jeweiligen Elevation die Jalousien im aktiven Sonnenschutz nicht herunter fahren.

Bei der Gelegenheit könnte man für jedes Fenster auch noch hinzufügen, dass der Sonnenschutz nicht aktiv sein soll, wenn beispielsweise das Fenster (Terrassentür) durch eine Markise verschattet ist (Link auf Objekt in ioBroker) - ist die Markise ausgefahren dann kein aktiver Sonnenschutz, ist sie eingefahren dann Sonnenschutz an (oder die ganz ausgefeilte Variante: ab x% Markise ausgefahren).

**Comment by simatec** [comment]
Wäre es nicht sinnvoller hier mit Lichtsensoren zu arbeiten?

**Comment by guitardoc** [comment]
Meistens hat man ja einen zentralen Lichtsensor “für alles”. Ich habe beispielsweise 21 Fenster (OK, nicht alle davon sind durch Dachüberstände verschattet), da wird es mit Lichtsensoren für jedes Fenster schnell teuer… :-)

Den zweiten Teil hab ich möglicherweise nicht richtig verstanden. Du meinst, dass man den zentralen Lichtsensor nimmt und dann für jedes Fenster ein kleines Skript schreibt, welches den Wert des Lichtsensors für jedes Fenster so anpasst, dass ab einer bestimmten Elevation der Sonnenschutz nicht mehr ausgeführt wird? Das würde natürlich gehen. 

Aber wesentlich eleganter wäre es doch, wenn man das gleich in diesem deinem (hervorragenden!!!) Adapter einstellen könnte, oder? :-) Muss ja nicht gleich morgen möglich sein… :-D

**Comment by simatec** [comment]
Wie oben geschrieben, würdest du für den Anfang mit dem Wert der Elevation arbeiten können. 
Den State trägst du je Rollladen bei dem Lichtsensor ein und wählst den für dich passenden Wert.

**Comment by jpawlowski** [comment]
Kannst du nicht einfach mit einem Blockly Script auf `info.Elevation` triggern und entsprechend dann unter `shutters.autoSun` das entsprechende Rollo auf `false` setzen, solange die Elevation für dich zu hoch ist?
Mein Verständnis wäre, dass dann keine Beschattung mehr aktiviert würde. Sofern jedoch bereits eine Beschattung liefe (was ja in deinem Fall wahrscheinlich ist), würde diese momentan nicht abgebrochen bzw. beendet, da die Änderung der `autoSun` Werte momentan wohl noch nicht zu einer Neubewertung des Status nebst entsprechender Korrektur führt.
Siehe dazu auch #441

**Comment by Jack77777777** [comment]
> Wäre es nicht sinnvoller hier mit Lichtsensoren zu arbeiten? 
> 
> Hier könntest du jedes Fenster bedienen und individuell anpassen.
> 
> 
> 
> Du kannst aber auch beim den Optionen für den Lichtsensor den State der Elevation konfigurieren und hättest somit den Wert direkt für jeden Rollladen zum konfigurieren.
> 
> 
> 
> Also shuttercontrol bietet dies bereits jetzt mit ein wenig Kreativität an ;-)

Das verstehe ich nicht ganz. Ich habe den selben Fall und würde gerne die Beschattung bei Elevation größer 40 deaktivieren und den Rolle öffnen. Wenn ich für den Lichtsensor nun dwn State der Elevation nehme und dieser größer 40 wird, wird der Rollo doch geschlosseb und nicht geöffnet, oder ?
