### ISSUE TITLE
Markise falsche Richtung bei Alarm

### ISSUE THREAD

**Issue by LudwigErr** [simatec/ioBroker.shuttercontrol#426]
erstmal grosses Lob für den Adaper! Die Rolladensteuerung (mit Shelly 2.5'ern) funktioniert damit sehr gut! Bisher nutze ich nur einen einzigen Xiaomi Lichtsensor, allles Rolläden fahren damit einwandfrei.

Aber mit der Markise komme ich auf keinen grünen Zweig. Kippe ich Wasser auf den (HM-) Regensensor, reagiert sie sofort, aber sie fährt raus (=schliesst) anstatt rein (=sollte ja öffnen).

In #420 schreibt Loi83 ja auch: "bei mir schließen sich die Rollos bei Regen über die Alarmeinstellung." Aber genau das soll eine Markise ja nicht. Sondern sie soll öffnen (= einrollen bzw. auf 100%) fahren.

Gebraucht würde also bei den Alarmeinstellungen nicht nur "Regenalarm für Rollo aktivieren" sondern auch ein Schalter "im Alarmfall hoch oder runter fahren". Dasselbe gilt natürlcih auch für den Windalarm. 

Die Level bzw. Positionen der HM Markisensteuerung (HM-LC-Bl1-FM) sind wie bei den Rolläden (Shellys): 0% =geschlossen  (bzw. ausgefahren) 100%=geöffnet (bzw. eingefahren). 

So ist das auch in shuttercontrol in den Haupteinstellungen des Geräts eingestellt. Also Rolladenhöhe beim runterfahren 0% / beim hochfahren 100%

Mit einer Richtungsumkehr im Alarmfall wäre das für mich am logischten einzustellen.

Oder denke ich an irgend einer Stelle falsch? 
Viele Grüsse, Ludwig

**Comment by simatec** [comment]
Shuttercontrol bedient in erster Linie Rollläden.
Dein Workaround würde ich in Kombination mit Alias lösen.
Für Shuttercontrol besteht nur die Möglichkeit Rollläden bei Regen zu schließen
