### ISSUE TITLE
Steuerung nach Himmelsrichtungen

### ISSUE THREAD

**Issue by kaip2503** [simatec/ioBroker.shuttercontrol#429]
Moin, 

erstmal vielen Dank für den Adapter. 
Ich versuche derzeit meine Rollos nach Himmelsrichtung fahren zu lassen. Leider ohne Erfolg. 
Folgende Einstellungen habe ich: 
![Bildschirmfoto 2022-05-26 um 08 50 49](https://user-images.githubusercontent.com/73375585/170434100-9141b80d-e906-40c5-b8e6-f3adae121910.png)

Dazu ein Auszug aus dem Log:
![Bildschirmfoto 2022-05-26 um 08 56 07](https://user-images.githubusercontent.com/73375585/170434696-9857dd3a-8bbb-4e6d-be05-7029a9975d6e.png)

Das Rollo ist nicht gefahren, obwohl die Sonne bei 95.6 steht und laut Adapter bei 90 +/- 60 auf 50 % stehen sollen.

Habe ich etwas falsch eingestellt oder liegt hier ein Fehler vor? 

Besten Dank und beste Grüße 
Kai

**Comment by kaip2503** [comment]
So sieht übrigens der currentStates aus: 
  "BueroRollo:1_LEVEL": {
    "shutterName": "BueroRollo:1.LEVEL",
    "currentAction": "Manu_Mode",
    "currentHeight": 100,
    "triggerAction": "Manu_Mode",
    "triggerHeight": 100,
    "oldHeight": 50,
    "firstCompleteUp": false,
    "alarmTriggerLevel": 100,
    "alarmTriggerAction": "Manu_Mode",
    "lastAutoAction": "up_LivingTime"

**Comment by simatec** [comment]
Wenn dein Fenster auf manu_mode steht, wird tagsüber nicht mehr automatisch gefahren. 

Steht aber auch alles in der Doku

**Comment by kaip2503** [comment]
Habe mir jetzt die ganze Doku durchgelesen und an den Rollos jeweils Wohnzimmer (Automatik) eingestellt. Außerdem einen Trigger erstellt, der immer auf True steht.

**Comment by simatec** [comment]
Was hast du denn für einen Aktor. 
wie geschrieben, steht der State des Rollladens auf Manu_Mode, wird erst am Abend wieder geschlossen. 

Es gibt 2 Gründe für den Manu_Mode. 
1. Du fährst den Rollladen tagsüber manuell 
2. Dein Aktor sendet während der Fahrt verschiedene States

1. erklärt sich von alleine. Bei 2. solltest du in den Extra Einstellungen die Überprüfung des Rollladens aktivieren und die Zeit für die Überprüfung auf die maximale Fahrzeit anpassen

**Comment by kaip2503** [comment]
Das sind alles die Homematic Jalousieaktoren. 

Er wechselt irgendwie nicht vom Manu_Mode weg. Auch nicht, wenn ich über openAll alles einmal initialisiere. Ich werde mal explizit darauf achten, keine manuellen Fahrten zu machen. Aber bei zwei Rollos heute, die hätten beide fahren müssen, und die ich nie per Hand fahre, hat es bei einem geklappt, bei dem anderen nicht. Die Einstellungen sind aber bei beiden komplett gleich. 

Ich werde es aber beobachten und aktiviere mal die Extra Einstellung. 

Besten Dank für deine schnelle Hilfe.
