### ISSUE TITLE
Lamellensteuerung (eventuell universelle Idee?)

### ISSUE THREAD

**Issue by rtwl21** [simatec/ioBroker.shuttercontrol#430]
Ich weiß, dass der Entwickler keine individuelle Lamellensteuerung implementieren will, damit der Adapter universell bleibt.
Dennoch hab ich eine Idee, welche ich hier kurz anführen möchte.

Wäre eine zusätzliche Option möglich, so dass man einstellen kann, dass nach jedem Schließen (beim Sonnenschutz) die Jalousien nach dem Schließvorgang wieder um X% geöffnet werden?
Mit Shellys und meinen Raffstores, wäre das auf jeden Fall die optimale Lösung. User mit kleinen Jalousielamellen bei denen 1% hoch schon wieder voll geschlossen bedeutet, werden diese Möglichkeit (vermutlich) sowieso nicht nutzen können.

Der Wunsch danach ist ja sehr groß, daher würden sich sicher einige darüber freuen.
Vielen Dank!

**Comment by simatec** [comment]
Kannst du nicht für den Sonnenschutz einfach den Rollladen auf 2% konfigurieren?
Damit wäre er doch auch nicht komplett geschlossen

**Comment by rtwl21** [comment]
Nein, da ich keine Rollläden habe, sondern Raffstores. Da würden die Lamellen dennoch komplett geschlossen sein und lediglich unten ein paar cm offen stehen.

bei Raffstores verhält es sich ja so, dass beim runterfahren die Lamellen geschlossen sind, beim hochfahren geöffnet.

will man also die Lamellen bei ca 50% mit 45° schräg haben, muss man nach dem hochfahren 2% runter. Allerdings beim runterfahren 2% hoch.

das beides nicht möglich bzw ein großer Aufwand wäre ist mir klar. Daher auch die oben genannte Idee als "Zwischenlösung"

**Comment by simatec** [comment]
Ist so leider nicht umsetzbar, da der Adapter die Stellung prüft und danach den Modus setzt.
Fährst du wieder um 2 % aus den Sonnenschutz hoch bedeutet dies Manu_mode und hält dein Raffstore in der Position.

Löse es über ein Alias bzw. einen Extra States.
Fahre den state mit shuttercontrol in die gewünschte Position.

Dann baue einen Script oder Blockly, der die Raffstores über diesen Wert steuert.
Am Ende des Scripts, kannst du dann nach der Fahrzeit wieder um 2% anheben.

Eigentlich schnell in einem Blockly gebastelt
