### ISSUE TITLE
Initialisierungsfahrt automatisch?

### ISSUE THREAD

**Issue by Jassco** [simatec/ioBroker.shuttercontrol#441]
Hallo Simatic,

in der Hilfe ist beschrieben, das bei einem Adapterneustart eine Initialisierungsfahrt per "obenAll" durchgeführt werden muss. Wäre es denkbar, dass der Adapter künftig nach einem Neustart eine Initialisierungfahrt selbstständig vornimmt?

Wenn ja, wäre es denkbar dies über eine Checkbox unter EXTRA-Einstellungen zu parametrieren?

Auszug aus der Hilfe:
_"Achtung: Wenn der Shuttercontrol Adapter neu gestartet wird (Auch nach Konfigurationsänderungen) müssen die Rollläden mittels des Button "obenAll" (shuttercontrol.0.control.openAll) hochgefahren werden. Auch wenn diese schon offen sind! (Initialisierungsfahrt) Dies initialisiert alle Adapter internen Werte."_

**Comment by jpawlowski** [comment]
Nach meinem Gefühl scheint das gar nicht (mehr) notwendig zu sein, habe daher davon abgesehen das bisher irgendwie zu berücksichtigen. Denke auch es sollte überflüssig sein, solange man sich auf die Werte der Rollos verlassen kann.

**Comment by simatec** [comment]
Ist mit aktuellen Version nicht mehr nötig.
Der Adapter speichert die letzten Settings des Rollladens.
D.h. ein Neustart ist kein Thema ... Den Adapter über mehrere Stunden oder tage ausschalten geht natürlich nicht, da sich in der zeit Werte ändern, die der Adapter nicht erfasst.

**Comment by jpawlowski** [comment]
Das ist super! 👍 Dann vielleicht nur noch gelegentlich die Doku aktualisieren 😉
