### ISSUE TITLE
Andere Beschattung bei Abwesenheit

### ISSUE THREAD

**Issue by jpawlowski** [simatec/ioBroker.shuttercontrol#442]
Ich nutze normalerweise die Markise für die Beschattung, wenn ich zuhause bin (das Rollo würde mir den Weg auf den Balkon versperren ;-)).

Bei Abwesenheit jedoch macht es natürlich Sinn, dass die Beschattung stattdessen vom Rollo übernommen wird (keine Abhängigkeit zu plötzlichem Regen oder Windböhen, macht es einfacher).

Nun setze ich die `autoSun` Werte für die Markise und das entsprechende Rollo in Abhängigkeit der Anwesenheit entsprechend.

Ich konnte das ganze noch nicht lange genug beobachten, ob bei Abwesenheit auch tatsächlich das Rollo statt der Markise gefahren wird. Was mir jedoch sofort aufgefallen ist, dass bei bereits aktiver Beschattung ein Wechsel der `autoSun` Einstellungen offenbar nicht zu einer Neubewertung der Status beider Geräte führt. Sprich, wenn ich die Wohnung verlassen habe, fährt die Markise nicht ein und das Rollo runter. Wenn ich beim Wechsel der An-/Abwesenheit manuell den Kontrollpunkt `control.sunProtect` trigger, findet scheinbar auch keine Neubewertung statt wie ich sie hier erwartet hätte. Leider fahren dann einfach sämtliche Rollos stur ihre Beschattungsposition an und die Rahmenparameter werden komplett ignoriert. Während das bei `openAll` und `closeAll` noch Sinn ergibt, erschließt es sich mir nicht ganz, warum ich bei der Beschattung nicht zumindest einige Parameter weiterhin berücksichtigen würde.

Letztlich würde es mir für meinen Fall jedoch genügen, wenn die Veränderung von `autoSun` auch entsprechend zur Folge hätte, dass das entsprechende Gerät aus der Beschattung genommen wird bzw. beim aktivieren die Bedingungen entsprechend geprüft würden und die Beschattung ganz normal davon abhängig aktiviert wird oder nicht. Wäre es möglich den Trigger mit einzubauen?

**Comment by simatec** [comment]
Für die Anwesenheitssteuerung und den unterschiedlichen Einstellungen rate ich zu folgenden Beispiel.
Installiert eine zweite Instanz, importiert die Einstellungen aus der Shuttercontrol Konfiguration in die zweite Instanz.

Ändert die Einstellungen, die ihr bei Abwesenheit anpassen wollt in der neuen Instanz.

Dann könnt Ihr über einen Script je nach An- oder Abwesenheit die jeweiligen Instanzen aktivieren oder deaktivieren

Somit habt ihr hier Möglichkeiten für unterschiedlich Konfigurationen.

Mehr RAM oder der gleichen habt ihr somit auch nicht, da immer nur eine Instanz läuft.
