### ISSUE TITLE
Sonnenschutz fährt nicht automatisch auf

### ISSUE THREAD

**Issue by Jassco** [simatec/ioBroker.shuttercontrol#443]
Hallo Simatec,

ich habe mir wirklich gründlich das Wiki durchgelesen, finde aber keine Lösung zu meinerm Problem bzw, vielleicht ist es ja nur ein Verständnissproblem meinerseits.

Ich versuche meine Jalousien nur mittels der Sonnenschutzeinstellung per Azimutparameter +/- (keine Sensoren, keine Zeiteinstellungen, keine Bereiche) zu steuern. Ich habe verstanden, dass die Angabe +/- sich auf die Himmelsrichtung des Fensters bezieht. Beispiel: 130° Fensterposition mit +/-50 ergibt einen aktiven Sonnenschutz von 80° bis 180°.

Bei erreichen des Sonnenstands 80° (ich bleiben am besten beim Beispiel mit der Annahme, dass das Fenster in nicht geöffnet wird) fährt die Jalousie runter. Nun habe ich gedacht (gehofft), dass die Jalousie bei erreichen der 180° Azimut hochfährt? Bei mir tut sie es nicht. Anmerkung: Der Button control.openAll lässt alle Jalousien ordnungsgemäß nach oben fahren.

Unter Objects sind die Variablen shutters.autoUp, autoDown, autoSun auf "true", autoLevel entspricht der aktuellen Position.

Habe ich ein Verständnisproblem der Funktion oder gar falsch paremetriert?

**Vielen Dank im Voraus für deine Hilfe :-)**

**Versions:**  
 - Adapter version: 1.4.12
 - JS-Controller version: 4.0.23
 - Node version: 14.19.3
 - Operating system: Linux raspberrypi 5.15.32-v8+
 
![Objects](https://user-images.githubusercontent.com/106919985/172700248-1644d019-1e6e-4e11-a7c8-1a44adc9a29b.JPG)
![Rolladenparameter_Haupt](https://user-images.githubusercontent.com/106919985/172700742-e6bcd8ad-0ec0-4fc0-8967-c5eac02b7f70.JPG)
![Rolladenparameter_Sonnen](https://user-images.githubusercontent.com/106919985/172700780-40285816-d7a9-4bd3-bee7-69ed0461e972.JPG)

Parameterdatei im json-Format: 
[system.adapter.shuttercontrol.0.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/8864521/system.adapter.shuttercontrol.0.txt)

**Comment by simatec** [comment]
Du hast bei dem Rollladen in den Extra Einstellungen des gezeigten Gerätes die Option „Rollladen im Sonnenschutz halten“ aktiv

` "KeepSunProtect": true `
