### ISSUE TITLE
closeAll not opened Button - Rollos nur bei geschlossenem Fenster schließen

### ISSUE THREAD

**Issue by firebowl** [simatec/ioBroker.shuttercontrol#444]
Wenn wir nicht zu Hause sind, lassen wir die Rollos nach Zeitplan schließen und öffnen, alles funktioniert super.
Wenn wir anwesend sind, möchten wir nicht das die Rollos automatisch fahren sondern dann wenn wir unsere zu Bett gehen Routine ausführen. Dies tun wir aktuell über eine Automation in Siri bzw. über zwei Verschiedene. Eine "normale", die alle Rollos auf die definierte Position fährt und eine "Sommer" bei der wir bestimmte Rollos nicht fahren, bei denen wir im Sommer Fenster zum lüften geöffnet lassen. Leider ist dies sehr umständlich und nicht sehr smart.

Ich würde das ganze gerne komplett über ShutterControl laufen lassen.
Am liebsten wäre mir, wenn ein Druck auch closeAll oder closeLiving das gleiche tut wie jetzt, mit der Ausnahme, dass offene Fenster berücksichtigt werden.
Also ein Druck auf closeAll soll alle Rollos schließen, bei denen das Fenster geschlossen ist. Wenn man nachträglich eines der offenen  Fenster schließt, fährt auch der Rollo in die definierte Position.

**Comment by simatec** [comment]
Naja ich hatte es im Forum schon geschrieben. 
Shuttercontrol soll deine Rollläden ja automatisieren. 
Grundsätzlich braucht man da nicht eingreifen. 
Bei mir fahren zu 99% die Rollläden nur in Automatikbetrieb. 

Mit Siri oder anderen Skripten etc. einzugreifen ist keine gute Idee, da es am Ende immer die Logik hinter Shuttercontrol aus dem Gleichgewicht bringt. 

Was die Button angeht, bin ich eher skeptisch. 

CloseAll und OpenAll machen ja am Ende genau dass, was sie sollen und wie auch der Name sagt. 

Wenn ich den Code nun so anpasse, dass geöffnete Fenster nicht berücksichtigt werden, würde der Name nicht mehr passen und die Logik auch nicht dahinter. 

Ich hätte dann sofort eine Vielzahl an Usern, die hier schreiben werden, dass die Funktion nicht alle Rollläden schließt 

Ich schaue mal, wie ich deinen Wunsch umsetzen kann, aber grundsätzlich wird hier nicht mit openAll und closeAll gearbeitet werden können.

**Comment by firebowl** [comment]
Danke für die schnelle Antwort. 
Ich möchte ja auch eigentlich überhaupt nicht mit Siri oder co reinpfuschen, deshalb die Anfrage. ;)
Im Forum wurde ja schon eine Idee genannt, die ich auch hier im Topic geschrieben habe. Vielleicht wär ja ein Button wie closeAllWithoutBlocked oder sowas möglich. Dann könnte man genau den Button im ioBroker triggern wenn man nur Rollos ohne offene Fenster schließen möchte. 
Mal unabhängig davon, sehr cooler Adapter. Regelt bei mir sehr zuverlässig die Beschattung meiner Räume. :)
