### ISSUE TITLE
Manu_Mode

### ISSUE THREAD

**Issue by animatorecmd** [simatec/ioBroker.shuttercontrol#445]
Hallo zusammen,

nach Ansteuerung der Sonnensteuerung wechseln meine Motoren in den Status Manu_Mode. Daher erfolgt keine Rücknahme der Sonnensteuerung wenn die Parameter nicht mehr erfült sind.

Ich habe den Button überprüfung der Motoren nach 60 Sekunden aktiviert, keine Verbesserung.

Mit ansteuerung AutoAll fahren die Motoren dann wieder aus der Sonnenstellung heraus.

Versin 1.4.14 von Shuttercontroll, im LOG Errorlevel sind jedoch keinerlei Hinweise warum die Motoren die durch Shuttercontroll in den Sonnenmodus gefahren worden sind dann in den Manu_Mode wechseln.

Die Motoren sind von Rademacher und über Homepilot20 in den IOBroker eingebunden, Homepilot20 Version 0.0.40.

Im letzen Jahr hat die Sonnensteuerung 1A funktioniert, diesen Frühsommer habe ich jedoch einige herausforderungen. 

Hat jemand einen Tipp für mich?

Vielen Dank für die Hilfe.

**Comment by dustnppunkt** [comment]
Moin, bei mir das gleiche Phänomen. 
Ich habe Rolladen Aktoren von Homematic IP sowie Velux Rolläden über KIX 300 im Einsatz und bei "allen" taucht dieses Phänomen auf wobei vielleicht einmal häufiger bei den HmIP-BROLL. 
Wenn jemand Tipps hat wäre ich auch dankbar.
BG, Dustin

**Comment by simatec** [comment]
Bitte aktiviert die Überprüfung der Rollläden nach x Sekunden.
Der Wert sollte über der maximalen Fahrtzeit eurer Rollläden liegen

![image](https://user-images.githubusercontent.com/39792461/177167989-264b5740-b5d8-460d-8b00-0a3cf3f4d632.png)
