### ISSUE TITLE
Manu_Mode im DP ohne manuelle Fahrt

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#450]
Hallo @simatec,

im "auto_state DP" steht manu_mode obwohl die Rollläden nicht manuell verfahren wurden. Ich habe mal ein paar Screenshots und Debug Logs angehängt mit der Bitte wenn du etwas Zeit dir das mal anzuschauen und mir mitzuteilen ob das Problem bei mir zu suchen ist.

Wenn zusätzlich noch Infos benötigt werden einfach Bescheid geben.

Ich danke dir vielmals und wünsche nen schönen Sonntag!

Gruß Michael

[Debug_Log_24062022.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/8986164/Debug_Log_24062022.txt)
[Debug_Log_25062022.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/8986165/Debug_Log_25062022.txt)
[system.adapter.shuttercontrol.0.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/8986168/system.adapter.shuttercontrol.0.txt)

![IMG_0082](https://user-images.githubusercontent.com/56205459/175804602-39907092-c686-4adc-9cae-ca89c35e26f8.PNG)
![IMG_0083](https://user-images.githubusercontent.com/56205459/175804604-8028e589-54d8-4429-9192-00d2c2743037.PNG)
![IMG_0084](https://user-images.githubusercontent.com/56205459/175804605-23d82342-53e6-493b-a9eb-c9784b51af2d.PNG)
![IMG_0085](https://user-images.githubusercontent.com/56205459/175804608-34d7f253-7a19-4ecd-8f73-d83d5ba15f49.PNG)
![IMG_0086](https://user-images.githubusercontent.com/56205459/175804609-e346f144-f947-4350-a8a6-ca0665a731a5.PNG)
![IMG_0087](https://user-images.githubusercontent.com/56205459/175804610-c0cedcd7-8ffc-4ed3-b30b-f87997dc41c3.PNG)
![IMG_2127](https://user-images.githubusercontent.com/56205459/175804611-35240266-7935-461a-b152-b9b3ccf15351.PNG)
![IMG_2129](https://user-images.githubusercontent.com/56205459/175804612-45f45fd1-32d2-4c46-ad71-3b78ba24d7f1.PNG)
![IMG_2130](https://user-images.githubusercontent.com/56205459/175804614-86b9c609-1bb3-4955-b82c-9e669e756671.PNG)

**Comment by MMeinhardt1** [comment]
Das werde ich mal testen. 

Danke

**Comment by Eistee82** [comment]
Habe das selbe Problem. Ich hab die Zeit zum überprüfen auf 60sec gestellt. Fahrzeit im Zigbee Aktor ist 36sec. Der Positionswert wird bei einer Fahrt in 2% Schritten aktualisiert. Kann es sein das das Aktualisieren des Positionswertes als Manuelle Fahrt erkannt wird auch wenn sich der Wert dabei nicht ändert? Der Aktor sendet zyklisch seine aktuelle Position was als Aktualisierung in iobroker auch sichtbar ist. Der Zeitstempel letzte Änderung bleibt aber unverändert.

**Comment by simatec** [comment]
Bitte die neuste Version nutzen. Da sollte dies gefixt sein.

**Comment by MMeinhardt1** [comment]
Hi @simatec,
welche neueste Version soll denn installiert werden? Ich habe die 1.4.14 installiert und diese gibt es schon seit 3 Monaten.
Wo ist eine neuere Version zu finden?

Danke und ein schönes Wochenende

**Comment by simatec** [comment]
1.4.14 ist die Neuste

**Comment by MMeinhardt1** [comment]
Dann muss ich nach dem Sinn des vorherigen Beitrag fragen in dem es heißt dass die 1.4.14 benutzt werden soll obwohl sie zu dem Zeitpunkt der Fehler schon installiert war?

**Comment by simatec** [comment]
Das sehe ich in deinem Issue leider nicht, da es keine Angaben zur Version gibt

**Comment by MMeinhardt1** [comment]
Wenn du dir, entschuldige bitte wenn ich das so äußere, meine angehängten Dateien angeschaut hättest dann wüsstest du es. Ich habe mir schließlich alle Mühe gegeben so viel wie möglich an relevanten Infos mitzugeben. Hast du dir das gar nicht angeschaut?

**Comment by simatec** [comment]
> Wenn du dir, entschuldige bitte wenn ich das so äußere, meine angehängten Dateien angeschaut hättest dann wüsstest du es. Ich habe mir schließlich alle Mühe gegeben so viel wie möglich an relevanten Infos mitzugeben. Hast du dir das gar nicht angeschaut?

Doch hab ich, aber meine Vorschläge wurden nicht beantwortet. Und bitte vergiss nicht, dass wir alle Adapter in unserer Freizeit entwickeln und den Usern zur Verfügung stellen.

> Das werde ich mal testen.

Hier kam nach meine Empfehlung keine Feedback mehr seit über einem Monat.
