### ISSUE TITLE
Thermoschutz im Winter für Indoor Rollos

### ISSUE THREAD

**Issue by Lieggie** [simatec/ioBroker.shuttercontrol#451]
Hallo Zusammen,
Erstmal vielen dank für den Adapter und eure Arbeit. 
ich habe ihn seit 2 Monaten mit den IKEA Akkurollos fast fehlerfrei am laufen und er macht was er soll.

Da Ich User von Indoor Rollos bin habe ich eine Idee zur Erweiterung des Adapters. Der Frostalarm ist ja für Outdoor Rollos geschrieben und fährt die Rollos ein Stück nach oben um ein festfrieren zu verhindern.

Ist es Möglich in abhängikeit Uhrzeit und Aussentemperatur die Rollos als Termoschutz runter zu fahren.
Z.B. Ausserhalb der Sommermonate es ist später als 17 Uhr und kälter als -5°C fahre Rollos auf eingestellen wert zu, zum Termoschutz?   
 
Gruß Thomas

**Comment by simatec** [comment]
Du kannst in den Einstellung die Höhe definieren.
![image](https://user-images.githubusercontent.com/39792461/177167125-0a0f3911-e683-4fa6-9b1b-00f2a861c0e0.png)
