### ISSUE TITLE
Sonnenschutz Funktioniert nicht

### ISSUE THREAD

**Issue by 4358haltern** [simatec/ioBroker.shuttercontrol#452]
Hallo
Ich habe die Version 1.4.12 auf dem IoBroker installiert.

Ein Update war leider nicht möglich.
Installation habe ich nach ca 20 min Abgebrochen...

Folgende Situation.

Ich habe eine test Jalousie in dem Adapter.
Lediglich mit der Hauptfunktion // Sonnenaufgang -> Hoch / Sonnenuntergang ->Runter beides ohne Probleme..

aber

die Sonnenschutz Funktion.
Sonnenpostion-funktion funktioniert.
doch wenn der lux wert unter x ist bleibt die Jalousie oben...
keine Regung..

in der doku steht das es wenn z.b. 10000 eingestellt ist und ein eine Hysterese von 2% ist diese dann öffnet.
die Jalousie ist leider immer unten...

kann mir da wer den Fehler finden helfen...

<img width="851" alt="Bildschirmfoto 2022-06-30 um 19 54 24" src="https://user-images.githubusercontent.com/84634956/176745033-b5a90e24-45e3-44b8-b4c0-5024df583f99.png">

**Comment by ZeroQool007** [comment]
Hast du das Problem beheben können?
