### ISSUE TITLE
Sonnenschutz mehrerer Rollos trotz identischer Einstellungen nicht gleich

### ISSUE THREAD

**Issue by MojitoJoe1813** [simatec/ioBroker.shuttercontrol#461]
Nutze aktuell shuttercontrol v1.4.14.
Habe für die verschiedenen Rollos jeweils an jeder Himmelsrichtung einen HUE-Outdoorsensor mit Lux- und Temperatursensor.
Trotz identischer "Sun Protection Settings" (gleicher Sensor, Temperatur, Lux etc.) verschiedener Rollos der gleichen Himmelsrichtung werden nicht alle geschlossen?! Von vier Rollos Richtung Süden sind aktuell zwei (aufgrund von Sun-Protection) geschlossen, die anderen beiden nicht ?!

Ich habe keine Ahnung, wo ich da nach einem Fehler suchen soll? - In den Settings kann ich den jedenfalls nicht finden.
Siehe Screenshot: Dies sind die Einstellungen eines offenen Rollos, während das Rollo daneben (bis auf den Namen oben links) die identischen Einstellungen hat und geschlossen ist.

Wo liegt das Problem?

![image](https://user-images.githubusercontent.com/71935206/178955238-483869cc-c9e4-4a6e-8d12-b06ece1e46d4.png)

**Comment by MojitoJoe1813** [comment]
Was ich noch ergänzen kann: Es scheint so, als ob die Zeit-Einstellungen den Sonnenschutz "überschreiben"/vernichten. An dem sehr sonnigen, warmen Tag heute (Wochenende) waren wir bereits zwischen 09:00 und 10:00 Uhr wach und das Schlafzimmerfenster (Südseite) wurde kurz nach dem Öffnen durch uns auch ordnungsgemäß in den Sonnenschutzmodus gefahren. Genau um 11:00 war es damit aber vorbei und der Rollo hat sich komplett geöffnet, so dass die Sonne nun reinknallt.

![image](https://user-images.githubusercontent.com/71935206/179392323-cfde70fb-fe76-45f3-8498-be0fddf0a8a3.png)

Wie ich dann in den Zeiteinstellungen sehen konnte, ist für die sleeping area 11:00 Uhr genau die "earliest..." sowie "latest time to boot up on weekends" eingestellt. Das ist für mich natürlich weiterhin richtig und sinnvoll für Fälle, an denen ich wirklich so/zu lange schlafe bzw. im Urlaub bin etc.. Es soll aber natürlich nicht die Sonnenschutzeinstellung vernichten?!

Verstehe/Bediene ich da etwas falsch?

**Comment by MojitoJoe1813** [comment]
Ich habe nun schon einige Einstellungen versucht, um das inkonsistente Sonnenschutz-Verhalten mehrerer Aktionen (Schließen, Öffnen) an verschiedenen Fenstern zu verstehen und zu beheben.  Ich habe versucht, die Konfigurationsunterschiede auf das absolute Minimum zu reduzieren, nur um zu sehen, ob dann wenigstens Konsistenz im Verhalten zu erkennen ist. Auch die Dokumentation lese ich inzwischen regelmäßig, um vielleicht doch noch das letzte Detail zu entdecken, das dieses Verhalten erklärt...

Suspekt bzw. unbekannt sind mir die Rolladen-Objekte im Objektbaum von shuttercontrol. Haben diese evtl. etwas mit dem Verhalten zu tun? Was bedeutet 'autoState' und warum sind die Werte hier völlig unterschiedlich, obwohl ich nach meinem Gefühl kaum Unterschiede konfiguriert habe.

![image](https://user-images.githubusercontent.com/71935206/179702878-3b9e445a-5498-4b49-88bf-9cb63353dc9f.png)

**Comment by simatec** [comment]
So wie ich das sehe, solltest du die Überprüfung der Rollläden nach x Sekunden aktivieren. Deine Aktoren senden wahrscheinlich während der Fahrt immer wieder einen Status

**Comment by MojitoJoe1813** [comment]
Die Überprüfung habe ich nun in den allgemeinen "Extra-Settings" aktiviert - mal sehen ob dies etwas verändert. Mir ist unklar, was dies bewirkt. Zumindest kann ich sagen, dass meine Shelly2.5 während der Fahrt die Position nicht senden - und auf diesen state zielen die in shuttercontrol jeweils definierten Rollos ab:

Zustand: Offen, Keine Bewegung
![image](https://user-images.githubusercontent.com/71935206/179711657-0aec48c4-117b-4c3c-a72d-3a4fad13b69f.png)

Zustand : In Bewegung, bei etwa <50% und weiter schließend 
![image](https://user-images.githubusercontent.com/71935206/179711790-278a1e04-72e7-44c5-92ab-166608233468.png)

Zustand: Geschlossen, Keine Bewegung
![image](https://user-images.githubusercontent.com/71935206/179711866-be8a3b75-fe0a-4884-9f2f-4f131f3e8bf0.png)

**Comment by simatec** [comment]
Gerade für die Shellys gibt es diese Funktion mit der Überprüfung nach X Sekunden
