### ISSUE TITLE
Offene Fenster beim schließen berücksichtigen und nur auf zwischenposition fahren

### ISSUE THREAD

**Issue by softwarecrash** [simatec/ioBroker.shuttercontrol#462]
**Is your feature request related to a problem? Please describe.**
Fenster mit Oberlicht, innenliegende Rollos, nur ein Sensor an dem Fenster der offen/gekippt true meldet.
egal ob Zeit Automatik oder Sonnenschutz, wenn ein Fenster offen oder gekippt ist soll das entsprechende Rollo nur zb auf 70 fahren um das Oberlicht abzudecken.

**Describe the solution you'd like**
wäre schön wenn es eine Funktion gibt die es ermöglicht das rolle bei offenem Fenster trotzdem zu fahren bis zu dem punkt wo das offene Fenster ist, und wenn es geschlossen wird in die Position wie die anderen sprich ganz zu o.ä.

**Additional context**
ich hab glaube alle Einstellungen durchprobiert, konnte aber eine Funktion wie diese nicht finden, oder habe ich eine Einstellung / Kombination übersehen?

shuttercontrol V 1.4.12

**Comment by OliWit82** [comment]
Häng mich da mal,
habe leider auch noch keine Brauchbarelösung  gefunden. 
hätte auch gerne das man einstellen kann das die Rollos im Sommer nicht ganz runter fahren.

**Comment by simatec** [comment]
@softwarecrash Das sind schon sehr spezielle Fälle, die man so sicher nicht abgedeckt bekommt.

**Comment by simatec** [comment]
@OliWit82 Für diese Art der Steuerung und den unterschiedlichen Einstellungen rate ich zu folgenden Beispiel.
Installiert eine zweite Instanz, importiert die Einstellungen aus der Shuttercontrol Konfiguration in die zweite Instanz.

Ändert die Einstellungen, die ihr im Sommer anpassen wollt in der neuen Instanz.

Dann könnt Ihr über einen Script je nach Sommer oder Winter die jeweiligen Instanzen aktivieren oder deaktivieren

Somit habt ihr hier Möglichkeiten für unterschiedlich Konfigurationen.

Mehr RAM oder der gleichen habt ihr somit auch nicht, da immer nur eine Instanz läuft.

**Comment by ltigges** [comment]
Ich verstehe es so, dass beim automatischen Schließen und gekiptten Fenster die Rollos nur so weit runter fahren, wie bei "Rollladenhöhe bei öffnen des Fensters oder Tür" eingetragen ist.

**Comment by softwarecrash** [comment]
> Ich verstehe es so, dass beim automatischen Schließen und gekiptten Fenster die Rollos nur so weit runter fahren, wie bei "Rollladenhöhe bei öffnen des Fensters oder Tür" eingetragen ist.

genau.
