### ISSUE TITLE
Sonnenschutz wird nicht beendet

### ISSUE THREAD

**Issue by Eistee82** [simatec/ioBroker.shuttercontrol#463]
**Describe the bug**  
Der Sonnenschutz wird nicht beendet obwohl die Sonne unterhalb der eingestellten 4,1° sinkt. Es wird weiterhin sunprotect angezeigt.

**To Reproduce**  
Rollo mit Sonnenhöhe (Elevation) 4,1 eingestellt.
Sonnenschutz:
- Himmelsrichtung 280
- +/- Bereich 100 (etwas geneigtes Dachfenster)
- Einstellung Außentemperatur/Lichtsensor & Himmelsrichtung
- Sollwert Lichtsensor 25000, Hysterese 90
- Außentemperatur und Innentemperaturfelder sind leer

**Expected behavior**  
Wenn die Sonne unter 4,1° sinkt wird der Sonnenschutz beendet und das Rollo fährt hoch.

**Screenshots & Logfiles**  
Nichts im Log zu erkennen.

**Versions:**  
 - Adapter version: v1.4.14
 - JS-Controller version: 4.0.23
 - Node version: v16.16.0
 - Operating system: debian

**Comment by simatec** [comment]
Bitte poste deine Config als json

**Comment by Eistee82** [comment]
[system.adapter.shuttercontrol.0.json.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/9144183/system.adapter.shuttercontrol.0.json.txt)

**Comment by simatec** [comment]
Was sagt denn dein autoLevel? Steht das auf sunprotect oder manu_mode?

**Comment by Eistee82** [comment]
Das stand auf sunprotect und hat sich auch nicht verändert

**Comment by simatec** [comment]
Dann bitte den Adapter bitte mal auf Debuglog stellen und den Log posten, wenn die 4,1 unterschritten sind

**Comment by Eistee82** [comment]
Jetzt fährt es auch nicht herunter. Hier das Log:

shuttercontrol.0 | 2022-07-20 13:31:12.150 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:31:02.149 | debug | Brightness sensor value: 95573
shuttercontrol.0 | 2022-07-20 13:30:56.143 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:30:46.142 | debug | Brightness sensor value: 95573
shuttercontrol.0 | 2022-07-20 13:30:40.145 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:30:30.145 | debug | Brightness sensor value: 92271
shuttercontrol.0 | 2022-07-20 13:30:24.143 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:30:14.142 | debug | Brightness sensor value: 93046
shuttercontrol.0 | 2022-07-20 13:30:08.147 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:30:02.030 | debug | status alarm pending for alias.0.Büro.Beschattung.Rollo.position: false
shuttercontrol.0 | 2022-07-20 13:30:02.029 | debug | start pendingAlarm to check if an alarm is currently pending (exept frost)
shuttercontrol.0 | 2022-07-20 13:30:00.002 | debug | Sun Elevation: 59.4°
shuttercontrol.0 | 2022-07-20 13:30:00.002 | debug | Sun Azimut: 180.5°
shuttercontrol.0 | 2022-07-20 13:30:00.002 | debug | calculate astrodata ...
shuttercontrol.0 | 2022-07-20 13:29:58.147 | debug | Brightness sensor value: 94426
shuttercontrol.0 | 2022-07-20 13:29:54.141 | debug | status alarm pending for alias.0.Büro.Beschattung.Rollo.position: false
shuttercontrol.0 | 2022-07-20 13:29:54.140 | debug | start pendingAlarm to check if an alarm is currently pending (exept frost)
shuttercontrol.0 | 2022-07-20 13:29:52.140 | debug | Lightsensor changed: sainlogic.0.weather.current.solarradiation Value: 97231
shuttercontrol.0 | 2022-07-20 13:29:52.140 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:29:42.140 | debug | Brightness sensor value: 97231
shuttercontrol.0 | 2022-07-20 13:29:36.138 | debug | Brightness State Down is: false
shuttercontrol.0 | 2022-07-20 13:29:26.138 | debug | Brightness sensor value: 98053

**Comment by Eistee82** [comment]
OK das Problem scheint zu sein das es nicht funktioniert solang keine Temperaturasensoren für den Sonnenschutz eingetragen sind. Ich habe heute die Temperatursensoren mit eingetragen dann ging er auch in den Sonnenschutz. Das beenden des Sonnenschutz klappte ebenfalls sowohl mit Helligkeitssensor als auch anschließend nur auf Himmelsrichtung eingestellt mit den 4,1° Sonnenhöhe unterschritten. Ich möchte nicht temperaturabhängig beschatten sondern benötige einen Blendschutz der temperaturunabhängig ist. Daher die Frage ob man auch eine Auswahl schaffen kann die nur mit Helligkeitssensor und Himmelsrichtung die Beschattung steuert.

**Comment by simatec** [comment]
Trage mal deinen Helligkeitssensor bei der Außentemperatur ein. 
Wenn du nur damit arbeitest, ist dies der beste Weg
