### ISSUE TITLE
Nachtruhe wird nicht beendet

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#464]
Ich habe nachts das Schlafzimmerfenster auf - die Jalousien sind oben. Ende der Nachtruhe ist z.B. 06:00 Uhr. Wenn ich danach, z.B. 07:00 Uhr, das Fenster schließe, dann wird auch die Jalousie vollständig geschlossen - so als wenn noch Nacht wäre?

**Comment by simatec** [comment]
Denke da blockiert eine Einstellung für das automische Fahren bei geöffneten Fenster

**Comment by guitardoc** [comment]
Welche Einstellung könnte das sein?

Rollladen fahren bei Änderung des Fenster/Tür Zustandes steht auf Öffnen und Schließen 

Rollladenautomatik auch bei geöffnetem Fenster/Tür benutzen (Aussperrschutz) steht auf Aus 

Fahren, nachdem Fenster geschlossen wurde hat ein Häkchen

**Comment by simatec** [comment]
Zeige mal die Einstellung des betroffenen Rollladens

**Comment by guitardoc** [comment]
Wie mache ich das am besten?

**Comment by simatec** [comment]
![image](https://user-images.githubusercontent.com/39792461/184634877-eabdec86-cf0a-4ba0-b325-3a825495d303.png)

**Comment by guitardoc** [comment]
![6ABE9D04-2F43-425A-9E48-57059B8BE108](https://user-images.githubusercontent.com/77169595/184690003-4f94a26a-5f9e-4398-8f6d-766b299774b5.jpeg)
![950B3C37-4CD4-4220-915F-F6DBFB589889](https://user-images.githubusercontent.com/77169595/184690015-1547b1b3-f532-4311-9bdf-4e0e36f46fee.jpeg)
![163F51B9-D2B3-47DA-80E5-564CA4D550FE](https://user-images.githubusercontent.com/77169595/184690022-b0d1854b-1b1b-4b47-a026-68fcb3a90d94.jpeg)
![C4D9F98D-AE99-4C42-ADAD-E0945F093D60](https://user-images.githubusercontent.com/77169595/184690028-ef524c35-cf74-4579-bce6-f19de92491b4.jpeg)
![C1D0574B-85BE-4E04-AF6E-EBC76D41107D](https://user-images.githubusercontent.com/77169595/184690030-82bfefae-7353-47c8-89bb-24c580e0c5ee.jpeg)

**Comment by guitardoc** [comment]
Konntest du an den Einstellungen was finden woran das liegt?

**Comment by simatec** [comment]
Stelle es mal wie folgt ein:
![image](https://user-images.githubusercontent.com/39792461/190988883-766613cf-766d-45f5-8fe5-96ca21235868.png)
