### ISSUE TITLE
Zweiflügelige Fenster unterstützen

### ISSUE THREAD

**Issue by BlueBook4** [simatec/ioBroker.shuttercontrol#468]
Z.Z. kann man nur einen Öffnungssensor hinterlegen.

Bei  Fenster mit einem Rollo, aber mehreren Flügeln (z.B. Zweiflügeliges Fenster):
https://www.fensterversand.com/pla/fenstertypen/zweifluegelige-fenster.php?pla=fenster-2fluegelig-pvc-120x90cm-dreh-kipp-links-rechts-spannrahmen

wäre es schön beide Öffnungssensoren hinterlegen zu können.
(zumindest für das Lüftungsszenario, dass die Rollos auf Spaltfahren, wäre eine OderVerknüpfung toll :))

Oder geht das schon irgendwo und ich hab es übersehen?

**Comment by simatec** [comment]
Kannst du im iob zu einem state über alias zusammenlegen

**Comment by BlueBook4** [comment]
Ja, hatte auch schon an den Szenenadapter gedacht.
Okay, aber über die Aliasstates (hab ich noch nicht benutzt) geht es wohl noch besser.
Schau ich mir mal an.

Wäre für mich eher ein Workaround, aber einer - mit dem ich leben könnte.
Irgendwie wahrscheinlich eh sinnvoll Alias zu benutzen.
