### ISSUE TITLE
Manuelle Laufzeiten - Shelly keine Leistungsmessung

### ISSUE THREAD

**Issue by SoerenKaiser99** [simatec/ioBroker.shuttercontrol#470]
Shelly 2.5 liefern im manchen Fällen (z.B.hinter einem Relais) keine Leistungsdaten, somit ist auch keine Kalibrierung möglich. Dies bedeutet leider auch keine Möglichkeit der Prozentualen Steuerung.

Siehst du eine Möglichkeit auf manuelle Laufzeit mit den DP Close & Open umstellen zu können? 
Statt Level also manuell und dann die beiden DP nach Zeit zu verwenden?

Zur Info zum Problem:
Ich verwende 6 Shelly bei denen 5 problemlos laufen, einer ist in Reihe geschaltet. Hier geht es nicht. Der Shelly wurde bereits 2 mal getauscht. Es liegt also an dem Rolladen-Relais das den Blindstrom reduzieren muss. 

Gruß 
Sören

**Comment by simatec** [comment]
Das sollte über einen Script und/oder Alias möglich sein.
Shuttercontrol arbeitet nach den iobroker Standards und die beinhalten für Rollläden und Jalousien ein level.
