### ISSUE TITLE
Fahrt trotz Wind Alarm

### ISSUE THREAD

**Issue by Eistee82** [simatec/ioBroker.shuttercontrol#472]
**Describe the bug**  
Der Wind 2 Alarm ist auf true gesetzt. Sollposition offen (100). Das Rollo ist komplett geöffnet (Istposition 100). Es wird der Datenpunkt "shuttercontrol.0.control.closeAll" angesteuert (Script welches beim schlafen gehen alle Rollladen schließen soll). Das Rollo schließt trotz aktivem Alarm.

**Expected behavior**  
Wenn ein Alarm aktiv ist dann sollte das Rollo in der entsprechenden Position bleiben und nicht wo anders hin fahren.

**Versions:**  
 - Adapter version: 1.4.14

**Comment by simatec** [comment]
Das manuelle bedienen mit dem Button setzt alle vorherigen automatischen Funktionen außer Kraft

**Comment by Eistee82** [comment]
Naja das ist ja richtig. Aber ein Alarm sollte doch trotzdem eine höhere Priorität haben. Wenn das Rollo trotz Windalarm dann in Fetzen an der Wand hängt ist es halt nicht so toll. Und wenn ich trotz der Alarmfunktionen nun doch alles extern noch abfragen muss dann frage ich mich welchen Zweck das Modul dann noch erfüllt.

Ich steuere ja das Rollo nicht extern an was ja natürlich immer gehen sollte sondern über das Modul welches eine gewisse Intelligenz bringen soll.

**Comment by simatec** [comment]
Die Automatik greift dann auch beim nächsten Abfragen wieder … closeAll sagt ja aber auch der Name. Alles schließen…
