### ISSUE TITLE
Sonnenschutz und Bewölkung

### ISSUE THREAD

**Issue by Eistee82** [simatec/ioBroker.shuttercontrol#473]
**Is your feature request related to a problem? Please describe.**
Ich habe einen Datenpunkt Bewölkung der von 0% bis 100% die aktuelle Bewölkung des Himmels enthält (0% = keine Wolken / 100% = dichte Wolkendecke). Im Sommer kommt es öfter vor das es zwar sehr hell ist aber der Himmel zu 90% bewölkt und daher kein Sonnenschutz gewollt ist. Mit den Einstellungen im Sonnenschutz kann ich diesen Datenpunkt nicht verwenden da ja hier beim einer kleinen Zahl der Sonnenschutz aktiv werden soll und nicht bei einer großen Zahl. Mit der Hysterese lässt es sich nicht einstellen da diese ja prozentual auf den Sollwert gerechnet wird.

**Describe the solution you'd like**
In der Industrie hat es sich bewährt Analoge Sensoren über zwei Parameter SP (Schaltpunkt) und RP (Rückschaltpunkt) zu parametrieren. Dies ermöglicht es genau fest zu legen bei welchem Wert ein Sensor schalten soll. Dieses System würde es ermöglichen sowohl kleine als auch große Werte als Bedingung einzusetzen. Dazu muss dann nur geschaut werden welcher der zwei Parameter der größere ist um zu bestimmen ob beim überschreiten oder unterschreiten des Parameters der Zustand verändert werden muss.

**Describe alternatives you've considered**
Alternativ fände ich es gut wenn ich für die Sonnenschutzfunktion statt einem Sensor einfach einen Datenpunkt mit true/false verwenden könnte und ich damit dann extern meine Bedingungen zum Beschatten z.B. mit Blockly programmieren kann. Aktuell müsse ich mir einen fake Sensor mit einem Zahlenwert erstellen was unschön ist.

**Comment by simatec** [comment]
Kannst du über Alias lösen … dort kannst du den State für Shuttercontrol negieren
