### ISSUE TITLE
Manu_Mode ohne erkennbaren Grund

### ISSUE THREAD

**Issue by Eistee82** [simatec/ioBroker.shuttercontrol#474]
Ich fahre mein Rollo mit "shuttercontrol.0.control.openAll" in die obere Endlage. Dann steuere ich den Datenpunkt "shuttercontrol.0.control.autoAll". Nach ca. 1 min fährt das Rollo herunter und "shuttercontrol.0.shutters.autoState.Rollo" springt sofort beim Fahrtbeginn auf Manu_Mode. Eigentlich hätte ich erwartet das er in die Beschattung geht. Die Frage ist jetzt warum springt er auf Manu_Mode? Es wird definitiv nichts manuell gesteuert. Die Fahrt dauert ~40sec und ich habe schon "Wartezeit für die Überprüfung des Rollladenstatus (Sekunden)" auf 70 Sekunden eingestellt weil es mit 60sekunden auch passierte. Es hat allerdings nichts daran geändert.

Evtl. funktioniert mein Positionsdatenpunkt nicht korrekt. Aktuell kann ich diesen beschreiben was das Fahrkommando an die Jalousie sendet. Während diese dann fährt aktualisiert sich im Sekundentakt die Position im Datenpunkt bis dann irgendwann die vorher gesetzte Position angefahren wurde. Ich weiss leider nicht ob das so korrekt ist für den Adapter.

**Versions:**  
 - Adapter version: v1.4.1
[system.adapter.shuttercontrol.0 (1).json.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/9417345/system.adapter.shuttercontrol.0.1.json.txt)
4

**Comment by simatec** [comment]
Versuche mal bitte die States in Aliase zu packen und binde dann diese in Shuttercontrol ein.

**Comment by Eistee82** [comment]
Die Position ist ein Alias. Da mein Aktor über zigbee2mqtt läuft.
[alias.0.Büro.Beschattung.Rollo.position.json.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/9417663/alias.0.Buro.Beschattung.Rollo.position.json.txt)

Oder welche "States" meinst du?

**Comment by simatec** [comment]
Kannst du den Wert mal in einer Datenbank bei der Fahrt loggen?
Möchte gerne mal sehen, wie der State sich verhält

**Comment by Eistee82** [comment]
[Rollo Position.csv](https://github.com/simatec/ioBroker.shuttercontrol/files/9417882/Rollo.Position.csv)
Das mit dem SQL Adapter geloggt von heute

**Comment by simatec** [comment]
Senden die wirklich so oft? Da kommt ja alle 5 Minuten was über mqtt

**Comment by simatec** [comment]
Hmm eigentlich nicht so gut. Da sollte sich nur bei Änderungen etwas tun

**Comment by Eistee82** [comment]
Datum und Uhrzeit von geändert bleibt aber stehen. Und wenn ich die main.js richtig verstehe dann fragst du das ja ab und schaltest nur bei einer Änderung auf z.B. Manu_Mode
`if (id === resShutterID && state.ts === state.lc) {`

**Comment by simatec** [comment]
Kannst du bitte mal den Debuglog von einer Fahrt bis zum Wechsel in den Manu_Mode posten

**Comment by Eistee82** [comment]
Hab glaube ich die Ursache allen übels gefunden. Meine Wetterstation schreibt in ihre Datenpunkte ab und an null statt eine Zahl. Das sorgte dafür das ganz kurz immer z.B. der Frostalarm kam und ging. Das brachte dann vermutlich den shuttercontrol so durcheinander das er auf Manu_Mode schaltete.

**Comment by simatec** [comment]
Das ist durchaus möglich ... Das sollte aber auch aus dem Debuglog zu sehen sein.

**Comment by chrimmel81** [comment]
Hallo, ich habe das gleiche Problem. Nach dem Fahren in den Sonnenschutz wird ohne Grund der manu_mode aktiviert, ohne das eine manuelle Änderung erfolgt. Ich habe aktuell den Sonnenschutz nur nach Position der Sonne aktiviert.
Der Log sieht so aus:


29.8.2022 17:05:37.979 | Manu_Mode | true | shuttercontrol.0
-- | -- | -- | --
29.8.2022 17:05:20.091 | sunProtect | true | shuttercontrol.0

Der Rolladenaktor hat um 17:05:37.865 den Level gemeldet der durch den Sonnenschutz angefahren wurde.
D.h. Shuttercontrol hat wohl um 17:05:20 wahrscheinlich den Befehl gegeben und nach 17 Sekunden war der Rolladen in Position und dann wurde diese gemeldet.

Viele Grüße
Christian

**Comment by simatec** [comment]
Bitte die Überprüfung der Rollläden nach x Sekunden aktivieren. 
das sind leider eure Rollladen Aktoren, die da bei den States funken. Shuttercontrol verarbeitet diese nur

**Comment by chrimmel81** [comment]
> Bitte die Überprüfung der Rollläden nach x Sekunden aktivieren. das sind leider eure Rollladen Aktoren, die da bei den States funken. Shuttercontrol verarbeitet diese nur

Ich teste es, danke!
