### ISSUE TITLE
State wird nicht aktualisiert, wenn Türsensor geöffnet ist

### ISSUE THREAD

**Issue by Henni111** [simatec/ioBroker.shuttercontrol#475]
**Describe the bug**  
Wenn ein Türsensor geöffnet ist, und sich währenddessen der Status des Fensters wechselt, wird dieses Update nicht übernommen. Nach dem Schließen des Türkontaktschalters fährt der Rolladen dann also wieder auf die Position, die er zum Zeitpunkt des Öffnens des Türkontakts hatte. Danach wird auch kein Update hiervon mehr gemacht, sondern der Rolladen schaltet in den Manu_Mode.
Beispiel:

**To Reproduce**  
Beispiel:
1. Der Rolladen schaltet in den Beschattungsmodus bei geschlossenem Türkontakt. 
2. Der Türkontakt wird geöffnet, der Rolladen fährt hoch.
3. Die Beschattung wird bei geöffnetem Türkontakt beendet. Der Rolladen bleibt oben.
4. Der Türkontakt wird geschlossen, der Rolladen fährt wieder auf die Sun_protect Position.
5. Die aktuelle Position entspricht nicht der, der sie nach Automatik sein sollte, daher schaltet der Rolladen in Manu_Mode und macht auch keine weiteren Updates mit.

**Expected behavior**  
In Schritt 4 sollte der Rolladen auf die neue Automatik-Position fahren. Es muss also beim öffnen des Türkontaktschalters nicht die Position des Rollladen gespeichert werden, sondern der Betriebsmodus (Automatik). Dann muss beim Schließen des Türkontakts der aktuelle Automatikstatus gesetzt werden und nicht der Status zum Zeitpunkt des Öffnens des Türkontakts. Wenn der Status zum Zeitpunkt des Öffnens Manu_mode war, sollte er aber in diesen zurückkehren und den Rollladen auf die gleiche Position fahren (sich also so verhalten, wie es jetzt ist)

**Comment by simatec** [comment]
Fix in v1.4.18
