### ISSUE TITLE
Temperatur beendet Beschattung aber Jalousien noch unten

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#480]
Ich denke, dass ich einen möglichen Fehler gefunden habe. 

Heute wurde es draußen eher kalt als es dunkel wurde. Mit anderen Worten, die Außentemperatur unterschritt den minimalen Wert schon obwohl die Jalousien noch im Sonnenschutzmodus (und heruntergefahren) waren. Als es dann dunkler wurde wurden die Jalousien nicht wieder geöffnet, da vermutlich der Sonnenschutzmodus aufgehoben wurde.

**Comment by simatec** [comment]
Wenn die Außentemperatur unterschritten wird, fahren die Rollläden aus dem Sonnenschutz. Es sein denn, du hast diese Funktion deaktiviert
