### ISSUE TITLE
Tür auf, Verschattung beendet, Tür zu, Jalousie fährt in Verschattung

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#481]
Die Verschattung ist an, Jalousien sind unten. Dann mache ich die Tür auf, Jalousie fährt hoch. Die Tür bleibt offen und die Verschattung wird zwischenzeitlich beendet. Wenn ich jetzt die Tür schließe, dann fährt die Jalousie wieder in die Verschattung, obwohl diese schon beendet ist. Ist das ein Fehler oder muss etwas anders eingestellt werden?

**Comment by simatec** [comment]
> Bitte fixen....

Du bist gerne eingeladen das zu fixen... Wie soll man mit solch Aussagen was machen... Keine Config, kein Debuglog...

**Comment by mango1402** [comment]
coding ist etwas umfangreich und undurchsichtig......
Irgendwie kommt er mit geöffneter Tür beim beenden vom Sonnenschutz nicht zum 'Started sunprotect end delay for...'
Deshalb wird dann auch nicht das Flag 'sunProtectEndtimerid' auf '0' gesetzt um danach den Trigger zu löschen.

btw, der end-delay-timer funktioniert sowieso nicht wirklich. Wird generell erst beim nächsten erreichen vom 5Min-Trigger 'weitergearbeitet'.
Und was noch aufgefallen ist: es ist für mich nicht nachvollziehbar, wann Aktionen bei Werteänderungen der Sonnenschutzbedingungen sofort, und wann erst beim nächsten 5Min-Trigger ausgeführt werden. Einmal ist's so, dann wieder so....

**Comment by simatec** [comment]
@mango1402 verstehe deinen Post nicht so recht

**Comment by mango1402** [comment]
@simatec: was denn nicht?

**Comment by mango1402** [comment]
Langsam beginnt wieder die Saison mit der automatischen Rollosteuerung. Und was soll ich sagen? Dein Einbau funktioniert noch immer nicht. Irgendwie passt die UND-Verknüpfung von currentAction = 'triggerd' und lastAutoAction = "down_Sunprotect" nicht....

Egal, ich bau mir wieder lokal meine Änderung von damals ein und dann funktionierts. Auf weitere Updates des Adapters wer'd ich dann pfeifen.....
