### ISSUE TITLE
Besucher-Funktion (Zuhause, Auswärts)

### ISSUE THREAD

**Issue by schuno85** [simatec/ioBroker.shuttercontrol#482]
Hallo.

Gäbe es die Möglichkeit / wäre es aus eurer Sicht sinnvoll, die beiden folgenden zusätzlichen Funktionen einzupflegen?

1) Besuch Zuhause
-> Steht der entsprechende Datenpunkt auf "true", werden die Jalousien erst zu einer definierten Zeit oder garnicht heruntergefahren.

2) Zu Besuch Auswärts
-> Steht der entsprechende Datenpunkt auf "true", werden die Jalousien entsprechend früher (inbsesondere im Winter) zu einer definierten Zeit heruntergefahren (Einbruchschutz).

Vielleicht gab es die Themen schon, ich konnte hierzu aber nichts finden.

**Comment by simatec** [comment]
Das könnte jeder für dich individuell über Skripte lösen
