### ISSUE TITLE
Fehlende Beschreibung Helligkeitssensor

### ISSUE THREAD

**Issue by schuno85** [simatec/ioBroker.shuttercontrol#483]
Hallo.

Unter den Extra-Einstellungen gibt es den Punkt "Einstellungen Helligkeitssensor".

Hierzu steht nichts in der deutschen Anleitung.

Wird das noch ergänzt?

![Helligkeit](https://user-images.githubusercontent.com/113306676/189542703-6e622533-8a53-4af9-b58f-15252855ab36.png)

**Comment by simatec** [comment]
Fix in V1.4.15
