### ISSUE TITLE
[Frage] lassen sich die einzelnen Konfigurationspunkte extern ändern (z.B. durch Blockly)

### ISSUE THREAD

**Issue by Dino0811** [simatec/ioBroker.shuttercontrol#484]
**Is your feature request related to a problem? Please describe.**
eher eine allgemeine Frage...

**Describe the solution you'd like**
Kann man Konfigurationspunkte extern durch Skripte verändern?
z.B. um das _automatische Hochfahren_ der Rollläden zur vorbestimmten Zeit auszusetzen? (z.B. bei Besuch oder Krankheit --> Unregelmäßigige Vorkommnisse) - oder im Sommer bestimmte _Rollläden vom runterfahren auszuschließen_ ohne jedes halbe Jahr "spät schließen" bei diversen Rollläden zwecks Lüftung manuell zu deaktivieren.
Ich weiß dass es möglichst automatisiert sein soll ohne manuell dazwischenzufunken (ist ja der Sinn an shuttercontrol). - Indem Fall geht es um die schöne Automatisierung mittels shuttercontrol und Akzeptanz im Haus (WAF)

**Describe alternatives you've considered**
z.B. hätte ich mir vorgestellt über Triggerdatenpunkte per Blockly die entsprechenden Einträge dann zu ändern - die Frage ist wo diese Einträge stehen, in den Objekten finde ich die Konfigurationsdetails leider nicht.

beste Grüße und danke für dieses mächtige Steuerungstool!

**Comment by simatec** [comment]
Folgende Objekte sind bedienbar und können auch über Scripte gesteuert werden.

`
shuttercontrol.X.shutters.autoSun
shuttercontrol.X.shutters.autoUp
shuttercontrol.X.shutters.autoDown
shuttercontrol.X.control
`
