### ISSUE TITLE
close and open a little

### ISSUE THREAD

**Issue by cainam1** [simatec/ioBroker.shuttercontrol#490]
If it closing because of the sun, it should be possible to open again like 1% to change the status of the slats so it is not complet dark

Nach dem Schliessen wegen Sonne, sollte es möglich sein, dass die Lamellen wieder leicht öffnen, resp. wieder um 1% rauf gehen so dass diese nicht total geschlossen sind und licht eintreten kann...

**Comment by simatec** [comment]
You can specify a height for the sun protection and don't have to close it completely

**Comment by cainam1** [comment]
this doesnt help... then the slats are closed on 50%. it should go to 50% and then open 1% so the slats are little open
