### ISSUE TITLE
Split switches autoChildren, autoLiving and autoSleep for up and down

### ISSUE THREAD

**Issue by wendy2702** [simatec/ioBroker.shuttercontrol#496]
Would it be possible to split the switches for autoChildren, autoLiving and autoSleep to be able to activate/deactivate the automatic for up and down separately.

i.e.:
autoChildren up
autoChildren down
autoLiving up
autoLiving down
autoSleep up
autoSleep down

**Comment by simatec** [comment]
You can control the automatic up and down for each roller shutter individually.

Each roller shutter has a state for autoUp, autoDown and autoSun

**Comment by simatec** [comment]
But it also has the advantage of being able to control all the roller shutters individually.
Has everything be for and again

**Comment by wendy2702** [comment]
Yes you are right but my idea was adding some additional switches and not to remove the switches for the single shutters. 

The idea came up because i was using centralized switches to enable auto for up/down as long as CCU controlled my shutters.

Maybe you like to think about.

If you don't like to implement you can close the issue and i will use some simple scripts.

Regards
