### ISSUE TITLE
Datenpunkt Rolladen Homematic IP Accespoint

### ISSUE THREAD

**Issue by Jeba0815** [simatec/ioBroker.shuttercontrol#498]
Hallo
I
Ich wollte meine Rolläden mit dem Adapter steuern. In der Anleitung steht dass der . level Wert von 0-255 sein kann.
Bei HMiP- AP wird der Wert in den Objekten aber mit 0.xx bis 1.xx gesteuert. 

Zum Beispiel
0 = offen
0.50= 50%
1 = Zu
Was gebe ich im Adapter ein Rolladen zu 0 und Rolladen auf 1 ??
Irgend wie klappt es nicht.

Nächster Punkt Aussperrschutz: Terassentür
Angeben kann mann true,false 0,1,2
Der Fenstergriffsensor liefert nur tiled, open , closed
Muss man das zwingend mit einem blockly Konvertieren?

**Comment by simatec** [comment]
Kannst du alles mit Alias umsetzen und in den Alias dann die Werte konvertieren. 

Level = 0-100%
Fenster = 0/1/2

**Comment by Jeba0815** [comment]
Leider hab ich mit der Alias Funktion noch nie was gemacht. 
Ich hab mir das angeschaut, aber nicht ganz verstanden wie ich Werte konvertieren kann. Alias anlegen und schalten ist klar. Gibts irgendwo ein Link wie man das einstellt

**Comment by simatec** [comment]
Forum and Adapter Readme
