### ISSUE TITLE
Feature Request and some remarks.

### ISSUE THREAD

**Issue by kugelkopf123** [simatec/ioBroker.shuttercontrol#50]
Maybe it would be a great idea, instead to select in the sunshadesettings a drop down menu to select which sensors/directions to combine. To make a drop down menu behind each sensor with the logic values to select: AND/OR/"AND NOT" "OR NOT", "Deactivated" Possibly add something like this to the trigger values as well. "Greater than", "less than", "less than or equal to", etc.

So it would be possible to combine different conditions. -->
_Move the shutter when the sun direction is correct or the UV sensor is activated but not when the outside temperature is below X°C._ 
Or to select the control by one sensor only. 

Something like this.

Just a suggestion to extend the range of functions. 

Furthermore, it might help a lot if the description would contain more details or concrete examples. 
For example, I am not quite clear why I have to set the sun elevation on the device settings page / main settings. But the sunshade settings have their own tab in the same menu. 
Just for the sake of clarity, it would be smart to have all things related to sun protection in this sunhadesettings tab. Accordingly, the shutter height should be found in the sun protection menu when the shutter is raised or lowered with reference to the sun height. 

Also the translation of some settings is a bit difficult to understand:
"Sollwert des Auslösers." What does this mean? Is this the value the trigger must have to trigger the action or is this the value the trigger normally has and if it deviates from this value, the action will be triggered?

No question, these are some points of criticism, but only to make the adapter even better than it already is. 
Great work so far!

**Comment by simatec** [comment]
The translations for better understanding have been completely revised from version 0.7.0, which should now explain some of them without documentation
