### ISSUE TITLE
Control Manual drive using shuttercontroll

### ISSUE THREAD

**Issue by bicmac** [simatec/ioBroker.shuttercontrol#503]
I would like to have possibility to control shutters manually using shuttercontroll. 
For example if I press a Enocean Button my IOBroker will right now closing the Shutter or opening the shutter or stop the drive but that will cancel automation. The idea is that IOBroker Action for that buttons not control the shutter directly, but tell the ASC to open or close the shutter (or drive to %) or stopp driving. 
Means with that I can have full control over shutters using shuttercontroll.
i undertstand that shuttercontroll should automate the shutter, but special in kids area or office area  sometimes kids or people want to adjust  the shutter manually and that without canceling automatic drives.
maybe its a good idea to say after manual drive automatic is stopped for some time (can setuped in config) as I know in FHEM the ASC module do that somehow. Means if I drive manually the automatic is stopped for example for the next 30min and after that the automation will start there work again for that shutter.

**Comment by simatec** [comment]
you can bring all roller shutters back into automatic mode in Shuttercontrol using the button.  If you want to automate this after 30 minutes, you can do it pretty easily with a script.
