### ISSUE TITLE
Window Open and Window Tile states

### ISSUE THREAD

**Issue by bicmac** [simatec/ioBroker.shuttercontrol#504]
shuttercontroll  have right now for window/door state only 0/1/2/true/false my sensors (enocean window handle) have open/closed/tilted as state. I would like to have a way to add state manually or at least I would like to ask to add that state as well to the selection.
in best case the check will also enhanced to check all with open* tilted* and closed* as some handles can have substate states like open_from_tilted.

**Comment by simatec** [comment]
you can easily solve this using aliases.  Shuttercontrol supports the standard values ​​and unfortunately cannot support every deviation due to different manufacturer standards.
