### ISSUE TITLE
Rollos fahren in Sonnenschutz obwohl kein Sommer mehr

### ISSUE THREAD

**Issue by SvenJ76** [simatec/ioBroker.shuttercontrol#505]
Hallo,
vielleicht hab ich es auch falsch verstanden, aber sollten die Rollos denn nicht mehr in den Sonnenschutzmodus fahren wenn die eingestellte Zeitspanne für den Sommer vorbei ist? Genau das machen sie nämlich noch aktuell bei mir.
Vielleicht kann das jemand erklären - Danke schön!

**Comment by poidi** [comment]
also ich habe nirgends gelesen, dass sie das nur im sommer tun sollen. außerdem finde ich es gut, weil es bei mir im homeoffice auch die blendung der sonne beinhaltet.
Denke du kannst es aber "einfach" mittels außentemperatur steuern, wenn du sie nur bei >25° fahren lassen willst, oder ähnlichem
