### ISSUE TITLE
Rollo fahren nicht zurück aus der Beschattung

### ISSUE THREAD

**Issue by hbayer-smarthome** [simatec/ioBroker.shuttercontrol#506]
Hallo
erstmal bin ich sehr begeistert von deinem Adapter. Ist wirklich sehr hilfreich!

Leider habe ich heute festgestellt, das vereinzelt Rollos nicht mehr aus der Beschattung zurück fahren.
Meine Untersuchung ergibt (ich hoffe, ich liege richtig!!!):

Wenn in die Beschattung mit Position 80 gefahren wird, melden vereinzelt Rollos die Position 81. Ich denke, shuttercontrol prüft auf Beschattungsposition=80 und wenn nicht, wird die Fahrt ignoriert. RICHTIG?!?

Könnte man hier evtl etwas wie eine deviation oder hysterese einbauen, etwa wie: Rollladenhöhe beim runterfahren=60 +-1???
![image](https://user-images.githubusercontent.com/66250470/195639719-a6bdc2f4-0bd6-4a3d-a519-a516738ef59b.png)

Für Hilfe wäre ich sehr dankbar!
hbayer

**Comment by hbayer-smarthome** [comment]
OK. Hat sich erledigt. Hab die Einstellung in Extra-Einstellung: "Überprüfen des aktuellen Rollladenstatus" gefunden.
An der Stelle nochmal vielen Dank für den Adapter! 👍

**Comment by simatec** [comment]
Done
