### ISSUE TITLE
Sunprotect wird als manuelle Fahrt identifiziert

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#512]
**Describe the bug**  
Hab einen Rolladen für Sunprotect eingestellt, weil im homeoffice das licht sonst blendet. Er fährt auch in den sunprotect, interpretiert dann aber das ganze als manuelle fahrt, und fährt nicht mehr hoch, wenn die kriterien nicht mehr erfüllt sind.

**To Reproduce**  
![2022-11-11_10h01_43](https://user-images.githubusercontent.com/7493037/201305065-2936347a-089c-4853-a257-993fed9690a2.png)

**Screenshots & Logfiles**  
`

shuttercontrol.0 | 2022-11-11 09:55:23.638 | debug | Shutter KZ-RL-Fenster:1.LEVEL was moved manually to: 40% - prevent trigger from driving back
-- | -- | -- | --
shuttercontrol.0 | 2022-11-11 09:55:23.638 | debug | save current height after State Check: 40% from KZ-RL-Fenster:1.LEVEL
shuttercontrol.0 | 2022-11-11 09:55:22.633 | debug | KZ-RL-Fenster:1.LEVEL drived manually to 40. Old value = 100. New value = 40
shuttercontrol.0 | 2022-11-11 09:55:22.632 | debug | KZ-RL-Fenster:1.LEVEL Updated trigger action to Manu_Mode to prevent moving after window close
shuttercontrol.0 | 2022-11-11 09:55:22.584 | debug | #2 shutterName: KZ-RL-Fenster:1.LEVEL
shuttercontrol.0 | 2022-11-11 09:55:22.583 | debug | Shutter state changed: KZ-RL-Fenster:1.LEVEL old value = 100 new value = 40
shuttercontrol.0 | 2022-11-11 09:55:08.115 | debug | save current height after State Check: 100% from KZ-RL-Fenster:1.LEVEL
shuttercontrol.0 | 2022-11-11 09:55:07.112 | debug | KZ-RL-Fenster:1.LEVEL Old value = 100. New value = 40. automatic is active
shuttercontrol.0 | 2022-11-11 09:55:07.111 | debug | Shutter state changed: KZ-RL-Fenster:1.LEVEL old value = 100 new value = 40
shuttercontrol.0 | 2022-11-11 09:55:07.109 | debug | Sunprotect KZ-RL-Fenster:1.LEVEL old height: 100% new height: 40%
shuttercontrol.0 | 2022-11-11 09:55:07.109 | debug | last automatic Action for KZ-RL-Fenster:1.LEVEL: down_Sunprotect
shuttercontrol.0 | 2022-11-11 09:55:07.108 | debug | Sunprotect KZ-RL-Fenster:1.LEVEL old height: 100% new height: 40%
shuttercontrol.0 | 2022-11-11 09:55:07.108 | debug | Sunprotect for KZ-RL-Fenster:1.LEVEL is active
shuttercontrol.0 | 2022-11-11 09:55:07.051 | info | Sunprotect #412 Set ID: KZ-RL-Fenster:1.LEVEL value: 40%
shuttercontrol.0 | 2022-11-11 09:55:07.050 | debug | KZ-RL-Fenster:1.LEVEL:  Check basis for sunprotect. Height:100 > HeightDownSun: 40 AND  Height:100 == currentHeight:100 AND currentHeight:100 == heightUp:100
shuttercontrol.0 | 2022-11-11 09:52:08.239 | debug | shutterUpButton KZ-RL-Fenster:1.LEVEL old height: 100% new height: 100%
shuttercontrol.0 | 2022-11-11 09:52:07.223 | info | Set ID: KZ-RL-Fenster:1.LEVEL to Auto-Mode
shuttercontrol.0 | 2022-11-11 09:50:29.376 | debug | KZ-RL-Fenster:1_LEVEL: save settings

`
**Versions:**  
 - Adapter version: 1.4.18
 - JS-Controller version: 4.0.23
 - Node version: v16.18.0 
 - Operating system: debian

**Additional context**

**Comment by poidi** [comment]
Man sieht bei timestamp: 2022-11-11 09:55:08.115  dass er offensichtlich nicht lange genug wartet, um den "neuen" Status des Rolladen abzufragen. Offenbar erwartet der Code, dass 1s nachdem er den Befehl zum runterfahren gegeben hat der Rolladen:
1. bereits im neuen Zustand angekommen ist
2. Der Zustand bereits rückgemeldet wurde
Dem ist aber nciht so, da alleine das runterfahren ca 20s dauert

**Comment by simatec** [comment]
There is a setting for the delayed check of the roller shutter status in Shutter Control under Extras.  Here you can freely configure the time in seconds.
