### ISSUE TITLE
Opening and closing of the roller shutters: Sunrise or sunset with individual offset

### ISSUE THREAD

**Issue by Christopher87R** [simatec/ioBroker.shuttercontrol#514]
Currently, the shutters are always opened and closed exactly at the time of sunrise or sunset. Most of the time, however, it is not yet really dark at this time. It would be nice if you could specify an individual offset.

It would be nice to be able to specify a separate offset for opening and closing for each shutter.

**Comment by djalexchrist** [comment]
![image](https://user-images.githubusercontent.com/71606842/204852988-4c5eaf99-687e-4053-a7a3-4eff0a5a9401.png)

**Comment by Christopher87R** [comment]
Thank you very much, that definitely helps. Unfortunately, the setting then applies globally and not individually for each shutter.
