### ISSUE TITLE
Weihnachtszeit

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#525]
Passend aktuell zur Jahreszeit: ist es möglich, den Zeitraum Weihnachtszeit als schreibbaren Datenpunkt in den Objekten zu veröffentlichen? Bisher kann man diesen nur direkt im Adapter als festen Bereich einstellen. Blöderweise ändert sich der Zeitraum aber jährlich - bei uns startet die Weihnachtszeit immer erst nach dem Totensonntag und da dieser Sonntags ist hat der kein festes Datum... So könnte man mit einem kleinen Script die Weihnachtszeit selbst setzen. Oder ich hab es nicht gefunden falls das schon irgendwie gehen sollte?

**Comment by simatec** [comment]
Ist nicht geplant… die Weihnachtszeit ändert sich ja nicht wirklich.
