### ISSUE TITLE
.... has to be type "boolean" but received type "number"

### ISSUE THREAD

**Issue by flickerfrei** [simatec/ioBroker.shuttercontrol#528]
Hi Simatec,
ich bekomme im Log alle 12 - 15 sek. den Eintrag
State value to set for "shuttercontrol.0.control.autoSleep" has to be type "boolean" but received type "number"

Im Bereich "Sleep" sind mehrere Rolladenaktoren von Rademacher, die über den Adapter Homepilot20 eingebunden sind.
Exemplarisch die Objektdaten aus einem Aktor:
`{
  "type": "state",
  "common": {
    "name": "Position_inverted Schlafzimmer Fenster Rollade",
    "desc": "Position_inverted stored in homepilot for device 2",
    "type": "number",
    "role": "level.blind",
    "min": 0,
    "max": 100,
    "unit": "%",
    "read": true,
    "write": true,
    "smartName": {
      "de": "Schlafzimmer Fenster Rollade"
    }`

Gibt es da einen Workaround, damit der Type Number Wert von Shuttercontrol als Boolean interpretiert werden kann?
Gerne liefere ich mehr Informationen, falls nötig.

**Versions:**  
 - Adapter version: v1.4.18
 - JS-Controller version: 4.0.23node
 - Node version: 16.15.0.

**Comment by simatec** [comment]
Du kannst da keine Nummer setzen. 
Das muss ein true oder false sein
