### ISSUE TITLE
Prüfung auf manuellem Bewegen der Rollos abschalten

### ISSUE THREAD

**Issue by SpezialAgent** [simatec/ioBroker.shuttercontrol#529]
Bei meinen Rollos spring shuttercontrol immer wieder in dem Modus "manu". Dadurch werden die folgenden Befehler nicht mehr ausgelöst.
Die Einstellung der Prüfung nach X-Sekunden der Level bringt keinen Unterschied. Die Rollos springen weiterhin in den Modues manu.

Wäre es möglich einen DP einzubauen, "Manu-Modus == true or false"? Dann kann jeder selber entscheiden, ob er die Prüfung haben möchte.
Gruß
Martin

**Comment by simatec** [comment]
Du solltest hier schauen, warum das passiert. 
Die Aktoren sind hier meist das Problem. logge mal eine Aktor mit. Wenn hier der Status sich ändert, erkennt Shuttercontrol dies als Bewegung. 
Was hast du für Aktoren?

**Comment by SpezialAgent** [comment]
Ich habe Enocean Aktoren Eltako FSB61NP-230V Funkaktor.

Die sind via Homematic und CuXD angeschlossen.

Ich den ersten Versionen Hatt ich kein Problem mit dem Manu-Modus.

**Comment by simatec** [comment]
Bitte logge im iobroker richtig mit. 
ggfs. über Influxdb, mysql oder history

**Comment by SpezialAgent** [comment]
Okay, ich schalte dann das Logging in Influxdb an. Ich schicke dir dann morgen Abend das Ergebnis.
Gruß
Martin

**Comment by SpezialAgent** [comment]
So sehen die Datenpunkte aller Rollos aus:
<img width="1097" alt="Bildschirmfoto 2023-01-16 um 19 06 54" src="https://user-images.githubusercontent.com/45120419/212742439-3810fdcc-1412-45d9-88df-4b6780bc553a.png">

**Comment by simatec** [comment]
Wie du selber in deinem Logging siehst, läuft da parallel ein Script, der Shuttercontrol da reinfuscht. 
das solltest du ändern

**Comment by SpezialAgent** [comment]
Richtig, das Script schreibt bei Änderung den Level-Wert in einen separaten DP. Ich hatte auch einen alias benutzt, um das Verhalten des Rollos zu monitoren. Das Umschalten auf den alias DP hat eine große Besserung gebracht.
Ich habe nun für den Test ein Rollo auf den Homematic-DP (CuXD) gesetzt und das Script abgeschaltet.
Heute Abend oder besser morgen Abend schicke ich dir den History Log.

**Comment by SpezialAgent** [comment]
Hier die Verlaufsdaten von heute:
<img width="1114" alt="Bildschirmfoto 2023-01-17 um 18 33 08" src="https://user-images.githubusercontent.com/45120419/212970989-8a6d32bc-5a10-4b58-9758-e3da52d80b6b.png">

**Comment by simatec** [comment]
Und was geht jetzt genU nicht? Hast du die Verzögerung zur Überprüfung eingestellt? 
Hier sollten sicher 40 Sekunden ausreichen

**Comment by SpezialAgent** [comment]
Hallo simatec, hier meine Rückmeldung:
Ich hatte shuttercontrol auf die hm-rpc Datenpunkte (für die Enocean shutter) eingestellt. Zeitverzögerung pro Rollo 10 Sekunden. Alle Rollos sind beim ersten mal gelaufen. Bei den 3 großen Rollos im Wohnzimmer gab es danach wieder den Manu-Modus. Ich hatte das auch mit einer Zeitverzögerung von 40, 60 und auch bei 120 Sekunden. Das hat keinen Unterschied gemacht.
Danach hatte ich statt der hm-rpc Datenpunkte die alias Datenpunkte genommen. Aber auch hier sprang der Status bei drei Rollos wieder auf Manu.
Ich schicke dir am Wochenende mal die history-Daten. Da habe ich Zeit und meine Frau wird den Test dann wohlwollender mitmachen. Vielleicht schaffe ich es auch Morgen.

**Comment by simatec** [comment]
Ich glaube wir reden nicht vom gleichen. Zeige mal im Screenshot deine Einstellungen zur Verzögerung der Überprüfung der Rollläden

**Comment by SpezialAgent** [comment]
Ich kenne den Punkt. Die erwähnten 10 Sekunden bezogen sich auf ein versetztes Fahren der Rollos, so dass der Funk die Autoren nacheinander ansprechen kann.
Zu Issue:
Mein Vorschlag ist, dass mithilfe eines Flags "Manu Mode ein/aus" die Überprüfung komplett abgeschaltet werden kann. Bei mir kommt regelmäßig bei allen Einstellungen, mit und ohne Überprüfung der angefahrenen Levels eine Meldung im Status: Manu-Mode.

Hier der Screenshot:
<img width="1010" alt="Bildschirmfoto 2023-01-18 um 21 15 37" src="https://user-images.githubusercontent.com/45120419/213285671-1f3509b0-0e6b-4f7e-9fec-adf18971d216.png">

**Comment by simatec** [comment]
Wenn der Rollladen nicht von irgendwo Änderungen bekommen sollte, dann kann kein Manu Mode kommen. Prüfe das nochmal? Kommt da aus der CCU etwas? Bewegst du die Rollläden manuell?

**Comment by SpezialAgent** [comment]
Das habe ich mir auch gedacht. In der CCU laufen keine Scripte. Ich habe alle Scripte meiner Rollladensteuerung in der Homematic deaktiviert. Meine Vermutung ist, dass die Enocean Autoren irgendeine Änderung weitergeben. Definitiv wird kein Rollo manuell bewegt. 
Ich habe heute 4 Rollos auf Protokollierung geschaltet und schicke entweder heute Abend oder Morgen die Logs.
ich hänge mal die Einstellungen von ShutterControl an:

**Comment by SpezialAgent** [comment]
Hier das Json:
`{
  "_id": "system.adapter.shuttercontrol.0",
  "common": {
    "name": "shuttercontrol",
    "version": "1.4.18",
    "title": "shuttercontrol",
    "authors": [
      "simatec <nais@gmx.net>"
    ],
    "keywords": [
      "ioBroker",
      "Smart Home",
      "home automation",
      "Rollladen",
      "Jalousie",
      "Rollladensteuerung"
    ],
    "license": "MIT",
    "platform": "Javascript/Node.js",
    "main": "main.js",
    "icon": "shuttercontrol.png",
    "enabled": true,
    "extIcon": "https://raw.githubusercontent.com/simatec/ioBroker.shuttercontrol/master/admin/shuttercontrol.png",
    "readme": "https://github.com/simatec/ioBroker.shuttercontrol/blob/master/README.md",
    "loglevel": "info",
    "mode": "daemon",
    "type": "climate-control",
    "compact": true,
    "materialize": true,
    "stopBeforeUpdate": true,
    "dependencies": [
      {
        "admin": ">=3.0.0"
      }
    ],
    "installedFrom": "simatec/ioBroker.shuttercontrol",
    "installedVersion": "1.4.18",
    "host": "iobroker",
    "plugins": {
      "sentry": {
        "dsn": "https://5f58df7167d846e3a90bae5414d4fc09@sentry.iobroker.net/62"
      }
    },
    "contributors": [
      "Rene G. <info@rg-engineering.eu>"
    ],
    "connectionType": "local",
    "dataSource": "push",
    "adminUI": {
      "config": "materialize"
    }
  },
  "native": {
    "livingAutomatic": "livingSunriseSunset",
    "W_shutterDownLiving": "21:30",
    "W_shutterUpLivingMin": "06:30",
    "W_shutterUpLivingMax": "08:30",
    "driveDelayUpLiving": "10",
    "WE_shutterDownLiving": "22:00",
    "WE_shutterUpLivingMin": "07:30",
    "WE_shutterUpLivingMax": "08:30",
    "sleepAutomatic": "sleepSunriseSunset",
    "W_shutterDownSleep": "21:30",
    "W_shutterUpSleepMin": "06:30",
    "W_shutterUpSleepMax": "08:30",
    "driveDelayUpSleep": "10",
    "WE_shutterDownSleep": "21:30",
    "WE_shutterUpSleepMin": "08:00",
    "WE_shutterUpSleepMax": "08:30",
    "childrenAutomatic": "childrenSunriseSunset",
    "W_shutterDownChildren": "21:30",
    "W_shutterUpChildrenMin": "06:30",
    "W_shutterUpChildrenMax": "08:30",
    "driveDelayUpChildren": "10",
    "WE_shutterDownChildren": "22:00",
    "WE_shutterUpChildrenMin": "08:00",
    "WE_shutterUpChildrenMax": "08:30",
    "latitude": "52.67027760",
    "longitude": "13.31318640",
    "sunProtEndElevation": "2",
    "astroDelayUp": "15",
    "astroDelayDown": "10",
    "driveDelayUpAstro": "10",
    "SummerStart": "01.04.",
    "SummerEnd": "01.09.",
    "XMasStart": "26.11.",
    "XMasEnd": "07.01.",
    "publicHolidays": true,
    "publicHolInstance": "feiertage.0",
    "HolidayDP": "0_userdata.0.Status.Urlaub.Heute_Urlaub",
    "lightsensorDown": "",
    "lightsensorUp": "",
    "lightsensorUpDown": "",
    "schoolfree": false,
    "schoolfreeInstance": "",
    "schoolfreeDP": "",
    "schoolfreeChildrenArea": false,
    "schoolfreeSleepArea": false,
    "schoolfreeLivingArea": false,
    "LateAllDown": true,
    "LateAllDownTime": "23:00",
    "betweenPositionTime": "22:05",
    "noGoTime": "1",
    "currentShutterState": true,
    "currentShutterStateTime": "60",
    "triggerAutoSleep": "",
    "triggerAutoLiving": "",
    "triggerAutoChildren": "0_userdata.0.Anwesenheit.Anwesenheit-Gast-Rollo",
    "alarmWind1Level": "",
    "alarmWind1": "",
    "alarmWind2Level": "",
    "alarmWind2": "",
    "alarmRainLevel": "",
    "alarmRain": "",
    "alarmFrostLevel": "20",
    "alarmFrost": "0_userdata.0.Status.Heizung.Warnung_Frost",
    "alarmFireLevel": "",
    "alarmFire": "",
    "events": [
      {
        "enabled": true,
        "shutterName": "Rollos.Ankleidezimmer",
        "name": "0_userdata.0.Rollos.Ankleidezimmer",
        "triggerID": "hm-rpc.1.NEQ1652147.1.STATE",
        "typeUp": "sleep-auto",
        "typeDown": "sleep-auto",
        "type": "off",
        "heightDownSun": "30",
        "direction": "270",
        "directionRange": "40",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "",
        "tempOutside": "23",
        "lightSensor": "",
        "valueLight": "15",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "5",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": false,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Rollos.Schlafzimmer",
        "name": "0_userdata.0.Rollos.Schlafzimmer",
        "triggerID": "hm-rpc.1.NEQ1652110.1.STATE",
        "typeUp": "sleep-auto",
        "typeDown": "sleep-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "90",
        "directionRange": "30",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Schlafzimmer.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": true,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Ost1 Fenster Rollladen:1.LEVEL",
        "name": "hm-rpc.0.CUX3602004.1.LEVEL",
        "triggerID": "hm-rpc.1.NEQ1677948.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "90",
        "directionRange": "30",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Wohnzimmer.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": true,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Ost2 Fenster Rollladen:1.LEVEL",
        "name": "hm-rpc.0.CUX3602003.1.LEVEL",
        "triggerID": "hm-rpc.1.NEQ1677973.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "93",
        "directionRange": "33",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Wohnzimmer.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": true,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Wohnzimmer Sued Fenster Rollladen:1.LEVEL",
        "name": "hm-rpc.0.CUX3602002.1.LEVEL",
        "triggerID": "hm-rpc.1.NEQ1678056.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "167",
        "directionRange": "57",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Kueche.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": false,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": true,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Kueche Fenster Rollladen:1.LEVEL",
        "name": "hm-rpc.0.CUX3602001.1.LEVEL",
        "triggerID": "hm-rpc.1.NEQ1652360.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "165",
        "directionRange": "55",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Kueche.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "40",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": false,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Rollos.HWR",
        "name": "0_userdata.0.Rollos.HWR",
        "triggerID": "hm-rpc.1.NEQ1652509.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "25",
        "direction": "255",
        "directionRange": "50",
        "tempInside": "22",
        "tempSensor": "0_userdata.0.Mittelwert.Temp-HWR.Mean_15",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-HWR.Mean_15",
        "tempOutside": "22",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "",
        "betweenPosition": false,
        "betweenPositionLevel": "",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": true,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Rollos.Gaestebad",
        "name": "0_userdata.0.Rollos.Gaestebad",
        "triggerID": "hm-rpc.1.NEQ1652595.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "260",
        "directionRange": "40",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Gaestebad.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": false,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Rollos.Gaestezimmer",
        "name": "0_userdata.0.Rollos.Gaestezimmer",
        "triggerID": "hm-rpc.1.NEQ1651899.1.STATE",
        "typeUp": "children-auto",
        "typeDown": "children-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "260",
        "directionRange": "40",
        "tempInside": "23",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Gaestezimmer.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": false,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      },
      {
        "enabled": true,
        "shutterName": "Rollos.Badezimmer",
        "name": "0_userdata.0.Rollos.Badezimmer",
        "triggerID": "hm-rpc.1.NEQ1652001.1.STATE",
        "typeUp": "living-auto",
        "typeDown": "living-auto",
        "type": "outside temperature and direction",
        "heightDownSun": "30",
        "direction": "260",
        "directionRange": "40",
        "tempInside": "",
        "tempSensor": "",
        "outsideTempSensor": "0_userdata.0.Mittelwert.Temp-Badezimmer.Mean_15",
        "tempOutside": "23",
        "lightSensor": "0_userdata.0.Mittelwert.Sonnen-Einstrahlung.Mean_15",
        "valueLight": "100",
        "heightUp": "100",
        "heightDown": "0",
        "triggerState": "false",
        "triggerStateTilted": "none",
        "triggerDrive": "100",
        "triggerDriveTildet": "50",
        "triggerChange": "upDown",
        "elevation": "2",
        "autoDrive": "onlyUp",
        "hysteresisOutside": "5",
        "hysteresisInside": "5",
        "hysteresisLight": "10",
        "currentAction": "",
        "currentHeight": "",
        "oldHeight": "",
        "firstCompleteUp": "",
        "triggerHeight": "",
        "LateDown": true,
        "inSummerNotDown": false,
        "KeepSunProtect": false,
        "triggerAction": "",
        "driveAfterClose": true,
        "useXmasLevel": false,
        "XmasLevel": "0",
        "betweenPosition": false,
        "betweenPositionLevel": "50",
        "trigDelyUp": "5",
        "trigDelyDown": "5",
        "sunProtectEndDely": "0",
        "sunProtectEndtimerid": "",
        "enableAlarmWind1": false,
        "enableAlarmWind2": false,
        "enableAlarmRain": false,
        "enableAlarmFrost": false,
        "enableAlarmFire": false,
        "alarmTriggerAction": "",
        "alarmTriggerLevel": "",
        "lastAutoAction": ""
      }
    ]
  }
}`

**Comment by SpezialAgent** [comment]
Das Ergebnis war leider nicht erfolgreich:

<img width="1010" alt="Bildschirmfoto 2023-01-19 um 18 01 50" src="https://user-images.githubusercontent.com/45120419/213511215-52bf5c7c-ce03-45dc-b4d4-fb49d2951a61.png">

Hier die History:
<img width="1140" alt="Bildschirmfoto 2023-01-19 um 18 03 12" src="https://user-images.githubusercontent.com/45120419/213511652-dcad505a-988c-4cea-827b-3f62e83a157b.png">

<img width="1140" alt="Bildschirmfoto 2023-01-19 um 18 03 41" src="https://user-images.githubusercontent.com/45120419/213511700-b40f8c22-473e-44e6-9d8b-b5e4c95d722c.png">

**Comment by simatec** [comment]
Man sieht es ja gut. Shuttercontrol setzt auf 20% und dann kommen kurze Zeit später 19%
ist normal, dass Shuttercontrol in den manu mode geht. 
Was sind das für Aktoren? kann man die kalibrieren? 
Spielen wirklich keine Scripts von iobroker oder ccu da in die Karten?

**Comment by SpezialAgent** [comment]
Das beschreibt das Problem genau. Ich habe alle Scripte meiner früheren Rollo-Steuerung auf der CCU deaktiviert, um eine Interaktion mit Shuttercontrol auszuschliessen. Auch auf dem ioBroker laufen keine Scripte mit einer Ausnahme: Das Ankleidezimmer hat einen HmIp-Broll. Dieser hat einen Steuerkanal und einen Kanal für den echten Level. Diesen Synchronisiere ich mit einem Script. Das ist aber die Ausnahme.
Alle anderen Aktoren, genau die die auch die Probleme machen, sind Eltakto FSB61NP-230V Funkaktoren.

Diese können nicht kalibriert werden. Sie sind über das CuXD-Addin in der CCU in die Steuerung der CCU integriert worden und per hm-rpc Adapter im ioBroker aufgenommen worden.
Warum die wenige Sekunden nach dem Fahren ihren Wert um 1% ändern, kann ich nicht sagen und das ist wohl ein großes Geheimnis. In verschieden Foreneinträgen gab es den Tipp, die Fahrzeit zu stoppen und einzutragen. Das habe ich bei allen Aktoren gemacht. 
Wie du dem Protokoll entnahmen kannst, betrifft der Fehler hauptsächlich die Aktoren, die auf Frostschutz waren. Ausnahme war das Schlafzimmer-Rollo. Gleicher Aktor und auch Frostschutz.

Ich bin seid dem Start von ShutterControl dabei und habe den Adapter sehr begrüßt. Seit dem Einführen des Manu-Modus hatte ich die beschriebenen Störungen, ohne die Rollos manuell zu fahren. Ich bin daher auf eine Steuerung in der CCU zurück gegangen. Vor einiger Zeit habe ich im Forum, wo gleichgelagerte Probleme mit dem mau-Modus beschrieben wurde, den Tipp über ausgelagerte Datenpunkte in 0_userdata.0.xxxx bekommen. Die Rollos werden dann über kleine Scripte, die auf Änderung des State-DPtes von Shuttercontrol reagieren, gesteuert.

Das ist nun meine Lösung.

Schön wäre es, wenn man, wie im Issue angefragt, die Überprüfung per Flag ausschalten könnte. Jeder nach seinem Gusto. bei mir scheint das Möglicherweise ein Rundungsfehler in irgendeiner Routine zu sein. Das ist die einzige Erklärung, die mir einfällt. Ausschliessen kann ich konkret das manuelle Fahren der Rollos.

Hier auch an dieser Stelle ein herzliches Dankeschön für den genialen Adapter.

Gruß
Martin

**Comment by SpezialAgent** [comment]
Ich habe mir heute Morgen die Werte angeschaut. Bei Frostschutz habe ich 20% eingetragen. Einige Aktoren haben aber 19% angezeigt.
Vielleicht kannst du bei der Überprüfung der Fahrzustände auch einen Wertebereich eingeben, z:b. 18 bis 22%?

**Comment by simatec** [comment]
Ich würde da mal zu Eltako an deiner Stelle Kontakt aufnehmen.
Wenn du 20% einstallst, kann es ja am Ende nicht korrekt sein, dass der Rollladen auf 19% geht.

Du bist der erste hier mit diesem Problem und ich würde mit einer Range das komplette Grundkonzept von Shuttercontrol über den Haufen werfen müssen.

**Comment by SpezialAgent** [comment]
Okay, verstanden. Vielleicht kommt es ja doch mal in ein Release oder ein Schalter, um die Prüfung abzuschalten.
Danke für deine Mühe.
Gruß
Martin

**Comment by SpezialAgent** [comment]
Naja, der erste und einzige bin ich nicht. Im Forum gibt es viele Meldungen dazu. Von einem Teilnehmer habe ich auch das Script übernommen, dass auf Änderungen von State reagiert und die Datenpunkte Level der Shutter unterhalb userdata anlegt.

**Comment by SpezialAgent** [comment]
Kannst du mir bitte die Bezeichnungen der States geben? In der Doku ist das leider nicht erwähnt.
Ich habe up, down, frost, Xmas. Ich habe nun den Fire-Alarm aktiviert. Vermutlich wird dann fire eingetragen?
