### ISSUE TITLE
Windwächter / Hagelschutz

### ISSUE THREAD

**Issue by phifogg** [simatec/ioBroker.shuttercontrol#53]
Erstmal danke für das Modul. Ich bin noch ganz neu bei IOBroker und suche mir einiges zusammen :) ShutterControl gefällt mir gut und wird vermutlich den Löwenanteil meiner Steuerung machen können. Super!!

Zwei Zusatzoptionen hätte ich gerne:
- Bei Wind grösser x km/h (kommend von einer Wetterstation) sollen die Storen hochfahren
- Bei Hagelmeldung (kommt von einem Webservice) sollen die Storen hochfahren

Jetzt könnte ich mir sicher einen Datenpunkt bauen und mittels Skript Türkontakt, Hagel und Wind auswerten und das als 'Triggerkontakt' nutzen. Würde aber gern das Skript vermeiden :)

Noch bin ich nicht fit genug das Modul zu forken und drin rumzubauen... irgendwann vielleicht.

**Comment by poidi** [comment]
Ja sowas in der Art wäre auch für eine Markisensteuerung natürlich sehr Empfehlenswert.
Wobei hier vermutlich auch eine Kombination mit einem Regensensor interessant wäre, oder halt generell ein Wert der anzeigt, dass die Markise einfahren sollte - mit Hysterese, oder minimale Zeitdauer nach dem Einfahren wieder auszufahren.

Damit auch hier nicht ein ständige Ein/Ausfahren passiert.

**Comment by vw-arneth** [comment]
Dies ist eine sehr Wichtige Option! Bei Sturm die Lamellen hochzufahren. Bitte für die nächste Version dringend nachrüsten. Vielen Dank

**Comment by Schmakus** [comment]
Halte ich auch für eine sehr wichtige Funktion! Aktuell lässt sich dies nur über Javascript/Blockly lösen, indem man direkt den Datenpunkt "open..." im Adapter ansteuert.

**Comment by FoxRo** [comment]
Hi Simatec
Evtl könnte ich hier was beitragen, dazu müssten wir aber ein Konzept mit den Anforderungen aufstellen.
Anforderungen:
Zentrale Alarm Eingangs-Objekte (Logik True/False) für:
1.  Windalarm1
2.  Windalarm2 (zb. Markise)
3.  Regenalarm 
4.  Frostalarm
5.  Feuer/Einbruchalarm

-  Jedes Rollo Objekt hat Checkboxen (Extra Settings), auf welches der Alarmsignale es reagieren soll
- In den globalen Extra (evtl Separater Tab Alarme) Einstellungen kann zu jedem Alarmtyp die anzufahrende Höhe konfiguriert werden. 
- Bei Frostalarm wird das Down durch die Höhe vom Frostalarm "ersetzt", also nur auf Frostalarm Höhe gefahren, anstatt bis "Down"
- Wenn ein Alarm Objekte "true" wird, fahren die angehakten Rollos auf die im Extra Menü definierte Höhe und wenn der Alarm wieder "false" wird, fährt er zurück in die Ursprungsstellung.
- Ausnahme ist "Feuer/Einbruchalarm" wenn dieser auf "false" zurück geht, dann bleiben die Rollos oben -> müssen manuell wieder initialisiert werden. zb. Button "openAll" / "closeAll".

Zur Umsetzung, sind da weitere neue Statusvariablen zu den Objekten erlaubt? oder muss dies mit den existierenden umgesetzt werden? Könnte problematisch/kompliziert in Kombination mit Trigger- und Init Funktion werden?
Die effektive Auswertung einer Wetterstation müsste aus meiner Sicht ausserhalb von Shuttercontrol gemacht werden, da es so viele verschiedene Typen und Dienste gibt.
Was meinst Du zu diesem Grobkonzept?
Habe ich was vergessen?
Danke für Dein Feedback.

**Comment by simatec** [comment]
@FoxRo Deine Idee hört sich gut an.
Grundsätzlich ist alles erlaubt, solange wir in dem Konzept von shuttercontrol und iobroker bleiben

**Comment by simatec** [comment]
@FoxRo wie ist hier der Stand? Bist du da noch dran?

**Comment by FoxRo** [comment]
@simatec - Sorry für die Verspätung. Hatte da in meiner Umgebung mal was angefangen, jedoch ist das eher auf Funktionsmuster Ebene. Also nichts für die Integration.
Leider bin ich aktuell Beruflich tief "unter Wasser", weshalb ich da nicht so schnell vorwärts komme wie ich das selbst gerne hätte.
Wenn Du oder jemand anders Zeit hat, würde ich es gerne abgeben, ansonsten wird's bei mir sicher Sept. bis ich da wieder richtig ran kann. Sorry.

**Comment by simatec** [comment]
Kommt in Version 1.3.0
