### ISSUE TITLE
Zeitkonfiguration für den Lichtsensor

### ISSUE THREAD

**Issue by lonsimbt** [simatec/ioBroker.shuttercontrol#538]
Ich begrüße es sehr, dass nun auch eine Zeitkonfiguration für den Lichtsensor implementiert wurde.

Ich würde mir aber wünschen, dass dies eine eigene "Art der Automatiksteuerung" für den Wohn-/Schlaf-/Kinderbereich wäre und nicht völlig getrennt unter den Extra-Einstellungen abgebildet wird. So fehlt z. B. die Möglichkeit alternative Uhrzeiten für das früheste/späteste Hochfahren am Wochenende anzugeben.

**Comment by simatec** [comment]
Die Auswahl des Lichtsensors für das hoch und runterfahren ist ein eigener Bereich und hat nichts mit dem Bereich der Zeitsteuerungen für den Wohn- und Schlafbereich zu tun. 

Die Zeiteinstellungen sind lediglich dafür gedacht, Grenzwerte selber festlegen zu können, ab wann der Lichtsensor greifen darf.

**Comment by lonsimbt** [comment]
Das finde ich eben unlogisch. Ich hätte mir gewünscht, dass es alternativ zur Steuerung nach festen Zeiten oder Astrofunktionen die Möglichkeit gibt nach Lichtsensor zu steuern. So steht die Steuerung nach Lichtsensor "quer" zu den anderen alternative Triggern. Insbesondere fehlt so zzt. die Möglichkeit alternative Uhrzeiten für das früheste/späteste Hochfahren am Wochenende anzugeben.

**Comment by Schmakus** [comment]
Jetzt komme ich auch durcheinander.... :-)
Für mein Verständnis: Die neuen Zeiten legen nur fest, wann der Helligkeitssensor greift, so richtig?
Weil aktuell arbeite ich mit dem Helligkeitssensor und den frühestens Öffnen Zeiten der Wohnbereiche. Und das funktioniert seither tadellos. Bedeutet, Helligkeitssensor reagiert z.B. um 7 Uhr, aber erst um 7:30 fahren die Rollläden weil so eingestellt.

**Comment by simatec** [comment]
Ist aktuell nicht geplant ...

**Comment by vain90** [comment]
Sehr schade. Genau das würde ich mir auch wünschen.
Astro und die Zeiten haben immer das Problem, dass einem im Winter bei Schnee die Rolladen zu früh runter fahren. Oder bei schlechten Wetter im Sommer zu spät. Ein Helligkeitssensor wäre so viel genauer. Aber leider Hebel ich mir damit komplett die Zeiten aus wann frühestens oder spätestens gefahren werden darf. Und dass natürlich mit der Unterscheidung der Schlafbereiche und ob Werktags/Wochenende.

Mein Wunsch wäre einen weiteren "Type of automatic control for the XXX area"

**Comment by simatec** [comment]
Du kannst doch Zeiten für deinen Helligkeitssensor bereits jetzt schon eintragen

**Comment by vain90** [comment]
Wenn ich dass jetzt nicht völlig falsch verstanden habe nur die frühsten Zeiten (Morgens und Abends).
Nicht aber für unterschiedliche Areas und auch nicht mit der Unterscheidung zwischen Werktags und Wochenende.

Genau das wäre extrem hilfreich. Der Helligkeitssensor müsste dazu als separater Träger für die Areas auswählbar sein.

Ein Riesendank für deine Mühen und diesem tollen und hilfreichen Adapter! 👍

**Comment by tschortschde** [comment]
Das finde ich auch ;-)
