### ISSUE TITLE
Verständliche Anleitung

### ISSUE THREAD

**Issue by tenkelmann** [simatec/ioBroker.shuttercontrol#54]
Hab grade die aktuelle Github Version installiert und wollte sie nun konfigurieren. Leider ist die Anleitung scheinbar noch von einer älteren Version und total unverständlich. Kann das mal einer, der sich mit dem Adapter auskennt, so anpassen das man auch als Nichtprogrammierer den Adapter korrekt konfigurieren kann.

**Comment by simatec** [comment]
Die Anleitung ist aktuell ...
