### ISSUE TITLE
Werte unter shuttercontrol.shutters.autolevel wer4den nicht richtig aktualisiert

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#550]
Ich habe diverse Shelly 2.5 als Rolladenaktoren. 
Im ioB werden die Werte unter shelly.0.shsw-25#xyzabc.shutter.position richtig angegeben, so wie der Öffnungsgrad der Jalousien auch ist.
Unter shuttercontrol.shutters.autolevel werden diese Werte aber nicht immer richtig aktualisiert. Der letzte Eintrag in shuttercontrol.shutters.autolevel steht auf 86% während unter shelly.0.shsw-25#xyzabc.shutter.position der richtige Wert 100% angezeigt wird. Auch nach Neustart des Adapters oder des ioB werden die Werte nicht aktualisiert.
Ist das ein Fehler oder muss ich irgendwo was einstellen?

**Comment by simatec** [comment]
Dann brauchen deine Shellys wohl etwas nach Änderungen. 
Hier würde ich dir raten, die Überprüfung der Rollläden nach x Sekunden zu nutzen. 
Solltest du diese schon nutzen, würde ich dort die Zeit etwas höher setzen

**Comment by guitardoc** [comment]
Du meinst den Wert unter Extra-Einstellungen.Extra-Einstellungen.Überprüfen des aktuellen Rolladenstaus? 

Ich habe den von ursprünglich 40s mal auf 120s gesetzt. Wenn die Öffnung kleiner 100% ist, dann werden die Werte aktualisiert (das funktionierte auch bei 40s schon zuverlässig). Wenn die Öffnung genau 100% ist, dann erfolgt die Aktualisierung auch bei 120s nicht immer.

Ich habe die Jalousien über Homekit-Homebridge gefahren. Im ioB wird der Öffnungswert unter den Shellys direkt nach wenigen Sekunden aktualisiert. Im Shuttercontrol nach dem eingestellten Wert für die Überprüfung, außer wenn sie voll geöffnet sind (100%), dann wird dort bei mir nur manchmal was aktualisiert. 

Was sich aber verifizieren lässt - Die letzte Jalousie in der Liste wird nur bei Werten <100% aktualisiert. Wenn es genau 100% sind, dann bleibt der Wert auch noch nach Stunden auf dem davor gültigen Wert.

**Comment by guitardoc** [comment]
Jetzt wurde auch der letzte Werte in der Liste auf 100% geändert. Das hat jetzt ungefähr 20 Minuten gedauert...

**Comment by simatec** [comment]
Shuttelcontrol reagiert grundsätzlich auf Änderungen des Rollladenstates.
Hast du den Shelly kalibriert?

Sonst müsste man mal im Debug-Log schauen
