### ISSUE TITLE
Korrektur Wert für Raffstore 

### ISSUE THREAD

**Issue by Apfelwurm1** [simatec/ioBroker.shuttercontrol#556]
Mir fehlt für den Sonnenschutz mit Raffstoren noch ein Korrekturwert für den Winkel der Lammellen.

Wenn shuttercontrol eine Beschattung startet und den Level auf 100 setzt wäre es für Raffstore perfekt wenn man den Winkel der Lammellen dann um Wert x ( zb. 2% ) korrigiert nach x sekunden und dann 98%  als Ergebnis hätte.

**Comment by simatec** [comment]
Dafür gibt es im Forum Scripte ... Shuttercontroll unterstützt aktuell keine Lammellen ... 
Vielleicht kommt es irgendwann mal in ferner Zukunft
