### ISSUE TITLE
Popup nach dem Speichern und Schließen des Adapters 

### ISSUE THREAD

**Issue by bambi-arch** [simatec/ioBroker.shuttercontrol#560]
Besteht die Möglichkeit, den User über ein Popup bei konfig. Änderungen zu informieren (wenn nicht alle Rollos oben sind), dass der Button "obenAll" gedrückt werden muss?
Ich vergesse dass leider immer mal wieder!

Danke

**Comment by bambi-arch** [comment]
@simatec 
Sorry, aus der Anleitung nehm ich es anders war:
"Achtung: Wenn der Shuttercontrol Adapter neu gestartet wird (Auch nach Konfigurationsänderungen) müssen die Rollläden mittels des Button "obenAll" (shuttercontrol.0.control.openAll) hochgefahren werden. Auch wenn diese schon offen sind! (Initialisierungsfahrt) Dies initialisiert alle Adapter internen Werte."

**Comment by simatec** [comment]
Doku ist angepasst ... War noch aus einer älteren version
