### ISSUE TITLE
Alarm Wind 1 ended und Rollo fährt hoch

### ISSUE THREAD

**Issue by Jack77777777** [simatec/ioBroker.shuttercontrol#563]
Wenn ich meine  meine Rollos manuell runterfahre, kommt kurz darauf...
**Alarm Wind 1 ended Set ID: Büro Jalousie value: 100%** und der Rolle fährt wieder hoch. Meine Systemvariable für den Windalarm ist die ganze Zeit auf "false"
1. Warum kommt das wenn meine Systemvariable die ganze Zeit auf false steht?
2. Warum fährt die überhaupt hoch ? ended bedeutet doch nicht hochfahren.
Benutzte Version ist 1.4.22
Habe schon eine neue Instanz installiert und manuell neu konfiguriert und die verhält sich genauso.

**Comment by simatec** [comment]
Dann wird deine Systemvariable ständig aktualisiert. Stelle deinen Script so ein, dass dein Wert nur bei Änderungen gesetzt und aktualisiert wird.
"ne" statt "any"

**Comment by Jack77777777** [comment]
@simatec was meinst Du damit ?
Mein Programm auf der CCU sieht so aus:
![image](https://user-images.githubusercontent.com/64719909/228915128-f1e4b1e9-68fa-440d-9b32-dd18332b278e.png)
