### ISSUE TITLE
Reaktion auf Regenalarm

### ISSUE THREAD

**Issue by raldi01** [simatec/ioBroker.shuttercontrol#564]
Ich würde mich freuen, wenn die Möglichkeit bestünde, die Reaktion des Adapters auf z.B. Regenalarm genauer zu bestimmen. In meinem Fall wünsche ich mir, dass Nachts nicht auf den Regensensor reagiert wird. In den Schlafräumen (im OG) ist bei mir Nachts ein Öffnungsgrad der Rolladen von 20% (Lüftungsschlitze offen) definiert. In allen anderen Räumen im EG sind 0% Öffnungsgrad als "Einbruchschutz" eingestellt.
Bei Regen sollen die Rolladen bei mir normalerweise auf 30% Öffnungsgrad fahren. Momentan reagiert der Adapter auch nachts auf Regen,d.h. bei kurzen Regenschauern ist da ganz schön Bewegung.
Das Workaround überall 20% Öffnungsgrad bei Regen einzustellen, ist nur bedingt geeignet. Dadurch ist zwar in den Schlafräumen Ruhe, aber im EG wird trotzdem fleissig rauf- und runtergefahren.
Es wäre schön, wenn sich das umgehen liesse.

**Comment by simatec** [comment]
Die Alarme haben im Konzept von Shuttercontrol immer Vorang vor allen anderen Auto-Funktionen.
Wenn du Nachts keine Bewegung der Rollläden willst, stelle die Höhe des Regenalarms auf den identischen Wert für das schließen der Rollläden
