### ISSUE TITLE
Sonnenschutz-Einstellungen neue Kombinationsauswahl

### ISSUE THREAD

**Issue by bambi-arch** [simatec/ioBroker.shuttercontrol#565]
Besteht die Möglichkeit zu den vorhandenen, noch die Auswahl "Innentemperatur & Lichtsensor" (ohne Außentemperatur) einzurichten? Wäre gerade jetzt bei den Übergangszeiten sehr hilfreich, weil die Außentemperatur noch sehr niedrig ist!

Danke

**Comment by bambi-arch** [comment]
@simatec 
Sorry, die Anleitung interpretiere ich für mich etwas anders. Für mich ist eine "UND-Verknüpfung" dass in der Kombi alles gegeben sein muss und nur der Lichtsensor optional ist.
![image](https://user-images.githubusercontent.com/104907692/228227102-fd2c5b20-1925-4c8f-843e-5c90508f114f.png)

**Comment by bambi-arch** [comment]
@simatec Welchen nutzen hat dann die Auswahl? Man könnte ja dann einfach alles leer lassen, was nicht geprüft werden soll oder?

**Comment by simatec** [comment]
Nimm die Option "Außentemperatur/Lichtsensor und trage dort halt die States von Innentemperatur und Lichtsensor ein.
Keine schreibt dir vor, die vorgegebenen Werte auch so zu nutzen.

Du kannst dir auch bei Regenalarm oder Windalarm ne Abwesenheit drauf legen, damit die Rollläden bei Abwesenheit runterfahren. 
Der Kreativität sind keine Grenzen gesetzt... Und nochmal... Wenn hier alle Userwünsche einfließen würden, dann wäre zum einen das Konzept des Adapters komplett über den Haufen geworfen und zum anderen wäre der Adapter nicht mehr bedienbar.

Was die Doku angeht, bist du gerne eingeladen, diese zu erweitern und zu verbessern.
Hier ist Hilfe immer sehr gerne gesehen.

**Comment by bambi-arch** [comment]
@simatec Ich glaub einer der größten Wünsche ist es von Entwicklern, dass Anwender die vorhandenen Dokus lesen und nicht immer auf "DAU" machen und ständig Fragen, was dort eigentlich steht! Vielleicht aber auch nur meiner! 

Das mit den Userwünschen kenne ich zu gut! Bin ich voll bei dir! Und nochmal, sorry, bin halt nach der Anleitung gegangen und hab deswegen meine Fragen/Wünsche geäußert. 

Wenn ich mal einigermassen mein SmartHome stehen haben, werde ich mich gerne in die Doku einbringen.

Der Adapter ist ein sehr gutes Produkt! Danke für deine Arbeit und mein Kommentar soll das auch nicht reduzieren!

**Comment by simatec** [comment]
Alles gut … sehe ich auch alles garnicht so eng. 
Es halt nur schwierig, da User jeden Tag den Adapter an ihr örtlichen Gegebenheiten angepasst haben wollen und das einfach so nicht möglich ist. 
Denke Shuttercontrol bietet sehr sehr viele Möglichkeiten und wenn mal was nicht so nach den Vorstellungen ist, gibt es immer noch die Option einen Script mit in Shuttercontrol einzubinden.
