### ISSUE TITLE
Individualisierung / Werte in Objekten

### ISSUE THREAD

**Issue by Apfelwurm1** [simatec/ioBroker.shuttercontrol#57]
Erst einmal hervorragendes Arbeit bisher. Was mir ein bisschen fehlt und deshalb auch der Future Request die Individualisierung des ganzen. 

Ein Beispiel: bei 23 Grad will ich ein Rollo um 50% schließen aber bei 30 Grad um 70 %

Lösung1:  
wenn ich die Werte in die Objekte und nicht in der Instanz habe kann ich das über ein Blockly oder der gleichen nachbessern. und würde in den wert bei 30° 70% schreiben.  

Lösung2:
in den Objekten den Zustand angeben.  z.b  open/sun/close  (Ähnlich dem autoSun)  dann könnte man mit eigenen Scripten weiterarbeiten. In meinem Fall verhindere ich bei Regen oder bewölkt die Beschattung.  Wenn ich den Status der Beschattung erhalte könnte ich somit weiterarbeiten. 

Ich denke Lösung 1 ist die Individuellste aber aufwendigste. Lösung 2 sollte eigentlich leichter umzusetzen sein. 

Ansonsten tolles Projekt.

**Comment by simatec** [comment]
eine vergleichbare Issue ist bereits in Arbeit
