### ISSUE TITLE
Sonnenschutz geht nicht

### ISSUE THREAD

**Issue by ZeroQool007** [simatec/ioBroker.shuttercontrol#572]
Hallo zusammen,

zum Testen des Sonnenschutz habe ich mir 3 Datenpunkte erstellt. 

![image](https://user-images.githubusercontent.com/12768323/230742124-105d4d21-82e2-4aff-813e-face880cba12.png)

Haupteinstellungen:
![image](https://user-images.githubusercontent.com/12768323/230742133-e5a91f04-cb19-4e1d-99a0-c7ae94b1412e.png)

Details:
![image](https://user-images.githubusercontent.com/12768323/230742140-a33bac9f-2dee-4eea-83d7-32f2fd0d4fd4.png)

![image](https://user-images.githubusercontent.com/12768323/230742149-43b3be72-6f65-490d-93bf-da3f2713b820.png)

![image](https://user-images.githubusercontent.com/12768323/230742168-b16e0bb1-2dbd-4c6f-9d7d-79301e9a0d34.png)

Ich bin etliche Kombinationen durchgegangen, aber das Rollo hat immer noch die Position 99%

Im Log sehe ich das der Trigger des Adapter anspringt, aber die Position verändert sich wie gesagt nicht. Was mache ich falsch? Danke

![image](https://user-images.githubusercontent.com/12768323/230742225-644bff5f-d95a-41ef-9f48-9f97a5129257.png)

**Comment by ZeroQool007** [comment]
hier die config
[system.adapter.shuttercontrol.0.json.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/11184484/system.adapter.shuttercontrol.0.json.txt)

**Comment by simatec** [comment]
Wenn dein Rollladen auf 99% steht, ist das laut deiner Config keine Position einer automatischen Fahrt. Dementsprechend wird es als manuelle Bewegung betrachtet und der Rollladen wird nicht bewegt. 
Erst am Abend wird die Automatik zum schließen wieder aktiviert.

**Comment by ZeroQool007** [comment]
Das gleiche ist auch bei 100%.
Ich muss irgendetwas noch falsch parametrisiert haben. Gibt es ein festen Zeitraum oder andere fixe Werte wann der Sonnenschutz nicht funktioniert? Zb ab 22:00 oder ähnliches

**Comment by simatec** [comment]
Ja laut deiner Config ab einer Elevation unter 10

**Comment by ZeroQool007** [comment]
Könnte man das mit 0 oder so aushebeln, damit ich das bspw abends im Büro testen bzw simulieren kann? Danke

**Comment by simatec** [comment]
Nein das geht nicht ...

**Comment by ZeroQool007** [comment]
oder kann ich den aktuellen Höhenwinkel irgendwo einsehen?

**Comment by simatec** [comment]
Ja den kannst du in den Objekten von shuttercontrol einsehen
