### ISSUE TITLE
Sunprotect setzt Status "manu_mode"

### ISSUE THREAD

**Issue by Riffcommander** [simatec/ioBroker.shuttercontrol#576]
**Describe the bug**  
Rollläden gehen gemäß der Einstellungen in den Sunprotect, öffnen danach aber nicht mehr.
Also Status wird anstelle Sunprotect der "manu_mode" von Shuttercontrol gesetzt.

**To Reproduce**  
Bedingungen für Sunprotect erstellen. 
Sobald die Bedingungen erfüllt sind, fahren die Rollladen in den Sunprotect, der Status geht jedoch auf "manu_mode".

**Expected behavior**  
Rollläden sollten eigentlich in den Status "sunprotect" gehen und dementsprechend nach Beendigung der Bedingungen wieder in die Position "Up" wechseln.

**Versions:**  
 - Adapter version: 1.4.23
 - JS-Controller version: 4.0.24
 - Node version: 16.19.1
 - Operating system: raspberrypi OS (Linux)

**Additional context**  
Ich kann leider nicht genau sagen, wie lange das Problem bereits besteht, da die Bedingungen für Sunprotect aufgrund meiner
Einstellungen gestern und heute erstmalig wieder erfüllt wurden. Hat aber letztes Jahr die komplette "Saison" bei gleichen Einstellungen problemlos funktioniert.

**Comment by simatec** [comment]
Dann fahren deine Rollläden nicht auf den exakten Wert und du musst die Überprüfung des Rollladen Status nach x Sekunden aktivieren. 
wie groß du die Zeit einstellst, hängt dann von deinen längsten Fahrzeiten ab

**Comment by Riffcommander** [comment]
Wert für die Überprüfung steht auf 120 sek. So stand der Wert auch letzten Sommer über.
Ein höherer Wert bringt leider auch keine Besserung.

**Comment by simatec** [comment]
Dann musst du den Grund suchen, warum deine Aktoren nicht den korrekten Wert zurückgeben. Shuttercontrol kann nur den Wert verarbeiten, der vom Aktor kommt.

**Comment by Riffcommander** [comment]
Da heute mal wieder "Testverhältnisse" herrschen kann ich bestätigen, das die Positionswerte von den Shellys korrekt gemeldet werden. Sowohl in den Datenpunkten des Shelly-Adapters als auch in den Datenpunkten vom Shuttercontrol passen die Werte.
Status "manu_mode" wird jedoch nach wie vor vergeben und verhindert das Beenden des Sonnenschutzes.

**Comment by Riffcommander** [comment]
Hab 1.4.23 und 1.4.24 getestet. Überprüfung ist aktiv und auf 120 Sekunden eingestellt.

**Comment by Riffcommander** [comment]
Leider erst heute wieder zum Testen gekommen.
Bei der 1.4.26 bestand das Problem immer noch.
Ein Downgrade auf 1.4.22 hat Erfolg gebracht. Rollladen werden im Modus auch wieder korrekt mit Sunprotect angezeigt. Das Problem tritt definitiv ab der Version 1.4.23 auf.

**Comment by simatec** [comment]
Die 1.4.28 hat den Fehler behoben.

**Comment by Riffcommander** [comment]
Perfekt! In 1.4.28 funktionierts wieder. Modus Sunprotect wird ordnungsgemäß gesetzt und fahren später auch wieder hoch.
Danke!
