### ISSUE TITLE
Nach neuemUpdate 1.4.23 fahren nicht mehr alle Rollläden 

### ISSUE THREAD

**Issue by Jeba0815** [simatec/ioBroker.shuttercontrol#577]
Hallo
Ich habe vorgestern das neue Update 1.4.23 von dem Adapter geladen.
Leider fährt nur noch ein Rolladen von den angelegten.
Ich nehme als Trigger einen Lux Sensor.  Die ganze Zeit hat das tadelos funktioniert, nach dem Update zickt es.

Rapi 4 8GB
NPM 8.19.3
Nodejs 16.19.1

**Comment by Jeba0815** [comment]
Habe gerad die v1.4.24 geladen. Werde Berichten ob es damit geht  Danke für den superschnellen Support

**Comment by Jeba0815** [comment]
Leider heute morgen das gleiche Poblem.
Wieder nur ein Rolladen gefahren.
In den Protokollen ist auch nur der drin, der auch funktoniert hat

**Comment by simatec** [comment]
Bitte Debuglog und Config hier posten.

**Comment by simatec** [comment]
Schaue bitte auch, im welchen Modus sich die Rollläden befinden. Wenn Sie im Manu_mode stehen, ist es normal, dass sie nicht hochfahren

**Comment by Jeba0815** [comment]
Du musst mir etwas auf die Sprünge helfen.
Debuglog von Iobroker?
wie bekom ich den Config Log? ist das die Datei "system.adapter.shuttercontrol.0.json"

wie bekomm ich eine Datei hier hochgeladen?

Also alle Rolläden stehnen auf "fahren mit Helligkeitssensor"

**Comment by Jeba0815** [comment]
hab mal gestern die Version 1.4.22 drauf gemacht  Damit hat es wieder funktioniert

**Comment by Jeba0815** [comment]
in den Logs vom iobroker sind auch jetzt alle Rolläden wieder aufgelistet. Vorher war immer nur einer drin.
<html><body>


2023-04-13 06:50:29.802 | info | Lightsensor #6 Set ID: Spielzimmer value: 0%
-- | -- | --
shuttercontrol.0 | 2023-04-13 06:50:29.725 | info | Lightsensor #6 Set ID: Rolladen Küche  ShutterPosition1 value: 0%
shuttercontrol.0 | 2023-04-13 06:50:29.659 | info | Lightsensor #6 Set ID: Esszimmer value: 0%
shuttercontrol.0 | 2023-04-13 06:50:29.594 | info | Lightsensor #6 Set ID: Wohnzimmer links value: 0%
shuttercontrol.0 | 2023-04-13 06:50:29.531 | info | Lightsensor #6 Set ID: Wohnzimmer rechts value: 0%
shuttercontrol.0 | 2023-04-13 06:50:29.390 | info | Lightsensor #5 Set ID: Terasse value: 0%


</body>
</html>

**Comment by died112** [comment]
Ich habe ebenfalls das Problem seit den letzten Versionen , das kein Rollo mehr durch den Helligkeitssensor aktiviert wird... Debug -Log habe ich jetzt mal aktiviert.

**Comment by simatec** [comment]
v1.4.25 sollte die Fehler beheben ....

**Comment by died112** [comment]
Bei mir mit aktueller Version wieder alles i.O..  Danke.

**Comment by woupi** [comment]
Ich habe mit der v1.4.23 ebenfalls ein Problem, aus den Texten hier geht aber nicht klar hervor ob es das gleiche ist, darum hänge ich mich mal hier ran.

Ich habe 7 x shelly 2.5. Diese funktionieren einwandfrei mit shuttercontrol.
Zusätzlich habe ich in den letzten Wochen noch 7 ShellyPro2PM verbaut. Diese machen Probleme.
Da ich den Fehler bei shelly vermutet habe, im shelly Forum gepostet.
Einige haben versucht zu Helfen und im Zuge dessen habe ich viel probiert.
Das Ergebnis ist:
- abwechselnd verlieren die 2pm die Position
- es liegt nicht an der Verdrahtung
- ohne MQTT in den shellys, verlieren Sie Ihre Position nicht
- mit MQTT und ohne shuttercontrolintegration, verlieren Sie Ihre Position nicht
- sobald ich sie in shuttercontrol integriere, verlieren sie nacheinander ihre Position

War das Problem bei euch ähnlich und ist es eventuell mit der 1.4.26 behoben?
Die 1.4.26 ist, wenn ich es richtig sehe, noch Beta und ich möchte, wenn es geht, keine beta installieren.
Wenn das Problem aber mit der beta behoben ist und es keine neuen anderen Probleme verursacht, würde ich das natürlich machen.
Vielen Dank und VG

**Comment by woupi** [comment]
Aus dem Shelly Forum kommt von einem user die folgende These und ich möchte mal nachfragen, ob das sein kann?

> Also ich bleibe bei der Vermutung, dass Shuttercontrol vielleicht zyklisch eine Sollposition im Shelly setzt, also der Shelly über diesen Datenpunkt per MQTT das ständig kommandiert bekommt, aber ja schon auf dieser Position steht. 

VG

**Comment by simatec** [comment]
Shuttercontrol setzt genau einmal pro Fahrt den State. Kannst du aber auch im Log henau sehen. 
kannst auch gerne den State von deinem Rollladen logen. Da siehst du genau, wer was setzt

**Comment by woupi** [comment]
Ok, danke. Am Wochenende bin ich wieder zu Hause, dann werde ich einen Rollo mit shelly pro 2pm wieder in shuttercontrol integrieren und mir mal ansehen wie das mit dem "State von deinem Rollladen logen" funktioniert.

**Comment by BastiRIP** [comment]
ich schließe mich hier mal an, auch wenn das Problem scheinbar mit Shelly selbst zusammenhängt. 
Ich bin noch im Aufbau und ziemlicher Neuling, aber mein Shelly 2.5 funktioniert wie er soll, die beiden Shelly 2pm funktionieren nicht Zeitgesteurt (Fixe Zeit/Sonnenuntergang)

**Comment by simatec** [comment]
Bitte auf die aktuelle Version updaten

**Comment by woupi** [comment]
> Bitte auf die aktuelle Version updaten

Endschuldige bitte, wenn ich jetzt blöd frage, aber galt das auch für mich?
Also, hast Du da was gefunden?
VG

**Comment by simatec** [comment]
Issue mit aktueller Version erledigt ...
