### ISSUE TITLE
Rolladen fährt direkt wieder hoch, wenn Sonne weg ist

### ISSUE THREAD

**Issue by dvdkrtz** [simatec/ioBroker.shuttercontrol#578]
Sobald mein Sonnensensor (PV Anlage) unter den hinterlegten Wert abzüglich Hysterese fällt, fahren die Rolläden direkt wieder hoch, obwohl in den Einstellungen eine Wartezeit von 30 Minuten hinterlegt ist:

![grafik](https://user-images.githubusercontent.com/5826328/234793914-381cc8d8-db42-4bc7-8bd6-2fd67e191a74.png)

Habe die aktuellste Version 1.4.29, ist aber mit der aktuellen Stable auch der Fall.

**Comment by simatec** [comment]
Bitte Debuglog und Config als JSON posten

**Comment by simatec** [comment]
Du hast den Helligkeitssensor doppelt drin und die Hysterese ist sehr gering.
Die 30 Minuten beziehen sich auf das beenden des Sonnenschutzes am Abend nach erreichen einer bestimmten Elevation

**Comment by dvdkrtz** [comment]
Ok, das heißt, über der Elevation wird das rauffahren nur über die Hystere gesteuert?

Ich habe denn Helligekeitssensor einmal für die Helligkeit und einmal für die Außentemperatur drin, weil ich keine Möglichkeit gefunden habe, die Verschattung nur über Sonnenstand und Helligkeit zu steuern.

**Comment by simatec** [comment]
Elevation beendet die Sonnenschutzfunktion am Abend.
Die Hysterese in Kombi mit deinem konfigurierten Wert beendet den Sonnenschutz tagsüber. Deine Hysterese ist aber mit 5% sehr klein. da reicht ne kleine Wolke und er fährt wieder hoch. Welcher Wert am besten passt, musst du dir ausprobieren

**Comment by dvdkrtz** [comment]
OK, meine Erwartung war, dass die 30 Minuten bei "Verzögerung, bis die Verschattung wird" auch greifen, wenn die Helligkeit unter die Hysterese fällt.

Dann taste ich mich über die Hysterese ran.

Vielen Dank.
