### ISSUE TITLE
Datenpunkt einführen für aktive oder inaktive Automatik

### ISSUE THREAD

**Issue by Roestkartoffel** [simatec/ioBroker.shuttercontrol#58]
Zusätzliche Datenpunkte für jeden Rolladen/Markise zwecks Visualisierung der Automatik, ob diese aktiv oder inaktiv ist, einführen.
Dann kann man sehen, ob die Automatik greift, wenn man innerhalb des Tages manuell in die Automatik eingegriffen hat.

**Comment by simatec** [comment]
kommt in Version 0.7.4
