### ISSUE TITLE
Wartezeit bei sinkender Helligkeit

### ISSUE THREAD

**Issue by dvdkrtz** [simatec/ioBroker.shuttercontrol#584]
Ich habe das Problem, dass trotz einer recht hohen Hysterese die Rolläden bei wechselnder Bewölkung hochfahren, direkt im Anschluss wieder runter fahren und dann wieder hoch fahren.

Ich fände es gut eine Zeit definieren zu können, die die Hysterese unterschritten sein muss, bevor die Rolläden wieder hoch fahren. Sobald die Hysterese wieder überschritten ist, soll der Timer neu gestartet werden.

**Comment by simatec** [comment]
Binde noch einen Temperatursensor ein oder spiele mit der Hysterese

**Comment by dvdkrtz** [comment]
Habe ich probiert. Temperatursensor bringt ja nichts, da der ja auch nicht greift, wenn die Hysterese unterschritten wird.
Und wenn ich die Hysterese zu hoch mache, um die Schwankungen auszugleichen, sitze ich am Ende im Dunkeln wenn die Sonne wirklich weg ist.

**Comment by simatec** [comment]
Doch ein Temperatursensor bringt etwas, da du darüber eine weitere Bedingung hast. 
Wie gesagt, spiele mit der Hysterese und finde deinen optimalen Wert. Dazu kannst du auch noch mit Himmelsrichtungen arbeiten. 

Shuttercontrol bietet viele Möglichkeiten

**Comment by dvdkrtz** [comment]
Mir ist nicht so ganz klar, wie der Temperatursensor da das Hochfahren verhindern soll.

Ich werde die Helligkeit jetzt extern per Blockly abfragen, den Timer setzen und wenn sie eine bestimmte Zeit unter dem Grenzwert liegt, einen Datenpunkt ändern, auf den Shuttercontrol dann triggert.
