### ISSUE TITLE
Rolladenhöhen als Datenobjekte

### ISSUE THREAD

**Issue by jh2k19** [simatec/ioBroker.shuttercontrol#585]
Ich vermisse die Möglichkeit die Rolladenhöhen aus den Haupteinstellungen und den Sonneschutz-Einstellungen über die Vis anzupassen. Es wäre echt toll, wenn diesse Einstellungen in die Datenpunkte gezogen werden könnten.

**Comment by simatec** [comment]
Ist vom Konzept her nicht geplant

**Comment by jh2k19** [comment]
Alles klar. Danke für die schnelle Rückinfo.
