### ISSUE TITLE
shuttercontrol und Abwesenheit

### ISSUE THREAD

**Issue by wg25** [simatec/ioBroker.shuttercontrol#587]
**Describe the solution you'd like**
Wäre es evtl. sinnvoll, eine Abwesenheitsfunktion zu integrieren? Wenn Bewohner nicht anwesend sind, könnten alle ausgewählten Rollläden in eine vorher festgelegte Höhe fahren. Wenn Bewohner wieder anwesend, dann alle Rollläden in den vorherigen bzw. aktuellen Zustand. Ich komme ursprünglich aus der FHEM Welt und der dortige shuttercontrol hatte diese Funktion und war echt hilfreich. Nur ein Vorschlag.

**Comment by jimknopf63** [comment]
> **Describe the solution you'd like**
> Wäre es evtl. sinnvoll, eine Abwesenheitsfunktion zu integrieren? Wenn Bewohner nicht anwesend sind, könnten alle ausgewählten Rollläden in eine vorher festgelegte Höhe fahren. Wenn Bewohner wieder anwesend, dann alle Rollläden in den vorherigen bzw. aktuellen Zustand. Ich komme ursprünglich aus der FHEM Welt und der dortige shuttercontrol hatte diese Funktion und war echt hilfreich. Nur ein Vorschlag.

Also ich habe das über eine 2te Instanz geregelt. Über den TR064 Adapter auf Anwesenheit überprüft (zw. 0 und 5 Uhr stdl). Wenn dann niemand zu Hause ist schaltet mir ein Script den die Instanzen um. Sobald dann wieder ein Handy im Haus ist wird wieder auf das normale Profil umgeschaltet

**Comment by wg25** [comment]
> Also ich habe das über eine 2te Instanz geregelt. Über den TR064 Adapter auf Anwesenheit überprüft (zw. 0 und 5 Uhr stdl). Wenn dann niemand zu Hause ist schaltet mir ein Script die Instanzen um. Sobald dann wieder ein Handy im Haus ist wird wieder auf das normale Profil umgeschaltet

Ja, ich mache es ähnlich. Mit zwei Instanzen meinst Du eine zweite shuttercontrol Instanz? Ich lasse einfach die gewünschten Rollläden in Abhängigkeit der Anwesenheit manuell runterfahren. Ich möchte aber eigentlich nicht in die shuttercontrol Routinen eingreifen. Wäre ja durchaus sinnvoll, einen Datenpunkt abzufragen, der die Anwesenheit überwacht und dann die gewünschten Rollläden schließt. Bei Rückkehr könnten diese automatisch in die vorherige Position zurückfahren (Verschattung oder ganz hoch oder wie auch immer). Nur ein Vorschlag alles in einem Modul zu haben.

**Comment by simatec** [comment]
Eine zweite Instanz die bei Abwesenheit aktiv wird und die erste deaktiviert sollte hier die beste Lösung sein.
