### ISSUE TITLE
Sonnenuntergang-Schließen

### ISSUE THREAD

**Issue by mango1402** [simatec/ioBroker.shuttercontrol#589]
Meine Rollo ist auf 'Sonnenuntergang - Wohnbereich (Automatik)' gesetzgt.
Zeit-Einstellung für Wohnbereich 'Sonnenauf- & Untergang'; Schließen der Rolläden auf '20:30'.
Laut Doku nehme ich mal an, dass dies dann die **späteste Zeit** zum schließen definieren solte:
```
Zeit Wohnbereich mit Sonnenauf- & Sonnenuntergang:
Die Rollläden werden nach Sonnenauf- und Sonnenuntergang gesteuert, jedoch fahren nicht vor der frühesten Zeit hoch und nicht nach der spätesten Zeit herunter.
```

Datenpunkt 'shuttercontrol.0.info.downTimeLiving' zeigt auch 20:30.

Rollo schließt aber erst zum Sonnenuntergang + Zeitverzögerung (aus den 'Astro-Einstellungen') - also z.B. gestern 20:26 + 15Min.

Versteh ich hier was falsch? Oder doch ein Bug?
Wenn log benötigt kann ich morgen hochladen.

lg
Manfred

**Comment by simatec** [comment]
Der Sonnenuntergang lag mit 20:26 vor der spätesten Fahrzeit ... Dementsprechend wir die zur Berechnung genommen.
Den Zeitversatz von 15 Minuten hast du ja definiert .... Also passt das genau so ins Konzept

**Comment by simatec** [comment]
Nein 20:26 + 15 Minuten
