### ISSUE TITLE
Mehr Optionen benötigt für "Steuerung für Hochfahren"

### ISSUE THREAD

**Issue by Roestkartoffel** [simatec/ioBroker.shuttercontrol#59]
In der Haupteinstellung jedes Rollladen werden mehr Optionen wie "Sonnenuntergang" und "Sonnenhöhe" für die "Steuerung für Hochfahren" benötigt. 
Da für eine Beschattung mittels einer Markise die auswählbaren Optionen nicht optimal sind. Eine Markise soll zum Beispiel bei Beginn der Abenddämmerung einfahren und nicht erst bei Sonnenaufgang.

**Comment by simatec** [comment]
Da sind Planungen für vorhanden, dies anders umzusetzen
