### ISSUE TITLE
Fensterputzermodus

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#591]
Wäre es möglich, einen ‚Fensterputzermodus‘ einzuführen? Man würde dann quasi den Datenpunkt manuell auf true auslösen und alle Jalousien fahren hoch und bleiben dort. 
Im Hintergrund wird alles andere (Verschattung etc.) weiter berechnet und wenn man den Datenpunkt dann manuell auf false setzt, dann werden die Jalousien in den zwischenzeitlich berechneten Zustand gefahren. Danke!

**Comment by simatec** [comment]
Auch hier gilt das Gleiche… Man kann nicht alle Userwünsche erfüllen. 
Einen Fensterputzmodus wird es nicht geben und ist jetzt auch sehr weit hergeholt. OpenAll und oder manuell hochfahren haben den selben Effekt

**Comment by guitardoc** [comment]
Dann fahren die Jalousien aber nur hoch bzw. runter und bleiben nicht dort. Man muss zusätzlich den Adapter komplett stoppen. Wenn es einen Weg gäbe, dies per Script selber zu realisieren, dann wäre es kein Problem, aber ich habe da keinen Weg gefunden wie man das machen könnte…

**Comment by simatec** [comment]
Bau dir einen Script, indem du von allen betroffenen Rollläden die States autoDown, autoUp und autoSun auf false setzt.
Dann fährt kein Rolladen mehr und du kannst deine Fenster putzen.

Finde es aber immer noch etwas to much... Wenn du Fenster putzt und ein Rollladen fährt gerade in Sonnenschutz, dann fährst du ihn einfach wieder hoch und er steht dann auf manumode....

**Comment by guitardoc** [comment]
Ahhh - damit würde es gehen. Kein Problem, wenn es über ein Script machbar ist, dann kann ich es selber programmieren. 
Du hast sicher recht, für die meisten Anwender ist das uninteressant, aber ich habe das System in unserem Firmengebäude im Einsatz und da kommen externe Fensterputzer. Die nehmen da keine Rücksicht was mit den Jalousien passiert - da geht auch schnell mal was kaputt… :-(

**Comment by simatec** [comment]
Dann würde ich sagen mit dem Script openAll ausführen und dann die States auf false setzen.
Wenn der Fensterputzmodus deaktiviert wird, dann wieder die States auf true und die Rollläden fahren wieder automatisch
