### ISSUE TITLE
Autolevel entspricht nicht dem Gerät

### ISSUE THREAD

**Issue by bambi-arch** [simatec/ioBroker.shuttercontrol#598]
Letztes Jahr hatte noch alles Perfekt funktioniert. Nach dem ich teilweise Probleme mit dem Sunprotect hatte bin ich auf 1.4.29 gewechselt.

Jetzt wird teilweise unterschiedliche Rollostände angezeigt zwischen Gerät und AutoLevel. Ich hab auch schon mit "openAll" versucht wieder alles auf "0" zu setzten. Aber am nächsten Tag das gleiche Problem.
Im Beispiel müsste eigentlich im Autolevel "1" angezeigt werden.

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/0d5ff091-2ff5-4446-a9ab-cd19b36eb76e)

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/ed7b201f-5e0d-4a9e-a11e-7b70ccc07d3b)

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/32c08af1-4016-4799-aa81-c701c60b9bb1)

**Comment by simatec** [comment]
Bitte v1.5.0 testen

**Comment by bambi-arch** [comment]
> Bitte v1.5.0 testen

Hab 1.5.0 installiert.
Erstes vorsichtiges Feedback.
Entweder es dauert mehrere Minuten bis es aktualisiert im DP passiert oder es passiert keine Aktualisierung. Ich kann kein Muster erkennen. Ich werde es weiter beobachten.

**Comment by bambi-arch** [comment]
Ich hatte gestern Abend alles auf 0 und auch mit "openAll" gemacht. Heute morgen teilweise wieder unterschiede zum DP der Geräte.
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/8d45d9c9-304c-443f-97e9-2e0d79b8e5af)

**Comment by simatec** [comment]
Die Werte kommen von deinen Aktoren... Da hat Shuttercontrol nix mit zu tun... Aktiviere die Überprüfung der Rollläden nach x Sekunden, wenn deine Aktoren hier länger brauchen

**Comment by bambi-arch** [comment]
So ist es in der Konfig:
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/03ec6b67-8097-4bb9-95a4-0a8b3c29e6e1)

Beispiel: Rollo runterfahren
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/6e0c67ad-5820-4923-9d65-6233d6d5e40d)

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/d3068ee9-28a7-4acb-8a4f-406284edd5c0)

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/f25a1ce2-6c4d-48c8-8f81-547ebb28eb6b)

Dann wieder hochgefahren:
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/104907692/639dd850-02bb-407c-bf51-373d4c97ce94)

Fazit: AutoLevel geht nicht, AutoState schon!

Ich weis nicht was ich falsch mache! Wahr vorher nie ein Thema.
