### ISSUE TITLE
possibility to define different settings for summer months (warm period of the year) and winter months (cold period of the year)

### ISSUE THREAD

**Issue by Qlink84** [simatec/ioBroker.shuttercontrol#6]

**Comment by raintonr** [comment]
We have a Loxone Miniserver and it uses the concept of 'heating period' and 'cooling period' that are designed to be specified in a calendar just as is being requested here.

However, I have found this to be problematic as in our location there are often days that require heating/cooling that are found outside of what a 'normal' season for each would be.

In this case, I have had much more success using the min/max temperature forecast from an available service (we use Darksky API). Ie. if the 24 hour forecast maximum is below a certain threshold then assume this is a heating period, no matter what time of year.

I can highly recommend this approach over the use of a calendar.
