### ISSUE TITLE
Ein Rollo über mehrere Fenster

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#60]
Hi,

Ich habe zwei Fenster, die sich ein Ein Rollo teilen. Somit sollte das Rollo auf 2 trigger reagieren können.
Soll ich einfach das gleiche Rollo 2x anlegen mit jeweils einem anderen Trigger?

Danke
Poidi

**Comment by simatec** [comment]
Oder die beiden Trigger zu einem mit JavaScript zusammenfassen
