### ISSUE TITLE
Rauchmelder-Datenpunkte für einzelne Rollladen

### ISSUE THREAD

**Issue by padman74** [simatec/ioBroker.shuttercontrol#601]
Ich habe Feuermelder, die den Alarm nicht automatisch an den nächsten Feuermelder weitergeben. 
Daher wäre es sinnvoll für jeden Rolllladen einen individuellen Datenpunkt angeben zu können.

Viele Grüße
padman

**Comment by simatec** [comment]
Ist aktuell nicht geplant... Feueralarm im Haus, sollte grundsätzlich für alle Rollläden gelten und kann über ein Skript erfolgen.
