### ISSUE TITLE
Rolladen automatisch öffnen/schließen

### ISSUE THREAD

**Issue by ZeroQool007** [simatec/ioBroker.shuttercontrol#604]
Hallo zusammen,

der Aussperrschutz ist aktiv, also der Rolladen geht bei geöffneter Tür nicht herunter was auch Super ist. Gibt es auch eine Funktion wenn ich Abends rein gehe und die Tür schließe, dass der Rolladen automatisch herunterfährt? 

Die nächste Funktion die ich suche, wenn der Rolladen unten ist und ich die Tür öffne, dass der Rolladen automatisch hochfährt.

Danke

Gruß

**Comment by simatec** [comment]
Das lässt sich alles so realisieren.. Schaue in die Doku, da ist alles dazu niedergeschrieben 

https://github.com/simatec/ioBroker.shuttercontrol/blob/master/docs/de/shuttercontrol.md#haupteinstellungen
