### ISSUE TITLE
Rolladen fahren nicht mehr Automatisch, nach manueller Bedienung

### ISSUE THREAD

**Issue by Jeba0815** [simatec/ioBroker.shuttercontrol#605]
Nachdem ich manuell  einen Rolläden gefahren habe, greift bei diesem die Automatik nicht mehr. Alle anderen Rolläden gehen ordnungsgemäß runter und hoch. 

Ich habe an einigen Homematik IP Aktoren, an ein paar anderen Sonoff Touch  Es tritt bei beiden Varianten auf.
Ohne manuelles Verfahren eines Rollladens geht alles wie es soll.

Hab jetzt die 1.5.0,sowie drei Versionen vorher getestet. Bei allen ist das plötzlich.

Hat das evtl. noch jemand

**Comment by simatec** [comment]
Werden Rollläden manuell gefahren, wird die Automatik bis zum abendlichen Schließen ausgesetzt

**Comment by Jeba0815** [comment]
Wenn ich mittags die Rollläden wegen der Sonne,manuell halb zu gefahren habe,sind sie aber Abends ganz zu gegangen. Das hat immer geklappt.
Morgens gehen dann alle hoch, außer die, die man manuell an Tag zu vor bewegt hat.
Das heißt, dass ich sie nach dem es Dunkel ist manuell zu mache, gehen sie morgends auch nicht mehr  auf
Als Trigger ist bei mir ein Lux Sensor von Homematic.

**Comment by simatec** [comment]
Bitte poste hier die Config des betroffenen Rollladens und den Debuglog der Fahrten
