### ISSUE TITLE
Rollladen gehen nach manueller Betätigung nicht mehr in den Manu_Mode

### ISSUE THREAD

**Issue by Exc3pt10n** [simatec/ioBroker.shuttercontrol#606]
Hallo,

die Rollladen gehen seit dem letzten Update nicht mehr in den Manu_Mode. 

Das bedeutet, wenn der Sonnenschutz die Rollladen gefahren hat und man anschließend die Höhe manuell verändert, der Sonnenschutz die Rollladen im nächsten Zyklus wieder bewegt.
Vor dem Update wurden die Rollladen nach manueller Betätigung erst abends wieder gefahren.

Des weiteren ignoriert der Sonnenschutz die Einstellung "Objekt-ID zum aktivieren/deaktivieren des Auto-Schlafbereichs (z.B. Anwesenheitserkennung)" Ich habe zum Test hier den Wert "false" gesetzt dennoch hat der Sonnenschutz die Rolllade bewegt.

**Comment by simatec** [comment]
> Hallo,
> 
> die Rollladen gehen seit dem letzten Update nicht mehr in den Manu_Mode.
> 
> Das bedeutet, wenn der Sonnenschutz die Rollladen gefahren hat und man anschließend die Höhe manuell verändert, der Sonnenschutz die Rollladen im nächsten Zyklus wieder bewegt. Vor dem Update wurden die Rollladen nach manueller Betätigung erst abends wieder gefahren.
> 

Das ist so gewollt und war ein Userwunsch... Fahre statt auf 100% für auf dann einfach auf 99%. Damit bist du im Manu_mode

> Des weiteren ignoriert der Sonnenschutz die Einstellung "Objekt-ID zum aktivieren/deaktivieren des Auto-Schlafbereichs (z.B. Anwesenheitserkennung)" Ich habe zum Test hier den Wert "false" gesetzt dennoch hat der Sonnenschutz die Rolllade bewegt.

Der States hat nix mit Sonnenschutz zu tun. Wenn du die Automatik eines einzelnen Rollladens abschalten willst, musst du  autoSun, autoUp und autoDown des Rollladens deaktivieren

**Comment by Marcus1807** [comment]
> > Hallo,
> > die Rollladen gehen seit dem letzten Update nicht mehr in den Manu_Mode.
> > Das bedeutet, wenn der Sonnenschutz die Rollladen gefahren hat und man anschließend die Höhe manuell verändert, der Sonnenschutz die Rollladen im nächsten Zyklus wieder bewegt. Vor dem Update wurden die Rollladen nach manueller Betätigung erst abends wieder gefahren.
> 
> Das ist so gewollt und war ein Userwunsch... Fahre statt auf 100% für auf dann einfach auf 99%. Damit bist du im Manu_mode


Das Verhalten ist aber nicht so toll: wie soll ich denn das Rollo auf 99% fahren, wenn jemand die Taste nach oben betätigt? Dann fährt das Rollo immer komplett nach oben.
Hätte man das nicht konfigurierbar machen können?

**Comment by 5G7K** [comment]
Nur zur Info: bis zu den letzten größeren Änderungen war das (letztes Jahr) noch so implementiert, dass nur das ERSTE manuelle komplette Hochfahren den automatischen Sonnenschutz erlaubt hat. Use case: Rollladen wird morgens manuell vor dem automatischen Hochfahren geöffnet -> dann soll er natürlich in den Sonnenschutz fahren dürfen.

Ich persönlich kann auch mit der aktuellen Variante leben. Wird hochgefahren und dann eben nochmal ganz kurz runter.

**Comment by simatec** [comment]
In der nächsten Version werde ich das ganze konfigurierbar machen. Dann kann es jeder nach seinen Wünschen anpassen

**Comment by Marcus1807** [comment]
Was muss ich jetzt einstellen,  damit die Rollos nachdem ich sie manuell bewegt habe nicht mehr automatisch im nächsten Zyklus bewegt werden?

**Comment by simatec** [comment]
Welche Version ist installiert?

**Comment by Marcus1807** [comment]
Installiert ist die 1.6.1
Ist das der Haken bei "Extra-Einstellungen/Extra-Einstellungen/Blockieren des ManuModus... "
Muss ich die Checkbox leer lassen, wenn der Rollo nicht wieder automatisch bewegt werden soll, oder? 
Danke Dir für die Info...

**Comment by simatec** [comment]
Ja der Hacken ist in den Standard Einstellungen nicht gesetzt
