### ISSUE TITLE
Vorschlag für die Anleitung "Sonnenschutz-Einstellungen"

### ISSUE THREAD

**Issue by RasputinBerry** [simatec/ioBroker.shuttercontrol#607]
Hallo simatec,

hier [https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v1-5-x/6146](url) wurde bereits eifrig diskutiert, jetzt möchte ich nicht nur "meckern" und mich mit einem Vorschlag einbringen:
[Vorher.odt](https://github.com/simatec/ioBroker.shuttercontrol/files/11892297/Vorher.odt)
[Nachher.odt](https://github.com/simatec/ioBroker.shuttercontrol/files/11892298/Nachher.odt)

Falls der Vorschlag (inhaltlich hoffentlich richtig) gefällt... muss ich noch etwas tun ?

Grüße

**Comment by simatec** [comment]
Bitte direkt als PR erstellen

**Comment by RasputinBerry** [comment]
Gern ... da ich mich mit PR (=Pull requests) nicht auskenne bitte ich Dich um"Starthilfe" ... Ich habe keine Ahnung was ich hier konkret tun muss ... (Sorry, jeder fängt mal an ...;-))

Hast Du den Vorschlag mal durchgelesen ? Habe ich das richtig formuliert (=richtig verstanden ?) ?
Danke

**Comment by simatec** [comment]
Online kannst du es hier direkt editieren. Nach dem speichern wirst du durch den Vorgang für einen PR geführt.

https://github.com/simatec/ioBroker.shuttercontrol/edit/master/docs/de/shuttercontrol.md
