### ISSUE TITLE
zusätzliche Räume

### ISSUE THREAD

**Issue by bicmac** [simatec/ioBroker.shuttercontrol#608]
Momentan muss ich die Küche und das Bad dem Living/Room zuweisen. und wenn ich über die Controll Funktion den Raum "manuell" öffnen oder schliessen will öffnet sich damit WZ + Küche + Bad.
Zusätzlich bräuchte ich aber gerade im bad unterschiedliche Zeiten so das die momentane Konfig nicht wirklich 100% den Nutzen entspricht.
Kann man ggf noch einen oder 2 zusätzliche Räume wie Küche oder Bad einbauen so das man eine Typische Wohnung abbilden kann?
Im Idalfall würde es noch einen 3. Raum "Büro" geben, da dieser nochmal extra gesteuert werden müsste im Haus.

Aber sonst vielen Dank für den wirklich guten Adapter.

**Comment by simatec** [comment]
Das Thema wurde hier bereits mehrfach diskutiert ... Shuttercontrol hat keine Räume, sondern Bereiche.
Mit allen Möglichkeiten, bietet Shuttercontrol sehr viel unterschiedlichste Möglichkeiten zur zeitlichen Steuerung und sollte somit alle Varianten abdecken.

**Comment by bicmac** [comment]
@simatec dann eben Bereiche und nicht Räume (das ist doch egal wie man es nennt).
Für mich hat ein Haus oder eine Wohnung aber nicht nur living/Sleeping/Child sondern eben auch "Houshold" (also Bad/Küche/Vorrat) und gerade in der heutigen Zeit "Office".
Somit kann ich in der jetzigen Ausbaustufe eben nicht alles abbilden  oder worunter zählst du die Rollos in der Küche oder im bad oder in dem ggf vorhandenen Arbeitszimmer?

**Comment by simatec** [comment]
Für mich ist das der Wohnbereich ... 
Wie gesagt, das Konzept von Shuttercontrol baut auf dieser Grundlage auf und es wurde hier bereits mehrfach diskutiert ...

**Comment by bicmac** [comment]
Schade das requests einfach so geschlossen werden. ja es ist dein Adapter aber su selber sagtest ja das es öfter diese Diskussion gibt. Daher denke ich das ja der Bedarf da ist. zumal ich immer nich glaube das Wohnen und Küche und Büro nicht das selbe sein sollte.

**Comment by simatec** [comment]
Er wurde geschlossen, weil es nicht zu dem gesamten Konzept passt und deine Wünsche extrem viel Eingriff in den Code bedeuten würde. 

Da dieses Thema bereits ausdiskutiert wurde, muss es nicht immer neue Issues dazu geben. 

Du kannst eine weitere Instanz nutzen, um weitere Bereiche zu schaffen. Eine zweite Instanz schafft also 3 weitere Bereiche

**Comment by bicmac** [comment]
@simatec ok das mit der 2. Instanz hilft mir schon mal.
Kann man evtl wenigstens einbauen das man die „Bereiche“ umbenennen kann?
