### ISSUE TITLE
Helligkeitssensor: Weitere Konfigurationsmöglichkeit

### ISSUE THREAD

**Issue by Flipperbastler** [simatec/ioBroker.shuttercontrol#615]
Da ich an meinem Wohnort mit dem "Öffnen & Schließen mit Sonnenauf- und Sonnenuntergang" nicht wirklich gut zurecht gekommen bin, lasse ich nun die Rolläden mit dem Lichtsensor der zentralen Wetterstation fahren. (Hintergrund: Hier im Süden Deutschlands - im Donautal - beginnt es bereits früh im September mit sporadisch dicken Morgennebelfeldern und das Naturschauspiel endet erst wieder spätestens Mitte März ===> Der "rechnerische" Sonnenaufgang hat bereits statt gefunden, aber draußen ist es immernoch stockdunkel.

Daher ist die Steuerung mit Helligkeitssensor für mich "ein Segen", wennglich ich damit auch nicht unumfänglich glücklich bin:

Heute (Sommer-Sonntag) sind die Rolläden bereits um 5:45 Uhr hochgezogen worden. Ich wäre für die Möglichkeit der Einstellung, den Helligkeitssensor ebenfalls mit "frühestes Öffnen und spätestes Schließen" belegen zu können, wie beim "Sonnenauf- und Untergang" bereits vorgesehen, sehr dankbar! Toll wäre hierbei auch die ebenfalls in anderen Bereichen bereits implementierte Wahlmöglichkeit "Werk- / Feiertag".

Darüber hinaus wäre es für den Helligkeitssensor (Extra-Einstellungen / Einstellungen Helligkeitssensor) toll, diesen mit **"frühestes Schließen"** verknüpfen zu können. Hintergrund: Bei starken Sommergewittern am Vormittag / Nachmittag fahren alle meine Rolläden runter, weil es draußen plötzlich "finstere Nacht" wird.

**Comment by simatec** [comment]
> Der "rechnerische" Sonnenaufgang hat bereits statt gefunden, aber draußen ist es immer noch stockdunkel .

Du hast in Shuttercontrol die Möglichkeit mit Verzögerungen für die Astrozeiten zu arbeiten. Das wäre hier die Lösung für dein Problem
