### ISSUE TITLE
Regenalarm nur für geöffnete Shutter

### ISSUE THREAD

**Issue by radebold** [simatec/ioBroker.shuttercontrol#618]
Also so wie ich es verstehe erfolgt bei einem Regenalarm immer eine Fahrt zur eingestellten Position.

Aus meiner Sicht wäre es hilfreich, wenn diese fahrt nur erfolgt, wenn das Rollo auschließlich oberhalb der hinterlegten Position ist.
Nach meinem ermittelten Infos fährt das Rollo auch Nachts, wenn die Rollos eigentlich unten sind und das ist ziehmlich nervig.

Kann man das irgendwie umsetzen?

Und noch ein Frage: Wird der Alarm auch irgendwann wieder aufgehoben und das Rollo geht in den "normalen" Zustand?

Vielen Dank

Thomas

**Comment by simatec** [comment]
Die Alarme haben immer Vorgang
