### ISSUE TITLE
Sicherung der Settings

### ISSUE THREAD

**Issue by radebold** [simatec/ioBroker.shuttercontrol#620]
Kann man irgendwie die EInstellungen Sichern und für eine andere Instace bereitstellen?

**Comment by simatec** [comment]
Du kannst die Konfiguration sehr einfach sichern
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/e2b7eddc-2db4-4339-9d74-ddd8d0fa994f)

Wenn du sie für eine andere Instanz nutzen willst, musst du diese mit einem Editor bearbeiten und die Instanznummer ändern.

`
system.adapter.backitup.0
`

Die Wiederherstellung der Einstellungen erfolgt über die Pfeiltasten oben Rechts in dem Konfigurationsmenü von Backitup.

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/4dc5db52-9ca6-4d96-8175-9df9d99ac5b1)
