### ISSUE TITLE
Unterstützung von Homematic HmIP-SRH / mehrere Fensterzustände

### ISSUE THREAD

**Issue by Mad-Eye87** [simatec/ioBroker.shuttercontrol#622]
Hallo,

wäre es möglich mehrere Fensterzustände zu unterstützen? Beim HmIP-SRH Steht 0 für geschlossen, 1 für gekippt  und 2 für offen.
Es wäre super vor allem Nachts zum Durchlüften, unterscheiden zu können ob gekippt oder ganz offen und je nach zustand andere Öffnungshöhen anzufahren.

**Comment by simatec** [comment]
Wird bereits unterstützt ...

https://github.com/simatec/ioBroker.shuttercontrol/blob/master/docs/de/shuttercontrol.md#haupteinstellungen
