### ISSUE TITLE
Die unterschiedlichen höhen als Datenpunkte

### ISSUE THREAD

**Issue by Zelkin0815** [simatec/ioBroker.shuttercontrol#624]
Der Adapter ist echt klasse!!
Wenn die einstellbaren werte aus der Config als Datenpunkte vorhanden wären (insbesondere die höhen Einstellungen) wäre das ding bombe!
So könnte man z.B. die werte in Vis einstellbar machen, ohne dass jedes mal der mit dem IOBroker umgehen kann ran muss ;)

**Comment by simatec** [comment]
Ist aktuell nicht geplant, da es nicht in das gesamte Konzept von Shuttercontrol passt.
