### ISSUE TITLE
Auto-close-event ignores configured window-open position

### ISSUE THREAD

**Issue by dklinger** [simatec/ioBroker.shuttercontrol#626]
**Describe the bug**  
Blind is closed by time-automation, despite the window is open and shuttercontrol is configured to maintain a specific height while the window is open.

**To Reproduce**  
1. In the blind settings, configure the blind to maintain a height of 40% when the window is open. 
2. Open the window
3. Wait until the daily shutdown-time is reached. 
4. The blinds closes itself instead of moving to the "window open" position. 

**Expected behavior**  
As the setting is used when the blind is closed and I open the window, I would expect that it's also used when the blind is closed. So, if the window is open when the blind is auto-closed by the configured evening-event (time, golden hour, sun height) that it is only closed until the % of the "window open" setting

**Versions:**  
 - Adapter version: 1.6.1
 - JS-Controller version: 4.0.24
 - Node version: 18.16.1
 - Operating system: docker

**Comment by dklinger** [comment]
Btw, from my POV it's a bug. But I understand that this may be by design. So, please let me know if that's the case.

**Comment by simatec** [comment]
Please use the option "Lockout protection" for this purpose
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/1bab847a-21a4-4205-8719-8ba916ff5486)

**Comment by dklinger** [comment]
As far as I understand, this will keep the window at the state at which it currently is, if the window is open, right?
My current settings are this:
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/2249766/a8102678-a32e-4413-ade5-16a4a8b1e6ea)
As I have set "Open and Close" and "roller blind height if windows is open" to 40, I would expect the adapter to move to 40 when the blind close event is triggered in the evening.
Similar like when I open the window at night, which will open the blind to height 40. 
How does it make sense that a destined state (window is open) with the exact same setting can lead to different outcomes?
- Trigger: Open window while blind is close; Result: Blind moves to 40% height.
- Trigger: Blind moves to close while window is open; Result: Blind moves to 0% heigt.

**Comment by simatec** [comment]
This is not a bug but wanted... If you do not want this, you can keep the shutter open until the window is closed.

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/c56fe526-1a1f-4c51-b5f8-52491f0ccf59)
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/8c0206aa-ed1a-4d17-bd44-5961665ce5fc)

**Comment by dklinger** [comment]
Ok, thanks. Looks like that's the best option in my case then.

As your answer sounds like the current behavior is by intention, can I ask what is the reason that the entire closure has a higher priority than considering the open window sensor and the value of "Rolladenhöhe bei öffnen des Fenster oder Tür"?
Does this have security considerations or is it because the "Rolladenhöhe bei öffnen des Fenster oder Tür" was always meant only for triggering by the window sensor? Or some other reason?

**Comment by simatec** [comment]
Security considerations...
