### ISSUE TITLE
Erweiterung Fensterkontakt Wert

### ISSUE THREAD

**Issue by Scotty-89** [simatec/ioBroker.shuttercontrol#627]
Hallo zusammen,

ich würde gern den Adapter nutzen um damit meine ganzen Skripte ab zu lösen, nur leider geht es nicht da meine verwendeten Fensterkontakte sich nicht mit dem Adapter auswerten lassen.
Ich nutze hier das Bosch System und dort liefern die Fensterkontakte kein Boolean sondern ein String...
In der Bosch Welt gibt es den Status "OPEN" und "CLOSED" als String.

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/54929714/33081bf3-01b5-4edf-877b-4aba65a10de4)

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/54929714/d746c276-abc2-4ade-8eed-c03028112059)

Daher wäre mein Wunsch den Wertevorrat um die zwei Werte für die Fensterkontakte zu erweitern.
wäre das möglich ?

Vielen Dank

**Comment by simatec** [comment]
Du kannst dir Kontakte als Alias anlegen und somit die Werte anpassen

**Comment by Scotty-89** [comment]
Was genau meinst du ? 
im Adapter oder separate datenpunkte die ich wieder über ein Skript „spiegeln“ muss ?

**Comment by simatec** [comment]
Du musst kein Skript verwenden. Man kann im iobroker Aliase anlegen und diese frei konfigurieren
