### ISSUE TITLE
Wert aus Schoolfree Adapter wird nicht korrekt übernommen

### ISSUE THREAD

**Issue by Octopyrox** [simatec/ioBroker.shuttercontrol#630]
**Describe the bug**  
Im Menü "Extra-Einstellungen -> Schulferien-Einstellungen" ist "Schollfree Adapter verwenden" markiert und die korrekte Instanz (schoolfree.0) gewählt. Der Datenpunkt schoolfree.0.info.today ist false, trotzdem fahren die Rollläden zu Zeiten wie für Wochenende eingestellt. Automatiksteuerung ist zeitabhängig. Hinweis: Der Datenpunkt shuttercontrol.0.control.schoolfree steht auf true.  

**To Reproduce**  
1. Im Menü "Extra-Einstellungen -> Schulferien-Einstellungen" den "Schollfree Adapter verwenden" markieren, korrekte Instanz (schoolfree.0) wählen.
2. Warten bis der Schollfree Adapter, vermutlich bei Datenpunkt schoolfree.0.info.today true wird.
3. Datenpunkt shuttercontrol.0.control.schoolfree bleibt false 

**Expected behavior**  
Status des Datenpunktes shuttercontrol.0.control.schoolfree aktualisiert sich analog schoolfree.0.info.today.
Bei true -> Rollläden fahren laut Wochenendeinstellungen
Bei false -> Rollläden fahren laut Werktagseinstellungen

**Versions:**  
 - Adapter version: 1.6.1
 - JS-Controller version: 4.0.24
 - Node version: 18.6.0
 - Operating system: Rasp

**Comment by simatec** [comment]
Der Datenpunkt shuttercontrol.0.control.schoolfree ist für User, die dies manuell nutzen wollen und nicht den Schoolfree Adapter verwenden. Stelle den Datenpunkt auf false, wenn du nur den Adapter verwenden möchtest.

**Comment by Octopyrox** [comment]
Ach so, ok. Sorry! Das hab ich dann wohl missverstanden. Durch den manuellen Eingriff hab ich die Info vom Schoolfree Adapter also überschrieben.

Ich probier's gleich aus.

Vielen Dank für die schnelle Antwort!!
