### ISSUE TITLE
Frage: Schließen der Rolladen

### ISSUE THREAD

**Issue by janzev** [simatec/ioBroker.shuttercontrol#633]
Ich habe eine Verständnisfrage zu der Einstellung (Zeit-Einstellungen) "Schließen der Rollläden in der Arbeitswoche" bzw. "Schließen der Rollläden am Wochenende". 

In der Adapter-Dokumentation wird diese Einstellung mit "Übliche Zeit für die Verdunklung" beschrieben. Wenn ich nun aber in die Objekte schaue, steht die "DownTimeLiving" nicht auf der "üblichen Zeit" sondern auf der Zeit des Sonnenuntergang (+ eingestellter Verzögerung). Ist es möglich hier auch einen Zeitbereich wie beim Öffnen der Rolladen einzustellen? Oder ist es möglich hier eine feste Uhrzeit nur für das Schließen der Rolladen festzulegen? Wie ist hier die Logik des Adapters zur Berechnung der Zeit?

**Comment by simatec** [comment]
Schaue mal dazu bitte in die Doku. Auch das Forum ist ein guter Anlaufpunkt für solche Fragen.
Ein Issue ist eher nicht dafür geeignet... Danke für dein Verständnis
