### ISSUE TITLE
Öffnen / Schliessen mit Helligkeitssensor

### ISSUE THREAD

**Issue by EinfachNurKlaus** [simatec/ioBroker.shuttercontrol#649]
Vielleicht nur eine Verständnisfrage. 
Mit der Definiton der frühsten Öffnen- und Schliessenzeit wäre meine Erwartungshaltung:
Öffnen: auch wenn früher die Helligkeit schon überschritten, warte bis Zeit x, öffne dann: klappt bestens!
Schliessen: auch wenn früher schon Helligkeit unterschritten, warte bis Zeit y, schliesse dann: Tut es aber nicht, sondern schliesst erst mit dem globalen "Alles Schliessen"-Event

Hab ich einen Denkfehler oder gibt es hier ein Problem?

Adapter und Umgebung sind auf aktuellem Stand heute (stable)
Weitere Infos natürlich gern, wenn erforderlich.

Danke an dieser Stelle für dieses gelungene Stück Software.

**Comment by simatec** [comment]
Bitte poste deinen Debuglog von Shuttercontrol und die Config als JSON.
Schreibe bitte dazu, um welchen Rollladen es sich handelt

**Comment by EinfachNurKlaus** [comment]
Hallo, hier die gewünschten Daten. Betrifft alle Rallläden im EG. Lief jetzt drei Tage auf Protokollstufe Debug. Vielen Dank schon mal.

[Log_und_Konfig.zip](https://github.com/simatec/ioBroker.shuttercontrol/files/12842978/Log_und_Konfig.zip)

**Comment by EinfachNurKlaus** [comment]
ok, nachvollziehbar, ist dann aber immer noch 5MB, hoffe das geht durch
[iobroker.2023-10-08.log](https://github.com/simatec/ioBroker.shuttercontrol/files/12846310/iobroker.2023-10-08.log)

die konfig nenne ich mal in txt um, json nimmt er nicht 
[system.adapter.shuttercontrol.0.json.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/12846333/system.adapter.shuttercontrol.0.json.txt)

Grüße

**Comment by simatec** [comment]
Shuttercontrol reagiert auf Änderungen des Lichtsensors.
Dein Lichtsensor hat laut Log das letzte mal um 18:48 eine Änderung gehabt.
Da deine Zeit auf nach 20 Uhr eingestellt ist, und der Sensor nach 20 Uhr keine Änderung mehr hatte, fuhren auch die Rollläden nicht.

`2023-10-08 18:48:01.955  - [34mdebug[39m: shuttercontrol.0 (5524) Lightsensor changed: openknx.0.08_Externe_Daten.Wetter.Helligkeit Value: 4`

**Comment by EinfachNurKlaus** [comment]
Das wars, vielen Dank. Das Umstellen auf senden periodischer Daten auch ohne Änderung hat es gelöst. Rollläden fuhren zum gewünschten Zeitpunkt.
