### ISSUE TITLE
Sperrzeit zum Schließen der Rolladen

### ISSUE THREAD

**Issue by houselightguy** [simatec/ioBroker.shuttercontrol#650]
Ich bin ziemlich begeistert von dem Adapter und nutze diesen auch seid einiger Zeit. 
Es gibt allerdings eine Sache die für mich sehr praktisch wäre. 
Undzwar lasse ich die Rolladen in Abhängigkeit von Sonnenauf- und untergang fahren. Allerdings kommen wir jetzt so langsam in einen Zeitraum in der mir diese zu früh runterfahren. 
Wäre es möglch die Zeiteinstellung für das herunterfahren um die frühst und spät möglichste Zeit zu erweitern? so wie beim Hochfahren.

**Comment by simatec** [comment]
Für das herunterfahren wird automatisch der Sonnenuntergang berücksichtigt... Sollte es vor der eingestellten Zeit also schon dunkel werden, fahren die Rollläden mit erreichen des Sonnenuntergangs zu.
Eine Range wie beim hochfahren ist nicht geplant, da es in der Funktion auch eine andere Bedeutung hat

**Comment by houselightguy** [comment]
Habe ich den eine andere Möglichkeit das zu realisieren? Im Moment sehe ich das nur das ich im Frühjahr auf Sonnenauf- und untergang einzustellen und im Herbst auf feste Zeiten umzustellen. Vielleicht könnte man einplanen diese Funktion hinzuzufügen :-)

**Comment by Skol6** [comment]
Du kannst in den Extra-Einstellungen unter Astro-Einstellungen Verzögerungen erstellen und dir dort die gewünschten Minuten definieren, die erst nach Sonnenuntergang gefahren werden soll.

**Comment by fkieling** [comment]
@Skol6 Nur leider ist des ein statischer Wert, der nur manuell gesetzt werden kann. Flexibler und hilfreicher wäre es, wie @houselightguy es sich wünscht. Wenn ich möchte, daß mein Rollladen in Abhängigkeit des Sonnunterganges herunterfährt, dies aber nicht vor z.B. 21:00 geschehen soll, muß ich in der dunklen Jahreszeit die Verzögerung mehrfach manuell anpassen. 
Deswegen wäre es super, wenn es eine Möglichkeit gäbe, den frühesten Zeitpunkt für das Herunterfahren definieren könnte. Also genau, wie es beim Hochfahren auch möglich ist. Ich würde mich auch über diese Möglichkeit freuen.

**Comment by simatec** [comment]
Ich sehe deinen Wunsch eher am Thema "nach Sonnenuntergang fahren" vorbei.
Auf der einen Seite willst du, dass die Rollläden nach Sonnenuntergang schließen, dann aber doch nicht. Es ergibt nicht so richtig Sinn. Wenn im Winter die Rollläden schließen, ist es draußen bereits dunkel. Warum sollten diese dann bis 21 Uhr geöffnet bleiben.

Du kannst das schon umsetzen, aber halt nicht ohne selber je nach Jahreszeit anzupassen.
Shuttercontrol bietet dir hier einige Möglichkeiten, aber so eine Konstellation wird nicht unterstützt.

**Comment by fkieling** [comment]
Hi @simatec. Es macht durchaus Sinn. Ein Beispiel:
* Der Rollladen soll zw. 21:00 und 22:30 herunterfahren
* dies soll er in Abhängigkeit vom Sonnenuntergang machen
* im Sommer kein Problem
* im Winter erfolgt der Sonnenuntergang zwar früher, aber trotzdem möchte ich den Rollladen nicht vor 21:00 herunterfahren. Aonsonsten würde er teilweise schon 18:00 oder früher unten sein.
* Weshalb soll der Rollladen trotzdem erst 21:00 herunterfahren? Fährt er bereits früher (18:00, 17:00, ...) hinterläßt dies schnell ein Gefühl des abgeschottet seins. Also durchaus sinnvoll.

Wenn ich einen guten Adapter habe möchte ich nicht mehrfach im Jahr eine solche Kleinigkeit anpassen müssen. Daher kommt der Wunsch von @houselightguy und mir :)

Ich habe inzwischn versucht, den Wert für das zeitverzögerte Fahren per Script anzupassen. Leider ist dieser Wert nicht über die Objekteigenschaften zu erreichen :S
