### ISSUE TITLE
Steuerung Tür/Fensterkontakt - Fahren nach Kippen / Schließen

### ISSUE THREAD

**Issue by Skol6** [simatec/ioBroker.shuttercontrol#651]
Hallo Zusammen,

Hab es endlich geschafft Shuttercontrol zum laufen zu bringen und bin erstmals begeistert.
Die Lamellensteuerung für Homematic lässt sich mit dem Script  [https://github.com/Schmakus/ioBroker-SetShutterLevel-HomematicIP](url) umgehen.

Aber mir ist folgendes Verhalten aufgefallen:
- Fenster/Tür offen: Fenstersensor erkennt das Fenster offen ist und fährt den Zustand offen an: Perfekt, ich will ja rausgehen
- Fenster/Tür wieder geschlossen: Wird vom Sensor erkannt, und Shuttercontrol fährt den Status für geschlossen an

Wie kann man das Einstellen das Shuttercontrol nur auf "Geschlossen" geht, wenn auch die anderen Bedingungen (z.b. Sonnenstand, Elevation, Nacht, ...) entsprechend ein Schließen des Sonnenschutzes auslösen.
Es werden nach jedem Schließen die Raffstores geschlossen!

Ist das ein Bug oder Feature Request oder RTFM?
Grüße, Skol

**Comment by Skol6** [comment]
Mhmm. schaut aus das es manchmal klappt. Hab aber nicht herausgefunden wann :(

**Comment by simatec** [comment]
Das sind alles eher Fragen für das Forum... Dort gibt es einen Thread, wo Funktionen diskutiert werden und dir erfahrende User helfen, die perfekten Einstellungen für deine Bedürfnisse zu finden.

**Comment by Skol6** [comment]
Wo finde ich das?

**Comment by simatec** [comment]
https://forum.iobroker.net/
