### ISSUE TITLE
Shuttercontrol für KNX Betrieb ermöglichen

### ISSUE THREAD

**Issue by FoxRo** [simatec/ioBroker.shuttercontrol#67]
Hallo Simatec
Damit es nicht vergessen geht, eröffne ich mal ein Issue betr. dem Problem, dass Shuttercontrol im Moment mit KNX nicht kombiniert werden kann.
https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v0-6-x/1892
wie beschrieben, werden im KNX Umfeld normalerweise Bereiche von 0-255 verwendet wobei 0 = Oben und 255 = Unten ist.
Teilweise funktioniert Shuttercontrol schon (Zeitsteuerung) wenn man die Werte einfach anders herum vorgibt. Die Türkontakt Überwachung kann damit aber nicht umgehen.
Evtl gibts eine Möglichkeit, fix die vorgegebenen Werte auf die definierten Kommunikationsobjekte zu senden, dann spielt es keine Rolle mehr wie das anzusprechende System tickt.
Danke vielmals!
Viele Grüsse, Roli

**Comment by JensOBreuer** [comment]
Bei mir funktioniert in diesem Kontext auch der Sonnenschutz nicht - lediglich die Rolladenzeitsteuerung funktioniert. Wäre super, wenn es hier eine Lösung gäbe.
Viele Dank und beste Grüße,

Jens

**Comment by greatluis** [comment]
Also ich benutze für die Kompatibilität mit KNX die Alias-Funktion. Damit lässt sich einfach der Wertebereich anpassen. Ich habe damit bei mir den Wertebereich  0-100 invertiert. War damals auch für iqontrol nötig, mittlerweile jedoch nich mehr. Ist zwar einmalig ein Aufwand jedoch für viele Fälle hilfreich (IOT-Adapter,etc )
![Anmerkung 2020-06-22 184827](https://user-images.githubusercontent.com/13763822/85314900-6d5dc500-b4ba-11ea-87ba-97b7c9a14ab2.png)

**Comment by FoxRo** [comment]
habe mal als erstes den Bereich vom Trigger angeschaut und eine Änderung in meinem Fork https://github.com/FoxRo/ioBroker.shuttercontrol/pull/1 gemacht.
Die Änderung funktioniert bei mir soweit einwandfrei.
@simatec : ich habe den mal als Pull Request eingestellt, hoffe Du kannst das sehen. Bitte prüfen, ob meine Änderungen mit der Standardlogik nach wie vor kompatibel sind. Danke.
Das mit dem Sonnenschutz werde ich mir in den nächsten Tagen mal anschauen - den Code kenne ich unterdessen ja ein wenig :-)
Viele Grüsse, Roli

**Comment by FoxRo** [comment]
Es hat mir keine Ruhe gelassen und hatte noch eine Idee, wie ich auch den Teil vom SunProtect einigermassen korrekt abfragen kann. Habe dazu den Patch2 https://github.com/FoxRo/ioBroker.shuttercontrol/tree/FoxRo-patch-2 erstellt.
@simatec : habe dazu einen Pull2 als weiteren Patch erstellt und dabei auch die alte Logik vom Trigger wieder hergestellt.
Könnt ihr euch das bitte mal anschauen und wenn möglich testen?
Ich habe die SunProtect bei mir noch nicht in Betrieb, deshalb ist testen bei mir aktuell noch nicht möglich.
Viele Grüsse, Roli

**Comment by FoxRo** [comment]
Hi Simatec
War auch erstaunt, an wie vielen Stellen schon heute im Code ausgewertet wird, wo genau der Rollladen steht, und wieviele Bedingungen da abgefragt werden, bevor ein Rollladen fährt. Meine Erweiterungen sind sicher nicht mit der "Feder" eines hochkarätigen Programmierers gemacht worden. Gebe auch zu, dass ich kein professioneller Programmierer bin und Java schon gar nicht zu meinen stärken gehört. ;-)
Zur Verteidigung, die Abfrage rund um den Trigger habe ich im PR2 zurück gebaut so, dass die Logik auch für die anderen Systeme wieder gleich bleibt und keine Funktion verloren geht. 
Wenn Du eine bessere Idee hast, wie diese Unterscheidung eingebaut werden kann, um so besser, dann macht dies nämlich ein Profi. 
Adapter spezifische Aliases zu erzeugen, finde ich auch nicht so "prickelnd", denn es macht die Übersicht über das Gesamtsystem leider auch nicht einfacher.
Du kannst also meine PR's gerne ablehnen und Deine eigene Idee einbauen. Bis es soweit ist, habe ich mit meinem Fork zumindest eine Möglichkeit, den Shuttercontrol nun auch für meine Umgebung zu nutzen - und dafür bin ich schon jetzt sehr dankbar, denn der Shuttercontrol finde ich sehr cool!
Danke für Deine Arbeit!
Viele Grüsse, Roli

**Comment by simatec** [comment]
Alles gut und ich danke dir für deine Mühe. Allerdings sind die PR‘s auch nur in deinem Fork und nicht in meinem Branch

**Comment by FoxRo** [comment]
Hallo Simatec
Sieht danach aus, dass auch Deine Idee nicht funktioniert hat. Schade, dass dieses Feature zur breiteren Unterstützung von verschiedenen Automatisierungssystemen nun wohl nicht kommen wird. 
Falls Du meinen PR2 doch noch haben möchtest, lass es mich wissen, dann stelle ich diesen Dir noch rein.
Ansonsten bleibt mir an dieser Stelle wohl nur noch der "Tod" mit Alias oder Fork.
viele Grüsse, Roli
