### ISSUE TITLE
Does not close at x o'clock despite the set time at sunset

### ISSUE THREAD

**Issue by CKMartens** [simatec/ioBroker.shuttercontrol#671]
Hello,

Would it be possible to set the blinds to close at sunset and also add an option so that they do NOT close before x o'clock.

Specifically: I want to close my blinds in the living room at sunset. But in winter, despite the early sunset, it should not close before 8 p.m

**Comment by simatec** [comment]
You can solve this using the "Close later" option.
Please read the [documentation](https://github.com/simatec/ioBroker.shuttercontrol/wiki/Shuttercontrol-Wiki-Deutsch#sonderzeiten). The function is described there.
