### ISSUE TITLE
Wertebereich für Lichtsensor

### ISSUE THREAD

**Issue by frostnatt** [simatec/ioBroker.shuttercontrol#68]
Hallo Simatec,

wäre es möglich, eine Beschränkung des Wertebereichs für Lichtsensor (0 - 5000) zu erweitern bzw. aufzugeben?
Ich habe einen Lichsensor, welcher auch 6 Stellige LUX-Werte liefern kann. Wenn ich einen größeren Schwellwert als 5000 eintrage, wird bei Überschreitung von 5000 gefahren. Die Hysterese-Prozentangabe bezieht sich in diesem Fall auch auf 5000 und nicht auf den angegebenen Wert.

Viele Grüße

**Comment by simatec** [comment]
gefixt in Release 0.7.0
