### ISSUE TITLE
Swap Open/Close

### ISSUE THREAD

**Issue by MarcK26** [simatec/ioBroker.shuttercontrol#683]
Hi, 
is it possible to swap the Open/close command somewhere?
I get the current position "100" via KNX when the shutters are down.
If the shutters are up, the position is "0".

If I now click on "Close" in ShutterControl, the shutters move up.

Would it be possible to offer an Open/Close swap here?

**Comment by SMHRambo** [comment]
You can swap the value for the up and down position inside the shutters of shuttercontrol.

**Comment by MarcK26** [comment]
Hi @SMHRambo thanks, can you show me where I can find it? 
Thank you!

**Comment by SMHRambo** [comment]
https://github.com/simatec/ioBroker.shuttercontrol/blob/master/docs/en/shuttercontrol.md

ShutterControl->TAB MAIN SETTINGS->EDIT SHUTTER->TAB MAIN SETTINGS

Roller shutter height when moving down: Position value when the roller shutter is closed.
Roller shutter height when raised: Position value when roller shutter is open.

![shuttercontrol](https://github.com/simatec/ioBroker.shuttercontrol/assets/1950165/eaf16ea8-cc0d-49be-abc9-f0da3687558c)

**Comment by simatec** [comment]
done
