### ISSUE TITLE
Problem seit ca. einer Woche - Rollladen fahren plötzlich wieder hoch

### ISSUE THREAD

**Issue by crusader85** [simatec/ioBroker.shuttercontrol#684]
**Describe the bug**  
Rollladen werden mit Helligkeitssensoren gesteuert. Fahren pünktlich runter. Aber, obwohl Sensor auf 0 irgendwann später wieder hoch. 

**Expected behavior**  
unten bleiben wie bisher bis zum nächsten Morgen

**Versions:**  
 - iobroker komplett aktuell (inkl. Nodejs, etc. )
 - Operating system: Ubuntu 22 LTS

**Comment by simatec** [comment]
Bitte den Debuglog posten
