### ISSUE TITLE
Dynamische Weihnachtszeit über Datenpunkt

### ISSUE THREAD

**Issue by Spezialtrick** [simatec/ioBroker.shuttercontrol#685]
Danke, für den hervorragenden Adapter, @simatec!

Ist es möglich den Zeitraum der Weihnachtszeit mit eigenen Datenpunkten zu steuern? Also wie hier:

![Bildschirmfoto 2023-12-10 um 22 25 20](https://github.com/simatec/ioBroker.shuttercontrol/assets/7795075/983081d7-8203-4ede-ac23-8b2d7fdb0564)

**Comment by simatec** [comment]
Nein das ist nicht möglich und auch nicht geplant... Die Weihnachtszeit ist ja eigentlich jedes Jahr zur selben Zeit ... :)
