### ISSUE TITLE
Frostalarm übersteuert auto-down flag

### ISSUE THREAD

**Issue by wg25** [simatec/ioBroker.shuttercontrol#686]
**Describe the bug**  
Sonnengesteuerte Rollläden, die auf AutoDown=false stehen, dem Frost-Alarm folgen und spät schließen sollen, werden nach einem Aktualisieren des Frost-Alarm flags und nach der Down-Zeit trotzdem runtergefahren, nicht erst zur spät schließen Zeit.

**To Reproduce**  
1. AutoDown = false, Frostalarm aktivieren, spät schließen aktivieren
2. Frostalarm Flag aktualisieren vor der spät schließen Zeit
3. Rollladen fährt runter

**Expected behavior**  
Rollladen sollte erst zur spät schließen Zeit runterfahren und dann in die Frostposition (bei Frost)

**Screenshots & Logfiles**  
[shutter.log](https://github.com/simatec/ioBroker.shuttercontrol/files/13688784/shutter.log)

**Versions:**  
 - Adapter version: v1.6.3

**Comment by simatec** [comment]
Fix in v.1.7.0
