### ISSUE TITLE
Frost Alarm funktioniert nur bei 6 von 10 konfigurierten Rolläden

### ISSUE THREAD

**Issue by jayjayM74** [simatec/ioBroker.shuttercontrol#695]
**Describe the bug**  

- Der Frost Alarm funktioniert nur bei 6 von 10 Rollläden trotz jeweils identischem Status/Setup
- Bei allen 10 Rollläden ist das Frost Alarm Flag gesetzt
- Alle 10 Rollläden sind ebenfalls für automatisches Öffnen bzw. Schiessen konfiguriert
- Das automatische Öffnen und Schliessen funktioniert ohne Probleme
- Wenn abends alle Rollläden auf down stehen und das Frost Flag auf true gesetzt wird, fahren immer die gleichen 6 Rollläden auf (die konfigurierten) 23 Prozent (Frost-Modus). Die 4 restlichen Rollläden bleiben auf down / 0 Prozent und bewegen sich nicht

**To Reproduce**  
1. Generelle Höhe für Frost Alarm auf 23 setzen
2. Datenpunkt für Frost Flag einrichten und im Shuttercontroller setzen
3. Das Frost Alarm Flag bei allen Rollläden setzen
4. Bis zum nächsten Tag abends warten, bis alle Rollläden planmässig auf down stehen
5. Datenpunkt des Frost Flag auf true setzen

**Expected behavior**  
Alle Rollläden fahren auf 23 Prozent

**Versions:**  
 - Adapter version: 1.6.3
 - JS-Controller version: 5.0.12
 - Node version: 18.18.2
 - Operating system: linux

**Comment by dustnppunkt** [comment]
Selber Fehler bei mir.

Adapter version: 1.6.3
JS-Controller version: 5.0.16
Node version: 18.18.2
OS: Raspberry Pi OS

**Comment by jayjayM74** [comment]
Neueste Erkenntnis:
- Wenn das Frost Flag bereits vor Erreichen des abendlichen, automatischen Herunterfahrens (nach Sonnenstand) der Rollläden auf TRUE steht, werden alle Rollläden ordnungsgemäss nur auf 23% heruntergefahren
- Wenn in diesem Fall anschliessend das Frost Flag manuell auf FALSE gesetzt wird, fahren alle Rollläden ganz zu
- Wenn anschiessend das Frost Flag auf TRUE gesetzt wird, tritt der Fehler wieder auf und es fahren nur 6 von 10 Rollläden auf 23%. Die restlichen 4 Rollläden bleiben zu

**Comment by jayjayM74** [comment]
Weitere, neue Erkenntnis:
- das Frost Flag steht seit gestern Abend auf TRUE
- heute Vormittag wurden alle Rollläden automatisch bzw. manuell hochgefahren
- gerade eben, 14:48, stieg die Aussentemperatur auf >0 Grad, das Frost Flag wurde per Skript auf FALSE gesetzt. Daraufhin wurden 6 unserer 10 Rollläden von 100% Öffnungsgrad auf 0% Öffnungsgrad gesetzt und sind zugefahren
Logfileeintrag: 
shuttercontrol.0 2024-01-19 14:48:20.579	info	Alarm frost ended Set ID: Jannik_links value: 0%

**Comment by simatec** [comment]
Bitte den Debuglog des Vorgangs posten...

**Comment by jayjayM74** [comment]
Anbei das Debuglog des Vorgangs [Shuttercontrol_log_debug_20240312.log](https://github.com/simatec/ioBroker.shuttercontrol/files/14568848/Shuttercontrol_log_debug_20240312.log).

**Beispiel**
- Rolladen bei dem das Hochfahren bei Frostalarm **korrekt** funktioniert: SHSW-25#3494547A9D9F (Jannik_links)
- Rolladen bei dem das Hochfahren bei Frostalarm **nicht** funktioniert: SHSW-25#40F52004A194 (Jannik_rechts)

**Comment by simatec** [comment]
Kannst du bitte die Config als JSON posten?
Ich kann das Verhalten nicht nachstellen.

**Comment by simatec** [comment]
Geschlossen, da keine Infos kamen....
