### ISSUE TITLE
Sonnenschutzsteuerung NUR nach Helligkeitswert + FALSE Funktion/Kriterium

### ISSUE THREAD

**Issue by Toysman** [simatec/ioBroker.shuttercontrol#697]
**Is your feature request related to a problem? Please describe.**
1 - ja und nein - eine Steuerung nur nach Helligkeitswert ist nicht möglich
2 - es sollte eine FALSE Option geben, die die Sonnenschutzfunktion verhindert

**Describe the solution you'd like**
1 - Parameter - "nach Helligkeitssteuerung"
2 - Parameter - wenn Helligkeit > Wert UND Kontakt = TRUE dann nicht ausführen bzw. wenn Helligkeit > Wert UND KOntakt = FALSE dann ausführen 

**Describe alternatives you've considered**
zusätzliche Schaltungen via Blockly

**Additional context**
zu 2: Beispiel falls eine Markiese vorhanden ist, wenn diese ausgefahren ist, dann keine Beschattungsfunktion

**Comment by simatec** [comment]
> **Is your feature request related to a problem? Please describe.** 1 - ja und nein - eine Steuerung nur nach Helligkeitswert ist nicht möglich 2 - es sollte eine FALSE Option geben, die die Sonnenschutzfunktion verhindert
> 

Das ist bereits möglich... jeder Rollladen kann für den Sonnenschutz aktiviert oder deaktiviert werden.

> **Describe the solution you'd like** 1 - Parameter - "nach Helligkeitssteuerung" 2 - Parameter - wenn Helligkeit > Wert UND Kontakt = TRUE dann nicht ausführen bzw. wenn Helligkeit > Wert UND KOntakt = FALSE dann ausführen
> 
Dein Extrawunsch musst du dann über ein Script lösen und damit den state `shuttercontrol.0.shutters.autoSun.XXXXX` setzen

> **Describe alternatives you've considered** zusätzliche Schaltungen via Blockly
> 
> **Additional context** zu 2: Beispiel falls eine Markiese vorhanden ist, wenn diese ausgefahren ist, dann keine Beschattungsfunktion

Shuttercontrol deckt bereits extrem viel ab, kann aber nicht jeden Userwunsch erfüllen. Es sollte für alle noch bedienbar bleiben.
Von daher müsstest du deine Wünsche mit Javascript lösen und über den Script die States von Shuttercontrol setzen.
Bitte lies dir auch die [Doku](https://github.com/simatec/ioBroker.shuttercontrol/wiki/Shuttercontrol-Wiki-Deutsch) durch.
