### ISSUE TITLE
Zusätzliche Einstellungen

### ISSUE THREAD

**Issue by MUD215** [simatec/ioBroker.shuttercontrol#698]
Hallo

Daumen hoch für das Projekt und die viele Arbeit. Das war mir jetzt eine Donation wert, unabhängig von der Umsetzung der folgenden Anfragen:

1. Könnten weitere Kriterien für das Öffnen und Schließen der Rollläden per Helligkeitssensor vorgesehen werden? Genauer geht es um die Festlegung der frühesten Bewegungszeiten. Da gibt es derzeit jeweils eine zum Öffnen und eine zum Schließen. Schön wäre eine weitere Einschränkung für z. B. Wochenende oder Urlaub.

2. Könnten die Funktionen zur "Weihnachtszeit" um den Punkt erweitert werden, dass auch am Morgen die Rollläden erst einmal in eine Zwischenposition fahren und später komplett öffnen?

Danke

**Comment by simatec** [comment]
Shuttercontrol deckt bereits sehr viele Funktionen ab und bietet somit extrem viele Möglichkeiten.
Leider kann nicht jeder Userwunsch umgesetzt werden.
In deinem Fall wäre es am Sinnvollsten, wenn du deine Wünsche über ein Script löst.

Bitte lies dir dazu auch die [Doku](https://github.com/simatec/ioBroker.shuttercontrol/wiki/Shuttercontrol-Wiki-Deutsch) von Shuttercontrol durch.

**Comment by MUD215** [comment]
Hallo,

deine Antwort gerade erst gelesen.
Ich werde mich daran versuchen.

Danke
