### ISSUE TITLE
Zeitverschiebung nicht Global, sondern auch auf einzelne Aktoren 

### ISSUE THREAD

**Issue by Koehleke** [simatec/ioBroker.shuttercontrol#699]
Unter extra -> Astro kann eine Verschiebung global für herunterfahren und hochfahren eingestellt werden. Dies hat leider auch Auswirkung auf die Einstellung im Rolladen wenn man klassisch Sonnenuntergang auswählt. Eine lokale Einstellung im Rolladen für die Zeitverschiebung herunterfahren oder hochfahren wäre schön

**Comment by simatec** [comment]
Das ist vom Konzept des Adapters so leider nicht möglich und nicht geplant.
