### ISSUE TITLE
Rollladen nicht fahren bei aktivem Sonnenschutz

### ISSUE THREAD

**Issue by watcherkb** [simatec/ioBroker.shuttercontrol#70]
Morgens soll die Rolllade um 8.00Uhr für Wohnbereich öffnen. An dem Fenster ist der Sonnenschutz zu dem Zeitpunkt aber bereits gültig. Trotzdem fährt die Rolllade hoch und kurze Zeit später wieder auf die Sonnenschutzposition. Besser wäre es wenn die Rolllade sich garnicht erst bewegt, weil Sonnenschutz aktiv ist.

**Comment by 5G7K** [comment]
Du hast Sonnenschutz-Höhe = Höhe geschlossen?
Ich habe das Szenario aktiv mit Sonnenschutzhöhe = 30%. Das funktioniert hier so. Rollladen öffnet direkt auf 30%.
Probiere das doch mal zum Testen aus.

Wenn du MANUELL öffnest, DANN fährt der Rollladen nach kurzer Zeit automatisch wieder in den Sonnenschutz.

Wenn das Problem immer noch besteht, dann bitte Debug Log des Hochfahrens und Einstellungen posten

**Comment by 5G7K** [comment]
Kann es sein, dass du folgenden Bug meinst:
-Rollladen geschlossen
-Sonnenschutz  ist von den Werten her bereits aktiv
-Rollladen wird manuell geöffnet und fährt danach in den Sonnenschutz
-Wenn nun die Zeit-automatik danach startet, wird der Rollladen trotzdem hochgefahren und fährt später erneut in den Sonnenschutz. Eigentlich sollte hier nichts mehr passieren.

Das konnte ich so reproduzieren. Fix ist erstellt und bei mir im Test. Wenn ok, dann gebe ich den frei

**Comment by watcherkb** [comment]
Hi. Ich werde dir konkret morgen die Logs zur Verfügung stellen, weil ich das heute nicht mehr nachvollziehen konnte wer wann geöffnet hat.

zu deinem letzten Fall: bis auf den Punkt 3 (Rolladen wird manuell gefahren) ist die Beschreibung so korrekt. Manuell habe ich den Rollladen nicht gefahren soweit ich mich erinnern kann.

**Comment by simatec** [comment]
sollte mit Version 0.7.3 gefixt sein
