### ISSUE TITLE
Rolladen in Zwischenposition schliessen nicht

### ISSUE THREAD

**Issue by Brakelmann** [simatec/ioBroker.shuttercontrol#706]
**Describe the bug**  
"Alle Rollläden in der Zwischenposition vollständig schließen" wir nicht ausgeführt.

**To Reproduce**  
Ich habe einige Rolladen konfiguriert, die die Option "In Zwischenposition fahren und später komplett schließen" zu nutzen.
Die Rolladen fahren auch in die Zwischenposition, werden aber später nicht geschlossen.

**Expected behavior**  
Die Rolladen sollten zu der Konfigurierten Zeit ganz schliessen.

**Screenshots & Logfiles**  
<img width="1238" alt="Bildschirmfoto 2024-02-11 um 20 38 59" src="https://github.com/simatec/ioBroker.shuttercontrol/assets/32041481/36f30f64-1dd4-4551-8814-0491bcf48711">

<img width="917" alt="Bildschirmfoto 2024-02-11 um 20 39 28" src="https://github.com/simatec/ioBroker.shuttercontrol/assets/32041481/59f4b211-fb7e-42db-84e9-7acde0a83caa">

starting. Version 1.6.3 in /opt/iobroker/node_modules/iobroker.shuttercontrol, node: v18.19.0, js-controller: 5.0.17

**Versions:**  
 - Adapter version: V 1.6.3
 - JS-Controller version: 5.0.17
 - Node version: V18.19.0
 - Operating system: docker_container 

**Additional context**  
Debug Log File:
[Shuttercontrol_Debug_log.odt](https://github.com/simatec/ioBroker.shuttercontrol/files/14233944/Shuttercontrol_Debug_log.odt)

**Comment by simatec** [comment]
Bitte poste deine Config als JSON File

**Comment by Brakelmann** [comment]
Das sollte die hier sein...
[system.adapter.shuttercontrol.0.json](https://github.com/simatec/ioBroker.shuttercontrol/files/14402753/system.adapter.shuttercontrol.0.json)

**Comment by simatec** [comment]
Deaktiviere mal die Option ... Denke die überschneidet sich...
Des Weiteren versuche mal die Zeit etwas runterzunehmen ... 23.59 könnte eventuell Probleme beim Tageswechsel geben.
23:55 Uhr würde ich mal testen

**Comment by Brakelmann** [comment]
Habe die Einstellungen mal angepasst und werde berichten ob es funktioniert.

**Comment by Brakelmann** [comment]
Die Rolladen werden zur konfigurierten Zeit immer noch nicht ganz geschlossen.
Ich nehme erst mal die Einstellung für Rolladen spät schliessen, um die "halb" gefahrenen Rolladen zu ganz zu schliessen.
