### ISSUE TITLE
Feature Request/Idee: Temporäre Ausnahme für bestimmte Räume

### ISSUE THREAD

**Issue by SvenJ76** [simatec/ioBroker.shuttercontrol#714]
Hallo zusammen,

nur mal  als Idee aus (eigenem) gegebenen Anlass: Ich fände es total praktisch, wenn man für bestimmte Räume die normalen Öffnungs-/Schliesszeiten aussetzen könnte. Anwendungsfall wäre zB wenn Übernachtungsgäste auf der Couch übernachten, soll ja im Wohnzimmer dann nicht morgens der Rollo hochgehen.

VG
Sven

**Comment by MUD215** [comment]
Hallo,

diese Funktion würde ich ebenfalls sehr praktisch finden. Derzeit handhabe ich das über die Einstellungen des Adapters, dort kann man ja einzelne Produkte deaktivieren.

VG
Mathias

**Comment by simatec** [comment]
Das ganze kannst du über eine VIS, Homekit, Alexa oder sonst einer anderen Bedienung machen. Du kannst die jeweiligen States für down, up und sunprotect pro Rollladen aktivieren bzw. deaktivieren. Somit kann man für jeden Rollladen die Automatik ausetzen

**Comment by MUD215** [comment]
Bei Erstellung des Posts noch blind auf beiden Augen gewesen. Mittlerweile habe ich dies so umgesetzt. 
Danke für die Antwort.

Gruß
