### ISSUE TITLE
Feature Request/Idee: Ansteuerung der Rollladen über Relais

### ISSUE THREAD

**Issue by franks06347** [simatec/ioBroker.shuttercontrol#719]
Hallo,
ich habe für meine Rollläden keinen Datenpunkt 0...100 oder 0...255.
Sie sind bei mir über ein Relais-Board mit 8266 angebunden.
Ich habe pro Rollladen 2 Datenpunkte:
hoch on/off
runter on/off

Ist es möglich, shuttercontrol zu erweitern und eine Ansteuerung der Datenpunkte zu ermöglichen?

Vielen Dank.

Viele Grüße
Frank

**Comment by simatec** [comment]
Das Thema hatten wir schon mehrmals... Über Alias kannst du das ohne Probleme lösen.
Lege pro Rollladen einen Alias an und übersetzen On mit 100% und off mit 0%
