### ISSUE TITLE
Helligkeitgesteuerter Sonnenschutz: Sperrzeit fürs Hochfahren

### ISSUE THREAD

**Issue by frostnatt** [simatec/ioBroker.shuttercontrol#72]
Hallo Simatec,
Ich habe Probleme beim hellighkeitsgesteuertem Sonnenschutz. Vorbeiziehnde Wolken sorgen für große Schwankungen des Helligkeitssensors -> Rollos fahren mehrmals rauf und runter. Ich habe die Hysterese vergrößert, konnte das Problem aber nicht ganz beseitigen. Aktuell 
Eine zusätzliche konfigurierbare Sperrzeit fürs Hochfahren würde hier m.M.n. helfen. Das Hysteresefenster kann dann auch kleiner sein.
Eine Mögliche Umsentzung wäre:
1)Unterschreitung des unteren Schwellwerts startet einen timeout (nach dessen Ablauf die Rollos in die Beschattungsposition gefahren werden)
2)Wird der obere Schwellwert vor Timeoutende überschritten -> Timeout wird zurückgesetzt (Rollos bleiben in der Beschattungsposition)
Was meinst du?

**Comment by simatec** [comment]
Wie sind deine Einstellungen denn?
Eventuell regiert dein Sensor zu empfindlich bzw. deine Hysterese ist zu klein

**Comment by frostnatt** [comment]
Die Hysterese liegt bei 60% (bei 70000 Lux Schwellwert für Beschattung) - meines Erachtens mehr als ausreichend. Kurze Enbrüche des Helligkeitswerts, wie unten gezeigt, lassen den Rolladen täglich mehrmals fahren.
![Rollos_Büro](https://user-images.githubusercontent.com/43183391/86173154-d29b6100-bb1f-11ea-81e3-4f7c1c76c1ec.PNG)

**Comment by schadis** [comment]
hatte das gleich Problem mit zu vielen Schwankungen rauf runter trotz Hysterese von 70%.
hab nun über javascript (https://forum.iobroker.net/topic/1037/gleitender-durchschnitt-min-max-%C3%BCber-def-zeitraum/83) mir nen stunden durchschnitt gebastelt jetzt läufts rund

**Comment by frostnatt** [comment]
> 
> 
> hatte das gleich Problem mit zu vielen Schwankungen rauf runter trotz Hysterese von 70%.
> hab nun über javascript (https://forum.iobroker.net/topic/1037/gleitender-durchschnitt-min-max-%C3%BCber-def-zeitraum/83) mir nen stunden durchschnitt gebastelt jetzt läufts rund
Danke für den Hinweis. Ich denke aber, dass dieser Ansatz nur einen Teil des Problems lösen wird. Durch die Bildung des Mittelwerts entsteht eine Zeitverzögerung. Die Rollos fahren in die Sonnenschutzposition nicht sofort (was für mich keine geeignete Lösung ist) sondern erst wenn der Mittelwert größer als der eingestellte Schwellwert ist.

**Comment by schadis** [comment]
ist ja auch nur ne notlösung

**Comment by simatec** [comment]
Bindet noch einen weiteWert wie Hinmelsrichtung und oder Außen / Innentemp mit ein. 
Durch verschiedene Bedingungen könnt ihr viel gezielter den Sonnenschutz aktivieren bzw. deaktivieren
