### ISSUE TITLE
Steuerung Dachfenster bei Wetteralarm

### ISSUE THREAD

**Issue by Skol6** [simatec/ioBroker.shuttercontrol#720]
Hallo Leute,

ich hab eine Frage bzw. ein Problem bei den Wetteralarmen:
- Perfekt funktioniert die Steuerung der Jalousien und der Markise: Wenns regnet oder der Wind bläst, dann gehen sie auf 100% und fahren ein.
- Problem sind meine Dachfenster: deren Zustand bei geschlossen liegen ja bei 0% -> somit gehen sie auf 100% und öffnen sich.

Wie stell ich das so ein das sich die Dachfenster gerade anders herum verhalten?
Check ich das nicht? Ist das ein Bug? Oder ein Feature Request?

Vielen Dank, Skol

**Comment by Skol6** [comment]
keiner eine Idee?

**Comment by simatec** [comment]
Erstelle dir States mit Alias. Da kannst du dann konvertieren. Schaue im Forum, da gibt es etliche Threads dazu.

**Comment by Skol6** [comment]
hi, das mit Alias schaut ganz gut aus.
Ich frag mich aber trotzdem warum das nicht direkt über dein Plug In läuft.
Hier wird ha für jeden Aktor angegeben was offen und was geschlossen ist.

Wenn ich die Werte von Offen und Geschlossen 0 / 100 umdrehe, müsste das doch auch funktionieren?

![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/94216949/6d58a7c9-eae0-44e3-b8bb-a0c2bf7860aa)
