### ISSUE TITLE
Sonnenschutz: Anpassung für Raffstore

### ISSUE THREAD

**Issue by fasal13** [simatec/ioBroker.shuttercontrol#725]
Wäre es möglich gefolgt an das Herunterfahren auf null im Rahmen des Sonnenschutzes eine in Prozent oder Millisekunden angegebene Öffnung folgen zu lassen, damit darüber eine Anpassung der Lamellen erfolgen kann?

**Comment by simatec** [comment]
Eine Unterstützung für Lamellen ist aktuell nicht geplant.
Du kannst es aber mit einem weiteren angelegten Gerät lösen, was dann in der Geräteliste darunter angeordnet wird. 
Mit deiner eingestellten Zeitverzögerung wird dieser dann in die gewünschte Position gefahren.

Oder halt per Script...

**Comment by Hellboy-2010** [comment]
Auch wenn es nicht geplant ist, wollte ich auch mal Interesse bekunden...
