### ISSUE TITLE
Logik bei Fahren geöffnetes Fenster und Helligkeitssensor stimmt nicht

### ISSUE THREAD

**Issue by guitardoc** [simatec/ioBroker.shuttercontrol#727]
Folgende Situation:

Sonnenschutz aktiv, Jalousie unten.
Fenster wird geöffnet, Jalousie fährt hoch
Helligkeit unterschreitet Hysteresewert (Fenster ist noch geöffnet!)
Fenster wird geschlossen, Jalousie fährt runter <- das ist das Problem, denn die Helligkeit ist ja schon unterschritten, da müsste die Jalousie gleich oben bleiben
Nach einer Weile fährt die Jalousie dann hoch

**Comment by simatec** [comment]
Bitte Debuglog vom Vorgang und die Config des betroffenen Rollladens als JSON posten

**Comment by simatec** [comment]
geschlossen aufgrund fehlender Informationen...
