### ISSUE TITLE
Alarm unwetter

### ISSUE THREAD

**Issue by bambi-arch** [simatec/ioBroker.shuttercontrol#728]
Hallo,
besteht die Möglichkeit bei Alarm einen Punkt für Unwetterwarnung aufzunehmen?

Danke im Voraus.

**Comment by simatec** [comment]
Über Wind 1 und Wind 2 sind diese Optionen möglich.
In der Anleitung kannst du schauen, wie die Prioritäten sind...
https://github.com/simatec/ioBroker.shuttercontrol/wiki/Shuttercontrol-Wiki-Deutsch#alarm-einstellung

**Comment by bambi-arch** [comment]
Ok. Hätte etwas ausführlicher meine Idee schreiben sollen.
Ich habe bereits alle Alarmstufen im Einsatz.

Den Wind 1 und Wind 2 habe ich derzeit für meine Markisen im Einsatz. Die eine verträgt 15 km und die andere 25km.
Die Daten wie auch der Regen kommen direkt aus meiner Wetterstation.

Interessant wird es bei Hagel. Da gibt es nicht wirklich einen Sensor. Ist ist erschreckend wie offene Jalousien nach einem Hagel aussehen können. Daher dachte ich an einem zusätzlichen Punkt für Unwetter. Das kann ja dann jeder beliebt mit Skript steuern. Das ist ja jetzt besonders komfortabel mit dem neuen Unwetter-Adapter.

Auch ist es für die Bewohner schwierig zu verstehen, wenn Unwetter nur 1km entfernt ist und alle Markisen und Jalousien noch draussen sind. Dann wird doch das Smarthome wieder in Frage gestellt. Technisch sind die Parameter noch nicht erreicht. Und dann wird doch manuell wieder alles gesteuert.

Ich würde halt schon steuern wollen, bevor die Sensoren es erfassen können und leider nicht in der Lage sind.

Naja, vielleicht kannst du es dir ja nochmals durch den Kopf gehen lassen.
