### ISSUE TITLE
Fahrt aus Sonnenschutz bei Griffänderung auf "Kippen" unterbinden

### ISSUE THREAD

**Issue by MUD215** [simatec/ioBroker.shuttercontrol#729]
Hallo,

eventuell ist es auch ein Einstellungsfehler und die Funktion gibt es so bereits:

Ich möchte die Fahrt eines Rollladens im Sonnenschutz verhindern, wenn ich die Position des Griffes auf "Kippen" verändere.
Aussperrschutz ist aktiv auf "nur Öffnen". 
Weiter ist die Bewegung des Rollladens bei Änderung des Fenster-/Türzustandes aktiv. Das soll auch so sein, da der Bedientaster für den Rollladen etwas entfernt an der Zimmertür installiert ist. Da ist diese Funktion schon sehr hilfreich. Nur ändert sich die Position eben auch bei Stellung auf gekippt. Günstig wäre eine Auswahl, wann eine Fahrt bei Änderung durchgeführt werden soll, man "gekippt" also ausschließen könnte.

Gruß

Mathias

**Comment by simatec** [comment]
So sollte die Einstellung ausschauen
![image](https://github.com/simatec/ioBroker.shuttercontrol/assets/39792461/6353fed5-de9b-4078-9a7d-d0bbe2fe564f)
