### ISSUE TITLE
Feature-request: Add optional groups

### ISSUE THREAD

**Issue by Frischubau** [simatec/ioBroker.shuttercontrol#73]
[english version]
Thanks for the grateful work. The adapter is working fine.
Today I installed roller shutter in the bedroom of mine and at the room of my son.
The next week I want install the next roller shutter in the living room. Now I get a Problem, the times when the roller shutters will shutdown are different than the two groups ("Wohnbereich" and "Schlafbereich"). So I need more groups to collect roller shutters in the different groups and control the roller shutters in other timeframes.
My feature request is to implementade an option to add groups and set the goups for different timeframes and triggers like Wohnbereich/Schlafbereich..

**[Deutsche Version]**
Danke für die Arbeit, die in diesem Adapter steckt. Der Adapter funktioniert einwandfrei. 
Heute habe ich Rollläden in meinem Schlafzimmer und in dem Zimmer meines Sohnes angebracht.
Nächste Woche will ich den nächsten Rolladen im Wohnzimmer anbringen. Nun bekomme ich jedoch das Problem, dass die Rollläden zu verschiedenen Zeiten als die beiden Gruppen schließen soll ( "Wohnbereich" und "Schlafbereich"). So brauche ich nun mehr Gruppen um die Rollläden zusammen zu führen und diese zu anderen Zeiten agieren zu lassen.
Mein Feature-Request ist eine Möglichkeit zu schaffen, dass eigene Gruppen anzulegen sind um diese mit eigenen Zeiten und Auslösern zu versehen wie bei den Gruppen Wohnbereich/Schlafbereich.

**Comment by watcherkb** [comment]
Habe hier auch hin und wieder Bedarf mindestens einer weiteren Gruppe. Alternativ wäre eine Zeitsteuerung per Rolllade auch denkbar.

**Comment by RoberTo1111** [comment]
Danke für die geleistete Arbeit. Der Adapter ist genial. 
Würde mich auch über mehr Gruppen freuen. Am Schönsten, wenn die Gruppenanzahl unbeschränkt wäre. Quasi hinzuzufügen wie die Rollladenobjekte.

**Comment by simatec** [comment]
Ab Version 1.0.1 ist eine weitere Gruppe hinzugekommen.
