### ISSUE TITLE
Rollladen im Sommer nicht "komplett" schließen

### ISSUE THREAD

**Issue by Ghost-Talker** [simatec/ioBroker.shuttercontrol#743]
Hallo.

Vielleicht lässt sich die Funktion "Rollladen im Sommer nicht schließen" so erweitern, dass man einen Wert für die Höhe mit angeben kann. 

Würde hier im Sommer den Rollo gerne nur bis ca. 50% fahren lassen. 
Oder nur gerade so, dass die Löcher des Rollos noch offen sind.

Danke.

**Comment by simatec** [comment]
Lege eine zweite Instanz an, kopiere die Settings dort rein… passe deine gewünschten Höhen an. 
Mit einem Script kannst du dann die „Sommerinstanz“ zur bestimmten Zeit starten und die andere Instanz in der Zeit stoppen
