### ISSUE TITLE
Rollladen fährt aus dem Sonnenschutz (Fehlerhafte Gleichung?)

### ISSUE THREAD

**Issue by Sandweier** [simatec/ioBroker.shuttercontrol#746]
Anbei ein Auszug aus dem Debug.
Rechnerische Gleichung scheint fehlerhaft bei der Temperatur, denn Rolladen fährt aus dem Sonnenschutz und gleich wieder in den Sonnenschutz?
![Screenshot 2024-08-08 101205](https://github.com/user-attachments/assets/03032200-b025-4c58-aded-e2fb7bbad54b)

**Comment by 5G7K** [comment]
Im Log steht nur was geprüft wird.
Vergleich der Temperatur ist falsch ABER der rechte Ausdruck Lichtstärke ist WAHR. Daher fährt der wahrscheinlich aus dem Sonnenschutz? Und direkt wieder rein weil Sonne dann (nach einer Wolke?) wieder >2850 ist? Hysterese zu klein?

**Comment by simatec** [comment]
Wie @5G7K bereits geschrieben hat, ist deine Hysterese zu klein und er fährt bei einer Wolke aus dem Sonnenschutz

**Comment by Sandweier** [comment]
Herzlichen Dank für euer Feedback, hätte da ein Punkt zu eurer Theorie:
Wenn dem so wäre (Hysterese zu klein), warum ist dann die `Verzögerung (da stehen 300min drin) bis Beschattung beendet wird` nicht angesprungen.
So ganz, habt ihr mich noch nicht überzeugt!!!?

Anmerkung:Wir sollten doch mathematsich korrekt  bzgl. Temperaturvergleich arbeiten.Sonst habt ihr immer wieder Rückfragen
Viel Grüße aus dem Schwarzwald

**Comment by simatec** [comment]
Man sieht im Log doch ganz klar, dass die Lichtsenor sich geändert hat. 
Ein Delay ist nicht in der Kette mit drin?
Bitte poste deine Config als json, damit ich sehen kann, welchen Delay du meinst

**Comment by Sandweier** [comment]
[system.adapter.shuttercontrol.0.json](https://github.com/user-attachments/files/16568870/system.adapter.shuttercontrol.0.json)
Eben,das ist mein Punkt.Warum wurde bei 'Rollladen Arbeitszimmer`die Verzögerung `300min` hier nicht aktiv?
Viele Grüße aus dem Schwarzwald

**Comment by Sandweier** [comment]
Gleiches Thema hier nur andere Rolladen Garnituren.warum springt die Verzögerung nicht an, bei kurzzeitigem Wolkenzug.Parametriert ist die Verzögerung und die Aussentemeperatur und der Azimut ist im Ansprechbereich.
Mei
![Screenshot 2024-08-10 113114](https://github.com/user-attachments/assets/150f7462-b03c-4568-9cce-1654d3bfc137)
ne Meinung:Da spukt wohl die Aussentemperatur mathematisch rein?

**Comment by Sandweier** [comment]
Oder: Die Einschaltung der Beschattungsverzögerung dauert zu lange?

**Comment by Sandweier** [comment]
Glaube hab den Bug gefunden!
Genau,wenn das erste Mal die Helligkeit wg. Wolkenzug aus der Hysterese in Richtung Min. geht, fahren alle Rollläden trotz einer parametrierten Beschattungsverzögerung sofort in Position Auf. Also unter keiner Beachtung der parametrierten Beschattungsverzögerung. Nach dem nächsten Sonnenstrahl fahren sie wie gewollt in die Beschattung und auch beim nächsten Wolkenzug in die Verzögerung (Zeit wird getriggert) usw. alles gut.
Also gilt es m.E. dort zu suchen, warum genau beim ersten Mal Helligkeitstrigger der Hysterese, die Rolläden in Richtung auffahren. Möglicherweise wird ja da eine Zelle beim Tagesewechsel falsch vorbesetzt?
Herzliche Grüße aus dem Schwarzwald

**Comment by simatec** [comment]
Bitte vollständige Config als json und den Debuglog vollständig als code hier poste

**Comment by Sandweier** [comment]
Here we go!
[system.adapter.shuttercontrol.0.json](https://github.com/user-attachments/files/16574066/system.adapter.shuttercontrol.0.json)
[shuttercontrol debug10_08_24.txt](https://github.com/user-attachments/files/16574067/shuttercontrol.debug10_08_24.txt)
