### ISSUE TITLE
Feature-Request Trigger für Wohn/Schlafbereich über Datenpunkt

### ISSUE THREAD

**Issue by watcherkb** [simatec/ioBroker.shuttercontrol#75]
Was mir manchmal fehlt ist eine Art Trigger für Wohn/Schlafbereich über Datenpunkt. Manchmal möchte man schon vor dem eigentlichen Zeitpunkt die Rollläden schließen. Sprich die Zeit für hoch oder runterfahren ist noch nicht erfüllt und ich möchte über einen Datenpunkt jede Rolllade schließen/öffnen wie es pro Rolllade konfiguriert ist.
Aktuell behelfe ich mir mit der Alexa, Nachteil hier ist ich muss 2 Systeme pflegen.

**Comment by simatec** [comment]
Ab Version 0.8.0 gibt es Button für das manuelle fahren der Bereiche
