### ISSUE TITLE
Markise: Einfahren bei Wind/Regen

### ISSUE THREAD

**Issue by ph1ppm** [simatec/ioBroker.shuttercontrol#752]
Moin,

ich versuche mich hier seit Tagen an der richtigen Einstellung, kriege es aber nicht hin und benötige Unterstützung:
Wir haben zwei Senkrechtmarkisen aus Stoff vor großen Fenstern und eine herkömmliche Markise für den Sonnenschutz plus zwei Veluxfenster, die für den Moment aber irrelevant sind.

Die drei Elemente sollen anhand des Helligkeitssensors und der Außentemperatur gesteuert werden. Hinzu kommen zwei Alarme für Regen und Wind. Im Grunde sollen immer alle ausgefahren werden, wenn Helligkeit und Temperatur zu hoch sind. Also reiner Sonnenschutz. Bei Regen soll alles einfahren, damit die Stoffe nicht feucht werden.

Die Senkrechtmarkisen sind bei ClosedState = 100% eingefahren (man kann rausgucken).
Die normale, hängende Markise ist bei Position = 100% vollständig geöffnet/ausgefahren.
Also die Werte sind je Typ unterschiedlich.

Ich hab den Adapter neu gestartet ohne Regen, Wind oder Sonneneinstrahlung und das Log beigefügt. Sobald ich ihn starte, fährt die hängende Markise aus (Alarmevent: Regen Ende erkannt), was um diese Uhrzeit eigentlich nicht mehr passieren sollte aufgrund geringer Außentemperatur und fehlender Helligkeit. Die anderen beiden bewegen sich aber gar nicht - obwohl sie sich zumindest, wenn auch falsch, alle identisch bewegen sollten.

[shuttercontrol.log](https://github.com/user-attachments/files/16954958/shuttercontrol.log)
[system.adapter.shuttercontrol.0.json](https://github.com/user-attachments/files/16954959/system.adapter.shuttercontrol.0.json)

Was genau mache ich falsch? Scheinbar funktioniert es ja grundsätzlich auch mit einer Markise, wie ich anderen Issues entnehmen konnte.

Danke vorab

**Comment by ph1ppm** [comment]
//push

**Comment by simatec** [comment]
Meiner Meinung nach macht es Sinn, dass du für die Markisen Aliase anlegst, damit sie einheitliche Werte für offen und geschlossen haben... Dann sollte auch das Thema Alarm funktionieren.
