### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by Skol6** [simatec/ioBroker.shuttercontrol#759]
Hi,

nach dem letzten Update - Version 1.8.2 - bekomme ich folgenden Fehler:
> Cannot read properties of null (reading 'val')
> TypeError: Cannot read properties of null (reading 'val') at /opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:813:126
> unhandled promise rejection: Cannot read properties of null (reading 'val')
> Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

Vor dem Update -  Version 1.7.3 -  lief alles sauber. Habt ihr eine Idee?
Danke!

**Comment by simatec** [comment]
Bitte postet eure Config als JSON File

**Comment by cgajdzik** [comment]
Hatte den gleichen Fehler mit allen Versionen >= 1.8.0. Bin jetzt wieder zurück auf Version 1.7.3, die vor dem Update lief.

**Comment by simatec** [comment]
Mit v1.8.3 ist der Fehler behoben

**Comment by cgajdzik** [comment]
Hi @simatec,

kann bestätigen, dass der Fehler mit v1.8.3 gefixt ist. Danke
