### ISSUE TITLE
Feature-Request: Feiertage/Ferien/Urlaub über Datenpunkt

### ISSUE THREAD

**Issue by watcherkb** [simatec/ioBroker.shuttercontrol#76]
Manchmal möchte man ausschlafen wegen Urlaub/Feiertag oder die Kinder sind wegen Krankheit länger im Bett.
Aktuell ist nur der Adapter "Feiertage" möglich, schöner wäre es einen Datenpunkt auswählen zu können. Z.B. wäre dafür der Schoolfree Adpater besser geeignet, da er Ferientage UND Feiertage auswertet. Alternativ 2 Adapter zulassen, einen für Feiertage und einen weiteren für Ferien.
Ich favorisiere den Datenpunkt, da man ihn selbst steuern und über mehrere Adapter pflegen kann.

**Comment by watcherkb** [comment]
Nachdem ich es geschrieben habe, habe ich gesehen dass man das ja auch über den Datenpunkt shuttercontrol.0.control.Holiday oder unter Extra-Einstellungen "Objekt-ID für das setzen des Urlaubs" steuern kann. Somit wäre mein Feature-Request obsolet.

**Comment by simatec** [comment]
Closed
