### ISSUE TITLE
v1.8.2 - Adapter crash

### ISSUE THREAD

**Issue by Scrounger** [simatec/ioBroker.shuttercontrol#763]
**Describe the bug**  
after updating to v1.8.2 the adapter crash with the attached error message.
I only have configured "Alarm Wind 1 Höhe" and the error message is something with Alarm2
https://github.com/simatec/ioBroker.shuttercontrol/blob/3f7a55bc5390b305f91ee5ac5c16e0afe808d461/lib/shutterAlarm.js#L813

**To Reproduce**  
1. start the adpater
2. wait until it crash

**Expected behavior**  
should not crash ;-)

**Screenshots & Logfiles**  
```
shuttercontrol.0 | 2024-10-21 09:45:02.016 | error | Cannot read properties of null (reading 'val')
-- | -- | -- | --
shuttercontrol.0 | 2024-10-21 09:45:02.016 | error | TypeError: Cannot read properties of null (reading 'val') at /opt/iobroker/node_modules/iobroker.shuttercontrol/lib/shutterAlarm.js:813:126
shuttercontrol.0 | 2024-10-21 09:45:02.016 | error | unhandled promise rejection: Cannot read properties of null (reading 'val')
shuttercontrol.0 | 2024-10-21 09:45:02.015 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
```

![image](https://github.com/user-attachments/assets/5bfa88e0-d21e-46e6-abf4-31d07f7107bb)

**Versions:**  
 - Adapter version: 1.8.2
 - JS-Controller version: 6.0.11
 - Node version: v18.20.4
 - Operating system: ubuntu 22.04 LTS

**Comment by simatec** [comment]
Fix in 1.8.3
