### ISSUE TITLE
Feature Request - Sonnenschutz Zusatzabfrage

### ISSUE THREAD

**Issue by n3roGit** [simatec/ioBroker.shuttercontrol#78]
![image](https://user-images.githubusercontent.com/8565847/86256005-193c9a00-bbb8-11ea-8c87-976b0c46fccc.png)

Es wäre super, wenn man einen DP mit angeben könnte der den Sonnenschutz verhindert. Aktuell fährt das Rollo auch runter wenn der Sonnenwinkel erreicht wurde.

Bsp:
Wenn bewölkt -> keinen Sonnenschutz

**Comment by simatec** [comment]
Das kann man doch individuell gestalten und mit Javascript da was auf autoSun triggern. 
Shuttercontrol weiß doch nicht, wann es bewölkt ist. Alternativ einen Helligkeitssensor. Den kann Shuttercontrol verarbeiten

**Comment by n3roGit** [comment]
Das geht?

Ich hab an sowas gedacht wie ein weiterer Punkt in der Liste.

Custom DP
und den wert bei dem ignoriert wird
