### ISSUE TITLE
Rollläden mit anderen Level

### ISSUE THREAD

**Issue by dv1407** [simatec/ioBroker.shuttercontrol#80]
Hallo,
meine Rollläden haben den Status 0% offen und 100% zu.
Leider funktioniert der Adapter so nicht,
was muss ich einstellen?

**Comment by simatec** [comment]
Die Alias Funktion von iobroker für deine Rollläden nutzen und die Werte somit konvertieren. Shuttercontrol erwartet 100% = offen und 0% = geschlossen
