### ISSUE TITLE
Aktion TriggerID changed (Türkontakt) wird nicht ausgeführt während Rolladen in Bewegung ist

### ISSUE THREAD

**Issue by MultivitaminJuice** [simatec/ioBroker.shuttercontrol#81]
Hi!

wir hatten schonmal im [Forum](https://forum.iobroker.net/topic/22405/test-adapter-shuttercontrol-v0-7-x/1701) über das Verhalten gesprochen. Ich notiere es hier nochmal als Issues, damit die Anfrage nicht in den ganzen anderen Posts untergeht. Ich hoffe das ist OK soweit?!

Ein Rolladen steht in Sonnenschutzposition (Sunprotect aktiv). Später wird die Terassentür geöffnet, so dass der Wert von TriggerID sich ändert und der Rolladen in die entsprechende Position fährt. Während dieser Fahrt wird die Tür wieder geschlossen, so dass der Wert von TriggerID sich wieder ändert. Der Rolladen fährt dann nicht mehr in die entsprechenden Sonnenschutzposition.

Wenn sich der Türkontakt ändert "TriggerID changed" während der Rolladen fährt, gibt es kein "Save Trigger height" im Log und auch kein "Set ID:" Der Rolladen fährt dann nicht wieder runter.

Kannst du noch etwas damit anfangen? Kann ich etwas testen? Meld dich gern!

Gruß
Multivitamin

**Comment by poidi** [comment]
Ich schreib meine Situation auch hier dazu, weil es aus meiner Sicht das gleiche Verhalten ist, bitte sag bescheid, wenn ich das in einene eigenen Issue auslagern soll:

Ich hab ein Fenster offen. Dann kommt die Zeit in der Die Verdunkelung starten sollte. Durch den aktiven Aussperrschutz bleibt der Rolladen oben. So weit, so gut. Wenn ich jetzt das Fenster zumache, weil ich ins Bett gehen will, dann sollte meiner Erwartungshaltung der Rolladen in die Verdunkelungsposition fahren. Das tut er aber nicht.

Sollte das möglich sein, und ich hab was falsch eingestellt - oder ist das analog zu obigen Problem zu sehen?

Danke
Poidi

**Comment by simatec** [comment]
Release 1.0.0
