### ISSUE TITLE
DP-Button für 'alle Rollos in Sonnenschutz'

### ISSUE THREAD

**Issue by darkman242** [simatec/ioBroker.shuttercontrol#83]
Ist es möglich noch einen Button zu bekommen, um alle Rollos gleichzeitig in die definierten Sonnenschutz-Zustände zu fahren? Ich schliesse beim Sonnenschutz nicht komplett die Rollos wegen der Haustiere, würde aber gerne wenn ich das Haus verlasse und es warm ist bzw. eine große Wärme zu erwarten ist alle Rollos sofort in den Sonnenschutz fahren und somit die Automatik aussetzen. Ich möchte die Rollos nicht komplett runter fahren sondern nur den Sonnenschutz.

**Comment by simatec** [comment]
kommt mit Version 0.8.2
