### ISSUE TITLE
reopen #64: Aussperrschutz unverständlich.

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#84]
Auch wenn Issue #64 bereits geclosed ist, das Problem ist noch immer vorhanden. 

Der Unterschied zwischen "Aus" und "Auf und Ab" ist nicht ersichtlich.

Es sind dazu also schon 2 Forenanfragen und nun ein Issue unbeantwortet. Wäre schön wenn das erklärt wird.

Danke

**Comment by simatec** [comment]
Der Aussperrschutz wurde ab Version 0.7.0 überarbeitet und sollte nun verständlich sein. 
Aus und offen/geschlossen sind nicht identisch. 
Bei Aus fährt der Rollladen nie bei geöffneter Tür. Bei offen / geschlossen dagegen immer. Also kein Aussperrschutz.

**Comment by poidi** [comment]
Danke, deine Worte hier sind verständlich. Jedoch aus der Aktuellen Doku lese ich folgendes:

"""
Automatikbetrieb bei Triggerabweichung Das klingt jetzt etwas kompliziert, entspricht einem Aussperrschutz. Ist zum Zeitpunkt der automatischen Verdunklung/Beschattung der Sensor nicht in dem im ersten Feld der Zeile eingegebenen Sollwert wird das hier angegeben ausgeführt:

    Aus: kein Aussperrschutz, die Rollläden bewegen sich automatisch, egal wie der Sensor steht.
    nur Auf: Bei Verdunklungs- / Beschattungsende fährt der Rollladen hoch
    nur Ab: Bei Verdunklungs- / Beschattungsbeginn fährt der Rollladen herunter
    Auf und Ab: Der Rollladen darf sich egal wie der Sensor steht, in beide Richtungen bewegen
"""

Man merke: Bei sowohl bei "Aus" als auch bei "Auf und Ab2 steht: "egal wie der Sensor steht"

Da ist nicht was du oben gerade geschrieben hast.

**Comment by simatec** [comment]
Die Doku wird gerade komplett überarbeitet
