### ISSUE TITLE
Sonnenschutzeinstellungen anders realisieren

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#85]
Hi simatec, Hi Leute,

als erster mal allerhöchsten Respekt zu Deinen gut gelungenen und gut funktionierenden Adapter. 
Ich würde es sehr begrüßen wenn man für sein Haus / seine Wohnung die Sonnenschutzeinstellung pro Gebäudeseite erstellen könnte und dann dort nur angeben bräuchte welche Rolladen zu der entsprechenden Seite gehören. Das würde die Arbeit in meinen Augen verringern und es wäre deutlich schneller sichtbar welche Rolladen dem Sonnenschutz unterliegen und welche nicht. 

Allerdings habe ich leider keine Ahnung wieviel Arbeit das für Dich bedeuten würde und ob es eventuell noch mehr Leute gibt die das sinnvoll finden würden.

Vielleicht lässt es sich auch in einer Art Tabelle mit CheckBoxen umsetzen, in der man pro Rolladen auswählen kann automatisch auf, automatisch zu, nach Uhrzeit oder Sonnenstand, Wohnbereich oder Schlafbereich und Sonnenschutz ja/nein, wenn ja für welche Gebäudeseit usw.

Ich bin gespannt auf Dein und euer Feedback.

Schönes Wochenende noch

**Comment by vain90** [comment]
Den Vorschlag finde ich auch gut.
Man könnte quasi Gruppen von Himmelsrichtungen definieren und diese Gruppen kann man dann den Rolladen zuordnen. Wobei pro Rolladen nur genau eine erlaubt ist.
Aber es darf keinesfalls eine Einschränkung auf 4 Gruppen/Himmelsrichtungen geben. Denn es gibt sicherlich auch Gebäude die mehr Rolladen zu mehr als 4 Himmelsrichtungen haben!

Gruß

**Comment by 5G7K** [comment]
Was wäre denn der Vorteil? Nur die einmalige Pflege? Heute pflegt man die Himmelsrichtung + Range pro Rollladen. Das passt doch so super und ist sehr individuell. Pro Seite habe ich z.B. auch mehrere Varianten. OG mit Dachüberstand anders als EG, Baum vorm Fenster usw. Da benötige ich ja auch eine Vielzahl von Gruppen. Ich sehe den Vorteil irgendwie nicht.

**Comment by MMeinhardt1** [comment]
@5G7K, der Vorteil wäre das die Sonnenschutzeinstellungen pro Hausseite nur einmal eingestellt werden müssten und man sicher sein kann das sie überall gleich sind.
Wenn das für Dich auf Grund Deiner Komplexizität für Dich nicht in Frage kommt, dann müsstest Du es ja nicht nutzen.
Der Vorschlag von mir hat den praktischen Hintergrund das bei uns zur Zeit noch nicht alle Rolläden elektrifiziert sind und es wenn es soweit ist, die Arbeit für mich erleichert.

Alles in allem ist es aber entscheidend was simatec dazu sagt.

Bis dahin, gesund bleiben!

**Comment by simatec** [comment]
Gruppen sind nicht die Philosophie von shuttercontrol. Jeder Rollladen soll individuell einstellbar sein. Anfangs hatten wir Gruppen, was sich aber als nicht wirklich sinnvoll raustellte. Wird also nicht kommen ...

**Comment by MMeinhardt1** [comment]
Das ist doch mal ne Ansage. Schade
