### ISSUE TITLE
Definierung Wohn- und Schlafbereich und entsprechende Button

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#87]
Hallo,

ich habe meine Rolläden soweit konfiguriert, es funktioniert auch bislang alles. Konfiguriert sind meine Rolläden allerdings nur für das morgentliche Öffnen und nicht fürs Schließen und das als Wohnbereich.
Nun sind mir eben einige Button aufgefallen und ich habe diese getestet, folgende sind ohne Funktion "closeLiving", "openLiving", "closeSleep" und "openSleep". Die restlichen Button funktionieren so wie sie es sollen.

Danke

**Comment by simatec** [comment]
Wie kommst du zu der Erkenntnis, dass diese ohne Funktion sind?

**Comment by MMeinhardt1** [comment]
Naja das ist ziemlich einfach. Wenn ich die betätige unter objects dann passiert nichts, das ist für mich erstmal ein Indiz das sie nicht funktionieren. Oder habe ich da etwas falsch verstanden?

**Comment by simatec** [comment]
Dann zeige mal deine Config

**Comment by MMeinhardt1** [comment]
Möchtest du Screenshots haben oder gibt es ne Möglichkeit diese an anderer Stelle auszulesen?

**Comment by simatec** [comment]
ja bitte die Config über das Menü mit den Pfeiltasten auslesen und hier posten

**Comment by MMeinhardt1** [comment]
Hi,

hier meine Konfiguration. Dateiendung geändert von .json in .txt

[system.adapter.shuttercontrol.0.txt](https://github.com/simatec/ioBroker.shuttercontrol/files/4883710/system.adapter.shuttercontrol.0.txt)

**Comment by simatec** [comment]
Schaue ich mir an und wird in der nächsten Version gefixt ...
