### ISSUE TITLE
Unterstützung von getrennten Datenpunkten für Soll/Ist Rollladenposition

### ISSUE THREAD

**Issue by sabuty** [simatec/ioBroker.shuttercontrol#89]
Das Addon gefällt mir sehr gut. In Verbindung mit Homematic IP würde ich mir allerdings wünschen, dass ich für die Rollläden **optional noch zusätzlich einen Datenpunkt auswählen kann, der die reale Ist-Position wiederspiegelt**.

Hintergrund: Ein Homematic IP Rollladenaktor (zB BROLL) hat 3 Sollwert-Datenpunkte und einen Istwert-Datenpunkt. Nach manuellem Verfahren entspricht der Istwert nicht mehr einem der Sollwerte. Im speziellen Fall vom BROLL wird der Sollwert einfach nur auf 0 (zufahren) oder 100 (auffahren) gesetzt, bis der Benutzer die Fahrt am Schalter wieder abbricht. Der Istwert-Datenpunkt reflektiert allerdings immer den realen Stand.

Beispiel von gerade eben nach manueller Fahrt des Küchenrollos:
iobroker Objekte:
Küche Rollo:3.LEVEL = 47% _(Istwert)_
Küche Rollo:4.LEVEL = 0% _(der für shuttercontrol genutze Sollwertdatenpunkt)_

iobroker LogFile nach shuttercontrol Neustart:
debug | (2616) save current height: 0% from Küche Rollo:4.LEVEL _(entspricht nicht dem Istwert!)_

**Comment by sabuty** [comment]
Alternativ wäre die Unterstützung von iobroker Aliasen mit SET/ACTUAL states wahrscheinlich die bessere Möglichkeit.

So einen Alias habe ich testweise angelegt (mit dem iobroker.devices addon):
> alias.0.Bad_Rollo -- Blind
> *SET hm-rpc.0.001117XXXXXXXX.4.LEVEL
> ACTUAL hm-rpc.0.001117XXXXXXXX.3.LEVEL

Allerdings kommt shuttercontrol derzeit damit nicht klar und bekommt die Werte nicht gelesen:
> shuttercontrol.0 | 2020-07-14 08:32:48.228 | warn | (21258) Alias alias.0.Bad_Rollo has no target 9

**Comment by volkerrichert** [comment]
Das wäre wirklich gut. Ich habe velux via klf200. Vorher mit einem Script auf einem Punkt gemaped, aber jetzt als Alias. Natürlich geht das auch wieder per skript, aber 2 Datenpunkte / alias-Support wäre cool

**Comment by sabuty** [comment]
Ich habe das Thema auch mal im iobroker Forum [angesprochen](https://forum.iobroker.net/post/462330). Mittlerweile habe ich mir angeschaut, wie z.B. [iobroker.lovelace damit umgeht](https://github.com/ioBroker/ioBroker.lovelace/blob/622f1d8fa09a11b2b3ea9a088b40a2e18a968cf4/lib/server.js#L452). Das Beispiel ist zwar für eine Lampe, aber es wird geschaut, ob SET und ACTUAL existieren. Bei den [blinds](https://github.com/ioBroker/ioBroker.lovelace/blob/622f1d8fa09a11b2b3ea9a088b40a2e18a968cf4/lib/server.js#L978) ist das etwas wirrer.

Wahrscheinlich wäre es für shuttercontrol optimal, direkt mit Aliasen zu arbeiten, die vom iobroker.device Addon angelegt werden.

**Comment by volkerrichert** [comment]
also direkt das Channel angeben. Hm, gute Idee. Oder halt 2 Datenpunkte. einer zum Schreiben und einer zum Lesen. Wenn "lesen" nicht gesetzt ist, dann könnte der andere zum Lesen genutzt werden.  Dann wäre man genau da wo man jetzt ist

**Comment by dupan99** [comment]
Habe genau das Problem, besonders wenn die Funktion "Überprüfen des aktuellen Rollladenstatus" ausgewählt ist. Hier gibt es entweder 0% oder 100% aber keine Aktualisierung des wirklichen Wertes. (HM BROLL).

**Comment by simatec** [comment]
Bitte für solche Anwendungen Alias verwenden. 
Alias wurde extra für solche Sonderanwendungen entwickelt. 
Den erzeugten Alias könnt ihr dann in Shuttercontrol eintragen.
