### ISSUE TITLE
Sonnenhöhe für jede Rollade

### ISSUE THREAD

**Issue by AlexanderSch90** [simatec/ioBroker.shuttercontrol#9]
Auch wenn im Forum schon genannt, vielleicht hier doch übersichtlicher: 

Wenn ich mir noch eine Funktion wünschen dürfte:
In den individuellen Rollandeneinstellungen - Sonnenschutz - => Die Möglichkeit nach Sonnenhöhe den Sonnenschutz zu aktivieren...

Wir haben z.B. einen Dachüberstand, der dafür sorgt, dass im Sommer bei 50 Grad Sonnenhöhe kein direktes Licht einfällt. Im Frühjahr bei 30 Grad Sonnenhöhe entsprechend schon.

**Comment by simatec** [comment]
Schaue ich mir mal an

**Comment by AlexanderSch90** [comment]
Hey, 
closed bedeutet hier => wird nicht weiter verfolgt? Oder wird implementiert? :-)

**Comment by simatec** [comment]
Steht auf der Todo Liste
