### ISSUE TITLE
weitere Rollladen Position zwischen ganz auf und ganz zu

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#90]
@simatec , besteht eventuell die Möglichkeit das Du einen weiteren Datenpunkt bzw. einen weiteren Level für die Rollladen einfügen kannst. Wir haben im Erdgeschoss einige Rollladen die wir Abends in Astro-Abhängigkeit auf ein bestimmtes Level zufahren lassen, diese werden aber dann ganz geschlossen wenn wir uns schlafen legen. Und im Moment läuft das ganze per Script, schöner fände ich es wenn es auch über Deinen tollen Adapter gehen würde. Wenn sich das ganze dann auch noch realisieren lassen könnte das es in Abhängigkeit einer Abwesenheitserkennung entweder wenn keiner zu Hause ist ganz herunterfährt und wenn wir zu Hause sind auf unsere favorisierte Position, dann wäre das extrem krass.

Vielen Dank

**Comment by simatec** [comment]
Ab Version 1.1.0 verfügbar

**Comment by MMeinhardt1** [comment]
😃 super, vielen Dank für die Umsetzung. 👍
