### ISSUE TITLE
Buttons ohne Funktion, wenn AUTO Wohn/Schlafbereich genutzt wird

### ISSUE THREAD

**Issue by coyote1** [simatec/ioBroker.shuttercontrol#91]
Hi,
die Buttons für open/close Living/Sleep funktionieren nicht, wenn AUTO Wohn/Schlafbereich genutzt wird (laut deiner Aussage im ioBroker Thread, ist dies noch nicht im Code drin).
Issue dient eigentlich nur dazu, damit es nicht in Vergessenheit gerät, da du ja schon weißt, woran es liegt.

**Comment by MMeinhardt1** [comment]
das dürfte ungefähr diesem entsprechen [https://github.com/simatec/ioBroker.shuttercontrol/issues/87](url)

**Comment by simatec** [comment]
Die Buttons sind für Wohnbereich und Schlafbereich und nicht für Wohnbereich (Auto) und Schlafbereich (Auto)
