### ISSUE TITLE
Rollladenhöhe bei "Rollladen fahren bei Änderung des Fenster/Tür Zustandes" berücksichtigen

### ISSUE THREAD

**Issue by StahlJu** [simatec/ioBroker.shuttercontrol#92]
Hallo Simatec,
zunächst einmal herzlichen Dank für dieses tolle Stück Software.

Ich fände es super, wenn es eine Möglichkeit gäbe, die "Lüftungsautomatik" von zusätzlichen Parametern abhängig zu machen. Z.B. möchte ich nicht, dass ich bei einem Rollladen, der zu 90 % geöffnet ist, der Rollladen auf die Lüftungsposition fährt, sobald ich das Fenster öffne. Hier wäre eine Abhängigkeit von Rollladenhöhe, Uhrzeit und Helligkeit super. Eine der zusätzlichen Abhängigkeiten würde auch schon helfen.

**Comment by simatec** [comment]
Release 1.0.0
