### ISSUE TITLE
control-trigger: autoAll

### ISSUE THREAD

**Issue by poidi** [simatec/ioBroker.shuttercontrol#94]
Würde mir wünschen, wenn die automatik aus irgendeinem Grunde aussetzt (weil ein Fenster offen war, ich eine händische Beschattung gemacht habe,...) es mit einem Befehl möglich wäre, alle Rolladen in den automatikmodus zu überführen und auch die automatische Position anzusteuern.

Es gibt ja bereits einige autoXXX Trigger. Nur dieser autoAll Trigger fehlt für mich.

Danke!
poidi

**Comment by simatec** [comment]
Der Button openAll macht genau dieses ...
