### ISSUE TITLE
Zuordnung „living“ und „sleep“ anders lösen und einen zusätzlichen Bereich

### ISSUE THREAD

**Issue by MMeinhardt1** [simatec/ioBroker.shuttercontrol#96]
Hi simatec,

in einem anderen Issue habe ich gefragt ob es möglich ist eine weitere Rollladenhöhe für ein „zwischenschliessen“ einzubauen, aus diesem Grund schließen meine Rollläden Abend noch per Script auf eine halboffene Position. Daher habe ich für die Rollläden im Wohnbereich im Adapter die Methode für das schließen auf „aus“ eingestellt. Dieser Umstand sorgt leider dafür das ich die Rollläden nicht mit dem Button in der Objekten schließen kann, das öffnen über den Button funktioniert da im Adapter die Methode für das öffnen auf „Wohnbereich“ steht. Vielleicht besteht da ja die Möglichkeit den Adapter so umzubauen das man die Zugehörigkeit der Rollläden separat von der Methode des öffnen und Schließens einstellen kann.

Und weiter wäre es ganz praktisch einen weiter Bereich zu haben für z.B. den Keller oder anderweitig ungenutzte Räume mit Rollläden. 

Vielen Dank

**Comment by MMeinhardt1** [comment]
Hast Du Dir das schon mal angeschaut und überlegt ob Du es realisieren kannst / möchtest?

**Comment by meerkat82** [comment]
Hallo simatec,
der Bereich children ist nun ja schon enthalten. Wäre es evtl. möglich, das man die Bereiche selber anlegen kann und steuern kann? Ich würde für meine Steuerung eher mehrere Bereiche wünschen. Die Kinder gehen bspw. auch nicht gleichzeitig ins Bett.
