### ISSUE TITLE
Schalter für Automatikbetrieb

### ISSUE THREAD

**Issue by Apfelwurm1** [simatec/ioBroker.shuttercontrol#98]
Hallo zusammen, 
erst einmal herforragende Arbeit bisher. Ich hätte jedoch noch ein paar Verbesserungen. 

1. Was ich jedoch sehr vermisse ist eine Möglichkeit manuell verfahrenen Rolläden wieder in den Automatikbetrieb zu bringen. 
Das Adapter neustarten und dann die Rolläden auf 100% zu bringen ist nicht sehr konfortabel. Einen Schalter (oder Objekte false/true) für wiederherstellen des Automatikbetrieb wäre Klasse.

2. beim öffnen des Türkontakt fährt der Rolladen zwar in die höhe verbeleibt jedoch dann in dieser Position. Schöner wäre wenn dieser wieder in die Beschattung oder Close position verfährt. 
Hier würde auch noch weitere Verbesserung möglich. 
Rolläden schließt nicht bei geöffneten Türkontakt aber schließt später wenn der Türkontakt geschlossen ist. 
Beispiel: 
Türkontakt offen: = 100%  keine fahrt in Beschattung oder close
Türkontakt geschlossen Beschattungsfahrt oder schließen wird nachgeholt. 

Es ist nämlich so wenn open/close gewählt fährt das Rollo ohne Rücksicht auf den Fensterkontakt on close wenn nur open gewählt fährt das rollo nicht zu.

3. Die neuen Objekte sind gut jedoch fehlt mir ein automatik Wert. Ich würde gerne wissen wo der Rolladen stehen sollte und nicht nur wo er aktuell steht.

**Comment by 03-20** [comment]
Bitte einen Datenpunkt einbauen, der, wenn er getriggert wird, die jeweilige Rollade zu dem Zustand bringt, der von der Automatik grade herschen sollte.

Aktuell:
Die Rollade wird von Hand z.B. noch mal Hochgefahren -> Sie ist aus der Automatik bis zum nächsten Automatischen Fahren raus und ich muss sie Manuel auf eine gewisse höhe bringen für die Nacht.

Wunsch:
Ich trigger diesen Datenpunkt und die (manuell hochgefahrene) Rollade wird in den Zustand geschickt, den sie eigentlich haben sollte und in die Automatik wieder aufgenommen. Nicht erst bei der nächsten Fahrt.

Vielen Dank

**Comment by simatec** [comment]
Ist so nicht die Philosophie von shuttercontrol
